### ISSUE TITLE
Capitalization mismatch causes file not found

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#100]
Facebook\InstantArticles\Elements\AnimatedGif  is not found on ubuntu because filename is AnimatedGIF.php    renaming file to AnimatedGif.php fixes the problem

**Comment by diegoquinteiro** [comment]
Hi @sgatz,

Where is the error shown for you?

Thanks,
Diego

**Comment by mfelser** [comment]
This is a bug in the Instant Articles SDK. I submitted a pull request to fix it here facebook/facebook-instant-articles-sdk-php#24

**Comment by diegoquinteiro** [comment]
@mfelser @sgatz I've released a new version of SDK fixing the issue.

You can either download the new build on the releases page (v2.2) or simply do a `composer update` on master to get the new dependency version.

Does that fixes the issue for you?

**Comment by sgatz** [comment]
This is still an issue in 2.3.

**Comment by diegoquinteiro** [comment]
Please reopen if not! =)
