### ISSUE TITLE
Issue with latest version 2.3

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#101]
Hi guys,

I was very excited to see a new release of the plugin with what appears to be a GUI!

I've just installed it and got the following "fatal error" when trying to activate it:

> 
> Warning: require(/var/www/vhosts/**mysite**/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/**mysite**/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32
> 
> Fatal error: require(): Failed opening required '/var/www/vhosts/**mysite**/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/**mysite**/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32
> 
> Warning: Unknown: open(/var/lib/php/session/sess_4jtbg5uvhcmh04vbfg3pg82se4, O_RDWR) failed: Permission denied (13) in Unknown on line 0
> 
> Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) in Unknown on line 0

It appears as though a directory has been omitted from the release?

**Comment by YOzaz** [comment]
@samichamoun you need to run `composer install` before uploading to production.

**Comment by diegoquinteiro** [comment]
@samichamoun alternatively, you can go to the releases page and download a .zip build you can upload directly to your WP installation.

**Comment by samichamoun** [comment]
Yep, didn't realise the plugin was available from the releases page, working fine now!
