### ISSUE TITLE
FB embed removed

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#103]
We have updated the plugin to the latest version and found that the FB embed post was removed when the article goes live. 

We have tried using Jetpack embed/ Embed post tool (https://developers.facebook.com/docs/plugins/embedded-posts), but the embed posts didn't appear on RSS and the Instant Article.

**Comment by diegoquinteiro** [comment]
@CarsonLee27 you can wrap your embed in a `<div class="embed"></div>`. Does that work for you?

**Comment by CarsonLee27** [comment]
Let me try =D Do u mean adding the <div> to wrap the FB embed code? 

For example: 
<div class="embed">
<div class="fb-video" data-href="https://www.facebook.com/8TV.NEWS/videos/vb.147727305254920/1248376395190000/?type=2&amp;theater&amp;notif_t=comment_mention&amp;notif_id=1460430923429749" data-width="864" data-show-text="false">
<div class="fb-xfbml-parse-ignore">
<blockquote cite="https://www.facebook.com/8TV.NEWS/videos/1248376395190000/">泰南又发生爆炸 警察上车后被炸死

闭路电视清楚拍下爆炸画面，在宋卡府的火车站前，警察走进警车后，瞬间被炸得粉身碎骨！事发于昨午5时30分，1警死亡，10人伤。

Posted by <a href="https://www.facebook.com/8TV.NEWS/">八度空间华语新闻</a> on Monday, 11 April 2016</blockquote>
</div>
</div>
</div>

Slightly better, it show, but without video xD
![13000552_10153662663164492_1044966629_o](https://cloud.githubusercontent.com/assets/4049250/14461709/4e015270-00f6-11e6-9e95-afa4e7f2747f.jpg)

**Comment by diegoquinteiro** [comment]
I think you'll need to put both the embed code and the SDK init code inside the block to make it work. Can you try?

**Comment by CarsonLee27** [comment]
Tried. Doesn't work. The website is displaying perfectly but IA doesn't show up. 
<img width="863" alt="screen shot 2016-04-12 at 10 34 14 pm" src="https://cloud.githubusercontent.com/assets/4049250/14463730/d6de74da-00fe-11e6-9227-162f8116fa4b.png">

**Comment by diegoquinteiro** [comment]
Can you paste a code snippet here? I'll try to reproduce.

**Comment by CarsonLee27** [comment]
Sure. 

`<div class="embed">
<div class="fb-video" data-href="https://www.facebook.com/8TV.NEWS/videos/vb.147727305254920/1248376395190000/?type=2&amp;theater&amp;notif_t=comment_mention&amp;notif_id=1460430923429749" data-width="864" data-show-text="false">
<div class="fb-xfbml-parse-ignore">
<blockquote cite="https://www.facebook.com/8TV.NEWS/videos/1248376395190000/">泰南又发生爆炸 警察上车后被炸死

闭路电视清楚拍下爆炸画面，在宋卡府的火车站前，警察走进警车后，瞬间被炸得粉身碎骨！事发于昨午5时30分，1警死亡，10人伤。

Posted by <a href="https://www.facebook.com/8TV.NEWS/">八度空间华语新闻</a> on Monday, 11 April 2016</blockquote>
</div>
</div>
</div>`

Appreciate for the helps!!!

**Comment by CarsonLee27** [comment]
@diegoquinteiro any sign of bugs?? xD

**Comment by demoive** [comment]
@CarsonLee27 I haven't been able to reproduce this and there are no signs of bugs. In fact, using your sample source markup:

```html
<div class="embed">
  <div class="fb-video" data-href="https://www.facebook.com/8TV.NEWS/videos/vb.147727305254920/1248376395190000/?type=2&amp;theater&amp;notif_t=comment_mention&amp;notif_id=1460430923429749" data-width="864" data-show-text="false">
    <div class="fb-xfbml-parse-ignore">
      <blockquote cite="https://www.facebook.com/8TV.NEWS/videos/1248376395190000/">
        泰南又发生爆炸 警察上车后被炸死

        闭路电视清楚拍下爆炸画面，在宋卡府的火车站前，警察走进警车后，瞬间被炸得粉身碎骨！事发于昨午5时30分，1警死亡，10人伤。

        Posted by <a href="https://www.facebook.com/8TV.NEWS/">八度空间华语新闻</a> on Monday, 11 April 2016
      </blockquote>
    </div>
  </div>
</div>
```

The latest version of the plugin successfully generated the following markup in a fresh installation of WordPress:

```html
<figure class="op-social">
  <iframe>
    <div class="fb-video" data-href="https://www.facebook.com/8TV.NEWS/videos/vb.147727305254920/1248376395190000/?type=2&amp;theater&amp;notif_t=comment_mention&amp;notif_id=1460430923429749" data-width="864" data-show-text="false">
      <div class="fb-xfbml-parse-ignore">
        <blockquote cite="https://www.facebook.com/8TV.NEWS/videos/1248376395190000/">
          <p>泰南又发生爆炸 警察上车后被炸死</p>
          <p>闭路电视清楚拍下爆炸画面，在宋卡府的火车站前，警察走进警车后，瞬间被炸得粉身碎骨！事发于昨午5时30分，1警死亡，10人伤。</p>
          <p>Posted by <a href="https://www.facebook.com/8TV.NEWS/">八度空间华语新闻</a> on Monday, 11 April 2016</p>
        </blockquote>
      </div>
    </div>
  </iframe>
</figure>
```

If you find that the issue still reproduces on your end, I'm happy to say that we've recently improved our documentation with a section dedicated to help configuring the [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules) which hopefully provides enough information for you to define or make any adjustments necessary to get the transformation to work in your environment.

If you still find you are unable to define your own custom rules to resolve this case (1) try getting help from the [community on the WP Forum](https://wordpress.org/support/plugin/fb-instant-articles) and (2) we'd appreciate feedback on what part of the documentation that is lacking.
