### ISSUE TITLE
H2, H3 header is repeating the first paragraph of the articles, how to disable it? 

### ISSUE THREAD

**Issue by andrez4vz** [Automattic/facebook-instant-articles-wp#1051]
## Steps required to reproduce the problem

1. 
2. 
3. 

## Expected Result
No HX, Hx header showing on the article when no HX tag is used.

When publishing an article, our first paragraph (p) is also showing as a subtitle (h2) under the title of the article, making it really annoying for the readers.

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.1
* WordPress version:  5.4.2
* PHP version: 7.0

Without the above information we are not able to debug the issue and will close it.

**Comment by gisedaye** [comment]
@andrez4vz you can define custom transformations that adjust better your site structure.
Closing this as it's a customization issue on the dev side.
