### ISSUE TITLE
Consider removing caching in Instant_Articles_Post->_get_the_content()

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/facebook-instant-articles-wp#1053]
The caching in `Instant_Articles_Post->_get_the_content()` seems somewhat unnecessary and makes it more difficult to develop against the plugin. It would be helpful if it was removed, or there was a filter to disable it.

**Comment by danielbachhuber** [comment]
This has bitten us a few times now. Any conditional based on `is_feed( INSTANT_ARTICLES_SLUG )` is only correct part of the time, because the AJAX request to validate the FB IA transformation in the post editor can set the cache.

Another approach would be to provide some helper function that returns true when FB IA is rendering.

**Comment by gisedaye** [comment]
Closing, as it looks like it was fixed on the #1058 PR
