### ISSUE TITLE
"Related Post" not showing in footer. 

### ISSUE THREAD

**Issue by asadcj** [Automattic/facebook-instant-articles-wp#1056]
## Steps required to reproduce the problem

1. Problem is simple but didn't get solution. In instant article it's not showing the "Related Article"

## Expected Result
1. Show the related article in Instant Article

## Actual Result 
1. Not showing the "Related Article" in footer.

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.1
* WordPress version: 5.5
* PHP version: 7.2.33
--

Without the above information we are not able to debug the issue and will close it.

**Comment by gisedaye** [comment]
@asadcj Related articles needs to be set on each article using this markup https://developers.facebook.com/docs/instant-articles/reference/related-articles

You can add custom transformation rules to support your use case if needed.

Closing this as it's not an issue
