### ISSUE TITLE
Third party html5 player support?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#106]
Hi,

Just wondering whether there's any intention to support third party html5 players any time soon?

_Facebook sample_
```
<figure class="op-interactive">
  <iframe class="column-width" src="http://example.com/custom-interactive" height="60"></iframe>
</figure>
```

Currently, my video player is being embedded as a social post, using the op-social class.

I'm currently using Springboard, I'm sure there are other players people are using though.

Sample springboard iframe:
`
<iframe height="300" class="no-margin" src="https://cms.springboardplatform.com/embed_iframe/a-random-video"></iframe>`

**Comment by diegoquinteiro** [comment]
Thanks for the feedback.

This is the same case as #109, please see my response there.
