### ISSUE TITLE
Production articles show articles are Live, still Instant Article is not working 

### ISSUE THREAD

**Issue by snowakpos** [Automattic/facebook-instant-articles-wp#1060]
Production articles show articles are Live, still Instant Article is not working 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

<p>Nigerian afro-beat star, Damini &#8221;<em>Burna Boy&#8217;</em>&#8216; Ogulu has reacted to a call by RevolutionNow convener, Omoyele Sowore, for him to join in protesting against President Muhammadu Buhari’s government on Nigeria&#8217;s Independence Day Anniversary.</p>
<p>Recall that Sowore had earlier today, challenged Burna Boy to join the #RevolutionNow protest on October 1st.</p>
<p>Taking to Twitter, the politician and activist wrote: <strong><em>“Hello @burnaboy, everywhere I turn people describe you as a revolutionary musician, the foreign media even celebrate you compare you to Fela Kuti, but I am yet to see you lead anyone to a police station carrying a coffin for head of state! Join #Oct1stProtest #RevolutionNow.</em></strong>”</p>
<div style="clear:both; margin-top:0em; margin-bottom:1em;"><a href="https://www.correctng.com/hes-one-of-our-own-ogun-revenue-service-tussles-with-lagos-revenue-service-over-laycons-tax/" target="_self" class="ub3104e40745d031aac2686430b2ff318"><style> .ub3104e40745d031aac2686430b2ff318 { padding:0px; margin: 0; padding-top:1em!important; padding-bottom:1em!important; width:100%; display: block; font-weight:bold; background-color:#e6e6e6; border:0!important; border-left:4px solid #27AE60!important; text-decoration:none; } .ub3104e40745d031aac2686430b2ff318:active, .ub3104e40745d031aac2686430b2ff318:hover { opacity: 1; transition: opacity 250ms; webkit-transition: opacity 250ms; text-decoration:none; } .ub3104e40745d031aac2686430b2ff318 { transition: background-color 250ms; webkit-transition: background-color 250ms; opacity: 1.5; transition: opacity 250ms; webkit-transition: opacity 250ms; } .ub3104e40745d031aac2686430b2ff318 .ctaText { font-weight:bold; color:#27AE60; text-decoration:none; font-size: 16px; } .ub3104e40745d031aac2686430b2ff318 .postTitle { color:#000000; text-decoration: underline!important; font-size: 16px; } .ub3104e40745d031aac2686430b2ff318:hover .postTitle { text-decoration: underline!important; } </style><div style="padding-left:1em; padding-right:1em;"><span class="ctaText">READ ALSO:</span>&nbsp; <span class="postTitle">He's one of our own - Ogun Revenue Service tussles with Lagos Revenue service over Laycon's tax</span></div></a></div><p>Burna Boy has now responded to Sowore on Twitter, stating that the same people late Fela fought for were those who betrayed him.</p>
<p>In a post which he has now deleted, Burna replied; <strong><em>“When Fela was alive, the very people he was fighting for are the ones who put him through the real hell.</em></strong></p>
<p><strong><em>People even stayed away from my mother’s family for associating with Fela. They killed his mother and most Nigerians said he deserved it…”</em></strong></p>
<html>
  <head>
    <link rel="canonical" href="https://www.correctng.com/burna-boy-responds-as-sowore-calls-on-him-to-join-revolutionnow-protest/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.10.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.2.1"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.10.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="https://www.correctng.com/wp-content/uploads/2020/09/burna-boy-sowore.jpg"/>
        </figure>
        <h1>Burna Boy responds as Sowore calls on him to join #RevolutionNow protest</h1>
        <time class="op-published" datetime="2020-09-29T20:50:43+01:00">September 29th, 8:50pm</time>
        <time class="op-modified" datetime="2020-09-29T20:50:43+01:00">September 29th, 8:50pm</time>
        <address><a>Henry Iheanacho</a>Henry Iheanacho is an avid news content writer who loves movies and TV series with keen interest in governance-based discussions.&#13;
 &#13;
Email Address: itschigbo@gmail.com</address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=161162557854488_161162577854486&adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>Nigerian afro-beat star, Damini ”<i>Burna Boy’</i>‘ Ogulu has reacted to a call by RevolutionNow convener, Omoyele Sowore, for him to join in protesting against President Muhammadu Buhari’s government on Nigeria’s Independence Day Anniversary.</p>
      <p>Recall that Sowore had earlier today, challenged Burna Boy to join the #RevolutionNow protest on October 1st.</p>
      <p>Taking to Twitter, the politician and activist wrote: <b><i>“Hello @burnaboy, everywhere I turn people describe you as a revolutionary musician, the foreign media even celebrate you compare you to Fela Kuti, but I am yet to see you lead anyone to a police station carrying a coffin for head of state! Join #Oct1stProtest #RevolutionNow.</i></b>”</p>
      <p>Burna Boy has now responded to Sowore on Twitter, stating that the same people late Fela fought for were those who betrayed him.</p>
      <p>In a post which he has now deleted, Burna replied; <b><i>“When Fela was alive, the very people he was fighting for are the ones who put him through the real hell.</i></b></p>
      <p>
        <b>
          <i>People even stayed away from my mother’s family for associating with Fela. They killed his mother and most Nigerians said he deserved it…”</i>
        </b>
      </p>
    </article>
  </body>
</html>

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.1
* WordPress version: 5.5
* PHP version: 7

Without the above information we are not able to debug the issue and will close it.

**Comment by gisedaye** [comment]
@snowakpos we need more info about your issue, if still needed could you please open it again will all the information required to reproduce it.
Thanks!
