### ISSUE TITLE
The fb:pages tags on the url dont contain this page's id.

### ISSUE THREAD

**Issue by bboyadao** [Automattic/facebook-instant-articles-wp#1061]
The fb:pages tag on the url doesn't contain this page's id. The url has fb:pages tag but they don't have this page's id. Please work with your developers / webmaster to add this tag to your website.
i make sure my single post contains page id.
does this require for rss feed ?

<img width="878" alt="Screen Shot 2020-10-04 at 13 22 18" src="https://user-images.githubusercontent.com/25122065/95008499-a32b5180-0644-11eb-97a9-4ed3d0c8aa57.png">

**Comment by gisedaye** [comment]
@bboyadao you need to configure your Facebook page id from the plugins settings in order for it to be added to the Instant Articles markup.
Closing the issue, as it's a configuration issue on the dev side.

**Comment by jahidorjahid** [comment]
> @bboyadao you need to configure your Facebook page id from the plugins settings in order for it to be added to the Instant Articles markup.
> Closing the issue, as it's a configuration issue on the dev side.

but it says same problem

**Comment by bboyadao** [comment]
I was quit wp and developed a new one.
