### ISSUE TITLE
Custom code

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#107]
I have a number of cases where I'd like to strip certain blocks of HTML out of my articles all together so that they do not go into the RSS feed. Does the plugin support the ability to add our own custom code, without branching the plugin core code?

Could you please advise the best way to do so?

**Comment by diegoquinteiro** [comment]
You can use the Custom Transformer Rules field on the settings.

There you can specify a rule to ignore certain blocks, something like this:

```php
{
    "rules": [
        {
            "class": "IgnoreRule",
            "selector": "div.ignore-this"
        },
        {
            "class": "IgnoreRule",
            "selector": "p.ignore-this-also"
        }
    ]
}
```

The selector can be any CSS selector or a XPath starting with `//`.

**Comment by samichamoun** [comment]
Thanks - sorry but where should this code be added?

Can you also clarify how these rules work? Would the pre-defined class be applied to the selector within the RSS feed? I'm not sure I understand how a CSS style would stop something from appearing within the feed?

**Comment by demoive** [comment]
Our plugin makes use of the Facebook Instant Articles SDK for PHP which contains a Transformer that does all the heavy lifting of converting general markup into valid Instant Articles markup. The way that it knows how to transform source elements into the valid Instant Articles markup is by a set of rules which defines the mapping of how to parse the content of the post/page.

So to your 2nd question: it's not that a CSS style would strip something from the feed, rather, the CSS selector is used to target an element and, by associating this selector with the `IgnoreRule` type, the element won't be included in the transformation to Instant Articles markup.

Our plugin contains Rules which have been pre-defined to satisfy the most common WordPress source markup. Fortunately, you can override and define your own rules in the Settings page of the plugin under: Plugin Configuration > Publishing Settings > Custom transformer rules.

For more information on how the rules actually work, please see the documentation on the <a href="https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#matching-selector" target="_blank" rel="noreferrer">Selector Rules</a> section of the Quick Start guide.
