### ISSUE TITLE
feed-template.php...

### ISSUE THREAD

**Issue by donaldG** [Automattic/facebook-instant-articles-wp#108]
Curious why this markup doesn't reflect what is set out by the FB guidelines here: https://developers.facebook.com/docs/instant-articles/reference

For instance, it doesn't use ``<article>`` but instead uses ``<content:encoded>``

Maybe I'm being dense but won't this automatically make FB reject the feed? I also see in the admin that if I add a new article it shows me the correct FB markup but when I check the feed URL it's not formatted correctly...

**Comment by diegoquinteiro** [comment]
Hi @donaldG, thanks for the feedback.

The template on `feed-template.php` is actually generating the RSS feed containing the list of articles.

The article itself is rendered inside the `<content:encoded>` in a CDATA block.

**Comment by donaldG** [comment]
Ahhhhh, okay, awesome, thanks much for helping me understand that flow!
