### ISSUE TITLE
Soundcloud Player wrapped in op-social, but not supported

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#109]
I get this error from FB's feed crawler:  

Webview with op-social class without any supported embed type: When using op-social class on a webview, it must have a supported embed inside it e.g. Instagram, Twitter, Facebook, Youtube, etc. We didn't find any here.

for this embed that was auto-wrapped:
    ` <figure class="op-social"><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/257605833&amp;color=ff5500"></iframe></figure>`

**Comment by sgatz** [comment]
Note, the soundcloud player actually appears perfectly in an IA.  I think this is really a bug from the Instant Articles team giving off an erroneous error message.    (I see the same message for  funnyordie embeds)

**Comment by diegoquinteiro** [comment]
Please update to v2.5 and wrap your embeds in <div class="interactive">...</div> to get it properly output.

Does that work for you?

**Comment by diegoquinteiro** [comment]
Please reopen if it doesn't work.

Thank you!
