### ISSUE TITLE
V 2.3 - Drafts, pending & scheduled being sent to the facebook publishing tools production

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#110]
I just updated to the v2.3 and I'm using the api to push the articles and updates. However I just noticed a lot of my drafts, pending and scheluded articles are being sent to the publishing tools->Instant articles -> Production

They arent being published but still its worthless to be sent there before being published aint it? mostly cause if its gonna update every single mod thats its being done to them before publishing that could mean a lot of api calls

**Comment by diegoquinteiro** [comment]
@gabu69 we've done this so you can preview the version on your pages App and act before publishing. It'll be stored as draft until you publish it.

**Comment by gabu69** [comment]
I see, any option in the future for websites who publish/edit a lot and are not really interested in this option?

thanks for the fast reply

**Comment by CarsonLee27** [comment]
Agree with this =D Publishers normally publish the article once is ready. But @diegoquinteiro make sense also. Enable/Disable will be good.

**Comment by bactisme** [comment]
:+1:

**Comment by bactisme** [comment]
A workaround could be to remove this action : add_action( 'save_post', array( 'Instant_Articles_Publisher', 'submit_article' ), 10, 2 ); 

via another remove_action, that can be in your function.php for example.

**Comment by msurguy** [comment]
Also probably worth mentioning this in the FAQ since I got pretty scared at first seeing my drafts in IA but of course it makes sense to store drafts as drafts in both places, IA and WP.

**Comment by stuartshields** [comment]
I'd recommend looking into `pre_get_posts` you can set the `post_status` to just `publish` and that will work

**Comment by Pixelstyle** [comment]
It seems that Facebook is using all posts (drafts and published) in determining if your feed is approved. I just got rejected on the basis of drafted posts not having obligated fields filled.

I tried @bactisme 's solution but it doesn't work. Does anyone have a snippet that I can use to exclude drafts and scheduled posts?

**Comment by gabu69** [comment]
@Pixelstyle use the rss feed meanwhile better

**Comment by Pixelstyle** [comment]
This is with the RSS feed. So it responds the same as the API it seems.

**Comment by fabianpimminger** [comment]
Yeah, please make it possible to only send published articles to Instant Articles via the API. I've already got a few Auto-saved drafts from Wordpress with no content. 

Also - and I think this is an important issue - if you change the headline of an unpublished/draft post in Wordpress, the permalink changes and Facebook thinks this is a different post and makes a new Instant Article. Wordpress doesn't change permalinks when the page is published and you change the headline.

**Comment by gabu69** [comment]
Is there any update on this?

Im using RSS at the moment but I dont know if there was an upate in the last version or if its still the same?

Abailability to enable/disable drafts, pending, scheduled, etc would be great for all of us

**Comment by kevinlisota** [comment]
@diegoquinteiro This has another unintended consequence.

When the plugin feeds a draft to FB Instant Articles, it appears that the FB scraper tries to visit the site. The article is not published, so the site returns a 404 error, according to the FB debugger.

Now publish the article and try to share it on FB. You'll notice that the og:image, og:title and og:meta description are missing. This is because it previously tried to scrape and received a 404. 

We have to visit the FB debugger and click "scrape again" to get all of the open graph data scraped.

If this is how Facebook works, I would say this should be completely disabled. The ability to share a post with the proper open graph image, title and description is way more important than the ability to preview.

**Comment by demoive** [comment]
The "draft" portion of this issue was changed in v2.8.

Related: https://wordpress.org/support/topic/draft-articles-causing-errors

**Comment by demoive** [comment]
Related issue regarding "scheduled" posts:
https://wordpress.org/support/topic/planified-articles-are-empty

**Comment by demoive** [comment]
Calling for assistance: if anyone on this thread wishes to create and submit a PR to resolve the remaining issue where a "scheduled post" is being published to Facebook, here are some suggestions:

- Referring to the updates made in #151 in this commit: https://github.com/Automattic/facebook-instant-articles-wp/pull/151/commits/221fc435c19d95c5ea664bbb193fc45d3089c682
- Add a condition which checks for the published date of the page/post
- If Published date is in the future, prevent post/page from being published

**Comment by demoive** [comment]
The "scheduled" portion of this issue was resolved in v2.11.

**Comment by jppgks** [comment]
@kevinlisota I'm curious: is this still the case? If so, is there an API interface around the sharing debugger that could call some kind of "scrape again" method?
