### ISSUE TITLE
Error states PHP5.5 required

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#112]
I installed this on a PHP 5.3 install and got an error that 5.5 was required.   

@diegoquinteiro  First, I think you said you lowered the requirement to at least 5.4 (so the message should say that).  

Second, is there any reason this won't run in 5.3?  I thought you updated the SDK so that it would do fine in lower versions.

**Comment by diegoquinteiro** [comment]
@sgatz sorry, the message is really wrong. It actually requires 5.4.

We do not support 5.3 yet because our main SDK for Facebook Graph API does not support it.

Are you able to upgrade to 5.4?

**Comment by diegoquinteiro** [comment]
Message fixed in 2.5

**Comment by sgatz** [comment]
@diegoquinteiro I was able to upgrade and 2.7 is working well on PHP 5.5
