### ISSUE TITLE
Receiving 502 Error when attempting to access feed on WPEngine

### ISSUE THREAD

**Issue by bobderrico80** [Automattic/facebook-instant-articles-wp#113]
After deploying the plugin to my staging server on WPEngine, I receive a 502 Bad Gateway error when trying to access the feed. The error occurs after a 1-2 minute stall in the network. In talking to WPEngine's support team, it sounds like there is a server-side request that is taking too long, as they have a script that kills long-running requests.

On my local install, the plugin works as expected.

I realize this problem is most likely related to WPEngine since the plugin works fine on my local machine. I have created a support ticket with them to see what they can do on their end, but I figured I would create an issue here to see if I could get any insight into the error.

**Comment by diegoquinteiro** [comment]
Thanks a lot for investigating.

Please let me know if you find anything relevant so we can act on it!

**Comment by bactisme** [comment]
502 generally means that PHP crashed, or didn't respond fast enough.
/instant-article/ feed is quite slow on my blog, it need approximately 25 secondes to run.. If your webserver is setup for a slow timeout, you get 502.

**Comment by ewrightmedia** [comment]
I'm also running blog on WPEngine and receiving the 502 Bad Gateway error. It runs quickly locally, but taking a long time on live staging and then giving the error.

**Comment by ewrightmedia** [comment]
I kept a copy of v1 of the plugin and it runs fine just to give a bit more data

**Comment by diegoquinteiro** [comment]
Yes, the new transformation is a lot more sophisticated, so it'll definitely take longer.

I'll limit the RSS to a lower number of articles by default to avoid timeouts.

You can, and should, move to using the API by connecting your page in the Facebook Instant Articles Settings page on your WP installation. This way your articles will be pushed to Instant Articles automatically every time you save them.

**Comment by bobderrico80** [comment]
I got some feedback from WPEngine I'd like to share here.  The reason for the 502 was definitely timeout-related. The support team disabled the timeout script temporarily. It took the request 4 minutes to complete. 

https://www.dropbox.com/s/05o72d7zvzu4e5w/Screenshot%202016-04-12%2016.34.06.png?dl=0

The bulk of the time was `Facebook\InstantArticles\Transformer\Transformer::transform

Here is a screenshot of the stack trace with times. It's just a sample, the tech couldn't get the whole trace on the screen:

https://www.dropbox.com/s/enrm2thspvwgjww/Screenshot%202016-04-12%2016.36.59.png?dl=0

Would a solution be to tweak the `posts_per_page` and `posts_per_rss` query vars [here](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L162)?

**Comment by bobderrico80** [comment]
Follow-up to my last comment. As an experiment, I changed those values to 20, and that solved the problem.

My next question is... I know you need to submit 50 before you can be approved to publish. Is there a way to either (a) batch process through the feed in order to submit more articles without the timeout, or (b) manually submit individual articles?

We are _just_ getting to setup our accounts now, so I am learning as I go, so forgive me if I am missing something obvious.

**Comment by diegoquinteiro** [comment]
@bobderrico80 you are helping us a lot! Thank you!

I'll change the default to 20.

You should connect to your page in the plugin settings page and simply update the articles you wanna submit to Instant Articles.

Does that work for you?

**Comment by bobderrico80** [comment]
That works like a charm! Thank you!

**Comment by bactisme** [comment]
For everyone who would like to change quickly the number of post in the feed, a hook allow exactly that. 

    function num_instant_articles_query( $query ) {
    	if ( $query->is_main_query() && $query->is_feed( INSTANT_ARTICLES_SLUG ) ) {
    		$query->set( 'posts_per_rss', 20);
    	}
    }
    add_action( 'pre_get_posts', 'num_instant_articles_query', 100, 1 );

**Comment by diegoquinteiro** [comment]
Hi guys,

The number of articles was changed to 10 in v2.7 we just released. We do recommend using the API integration instead, though.

Thanks a lot!
