### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by msurguy** [Automattic/facebook-instant-articles-wp#114]
Hello! I have installed the plugin on my website, republished permalink config and am getting the following error when trying to access the `/feed/instant-articles` path:

```
 three blog posts show up fine, 
then: 
<content:encoded>
 <![CDATA[<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Maximum execution time of 30 seconds exceeded in /home/mywebsite.com/word/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Rules/ConfigurationSelectorRule.php on line <i>0</i></th></tr>
```

What is interesting is that this error shows up instantly, in no way there has been 30 seconds to load...

**Comment by diegoquinteiro** [comment]
Hi @msurguy,

Thanks for reporting!

What's the version of your plugin, your WordPress and PHP?

**Comment by stuartshields** [comment]
@diegoquinteiro I've seen this before, basically the server load is too intensive to generate the RSS feed. I think your fix of making it 20 posts to generate will fix it. However in my own testing I've had to lower it to 10 as it depends on what's being generated.

**Comment by msurguy** [comment]
@diegoquinteiro I have the latest Wordpress (4.4.2) and latest version of the plugin. Running PHP version 5.6.6. 

I got the plugin to work without generating the XML feed! Didn't know that you don't have to use the RSS feed to make this plugin work. Turns out the articles are published automatically on "Update" or new post creation which was not clear from the Readme.

Thank you for the plugin!

**Comment by msurguy** [comment]
Created a PR for readme to clarify that we don't have to use RSS: https://github.com/Automattic/facebook-instant-articles-wp/pull/115

**Comment by diegoquinteiro** [comment]
Thank you for all the help!
