### ISSUE TITLE
Special Characters with problems on feed

### ISSUE THREAD

**Issue by gusfune** [Automattic/facebook-instant-articles-wp#116]
Hello,
I'm having problems with the plugin when using with special characters.
So far i'm using `uf8mb4` as a charset for my database, everything, specially regular feeds are ok.
But the Instant Article feeds get garbled. It seems it gets converted to UTF-8 when it's already at UTF-8.
Link: http://blogdaarquitetura.com/feed/
Thanks a lot for the help with it.

**Comment by diegoquinteiro** [comment]
Hello from Brazil =)

Thanks for reporting. What version of the plugin are you using?

Please update to the latest if you're not on v2.5+

**Comment by gusfune** [comment]
Hello @diegoquinteiro,
I'm already using version 2.5. That happened on both 2.4 and 2.5.
Also tested on two other websites, same problem keeps happening.

**Comment by diegoquinteiro** [comment]
This feed: http://blogdaarquitetura.com/feed/ does not look like a feed produced by the plugin (it does not contains the articles).

I couldn't access http://blogdaarquitetura.com/feed/ either.

Did you change your feed slug?

**Comment by gusfune** [comment]
Yes. I have changed to http://blogdaarquitetura.com/feed/ia/
The URL works fine here, except for the garbled text in the posts which I have mentioned.

**Comment by diegoquinteiro** [comment]
No problem! Are you doing any custom integration with new-relic? I don't understand why a new-relic script ended up in the RSS output (look at the first article).

**Comment by gusfune** [comment]
I use application monitoring from New Relic, that's included with W3-Total-Cache.
I also made tests disabling all plugins, even with everything shut down, the problem still persists. Also raised the `max-execution-time` to 60 to avoid any PHP output errors and get a more straightforward result on the feed page.

**Comment by diegoquinteiro** [comment]
@gusfune I'm still puzzled by the fact that the `<head>` of the instant article has a script from NewRelic. I'll debug.

Did you try the API workflow by connecting your FB Page on the Instant Articles Settings page?

**Comment by gusfune** [comment]
Yes, I followed the whole process. I noticed the characters problem when I was actually previewing the posts on the Facebook Page.

The NR script is standard to measure app loading times, etc. It's automatically added by W3-Total-Cache, but, from my previous tests it doesn't change anything related to the feed output overall results.

**Comment by gusfune** [comment]
I just figured out and solved the problem after analysing how the plugin handles the encoding.
The problem was the missing module "mbstring" for PHP. After I installed the package in the server, the problem was automatically solved.
