### ISSUE TITLE
Issue with connecting FB page to IA plugin

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#118]
Sorry if this is a stupid question, unfortunately I don't have any past experience with Facebook apps.

After entering my App/Key, I click on the Facebook login button to "Login to Facebook and select the Facebook Page where you will publish Instant Articles."

Upon doing so, I get a popup error:

> Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

I've navigated to the App settings and attempted to add my domain, but when I try to save this, I get the following error:

> App domains must match the domain of the Secure Canvas URL, Mobile Site URL, Unity Binary URL, Site URL or Secure Page Tab URL. Please correct these domains: **_my-domain.com_**

Where is the Site URL set?

**Comment by diegoquinteiro** [comment]
You need to "Add a Platform" to add your Website to your app.

<img width="1438" alt="instant_articles_test_app_-_settings_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/1878108/14481104/0bc109f4-0106-11e6-8b18-98aa8245a4af.png">

**Comment by samichamoun** [comment]
thank you so much

**Comment by samichamoun** [comment]
This worked, however inside of Wordpress, the "Instant Articles" page is now blank when navigating to it. Should this be the case?

**Comment by diegoquinteiro** [comment]
@samichamoun no, it should not be the case. Can you give me more details on this?

Do you have access to logs or can you enable WP_DEBUG on your wp_config.php to see what is causing this?

**Comment by samichamoun** [comment]
Fatal error: Call to undefined function wp_parse_url() in /var/www/vhosts/craziestsportsfights.com/httpdocs/wp-content/plugins/fb-instant-articles/settings/class-instant-articles-settings.php on line 141

**Comment by diegoquinteiro** [comment]
I'll fix it on v2.6 and release it in a couple of hours.
