### ISSUE TITLE
Plugin version numbers

### ISSUE THREAD

**Issue by stuartshields** [Automattic/facebook-instant-articles-wp#119]
@diegoquinteiro Just so we don't reach v3 within a week, maybe the version numbers of the plugin should be kept to incremental versions for smaller fixes for example: 2.5.1 (bug fixes/small enhancements), 2.6 could be a for major changes in code?

**Comment by diegoquinteiro** [comment]
Thanks for the feedback.

We're evaluating migrating to SemVer, but for now we're keeping the versioning from the original plugin which uses only two numbers.

First number is a major (v2) version, second number is a minor version.

That said, we'll not reach v3 after v2.9, it will be v2.10. All versions within v2 will be backwards compatible.

We'll only move to v3 when we need to make a breaking/major change.

**Comment by stuartshields** [comment]
@diegoquinteiro Thanks for letting me know, it makes more sense now.
