### ISSUE TITLE
Is there a filter we can use to update the post "content"?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#122]
I'm trying to run some regular expressions over the post content to make a couple of custom updates to the HTML. One of the reasons for this is to correctly wrap the <figure class="op-interactive"> around our HTML5 videos.

Unfortunately it isn't viable for us to manually add this around each video tag, as the embed code is generated automatically from a third party, and asking writers to start adding HTML manually is not an easy task ;)

I have been trying to add_filter( 'instant_articles_content', 'myFunction' ) however this filter is defined in a protected function and does not appear to be doing anything.

I'd also like to use this to scan through our HTML and remove some unnecessary components in posts.

Let me know if I'm looking in the wrong area?

**Comment by stuartshields** [comment]
@samichamoun Have you tried the following:
`add_filter( 'instant_articles_content', array( $this, 'function_here' ), 10, 1 );`

**Comment by samichamoun** [comment]
Hmmm, looks to be triggering it, however when I return a value back, the post content gets completely removed. I've tried running regular expressions, concatenating strings and also just returning a simple string back - each time it strips the main post content out.

Any ideas?


```
function myFunc($content)
{
  //run some string manipulation.
  $content = $content . "hello world";
  return $content;
}

add_filter( 'instant_articles_content', array( $this, 'myFunc' ), 10, 1 );
```

**Comment by stuartshields** [comment]
@samhotchkiss I think you'll find that you need to get a fresh copy of the content, currently it's being filtered by the plugin. Something like this: `$content = get_the_content();` should help you.

**Comment by samichamoun** [comment]
@stuartshields not quite sure I follow why that would make a difference if the function is being passed in the $content parameter already, however I gave it a crack, but unfortunately nothing. I'm trying all sorts of combinations and cant do ANYTHING to append something to the content.

Are you able to append something?

**Comment by stuartshields** [comment]
@samhotchkiss Do you have any example code of what the videos output?

**Comment by samichamoun** [comment]
Sure, here's a sample:

> <script src="//www.springboardplatform.com/js/overlay"></script><iframe id="crzy003_1621795" src="//cms.springboardplatform.com/embed_iframe/5365/video/1621795/crzy003/craziestsportsfights.com/10" width="600" height="400" frameborder="0" scrolling="no"></iframe>

This is just one example of something I'm trying to strip/replace.

Unfortunately I'm a .NET programmer trying to adapt to WordPress/PHP. Could it be the case that the execution of code is out of order? I'm adding my add_filter's to the functions.php file, so I'm not sure what order things load (and whether it matters).

**Comment by stuartshields** [comment]
@samhotchkiss That video is inside a shortcode correct? It may have issues with `<script src="//www.springboardplatform.com/js/overlay"></script>` 

We have a 3rd party video service and just re-write the shortcode for the video and it works.

**Comment by samichamoun** [comment]
No it is not, the HTML I pasted above is a direct copy of what gets pasted into the article posts at time of creation.

Sorry can you also elaborate on the 3rd party video service?

**Comment by samichamoun** [comment]
Have you been able to successfully call the "instant_articles_content" filter from within a theme functions.php file and manipulate the post content? Like I mentioned below, I've tried just some basic string manipulation without any of the video stuff. I have not been able to append anything to the output of the RSS feed in the content section.

**Comment by stuartshields** [comment]
@samichamoun We use Simple Reach, and yes we use it for re-writing shortcodes.

**Comment by samichamoun** [comment]
I'm not sure what you're suggesting for me to do?

**Comment by samichamoun** [comment]
There are legitimate reasons for the HTML to remain "as is" and untouched on our website - we **only** want to peer into the Instant Article plugin and manipulate what gets pushed into the RSS feed. Does that make sense?

**Comment by stuartshields** [comment]
@samichamoun I can confirm the following works, this is from inside a class:

```php
add_filter( 'instant_articles_content', array( $this, 'test_function' ), 10, 1 );
public function test_function( $content ) {
var_dump('This is some text to test with');
return $content;
}
```

This should work in your functions.php file but I haven't tested it outside a class.
```php
add_filter( 'instant_articles_content', 'test_function' , 10, 1 );
public function test_function( $content ) {
var_dump('This is some text to test with');
return $content;
}
```

**Comment by samichamoun** [comment]
No luck.

To ensure that my code is actually running, I tried using the the_content" filter. I can confirm this is being updated. (e.g. $content . "helloworld"). Unfortunately this means it manipulates what displays on the website too.

I'm still not having any luck calling this instant_articles_content filter from the functions.php file. I'm not sure where else to call it from?

**Comment by stuartshields** [comment]
@samichamoun Maybe try writing a simple plugin to see if it works from there? https://codex.wordpress.org/Writing_a_Plugin

**Comment by samichamoun** [comment]
I just tried creating a plugin and returning something basic like "<div>" . $content . "</div>". 

The toggle debug information shows it works correctly with the Source Markup, however it seems like it gets stripped in the transformed markup.

What **doesnt** work though, is any manipulation of the $content parameter itself. I've tried running a simple preg_replace over $content (have validated the reg expression definitely works with online testers), but any time I try, it's as though the $content variable is an empty string inside of my filter function. Should I be able to see the value of $content in my filter? Any ideas?

**Comment by samichamoun** [comment]
Ignore my comments. I've managed to run a str_replace over it successfully, however can't get a preg_replace to work. Despite my regular expressions looking seemingly correct, there's a chance I've got an issue on my end. I'll bump this thread once I rule that out.

**Comment by samichamoun** [comment]
Had some luck with this. Have found a potential bug along the way though, but I'll close this off and open a fresh issue ticket.
