### ISSUE TITLE
Login button not working

### ISSUE THREAD

**Issue by xvilo** [Automattic/facebook-instant-articles-wp#124]
When I press login with facebook, it opens a pop-up. Then closes the popup and reloads the page, but the login with facebook buttons pops in again. Not a list of pages... What should I do?

Edit:
I have made a small gif of the problem:
![The Problem](http://i.giphy.com/l3V0jXqCKCLNCQttC.gif)

**Comment by diegoquinteiro** [comment]
Hi @xvilo,

That should be fixed in v2.7 we just released.

Thanks a lot!

**Comment by xvilo** [comment]
Great to hear!
