### ISSUE TITLE
Analytics not rendering correctly

### ISSUE THREAD

**Issue by stuartshields** [Automattic/facebook-instant-articles-wp#125]
Hi,

So if you do the following as per the Facebook SDK found here: https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#elements you'll get errors:

``` php
 ->addChild(
            Analytics::create()
                ->withHTML(
                    <h1>Some custom code</h1>
                    <script>alert("test");</script>
                )
        )
```

However if you do the following it works like a charm, I think the Facebook SDK documentation needs to be updated to reflect this:

``` php
$document = new \DOMDocument();
		$fragment = $document->createDocumentFragment();
		$valid_html = @$fragment->appendXML( "<script>". $analytics_code ."</script>" );
		if ( $valid_html ) {
			$article->addChild(
				\Facebook\InstantArticles\Elements\Analytics::create()
						->withHTML(
							$fragment
						)
				);
		}
```

**Comment by diegoquinteiro** [comment]
Hi @stuartshields,

Would you mind opening this issue on the SDK instead? 

https://github.com/facebook/facebook-instant-articles-sdk-php

We are working on improving the docs these days, so that will be much appreciated.

Thank you!
