### ISSUE TITLE
Inline Related Articles Element not working

### ISSUE THREAD

**Issue by fabianpimminger** [Automattic/facebook-instant-articles-wp#129]
Hi,

I'm trying to embed an inline related articles Element. I've used a filter on the "instant_articles_content" hook to have an inline < ul> list with the class "op-related-articles". I do understand, that this should be between paragraphs instead of at the end to be truly inline, but this code snippet is just for demonstration purposes.  

```
function tt_ia_add_recommended_stories($content) {
	return $content.'<ul class="op-related-articles"><li><a href="https://facebook.com"></a></li></ul>';
}

add_filter( 'instant_articles_content', 'tt_ia_add_recommended_stories', 10, 1 );

```

In the debug information toggle after saving the post, the class="op-related-articles" is removed and therefore, facebook doesn't recognise the related articles element.

Does anybody know what's going on here?

**Comment by everton-rosario** [comment]
Hello @fabianpimminger, thanks for using Instant Articles.

This issue should be fixed on the new version of the WordPress plugin.

Can you check it?
