### ISSUE TITLE
Automatic Ad Placement meta tag has wrong value

### ISSUE THREAD

**Issue by fabianpimminger** [Automattic/facebook-instant-articles-wp#132]
I've set the setting for automatic ad placement in the admin section to "None", but the meta tag is set to true in the instant articles:

`<meta property="fb:use_automatic_ad_placement" content="true"/>`

I guess that's the reason why I'm getting this warning?

![bildschirmfoto 2016-04-13 um 19 58 52](https://cloud.githubusercontent.com/assets/45733/14503859/31a4e648-01b2-11e6-8ef9-fd23b694878d.png)

**Comment by diegoquinteiro** [comment]
Thanks for reporting!

While we're fixing it, you can safely ignore the warning.

Thank you

**Comment by demoive** [comment]
This has been [fixed](https://github.com/facebook/facebook-instant-articles-sdk-php/commit/cd6526782172247023af7336739c3b7f10bea48e) in [v1.0.5](https://github.com/facebook/facebook-instant-articles-sdk-php/releases/tag/v1.0.5) of the Facebook Instant Articles PHP SDK.

@fabianpimminger, if you update your WordPress plugin to the latest version, you'll have the fix.

**Comment by fabianpimminger** [comment]
@demoive thanks. Already updated and it works now without the warning.
