### ISSUE TITLE
Convert Jetpack Tiled Galleries into FBIA Photo Galleries

### ISSUE THREAD

**Issue by rickybanister** [Automattic/facebook-instant-articles-wp#133]
Currently tiled galleries are unsupported/ignored by instant articles. Ideally we would convert them to IA photo galleries.

**Comment by bfrye26** [comment]
I would be happy if they even just showed up as a image. With them being fully ignored facebook does not consider it a good match

**Comment by jaygidwitz** [comment]
I agree with both of these. +1 on this issue

**Comment by everton-rosario** [comment]
@rickybanister @jaygidwitz @bfrye26 @chaselivingston Do any of you guys have the code?
I need more details, so we can implement transformation rules to this plugin.

Please, share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

This way we have the source markup before transforming, thus, implementing the transformation rules.

**Comment by jaygidwitz** [comment]
Thank you @everton-rosario. I'm attaching the source markup and transformed markup of a recent article. It has two jetpack galleries in it.

Please let me know if there is anything else I can do to assist.

The link to the live post, if you need it, is [here](http://www.surrealismtoday.com/balletx-summer-series-2016/).

[balletx-tiled-galleries-source-markup.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/364036/balletx-tiled-galleries-source-markup.txt)

[balletx-tiled-galleries-transformed-markup.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/364037/balletx-tiled-galleries-transformed-markup.txt)

**Comment by lubimow** [comment]
I have a similar problem.
That's [news](https://inforesist.org/predstavlen-novyiy-ukrainskiy-broneavtomobil-bars-6/).
I wrote in more detail [here](https://github.com/Automattic/facebook-instant-articles-wp/issues/333).



[Source Markup.pdf](https://github.com/Automattic/facebook-instant-articles-wp/files/364061/Source.Markup.pdf)
[Transformed Markup.pdf](https://github.com/Automattic/facebook-instant-articles-wp/files/364062/Transformed.Markup.pdf)

**Comment by everton-rosario** [comment]
@jaygidwitz Sorry for the long wait. 

I've created this GIST for you with a full working test and transformer to your markup: 
[Gist for jaygidwitz](https://gist.github.com/everton-rosario/fba8b1aeec57a61d298f312aa40a46c6)

Check on the file simple-rules.json that the last ones are the ones special configured for your markup.

**Comment by everton-rosario** [comment]
@lubimow Im going back to the #333 thread. Because your transformer looks it is working perfectly.

I've created this GIST but looks ok since you were using the default gallery component from WordPress (which is already covered within the transformer rules):
[lubimow GIST](https://gist.github.com/everton-rosario/363ecc10918c935130f32c840ecb9d09)
