### ISSUE TITLE
Wordpress changes the permalink of unpublished posts -> duplicate posts in Instant Articles

### ISSUE THREAD

**Issue by fabianpimminger** [Automattic/facebook-instant-articles-wp#135]
If you change the headline of an unpublished/draft post in Wordpress, the permalink changes and Facebook thinks this is a different post and makes a new Instant Article. 

Wordpress doesn't change permalinks when the post is published and you change the headline without problem when posts are already published.

I think this is related to #110 and would be fixed easily so that only published posts get sent to Instant Articles via API.

EDIT: Found out that the `get_canonical_url()` function is creating the dynamic permalinks for not published posts.

**Comment by philipjohn** [comment]
We had an issue where unpublished posts sneaked into the feed, but that has been solved now. Is this still an issue for you, @fabianpimminger ? As I think the fix in v2 may have solved this by proxy.

**Comment by everton-rosario** [comment]
@fabianpimminger Im closing this, considering it is fixed for your case.

Please reopen or file a new issue if you find any other problems with the Instant Articles wordpress plugin or its SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/
