### ISSUE TITLE
WP Gallery not shown in FBIA-Feed

### ISSUE THREAD

**Issue by withoutfield** [Automattic/facebook-instant-articles-wp#136]
Hi there, using Version 2.7 and noticed, that WP-Galleries not shown in FBIA-Feed.
For example, code in Article:
`[gallery ids="90218,90219,90220,90221,90222,90223,90224,90225,90226,90227,90228,90229,90230,90231,90232,90233,90234,90235"]`

Code in Feed:

`<figure class="op-slideshow"/><p></p>`

without closing figure-tag.

**Comment by diegoquinteiro** [comment]
Hi, @withoutfield. Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What version of WordPress are you using?
- What version of PHP are you using (if known)?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box (both sides)?

Thanks again!

**Comment by withoutfield** [comment]
@diegoquinteiro 
Plugin 2.7
WP 4.4.2
php 5.5.9

**Comment by withoutfield** [comment]
@diegoquinteiro 
What exactly do you mean with "post edit screen on the Facebook Instant Article box (both sides)"?

**Comment by banago** [comment]
@diegoquinteiro I have the same issue, no gallery is shown on GBIA. Here are my details:

 - Plugin: latest (synced with master)
 - WP: latest (4.5)
 - PHP: 5.5.31

Here is my post editor notes notes:

![fbia-gallery-issues](https://cloud.githubusercontent.com/assets/339914/14557483/dc694adc-02fd-11e6-9142-2cc984989fab.png)

I filter the default [gallery] functionality to display a gallery [like this](http://thespaces.com/2016/04/14/luca-sironi-captures-dichotomy-justice-italian-courtrooms/):

![custom-gallery](https://cloud.githubusercontent.com/assets/339914/14557559/35c995a0-02fe-11e6-8ce3-02e75cbce117.png)

What do I have to do to fix this? Thanks very much.

**Comment by withoutfield** [comment]
After adding `add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption' ) );` to my functions.php and refreshing my gallery articles slideshows appearing in IA!

**Comment by banago** [comment]
I was using a filter for my gallery so, excluding the filter from admin view did the trick:

    if( !is_admin() ) add_filter('post_gallery', 'my_post_gallery', 10, 2);

**Comment by pcolkin** [comment]
Hi @withoutfield could you please specify where exactly did you add that code to function.php? I am experiencing the same issue.
