### ISSUE TITLE
Intext Images not shown if they have caption

### ISSUE THREAD

**Issue by withoutfield** [Automattic/facebook-instant-articles-wp#137]
I noticed, that Images placed in text not showing in the feed if they have captions.

For example, Code in Article:

```

<h3>Check deine Quellen!</h3>
[caption id="attachment_91754" align="aligncenter" width="661"]<a href="http://www.blogrebellen.de/2016/04/13/medienkompetenz/bildrebellen-2/#main" rel="attachment wp-att-91754"><img class="wp-image-91754 size-artikel-content" src="http://www.blogrebellen.de/wp-content/uploads/2016/04/bildrebellen-661x670.jpg" alt="Eine mit clonezone gefälschte BILD-Sterseite" width="661" height="670" /></a> Eine mit clonezone gefälschte BILD-Sterseite[/caption]
```

Code in Feed:

`<h2>Check deine Quellen!</h2><p>Das Video der ...`

Without Caption, the Image is shown in the feed!

Article-Code without caption:

```
<h3>Check deine Quellen!</h3>
<a href="http://www.blogrebellen.de/2016/04/13/medienkompetenz/bildrebellen-2/#main" rel="attachment wp-att-91754"><img class="wp-image-91754 size-artikel-content" src="http://www.blogrebellen.de/wp-content/uploads/2016/04/bildrebellen-661x670.jpg" alt="Eine mit clonezone gefälschte BILD-Sterseite" width="661" height="670" /></a>

```

Images shown in feed:

`<h2>Check deine Quellen!</h2><figure><img src="http://www.blogrebellen.de/wp-content/uploads/2016/04/bildrebellen-661x670.jpg"/></figure><p>Das Video der ...`

**Comment by schneidan** [comment]
+1

**Comment by diegoquinteiro** [comment]
Hi, @withoutfield and @schneidan. Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box?

Thanks again!

**Comment by schneidan** [comment]
@diegoquinteiro Yeah, no problem.

Latest version of the plugin. Debug info is in my last post.

Looking into this more myself to see what's up on my end, and I've got a function overriding `img_caption_shortcode` that adds the `figure` tags rather than relying on the html5 theme support test in media.php, which is working for article output. (example post, note `<figure>` elements around images: http://schneidan.com/2016/04/12/expired-film-day-2016-results-2003-kodak-plus-x-125-agfa/).

My functions.php does have `add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption' ) );` but it seems like the IA plugin is seeing non-html5 output from the content when it tries to transform.

Not sure if the configuration could be changed to duplicate the `figure` behavior for the selector `div.wp-caption' ?

**Comment by schneidan** [comment]
I removed the `img_caption_shortcode` override in my theme and fell back to just the html5 theme support, which is working for me on articles. Doesn't change the results in the IA debugger, though.

**Comment by OPPtester** [comment]
Could this be related? 
Some featured images have caption and they show on the web, but they don't show in IA even though I see it in the rendered code:

`<figure>
          <img src="http://www.opptrends.com/wp-content/uploads/2015/04/Microsoft_Campus.jpg"/>
          <figcaption>A building on the Microsoft Headquarters campus is pictured July 17, 2014 in Redmond, Washington. (Stephen Brashear/Getty Images)</figcaption>
        </figure>`

The featured image itself shows just not the caption.

**Comment by schneidan** [comment]
I don't think so. I think FB just doesn't show the caption on the header image.

My issue has to do with images embedded in posts with a `[caption]` shortcode.

It looks like the plugin is calling `apply_filters( 'the_content', $content )` on line 318 of class-instant-articles-post.php, and my best guess is that the filter is, for some reason, expanding the `[caption]` shortcodes with the alternate method.

in `wp-includes/media.php` on the function `img_caption_shortcode` wraps the shortcode output in `<figure>` and `<figcaption>` if `current_theme_supports( 'html5', 'caption' )` -- otherwise it uses a `<div>` and `<p>` instead, which is the error I'm seeing.

I've been Googline all afternoon and I can't figure out exactly why this would be. When I use the `the_content` filter elsewhere in my theme, the correct html5 format is output, but the plugin's debug box indicates it is not getting the right stuff. I'm not enough of a WP expert to know if it's possible that the plugin's methods are somehow skipping my theme's functions.php in testing?

**Comment by withoutfield** [comment]
I did another Testpost with different Images in text. This the the Code in the article edit:

```
Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

[caption id="attachment_3024" align="aligncenter" width="900"]<a href="http://192.168.178.202:8888/rblln/home/homa-arkani-header/#main" rel="attachment wp-att-3024"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2013/12/Homa-Arkani-Header.jpg" alt="TEST22Alternativtext" width="900" height="903" class="size-full wp-image-3024" /></a> TEST22Bildunterschrift[/caption]

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

[caption id="attachment_3000" align="aligncenter" width="670"]<a href="http://192.168.178.202:8888/rblln/2015/10/28/test-quote/attachment/88/#main" rel="attachment wp-att-3000"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2015/10/88-670x279.jpg" alt="TEST22Artikelbild &quot;waiting for the film&quot; von BMiz (CC BY-SA 2.0)" width="670" height="279" class="size-artikel-content wp-image-3000" /></a> TEST22Artikelbild "<a href="https://www.flickr.com/photos/benmizen/17277301121/">waiting for the film</a>" von <a href="https://www.flickr.com/photos/benmizen/">BMiz</a> (<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>)[/caption]

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

<a href="http://192.168.178.202:8888/rblln/2014/11/18/6-links-die-dir-zeigen-google-alles-ueber-dich-weiss/youtube-videos/#main" rel="attachment wp-att-2895"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/11/youtube-videos.jpg" alt="TEST22Alttext" width="670" height="324" class="aligncenter size-full wp-image-2895" /></a>

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

<a href="http://192.168.178.202:8888/rblln/2014/10/08/test-1200/bad-grandpa_4/#main" rel="attachment wp-att-2853"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/10/Bad-Grandpa_4-670x502.jpeg" alt="Bad-Grandpa_4" width="670" height="502" class="aligncenter size-artikel-content wp-image-2853" /></a>

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

[caption id="attachment_2770" align="aligncenter" width="670"]<a href="http://192.168.178.202:8888/rblln/2014/07/09/kursiv-test/tunaknob-big-1070x430/#main" rel="attachment wp-att-2770"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/07/TunaKnob-big-1070x430-670x269.jpg" alt="TEST22BU" width="670" height="269" class="size-artikel-content wp-image-2770" /></a> TEST22BU[/caption]

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.

<a href="http://192.168.178.202:8888/rblln/2014/06/27/galerie-testartikel/bildschirmfoto-2014-06-23-um-11-21-33/#main" rel="attachment wp-att-2741"><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/06/Bildschirmfoto-2014-06-23-um-11.21.33-670x418.png" alt="Bildschirmfoto 2014-06-23 um 11.21.33" width="670" height="418" class="aligncenter size-artikel-content wp-image-2741" /></a>

Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.
```

And this is what come thru the IA-Feed:

```
<item>
				<title>test bilder caption</title>
				<link>http://192.168.178.202:8888/rblln/2016/04/15/test-bilder-caption/</link>
				<content:encoded>
					<![CDATA[<!doctype html><html><head><link rel="canonical" href="http://192.168.178.202:8888/rblln/2016/04/15/test-bilder-caption/"/><meta charset="utf-8"/><meta property="op:generator" content="facebook-instant-articles-sdk-php"/><meta property="op:generator:version" content="1.0.5"/><meta property="op:transformer" content="facebook-instant-articles-sdk-php"/><meta property="op:transformer:version" content="1.0.5"/><meta property="op:markup_version" content="v1.0"/><meta property="fb:article_style" content="default"/></head><body><article><header><h1>test bilder caption</h1><time class="op-published" datetime="2016-04-15T09:46:11+00:00">April 15th, 9:46am</time><time class="op-modified" datetime="2016-04-15T10:25:57+00:00">April 15th, 10:25am</time><address><a href="http://blog.rebellen.info">pEtEr Withoutfield</a>Selbsternannter Crossover-Medienrebell, Musik-Nerd, Cloud-Meister und Social-Media-Schleuder.</address><h3 class="op-kicker">DJISM</h3></header><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><figure><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/11/youtube-videos.jpg"/></figure><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><figure><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/10/Bad-Grandpa_4-670x502.jpeg"/></figure><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><figure><img src="http://192.168.178.202:8888/rblln/wp-content/uploads/2014/06/Bildschirmfoto-2014-06-23-um-11.21.33-670x418.png"/></figure><p>Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar plum jelly apple pie. Chocolate bar muffin soufflé liquorice liquorice icing. Jujubes jujubes jelly bear claw carrot cake dragée macaroon. Gummi bears lemon drops croissant pudding gingerbread halvah tart. Candy wafer apple pie cookie bear claw.</p><p>&lt;figure class="op-social"&gt;&lt;/figure&gt;</p></article></body></html>]]>
				</content:encoded>
				<guid isPermaLink="false">http://192.168.178.202:8888/rblln/?p=3030</guid>
				<description><![CDATA[Lemon drops chupa chups cookie dragée pastry gummi bears ice cream cake. Macaroon bonbon chocolate bar tootsie roll dessert sugar]]></description>
				<pubDate>2016-04-15T07:46:11+00:00</pubDate>
				<modDate>2016-04-15T08:25:57+00:00</modDate>
																			<author>pEtEr Withoutfield</author>
												</item>
```

Plugin-Version 2.8
WP-Version 4.5
php 5.6.10

**Comment by OPPtester** [comment]
I agree, seems FB does not show the feature/header image caption.

I just published an article that has an image inserted and no caption. I see the image with caption on IA. The caption is the alt/title text:

Image in post:

`<img class="wp-image-22121 aligncenter" src="http://www.opptrends.com/wp-content/uploads/2016/04/Faraday-Future-Car-Concept.jpg" alt="Faraday Future Supercar Concept" width="754" height="415" srcset="http://www.opptrends.com/wp-content/uploads/2016/04/Faraday-Future-Car-Concept.jpg 1039w, http://www.opptrends.com/wp-content/uploads/2016/04/Faraday-Future-Car-Concept-300x165.jpg 300w, http://www.opptrends.com/wp-content/uploads/2016/04/Faraday-Future-Car-Concept-1024x563.jpg 1024w" sizes="(max-width: 754px) 100vw, 754px" />`

IA rendered:

`<figure>
        <img src="http://www.opptrends.com/wp-content/uploads/2016/04/Faraday-Future-Car-Concept.jpg"/>
        <figcaption>Faraday Future Supercar Concept</figcaption>
      </figure>`

Does that mean the plugin will use the alt as caption anyway? works for me, it's good to see the alt as caption I guess.

Plugin: 2.8
WP: 4.5
PHP: 5.5.33

**Comment by schneidan** [comment]
I added a couple new drafts last night, and updated a couple of older posts. It appears that the act of updating these posts has caused the plugin to find the correct markup in them, and they are now functioning correctly. So I tried going back and hitting Update on a couple more articles, without even making any changes, and it appears that the IA plugin is seeing the right markup after updating. How strange.

So, does WordPress somehow store the results of `apply_filters( 'the_content', $content)`? Or perhaps W3TC is caching that stuff rather than re-process it unless a manual action updates the story?

Meanwhile, I discovered that my header images, which obviously draw from the featured image, which is often an image I've used elsewhere in my post, are being duplicated by the images in the body. I wonder if there's any way to test for this and eliminate the duplicates, since FB says the header image can't be duplicated in the body? Perhaps that's a separate issue.

@withoutfield I'm curious if your problem stems from your theme? Is it something custom, or maybe older? Perhaps you should take a look in your `functions.php` and look for a line like `add_theme_support( 'html5', array( 'caption' ) )` and, if it's not there, try adding it and then hitting Update on a few of your stories to see if the markup comes over better?

**Comment by withoutfield** [comment]
@schneidan You nailed it! Added theme support html5, updated some articles and now all images got `<figcaption>`!
Great, thanks

**Comment by schneidan** [comment]
So I guess what the devs might consider doing is checking theme support for html5 and adding a warning to the Settings panel if it doesn't exist. Something like 

`if ( ! current_theme_supports( 'html5', 'caption' ) ): echo 'Images embedded in posts will not work without HTML5 support in your theme!'; endif;`

cc: @diegoquinteiro

**Comment by finalhit** [comment]
No need to add HTML5 support to the theme.

See https://github.com/Automattic/facebook-instant-articles-wp/issues/205#issuecomment-220780141
