### ISSUE TITLE
Gallery in instant articles

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#138]
in facebook told me that news photographs they are not suitable
I put all the photos in a standard way - [gallery ids="510732,510723,510721,510718,510714"]
what to do in this case? how to solve a problem?

**Comment by withoutfield** [comment]
same here https://github.com/Automattic/facebook-instant-articles-wp/issues/136

**Comment by lubimow** [comment]
I have this:
https://www.dropbox.com/s/m5y9moe2c2bqq8v/2g1zmi3.jpg.png?dl=0

**Comment by diegoquinteiro** [comment]
Hi, @lubimow . Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What version of WordPress are you using?
- What version of PHP are you using (if known)?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box (both sides)?

Thanks again!

**Comment by lubimow** [comment]
@diegoquinteiro 
What version of the plugin are you using?  **2.7**
What version of WordPress are you using? **4.5**
What version of PHP are you using (if known)? **7**

I did not understand the last question.
explain more

**Comment by withoutfield** [comment]
@diegoquinteiro 
Plugin 2.7
WP 4.4.2
php 5.5.9

**Comment by banago** [comment]
Let's continue this conversation over at #136.

**Comment by withoutfield** [comment]
After adding add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption' ) ); to my functions.php and refreshing my gallery articles slideshows appearing in IA!

**Comment by lubimow** [comment]
@withoutfield  I is not working

**Comment by lubimow** [comment]
I have a problem was associated with the plugin for galleries "fotorama".
I disabled it and it worked

**Comment by demoive** [comment]
Glad all the issues reported have been resolved. We'll be closing out this issue.

@lubimow, by chance do you know exactly what the [Fotorama](https://wordpress.org/plugins/fotorama/) was causing a conflict with?

**Comment by lubimow** [comment]
@demoive yes 
I had to put Carousel and everything started to work

**Comment by DJUK16** [comment]
Im having serious gallery issues! not converting not loading not been right!

**Comment by everton-rosario** [comment]
@DJUK16 hey, are you still having a problem?
You added this comment into this closed thread, so it is a long way to get this kind of comments, sorry for the long wait.

If you still have some issues, please file a new issue with repro steps and the info you are seeing about the transformation to IA Markup.
