### ISSUE TITLE
Duplicate Articles Published

### ISSUE THREAD

**Issue by OPPtester** [Automattic/facebook-instant-articles-wp#139]
This is probably due to the latest update; I have authors who write posts and publish them. I edit their articles afterwards for editing/seo purposes and update of course. Sometimes the same articles gets updates multiple times.

Today, on FB->publishing tools->instant articles I see multiple instances of the same article for many articles.

Or could this be because I upgraded Wordpress to 4.5?

**Comment by OPPtester** [comment]
Just checked again on FB->publishing tools->instant articles->production shows the multiple instances, but development does not seems right.

FB has not approved me yet by the way.

**Comment by philipjohn** [comment]
Hi @OPPtester - are you able to provide more details about these duplicates? Is there *anything* different about them at all? Any differences will help us to spot why they may be treated as separate.

Do they only appear once in your feed, or multiple times?

**Comment by everton-rosario** [comment]
@OPPtester Thanks for using Instant Article.
Im considering this issue to be fixed with the latest version of the plugin. 

Feel free if you find out any other issue to the plugin.

Thanks.
