### ISSUE TITLE
Embeds: height & width filtered in IA-Feed, Display in IA-View too small

### ISSUE THREAD

**Issue by withoutfield** [Automattic/facebook-instant-articles-wp#141]
Some Emdes are not well formatted in IA-View, they are always to small.
If I take a look in the IA-Feed I notice, that there are no more height & width attributes in embed code.

For example, here is how a SoundCloud Emded looks without height/width.
https://drive.google.com/file/d/0BxVBtE8_BT92Tjk5SmFIeGlpdFE/view?usp=sharing

Is there a reason why these attributes are filtered and how can I fix this?

Cheers & Thanks

**Comment by diegoquinteiro** [comment]
Thanks one more time for the reporting =)

We'll attempt to reproduce the issue and will get back in touch for some more information if we aren't able to reproduce on our end.

Thanks again!

**Comment by withoutfield** [comment]
Same Problem with Vimeo!
Vimeo Link pasted in Article Body (oEmbed) 

Code on my Website:
`<p><iframe src="https://player.vimeo.com/video/161613650" width="1200" height="675" frameborder="0" title="First and Final Frames of Series" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>`

Code in IA-Feed:
`</p><figure class="op-social"><iframe src="https://player.vimeo.com/video/161613650"></iframe></figure><p>`

There is no width/height :/

Plugin 2.8
WP 4.4.2
php 5.5.9

**Comment by withoutfield** [comment]
Soundcloud now shows pretty in IA.

**Comment by withoutfield** [comment]
fixed this with `<div class="interactive">embed-code</div>`
