### ISSUE TITLE
oEmbeds on self are op-social

### ISSUE THREAD

**Issue by bactisme** [Automattic/facebook-instant-articles-wp#142]
Hi,

We use quite often the new wordpress own oembeds provider, simply putting a link on a another article inside the post.  

The generated code in the feed looks like this : 

`
    <blockquote><a href="http://www.numerama.com/business/162745-facebook-lance-linvasion-des-bots-dans-messenger.html#utm_medium=distibuted&amp;utm_source=fbinstant&amp;utm_campaign=162864">Facebook lance l’invasion des bots dans Messenger</a>
    </blockquote>
    <figure class="op-social"><iframe src="http://www.numerama.com/business/162745-facebook-lance-linvasion-des-bots-dans-messenger.html/embed/#?secret=PTtV8rXzEf"></iframe></figure>
`

It of course doesn't work. It shoule be op-interactive instead of op-social since my service is of course not know from facebook.

**Comment by diegoquinteiro** [comment]
Hi, @bactisme. Thanks for the reporting this with clear reproduction steps!

We'll attempt to reproduce the issue and will get back in touch for some more information if we aren't able to reproduce on our end.

Thanks again!

**Comment by demoive** [comment]
Hi @bactisme. The oEmbed you're using is likely generating markup in your post that is not fully recognized by the [Transformer](https://github.com/facebook/facebook-instant-articles-sdk-php) used by this plugin to produce the Instant Article. Fortunately, you can configure it to do so and we've recently extended our documentation with a section dedicated help configuring [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules).

Hopefully this gives you enough to get you started in defining the rules needed to make the transformation of your article in the way that you expect it to. Some observations which may be of help:

In the code sample you shared, I see two sibling elements:

```html
<blockquote>
  <a href="http://www.numerama.com/business/162745-facebook-lance-linvasion-des-bots-dans-messenger.html#utm_medium=distibuted&amp;utm_source=fbinstant&amp;utm_campaign=162864">
    Facebook lance l’invasion des bots dans Messenger
  </a>
</blockquote>
```

```html
<figure class="op-social">
  <iframe src="http://www.numerama.com/business/162745-facebook-lance-linvasion-des-bots-dans-messenger.html/embed/#?secret=PTtV8rXzEf"></iframe>
</figure>
```

... which I assume are both from the generated Instant Article? If so, this leads me to believe that the built-in rules of the transformer are (1) successfully handling the 1st block and (2) also successfully transforming the 2nd block, but as you say: not in a way that you expected. Your own custom rules should be able to address both concerns.

If you find you are unable to define your own custom rules to resolve this case (1) try getting help from the [community on the WP Forum](https://wordpress.org/support/plugin/fb-instant-articles) and (2) we'd appreciate feedback on what part of the documentation that is lacking.

Additionally, if you think your scenario is common enough where this plugin should support this case by default, please open an issue for consideration and provide an example the markup *before* it's generated into an Instant Article to help in creation of the rule.

**Comment by bactisme** [comment]
You 100% are right :
- The two elements i gave are html codes produced by fb instant article plugin.
- IA transform the two elements quite correctly (except op-social / op-interactive) 
- I could use custom rules to produce correct html

But ... 
wordpress post oembed is now a standard wordpress feature. Plugin users might expect that all WordPress features are correctly handled by this instant article plugin. So I still think it's a open bug or at least a missing feature.

**Comment by demoive** [comment]
@bactisme I've opened up #236 for native support of oEmbeds. In that task, could you provide the following from your scenario:

- the oEmbed code you put into the content
- the full *Source Markup* (before the transformation is done)
- the full *Transformed Markup* (essentially, the two sibling elements from my previous comment)

Thanks!
