### ISSUE TITLE
empty Page after FB-Login

### ISSUE THREAD

**Issue by withoutfield** [Automattic/facebook-instant-articles-wp#143]
After I connect to the FB-App and click "login to Facebook" my Site looks like this:

https://drive.google.com/file/d/0BxVBtE8_BT92Ny0tdGMxOGI2VVU/view?usp=sharing

No Popup is opening. 

Plugin-Version 2.7

**Comment by YOzaz** [comment]
I had this issue as well.
Deactivating / activating the plugin solved issue for me.

**Comment by withoutfield** [comment]
Hm, tried it. Unfortunately I still have this Problem :/
Thanks anyway

**Comment by diegoquinteiro** [comment]
Hi, @withoutfield. Thanks for the feedback.

Could you provide some more information about the issue you're having? That will help us reproduce the issue.

- What version of the plugin are you using?
- What version of WordPress are you using?
- What version of PHP are you using (if known)?
- What's the debug output shown in the post edit screen on the Facebook Instant Article box?

Also, can you change WP_DEBUG to true on your wp_config.php file and share any warning/error shown after this?

Thank you again!

**Comment by simonengelhardt** [comment]
@withoutfield we have not been able to reproduce this so far. Are you still running version 2.7 of the plugin or have you had a chance to upgrade to 2.8 (the latest version)? If you could provide any of the information requested above that would be super helpful. Thanks!

**Comment by philipjohn** [comment]
Closing for lack of info - feel free to re-open to provide more detail!
