### ISSUE TITLE
Tool: Shell script to install/update the plugin

### ISSUE THREAD

**Issue by banago** [Automattic/facebook-instant-articles-wp#146]
I put together this little shell script to speed up the install/update of the plugin. With the hope it's going to come handy to some of you, I'm publishing it here:

```bash
#!/usr/bin/env bash

# Grab latest version
printf "Getting latest version...\n"
wget -q https://github.com/Automattic/facebook-instant-articles-wp/archive/master.zip

# Unzip latest version
printf "Unzipping...\n"
unzip -q -o  master

# Install/update libraries
printf "Updating dependencies...\n"
cd facebook-instant-articles-wp-master/
composer install
cd ..

# Remove Zip
printf "Removing archive...\n"
rm ./master
printf "DONE!\n"
```
Best of luck!

**Comment by diegoquinteiro** [comment]
Hi banago! Thank you so much for this =)

You can always use the WP dashboard to update to the last stable version, but that's definitely handy to catch up with master.

**Comment by banago** [comment]
@diegoquinteiro my pleasure. I wasn't aware this plugin is in WP repo. What's the link there?

**Comment by diegoquinteiro** [comment]
Here is it: https://wordpress.org/support/plugin/fb-instant-articles

Thanks =)
