### ISSUE TITLE
Feed generation is really slow causing PHP Fatal timeouts in some environments

### ISSUE THREAD

**Issue by onpubcom** [Automattic/facebook-instant-articles-wp#147]
Using the latest wordpress.org release of the plugin (v2.7), the feed generation process takes really long leading to PHP Fatal errors along the lines of:

PHP Fatal error: Maximum execution time of 30 seconds exceeded in wp-includes/wp-db.php on line 1767

PHP Fatal error: Maximum execution time of 30 seconds exceeded in fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Rules/ConfigurationSelectorRule.php on line 0

PHP Fatal error: Maximum execution time of 30 seconds exceeded in fb-instant-articles/vendor/symfony/css-selector/XPath/Translator.php on line 159

Are there plans to optimize how fast the feed can be generated?

**Comment by diegoquinteiro** [comment]
Hi, @onpubcom. Thanks for the feedback.

We're working to improve our RSS generation. But we do recommend using the API integration instead. You can do this by following the instructions to connect to your Facebook Page on the plugin Settings. When you do this, your posts will be automatically submitted as you save them, and you can stop using the RSS.

Thanks again!

**Comment by onpubcom** [comment]
Sounds great, thanks for the quick response, we'll look in to doing what you suggested!

**Comment by a-zog** [comment]
Great ! Since it's possible to make it without the RSS, would be awesome if we can switch it off from the settings page.

Thank you for your efforts anyway

**Comment by demoive** [comment]
Related: https://github.com/facebook/facebook-instant-articles-sdk-php/issues/49
Fixed: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/46

**Comment by onpubcom** [comment]
👍
