### ISSUE TITLE
Turkish Letter Problem for img src

### ISSUE THREAD

**Issue by mustafaozkan** [Automattic/facebook-instant-articles-wp#148]
Hi,

I have a problem for img src.
my all images have turkish letter like ş,ç,ı,ğ,ü,ö

for example,
kyk-sözleşmeli-personel-alımı-2016.jpg

system parse like that.

kyk-s& #xF6;zle&# x15 F;meli-personel-al&#x1 31;m&#x 13 1;-2016.jpg

So my all feeds not running on facebook ?

How can i fix ?

**Comment by diegoquinteiro** [comment]
Hi, @mustafaozkan. Thanks for the reporting this with clear reproduction steps!

We'll attempt to reproduce the issue and will get back in touch for some more information if we aren't able to reproduce on our end.

Thanks again!

**Comment by mustafaozkan** [comment]
@diegoquinteiro Thank you for your interesting and for your awesome plugin :+1:

**Comment by demoive** [comment]
Related: https://wordpress.org/support/topic/problems-with-nordic-letters-%C3%A6-%C3%B8-and-a
