### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by EBuzznet67** [Automattic/facebook-instant-articles-wp#149]
Warning: require(/home/ebuzznet/public_html/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/ebuzznet/public_html/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

**Comment by maevecath** [comment]
Ran into the same issue!

**Comment by partcoffee** [comment]
Read the installation section or go to [releases](https://github.com/Automattic/facebook-instant-articles-wp/releases).

**Comment by diegoquinteiro** [comment]
@EBuzznet67 you can also download the latest version from the WordPress plugin repository.
