### ISSUE TITLE
Content from ACF

### ISSUE THREAD

**Issue by partcoffee** [Automattic/facebook-instant-articles-wp#150]
For more control we often publish all our content through advanced custom fields (ACF), and we rarely use the_content(). So while the rendered page looks fine in terms of markup, your plugin can't find any source markup apart from the default featured image, title and meta tags – and thus refuses to generate the item altogether.

However, a single character in the default WordPress content editor will generate a new item in the RSS feed, and ~~pick up on certain custom fields (a single H3), but far from all of them~~ the category as an H3 — so no ACF data what so ever.

Thoughts?

*Update: Is it simply generating the markup before the ACF markup, and therefore not picking up on it? Is it possible to reverse that order perhaps, if that's the case?*

**Comment by stuartshields** [comment]
@partcoffee As a test try something like this in your `functions.php` file:

```php
add_filter( 'instant_articles_content', 'test_function' , 10, 1 );
public function test_function( $content ) {
	print_r('IA filtered content');
	print_r($content);
	
	$content = get_the_content();
	print_r('unfiltered content');
	var_dump(content);
	
	return $content;
}
```

Check your Instant Articles feed for the output, maybe paste it in here if you have issues?

**Comment by partcoffee** [comment]
```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		<title>Test Agency - Instant Articles</title>
		<link>http://localhost:8888</link>
		<description>Test Tagline</description>
					</channel>
</rss>
```

Still completely blank when the default content editor field is empty. As a comparison, this happens if I add a test paragraph to the default content editor and publish:

```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		<title>Test Agency - Instant Articles</title>
		<link>http://localhost:8888</link>
		<description>Test Tagline</description>
								<item>
				<title>Test</title>
				<link>http://localhost:8888/test/</link>
				<content:encoded>
					<![CDATA[<!doctype html><html><head><link rel="canonical" href="http://localhost:8888/test/"/><meta charset="utf-8"/><meta property="op:generator" content="facebook-instant-articles-sdk-php"/><meta property="op:generator:version" content="1.0.3"/><meta property="op:transformer" content="facebook-instant-articles-sdk-php"/><meta property="op:transformer:version" content="1.0.3"/><meta property="op:markup_version" content="v1.0"/><meta property="fb:use_automatic_ad_placement" content="true"/><meta property="fb:article_style" content="default"/></head><body><article><header><figure><img src="http://localhost:8888/wp-content/uploads/2016/04/Test"/></figure><h1>Test</h1><time class="op-published" datetime="2016-04-14T11:04:47+00:00">April 14th, 11:04am</time><time class="op-modified" datetime="2016-04-15T06:20:32+00:00">April 15th, 6:20am</time><address><a>Magnus</a></address></header><p>test</p></article></body></html>]]>
				</content:encoded>
				<guid isPermaLink="false">http://localhost:8888/?p=1</guid>
				<description><![CDATA[test]]></description>
				<pubDate>2016-04-14T11:04:47+00:00</pubDate>
				<modDate>2016-04-15T06:20:32+00:00</modDate>
																			<author>Magnus</author>
												</item>
							<lastBuildDate>2016-04-15T06:20:32+00:00</lastBuildDate>
			</channel>
</rss>
```

**Comment by partcoffee** [comment]
Any updates on this? I've tried adding custom transformer rules, but still no luck. Sorry, I'm sure I'm missing something obvious!

**Comment by donaldG** [comment]
@partcoffee On your output of ACF fields you could try
```
$acf_content_fields = get_filed('acf-content-your-name-stuff');
apply_filters('the_content', $acf_content_fields);
```
Then it would pass all your ACF content through the_content(); filter

**Comment by demoive** [comment]
Just wanted to log a related issue from the WordPress forums. If this issue is ever resolved, would be nice to ping this thread as well: https://wordpress.org/support/topic/custom-fields-acf-for-author

**Comment by philipjohn** [comment]
How do you construct posts for the frontend, @partcoffee ?

If you're not using the normal content editor to store content, and using ACF instead, how do you get the value of those ACF fields printed out to the page when viewing a single post?

I'm imagining either a filter on `the_content` or a template file?

The plugin relies on `the_content()` so if that's being bypassed you'll need to reconstruct the building of post content for your FBIA feed.

**Comment by partcoffee** [comment]
I eventually scrapped the whole ACF thing for Instant Articles, but a way I managed to get parts of it working was through this, returning the content with the primary default `the_content`:

```
add_filter('the_content','add_acf_field');
add_filter('instant_articles_content','add_acf_field');
function add_acf_field($data) {
    $data .= get_field('acf_custom_text');
    return $data;
}
```

Ideally, I would have liked to structure my whole site with ACFs, but it seems to need at least one character in the default content editor to be initiated — unless I want to write additional functions for it to work.

**Comment by philipjohn** [comment]
Okay, cool, glad you got it sorted - and thanks for sharing that. Hopefully that'll help others.
