### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by 7onmoy** [Automattic/facebook-instant-articles-wp#152]
After activating the plugin, the whole site came down with error:

"The database couldn't be reached"

Upon checking the mysql, it gave error "Too many connections". I deleted the Facebook-instant articles plugin folder from the server. The site came up momentarily. But it went down again. Same error. Too many connections.

How to uninstall it completely? How do I uninstall the dependencies installed through composer? I'm sure they're creating this error. Please help.

**Comment by banago** [comment]
If you have deleted the folder, the dependencies have gone too because they reside inside the plugin directory. Seems you are having a traffic spike.

**Comment by 7onmoy** [comment]
Resolved.

Seems like even after deleting the folder, the connections to the db were not released. Restarting the db did the trick.

**Comment by banago** [comment]
:+1:
