### ISSUE TITLE
Have settings to set the articles in the feed

### ISSUE THREAD

**Issue by jashsayani** [Automattic/facebook-instant-articles-wp#155]
It would be nice to be able to have a "Settings" tab inside the Instant Articles page in Dashboard (or an Instant Articles section inside the Settings menu) where you have text fields to set the number of articles in the feed.

**Comment by YOzaz** [comment]
Other settings would be nice as well. E.g. custom field which would tell if article should be included in a feed.

**Comment by demoive** [comment]
Thanks for these suggestions.

@YOzaz your suggestion is tracked in #186.
@jashsayani I've added your suggestion to the same #186 issue.

We'll close this out to avoid duplication.
