### ISSUE TITLE
Consolidate the instructions in the Instant Articles page in Dashboard

### ISSUE THREAD

**Issue by jashsayani** [Automattic/facebook-instant-articles-wp#156]
When you go to the Instant Articles page in Dashboard, there are steps to set it up (step 1, step 2, etc). It would be nice to have a single set of instructions instead of having 3 different set of steps for setup.

This is essentially a request to enhance the UI. When I go to the page, it would be nice to see:
Big "1", and text box to enter App ID and Secret
Big "2", and a "Connect to Facebook" to select app
Big "3" for initial settings
Then show an alert with my feed url.

... or something of that nature, so a novice person can easily figure it out without digging around.

**Comment by jeremyclarke** [comment]
I think this is done. Close ticket?

**Comment by everton-rosario** [comment]
Nice catch @jeremyclarke .
Let us know in a new issue if you feel the docs/instructions are confusing or misleading.
