### ISSUE TITLE
Sends empty post when we bulk update

### ISSUE THREAD

**Issue by punit2502** [Automattic/facebook-instant-articles-wp#160]
When we bulk update posts, plugins sends empty instant articles to facebook

**Comment by diegoquinteiro** [comment]
Hi, @punit2502. Thanks for the reporting this with clear reproduction steps!

We'll attempt to reproduce the issue and will get back in touch for some more information if we aren't able to reproduce on our end.

Thanks again!

**Comment by demoive** [comment]
A fix for this was deployed in v2.9.
