### ISSUE TITLE
Multiple <![CDATA[...]]> when wrapping <script> (Facebook oEmbed)

### ISSUE THREAD

**Issue by abdusfauzi** [Automattic/facebook-instant-articles-wp#162]
@demoive I added the codes into my functions.php to improve social oEmbed recognition:

```
function vckt_social_embed_type( $provider_name, $url ){
    $wp_oembed = new WP_oEmbed();
	$provider_url = $wp_oembed->get_provider( $url );

	if ( false !== strpos( $provider_url, 'vimeo.com' ) ) {
		$provider_name = 'vimeo';
	} elseif ( false !== strpos( $provider_url, 'youtu.be' ) ) {
		$provider_name = 'youtube';
	} elseif ( false !== strpos( $provider_url, 'facebook.com' ) ) {
		$provider_name = 'facebook';
	}

    return $provider_name;
}
add_filter('instant_articles_social_embed_type', 'vckt_social_embed_type', 10, 2);
```

however, once it detected Facebook url thru oEmbed, the xml produced has `<![CDATA[ ... ]]>` around Facebook's oEmbed scripts. This broke XML as there are now double

```
<![CDATA[
    ...
    <![CDATA[ ... ]]>
    ....
]]>
```

This is the oEmbed produced.

```
<figure class="op-social"><iframe>
<div id="fb-root"/>
<p><script><![CDATA[(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id;  js.src = "//connect.facebook.net/ms_MY/sdk.js#xfbml=1&version=v2.3";  fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));]]></script></p>
<div class="fb-video" data-href="https://www.facebook.com/thevocket/videos/1686986014891705/" data-width="728">
<div class="fb-xfbml-parse-ignore">
<blockquote cite="https://www.facebook.com/thevocket/videos/1686986014891705/"><p><a href="https://www.facebook.com/thevocket/videos/1686986014891705/">Iklan Komersial Mesotropin</a></p>
<p>Vocket Fitness dikuasakan oleh Mesotropin HQ. Artikel lanjut di http://vckt.co/1T9WhNP</p>
<p>Posted by <a href="https://www.facebook.com/thevocket/">The Vocket</a> on 2hb Mac 2016</p>
</blockquote>
</div>
</div>
</iframe></figure>
```

**Comment by philipjohn** [comment]
Hi @abdusfauzi , can you elaborate on the need for your `vckt_social_embed_type()` function please? Those embeds *should* be handled automatically by the plugin.

**Comment by abdusfauzi** [comment]
@philipjohn i was trying to force the plugin to embed these two urls into feed xml

https://www.facebook.com/kazlan/videos/vb.683701305/10154008848741306/?type=3&theater
https://www.facebook.com/MFMiraFilzah/posts/181097478934711:0

i have both links in my post content, however, they were omitted from
```
<content:encoded>
     <![CDATA[ ... ]]>
</content:encoded>
```

**Comment by everton-rosario** [comment]
This should be fixed in the latest release of SDK.
Please update your SDK by running:

1. Open your command prompt terminal
2. Change dir to your plugin folder: usually /wp-content/plugins/facebook-instant-articles-wp
3. Run "composer update && composer install"

If you dont have composer, check how it works from the docs of SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/issues

**Comment by abdusfauzi** [comment]
@everton-rosario oh. alright, will update. didn't realised the plugin also utilise composer as update method.

**Comment by abdusfauzi** [comment]
@everton-rosario after updating to the latest SDK, using the `composer` command, this url which rendered nicely in WordPress content, does not present in the instant-articles xml feed.

https://www.facebook.com/MFMiraFilzah/posts/181097478934711:0

Screenshot:
---
![](http://i.imgur.com/RlMGjsh.png)
---
