### ISSUE TITLE
Can definition lists be used in Instant Articles?

### ISSUE THREAD

**Issue by schneidan** [Automattic/facebook-instant-articles-wp#164]
Can't find any clear answers in FB's documentation, but seeing this error on articles using def. lists:

`No rules defined for <dl> in the context of InstantArticle`

**Comment by philipjohn** [comment]
Hmm, I can't see anything in the docs on this. Perhaps @diegoquinteiro has a better answer?

**Comment by everton-rosario** [comment]
No DL can be used. 
We just accept <ul>  and <ol>.

Check it here: https://developers.facebook.com/docs/instant-articles/reference

**Comment by schneidan** [comment]
Any chance of converting them to other elements instead of just omitting them?
