### ISSUE TITLE
"Login With Facebook" returns to error 404 after successful Authorization

### ISSUE THREAD

**Issue by Asif2BD** [Automattic/facebook-instant-articles-wp#168]
Using latest version 2.8, with WordPress 4.4.2 (will update to 4.5 in next few hour, and will post if that solves, which I don't think will make any difference). Using latest version of PHP 7.

The link returns to an url like below
http://domain.com/wp-admin/"app-secret'&tab=profile#_=_

It shows real app secret, and gives solid 404. 

I have tested switching to PHP 5.6 and we are on NGINX server.

**Comment by langermank** [comment]
Any luck with this issue?

**Comment by philipjohn** [comment]
Hi @Asif2BD can you confirm exactly which version this was with, and if you still have the same issue with 2.11? Thanks!

**Comment by everton-rosario** [comment]
@Asif2BD Thanks for using Instant Articles. Do you have any more info regarding your login problem?

Please feel free to reopen or to file another issue regarding this problem.

**Comment by Asif2BD** [comment]
I still have the same issue in 2.1.1 wit WP 4.5.3.

**Comment by Asif2BD** [comment]
@everton-rosario could you please re-open?
