### ISSUE TITLE
Issues when submitting to Facebook

### ISSUE THREAD

**Issue by bfrye26** [Automattic/facebook-instant-articles-wp#169]
so two major things have caused issues with submitting to facebook. These included two major areas the Jetpack titled gallery was ignored making facebook review to report an error. If this was possible to ensure it just displayed one image it would help things out.

The other is review elements. They again are ignored. I tried adding in:

```
{
                "class": "PullquoteCiteRule",
                "selector" : "//div[class=final-words]"
            },

```

to the Custom transformer rules but that did not seem to really do anything. As of right now facebook needs these things fixed but I am stummped

**Comment by everton-rosario** [comment]
@bfrye26 Thanks for using Instant Articles. Do you have more info about your case?
We need the HTML code your WP has generated regarding this so we can help better with the transformation rules.

**Comment by timjacobi** [comment]
Closing as it hasn't been responded too in over a year.
