### ISSUE TITLE
Fatal error in Facebook over last few days

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#170]
Hi,

We had our feed exporting nicely but all of a sudden over the last 3-4 days, we've been seeing this error inside of FB:

General Fatals: Sorry, We Couldn't Parse the Article: Don't worry, we are looking into this! Please try again shortly.

Is this a FB issue?

Copy of feed can be seen here: http://craziestsportsfights.com/feed/instant-articles

**Comment by equa2k9** [comment]
The same problem
[http://botrend.no/instant-articles](http://botrend.no/instant-articles)

**Comment by everton-rosario** [comment]
@samichamoun @equa2k9 Thanks for using Instant Articles.
We had few issues within our ingestion backend server. Do you still experience the issues?

Im closing, but feel free to reopen or file another issue task.
