### ISSUE TITLE
Problem with Custom Shortcodes Video Embed

### ISSUE THREAD

**Issue by eustasskid** [Automattic/facebook-instant-articles-wp#171]
Hello, I'm using custom shortcodes to embed youtube and facebook videos. Example: [customyoutube id="XXXXX"] where XXXXX is the youtube video ID. The reason for this is that I added callback functions when the video finished playing. Now my problem is, Instant Articles render the shortcode as part of the content, thus the javascript part of the shortcode is displayed as paragraph block in the Instant Articles. Please kindly advice me how to transform the shortcode so that the output is IA compliant video embed. Thank you in advance.

**Comment by mdotk** [comment]
I have the same issue. The following is from source markup:

`<div class="su-youtube su-responsive-media-yes"><iframe width="600" height="400" src="http://www.youtube.com/embed/lWVWfpG_6A8" frameborder="0" allowfullscreen="true"></iframe></div>`

It disappears completely in transformed markup and Facebook rejects my request for inclusion to IA because of it.

**Comment by mdotk** [comment]
My issue above was fixed by paulo in the Wordpress support forums for this plugin. His solution was:

```
{
    "rules":
    [
        {
            "class": "SocialEmbedRule",
            "selector" : "div.su-youtube",
            "properties" : {
                "socialembed.url" : {
                    "type" : "string",
                    "selector" : "iframe",
                    "attribute": "src"
                }
            }
        }
    ]
}
```

**Comment by eustasskid** [comment]
I'm using the respective Javascript Api of Youtube and Facebook to embed their videos. And the javascript codes are displayed as paragraph block in the Instant Articles. Is it possible to render the custom shortcode so that it will return the Instant Articles formatted embed rather than the original codes I use in my site? Thanks for the help.

**Comment by donaldG** [comment]
Super helpful here! Our feed got denied due to video content as well, this helped me fix!

**Comment by demoive** [comment]
Glad that did the trick for you guys. This issue can be marked as closed.

Note, there is a separate issue logged to see about supporting this case by default in the plugin:https://github.com/Automattic/facebook-instant-articles-wp/issues/235
