### ISSUE TITLE
Images without <p>

### ISSUE THREAD

**Issue by partcoffee** [Automattic/facebook-instant-articles-wp#172]
Hi, the plugin is not picking up images unless I wrap them in a paragraph tag. Intentional? If so, is there a way to make it pick up on them?

We usually remove paragraph in our `functions.php`:

```
function filter_ptags_on_images($content){
   return preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
}
add_filter('the_content', 'filter_ptags_on_images');
```

**Comment by stuartshields** [comment]
@partcoffee Have you tried doing this inside of `instant_articles_content` filter instead?

**Comment by partcoffee** [comment]
Not quite sure how that would help to be honest, sorry! Still quite new to this. Ideally it should just pick up any images under the article tag. I can probably work with images wrapped in paragraphs, but I'd rather not.

**Comment by stuartshields** [comment]
You need to go through and read how the plugin is structured, a lot of issues are normally resolved by looking at the plugin code. The plugin itself is doing it's own `the_content` filtering.

However you might want to look into `Custom transformer rules` as it might resolve your issue.

Something like:

`php
{
    "rules":
    [{
        "class": "ImageRule",
        "selector": "figure|//img|//p[img]|//p[a[img]]|//a[img]",
        "properties": {
			"image.url": {
	                "type": "string",
	                "selector": "img",
	                "attribute": "src"
	        },
	        "image.caption": {
                "type": "element",
                "selector": "img"
            },
        }
    }]
}        
`

**Comment by everton-rosario** [comment]
@partcoffee Thanks for using Instant Articles.
This issue must be fixed by the latest SDK version and WP plugin rules.
https://github.com/facebook/facebook-instant-articles-sdk-php
