### ISSUE TITLE
Like button not showing next to article?

### ISSUE THREAD

**Issue by ewrightmedia** [Automattic/facebook-instant-articles-wp#175]
Hey Guys, not sure if something is incorrect on my part, but I don't see the like button showing up next to the main article headline.

The accent color is not set to white. Any insight majorly appreciated.

Thank you!

**Comment by ewrightmedia** [comment]
Oops, if you like the page, the like button will not show haha! Wanted to update this, thanks!

**Comment by everton-rosario** [comment]
@ewrightmedia Thanks for using Instant Articles.
Im glad you could find your way to solve the issue.

Sorry by late response.
