### ISSUE TITLE
Likes and comment on images by default?

### ISSUE THREAD

**Issue by ErikXXon** [Automattic/facebook-instant-articles-wp#178]
I use this rules and can get the likes and comments on single image **without caption**. Can anybody help me how I can get this to work with both caption and galleryslide.

`{
    "rules":
    [{
        "class": "ImageRule",
        "selector": "img",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            },
            "image.caption": {
                "type": "element",
                "selector": "img[@alt]"
            },
            "image.like" : {
                "type" : "exists",
                "selector" : "img"
            },
            "image.comments" : {
                "type" : "exists",
                "selector" : "img"
            }
        }
    }]
}`

Thanks in advance

**Comment by ErikXXon** [comment]
This rule is that Ill try to get to work

{
    "rules":
    [{
                "class": "ImageRule",
                "selector" : "figure",
                "properties" : {
                    "image.url" : {
                        "type" : "string",
                        "selector" : "img",
                        "attribute": "src"
                    },
                    "image.like" : {
                        "type" : "exists",
                        "selector" : "figure[data-feedback*='fb:likes']",
                        "attribute": "data-feedback"
                    },
                    "image.comments" : {
                        "type" : "exists",
                        "selector" : "figure[data-feedback*='fb:comments']",
                        "attribute": "data-feedback"
                    }
                }
            }]
}

**Comment by ErikXXon** [comment]
I got 
WP: 4.5
Plugin: 2.9

**Comment by everton-rosario** [comment]
Duplicated issue with this: #36

**Comment by timjacobi** [comment]
Closing as duplicate.
