### ISSUE TITLE
Single media element 'must be in body, with no media in cover'

### ISSUE THREAD

**Issue by imsimond** [Automattic/facebook-instant-articles-wp#18]
_Feedback from Facebook following submission of IA feed for sports.nbcsports.com. The quoted links probably won't be visible, but they may help diagnose the problem._

Single media element

If your article consists of a lone media item, such as a photo, single slideshow, or video, that content must be placed in the body of the Instant Article. To avoid repetition of the element, the cover (http://docs/instant-articles/reference/cover)%20section%20should%20not%20include%20any%20media) section should not include any media.

Additional Detail from your Reviewer:

If your article is only featuring one media element it must be in the body of the article. For more information on how to incorporate this media please see our the "Handling Images and Videos" section of our design guide here: https://developers.facebook.com/docs/instant-articles/guides/design

Examples of this error

· Horcoff suspended 20 games for PEDs (Updated) (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473)

· Azarenka, in form, and into Australian Open quarters (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473)

· Serena beats Sharapova, reaches Aussie Open semis (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473)

· Azarenka advances, Muguruza out in 3rd round in Australia Open (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473)

· World Series of Fighting 25: Who, What, When, Why and How (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473)

· Lomu, who revolutionized rugby with size, speed, dies at 40 (https://business.facebook.com/NBCSports/settings/?tab=instant_articles&business_id=736778816377473

**Comment by philipjohn** [comment]
This was only affecting WordPress.com, and is fixed by [d069ca2a792d682901cea84c672ee02aed8aff95]
