### ISSUE TITLE
Could we have a feature to optionally remove posts from the feed?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#181]
In the early days, while bugs are being ironed out, it would be great if there was an option on a post to actively remove it from the feed.

I'm sure there are valid instances where it would make sense for these to not be sent.

I'm having difficulties getting our feed approved because occasionally a post with issues (requires investigation) comes through. While I'm committed to getting the feed cleaned up, the 2-3 day turn around from FB jut to get the feed approved puts a massive hold on things.

Thoughts?

**Comment by withoutfield** [comment]
+1

I've tried this but still get an Server Error. 
https://wordpress.org/support/topic/prevent-article-from-being-included-in-the-feed?replies=5#post-8296267
Have to take some more time to check this solution, but it sound good.

**Comment by everton-rosario** [comment]
@samichamoun and @withoutfield Thanks for using Instant Articles. 
The review process exists to check a full compatibility with any partners. So taking down content just to get approved, isn't a good approach.
