### ISSUE TITLE
Adjusting analytics embed based on post data

### ISSUE THREAD

**Issue by smerriman** [Automattic/facebook-instant-articles-wp#182]
I want to set some post-specific custom variables within the Analytics embed code.

It's been mentioned several times that `instant_articles_transformed_element` can be used to filter the article - but while it looks like I can *add* to it, everything in the object parameter seems to be stored as private variables in a way that doesn't allow you to alter anything.

A couple of hacky options I've thought of:

- disable the embed code entirely, use that filter, and duplicate all of the code that adds it (not ideal, and I see there are other functions throughout the plugin which use the setting which are possibly affected?)

- somehow use the https://codex.wordpress.org/Plugin_API/Filter_Reference/option_%28option_name%29 filter to alter the embed code at the point it's fetched from the database - but this could affect what gets displayed on the admin page as well and break things.

Could you perhaps add some more filters that allow altering this content, or is there a better way?

**Comment by lesterchan** [comment]
I kinda +1 to this. When the GA code is embedded, the URL get tracked correctly, but the page title is not, it is displayed as "(not set)".

Ideally we can do something like ```ga('send', 'pageview', {title: 'POST TITLE'});```

**Comment by CarsonLee27** [comment]
Agree. I have this situation as well. I do notice there is not found in the GA display and low traffic compare to normal article we have.

**Comment by stuartshields** [comment]
You could try doing something like:

Add to functions.php
```php
public function fbia_analytics_code( $article ) {
$analytics_code = "
<script>
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

				ga('create', 'UA-XXXXXXX-1', 'auto');
				ga('set', 'title', '" . esc_js( get_the_title() ) . "');
				ga('send', 'pageview');
			</script>
"

$document = new \DOMDocument();
		$fragment = $document->createDocumentFragment();
		$valid_html = @$fragment->appendXML( $analytics_code ); 
		if ( $valid_html ) {
			$article->addChild(
				\Facebook\InstantArticles\Elements\Analytics::create()
					->withHTML( $fragment )
			);
		}
}

add_filter( 'instant_articles_transformed_element',  'fbia_analytics_code' );
```

**Comment by withoutfield** [comment]
Didn't worked for me, but this is exactly what I'm searching for.

**Comment by gecugamo** [comment]
@stuartshields that code doesn't seem to work. It breaks the instant article feed. Any ideas?

**Comment by everton-rosario** [comment]
@smerriman @withoutfield @gecugamo @CarsonLee27 @lesterchan Thanks for using Instant Articles.

We changed the behavior of withHTML() methods to receive plain string parameters.
This way it will just output whatever you pass as parameter string, without any escaping.

Please test it again using the latest version of SDK: https://github.com/facebook/facebook-instant-articles-sdk-php
In case of any issues, please file another issue.

**Comment by CarsonLee27** [comment]
@stuartshields Yes. This is something I looking forward. After I included in the functions.php, I believe we dun need to insert the GA code to  the custom embed code right? 

Or anyway to insert into custom embed code part to skip the messy code xD. 

@everton-rosario 
Nice. Is there any sample that we can include the post title into GA?
