### ISSUE TITLE
No rules and general fatals

### ISSUE THREAD

**Issue by thomaswn** [Automattic/facebook-instant-articles-wp#184]
After the latest update from 2.8 to 2.9 the plugin produces this message on the articles

> No rules defined for <html> in the context of InstantArticle

Also Facebook seems to return this error:

> General Fatals: Sorry, We Couldn't Parse the Article: Don't worry, we are looking into this! Please try again shortly.

Not sure if the latter is related to the plugin or not. EDIT: Additional research make it seem it is an issue that appears when articles are under review.

**Comment by timjacobi** [comment]
Closing as support for <4 has been dropped. Please update the plugin and open a new issue if this problem persists.
