### ISSUE TITLE
Class 'Logger' not found when activating plugin

### ISSUE THREAD

**Issue by laurentho** [Automattic/facebook-instant-articles-wp#187]
When activating the plugin, the following error appears:

`Fatal error: Class 'Logger' not found in ../wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 36`

Composer has been installed with the following lines in composer.json

`{
    "require": {
        "monolog/monolog": ">=1.0.0"
    }
}`

**Comment by GraemeFulton** [comment]
Same here, works fine for me locally, but not on redhat openshift. No idea why yet..

**Comment by GraemeFulton** [comment]
aha it looks like because 'log4php' is not being tracked by git:

![screen shot 2016-05-21 at 17 31 01](https://cloud.githubusercontent.com/assets/4354786/15449598/ed43706a-1f79-11e6-80de-60cf403c4fd1.png)

make sure it's tracked in your repo and push it - that should fix it

**Comment by everton-rosario** [comment]
@GraemeFulton thanks for your support.
@laurentho feel free to reopen if it still happens to you.
