### ISSUE TITLE
Facebook not approved (for galleries)

### ISSUE THREAD

**Issue by overpress** [Automattic/facebook-instant-articles-wp#189]
Hello, Facebook has not approved the instant article because there is no way to view the gallery. You can see it here on our site -> http://overpress.it/2016/04/15/ikea-bicicletta/

Facebook post this image -> https://scontent-mxp1-1.xx.fbcdn.net/hphotos-xaf1/t39.7075-6/13065845_461104347421905_1792789831_n.jpg

We can show the galleries in any way?

**Comment by stuartshields** [comment]
@overpress How are you generating those galleries? With a shortcode? Do you mind pasting what shortcode if that is the case.

Also as a hint, view the feed when debugging to see what's happening:
http://overpress.it/2016/04/15/ikea-bicicletta/instant-articles clearly shows no gallery.

**Comment by overpress** [comment]
No, we used the normal WordPress galleries, here are the source of the page -> https://dl.dropboxusercontent.com/u/22334399/Schermata%202016-04-21%20alle%2022.30.28.jpg

**Comment by stuartshields** [comment]
@overpress As a test if you can, remove: `td_gallery_title_input` and `td_select_gallery_slide` just to get the default gallery, does it show anything in the instant articles URL I supplied above? IF it does it could be a rules thing that you might have to setup. What plugin do you use that adds the td_gallery information in?

**Comment by overpress** [comment]
We can't delete it otherwise the gallery you would see with the style of the templates we use.

P.S. Anyway after you upgrade 2.9 version no longer see any images on instant article.

**Comment by overpress** [comment]
Up

**Comment by overpress** [comment]
Hi, is there anyone who can help us?

**Comment by everton-rosario** [comment]
@overpress Thanks for using Instant Articles.

You can try to implement a custom rule for the Slideshow component in the markup of Instant Articles: 
https://developers.facebook.com/docs/instant-articles/reference/slideshow

We are trying to get all the rules setup to cover most of common used plugins.

**Comment by overpress** [comment]
Hi, how can we do to insert the custom rule for markup?

**Comment by chaselivingston** [comment]
Related: #133

**Comment by everton-rosario** [comment]
@overpress  @chaselivingston Do any of you guys have the code?
I need more details, so we can implement transformation rules for this plugin.

Please, share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

This way we have the source markup before transforming, thus, implementing the transformation rules.

**Comment by overpress** [comment]
Hi @everton-rosario, I've shot more details here ->  https://github.com/Automattic/facebook-instant-articles-wp/issues/281

**Comment by everton-rosario** [comment]
@overpress Is that the full issue?
Did it work for you? If so we can internalize into the plugin so everybody that uses this plugin will get benefit as well.

**Comment by everton-rosario** [comment]
@overpress What do you mean by "did not work"? 
On the GIST i've shared with you, it was transforming and adding the <figcaption> tag as expected.

Can you share the details of the problem you are having now?
