### ISSUE TITLE
Fatal error after plugin instalation (solved)

### ISSUE THREAD

**Issue by georgeiMac5k** [Automattic/facebook-instant-articles-wp#191]
Hello, I've installed Instant articles WP plugin 2.9, but after activation in my WordPress administration area I  receive error message (Plugin cannot be activated in case of dangerous problem):

Warning: require(/var/www/web/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/web/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

Fatal error: require(): Failed opening required '/var/www/web/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/web/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

I am using WordPress 4.2.7. Do you have any ideas how to solve this problem?
Thank you :)

**Comment by Thielo** [comment]
1. The Plugin requires at least: WordPress 4.3 (source: https://wordpress.org/plugins/fb-instant-articles/)
2. "How" did you install it?
Did you
```
Run composer install on the root of the plugin folder. Make sure you have Composer installed.
Upload the folder to the /wp-content/plugins/ directory
Activate the plugin through the 'Plugins' menu in WordPress
```
Or did you just download it and pushed it onto you host?

Because if you don´t run the `composer install`-command it will not work. Maybe you should grab the Package over there: https://wordpress.org/plugins/fb-instant-articles/

**Comment by georgeiMac5k** [comment]
Thielo, thank you very much for reply. I didn't use the composer, my mistake. I just download the zip from github and install it over WP admin :) thanks for support, I will download package from the plugin page.
