### ISSUE TITLE
Share Count Reset

### ISSUE THREAD

**Issue by sbbic** [Automattic/facebook-instant-articles-wp#192]
When I submitted posts to be Instant Articles Facebook reset the share count on all those articles. That's fine for new articles, but I published some old articles and so our share count on those went to zero. Seems like some sort of bug.

**Comment by everton-rosario** [comment]
@sbbic Thanks for using Instant Articles.
Can you provide us more info? Like steps to reproduce, some print-screens of the steps you took?

Thanks

**Comment by timjacobi** [comment]
Closing as this hasn't been responded to in too long.
