### ISSUE TITLE
Custom Transformer Rules to Exclude Javascript Block

### ISSUE THREAD

**Issue by eustasskid** [Automattic/facebook-instant-articles-wp#193]
Can anyone provide me the correct transformer rules to exclude the everything inside the <script> block because javascript codes are displayed as text in my Instant Articles. Thank you for the replies.

**Comment by everton-rosario** [comment]
@eustasskid Thanks for using Instant Articles.
I couldn't understand the issue you are facing here. Can you please reopen with more details?

Thanks
