### ISSUE TITLE
Feature: mulitple ad slots

### ISSUE THREAD

**Issue by katsar0v** [Automattic/facebook-instant-articles-wp#194]
Currently it is possible to give one url, but then the same ad appears 3 times in the article. Is it possible to make it have different slots, or is there already a solution?

**Comment by sebpettersson** [comment]
+1

Only being able to specify one placement id is too limiting.

**Comment by everton-rosario** [comment]
@katsar0v Thanks for using Instant Articles.

Currently we have the component Ad where you can set any add you like.
Here is the doc: https://developers.facebook.com/docs/instant-articles/reference/ad
