### ISSUE TITLE
Facebook embed not working

### ISSUE THREAD

**Issue by aldnin** [Automattic/facebook-instant-articles-wp#197]
In the most recent version 2.9 jetpack is used to identify embeds for Facebook. It doesn't work, for some reasons after I debugged it: The jetpack constants are not defined at the moment they are used to be registered as handlers with the specific regex. Even when defining them, they are obviously unregistered at a later point in time, which prevents the code to apply the embedding cures in the compat class for jetpack embeds. This is a serious issue not being able to embed facebook postings in a plugin which is actually delivering content for facebook.

**Comment by everton-rosario** [comment]
@aldnin Thanks for using Instant Articles.
Do you have more info regarding this problem? Like steps to reproduce, screen shots etc?

Feel free to reopen or send another issue with the more detailed.
