### ISSUE TITLE
Allow Google Tag Manager for the custom analytics tracker code???

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#199]
I usually use Google Tag Managaer for my websites to implement Google Analytics + track some events in the pages

Ive tested and placed it manually in the publishing tools. If i try to add it in the plugin settings i get displayed this warning: **Invalid HTML markup provided for custom analytics tracker code**) and it works like a charm, but have a questions overall.

1. Is Google tag manager code allowed by Facebook to be added to the analytics tracking code?

**Comment by everton-rosario** [comment]
@gabu69 Thanks for using Instant Articles.

We don't block any code within the <iframe> tag.
Can you reopen this issue with a more detailed and step-by-step explanation on how we can reproduce this error, please?

Thanks

**Comment by thomasbacon** [comment]
I'm having this same issue as well, using default <script> provided from GTM:

`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXXX');</script>`

Also I've attached a screenshot. Thanks!

![instant-error](https://user-images.githubusercontent.com/6577933/29194207-326715ce-7dee-11e7-991e-f9b8a4e75603.png)
