### ISSUE TITLE
Jetpack YouTube wrappers breaks feed

### ISSUE THREAD

**Issue by philipjohn** [Automattic/facebook-instant-articles-wp#20]
Following on from #17 we've discovered that Jetpack's filters for YouTube embeds is causing the DOM parsing to fail to turn YouTube embeds into the right FBIA format.

Jetpack adds a `span` with a class of `embed-youtube` and that simple addition confuses this plugin which can no longer do the transformation.

I'm thinking we have 3 possible solutions:

1. Make our DOM transformation more liberal/forgiving of additional HTML to account for this
1. Have Jetpack stop adding it's wrapping `span` in feeds in general, assuming it does so for front-end purposes.
1. Have our plugin remove all filters on `the_content` before [grabbing the content](https://github.com/Automattic/facebook-instant-articles-wp/blob/bed2ee8438ec937eafaafafb2376d4c827fc0bb3/class-instant-articles-post.php#L206), circumventing oEmbed entirely. It would no longer rely on DOM manipulation.

The first option would be great, but could be complicated. I'm talking to Jetpack about the second option. The third option is likely to be too big a change to the fundamental way the plugin works.

**Comment by philipjohn** [comment]
@bjornjohansen Assigning to you following our chat last week

**Comment by rinatkhaziev** [comment]
```add_filter( 'video_embed_html', [ __CLASS__, 'ia_youtube_embed_html' ] );```

```
