### ISSUE TITLE
Feed Review from Facebook - Missing content

### ISSUE THREAD

**Issue by jashsayani** [Automattic/facebook-instant-articles-wp#201]
Hi,

I am using this plug-in and submitted by feed for review. Facebook did not accept the feed, because it does not include the text after the "More" break, in the post.

Here's the response from Facebook:
> **Missing content - text elements**
> _Additional Detail from your Reviewer:_
> Not all of the body text seen on the web is included. Please include all text seen on the web before resubmitting.

**Comment by everton-rosario** [comment]
@jashsayani thanks for using Instant Articles.
In the Instant Articles you cannot use the strategy of "more" button to show the rest of your article. The article must open all the content by upfront.
