### ISSUE TITLE
Two images in row issue

### ISSUE THREAD

**Issue by moston** [Automattic/facebook-instant-articles-wp#203]
When I have 2 images in row - it transforms feed to have only one in row. They're into the same para and I cannot do this by Transformer rules to get it work ;/

**Comment by everton-rosario** [comment]
@moston Thanks for using Instant Articles.

Do you have a HTML snipped on how these 2 images in row are disposed?
This way we can help you to configure the transformation rule in this case.

Please reopen when you have the details, so we can help you better.

Sorry for the long wait to reply.
