### ISSUE TITLE
Transformer doesn't get image components inside article content

### ISSUE THREAD

**Issue by avishayil** [Automattic/facebook-instant-articles-wp#204]
Like the title suggests, seems that the transformer can't seem to get the <img> components from inside the article content.

It gets the featured image just fine.

Example:
http://www.geektime.co.il/feed/instant-articles

**Comment by everton-rosario** [comment]
@avishayil Thanks for using Instant Articles.

The link you provided is the feed already transformed. Do you have the HTML markup where your Images are being "dropped"?

Please reopen this issue when you have the more detailed case.
