### ISSUE TITLE
Captions Stripped Out Of IA Markup

### ISSUE THREAD

**Issue by Singletrackmark** [Automattic/facebook-instant-articles-wp#205]
We are getting the following error message...

	No rules defined for <div class="wp-caption alignnone"> in the context of InstantArticle

Within our wordpress post captions use this format..

< div class="wp-caption alignnone" style="width: 1024px"><a href="http://grit.cx/wp-content/uploads/2016/04/Nigel_leech.jpg" rel="attachment wp-att-15283"><img src="http://grit.cx/wp-content/uploads/2016/04/Nigel_leech-1024x768.jpg" alt="Sunset gravel" width="1024" height="768" /></a>
<p class="wp-caption-text">Photo credit: Nigel Leech</p>
</div>

The entire image is stripped out of the final IA markup along with the caption.

**Comment by OPPtester** [comment]
[https://github.com/Automattic/facebook-instant-articles-wp/issues/137]

**Comment by Singletrackmark** [comment]
Thanks and sorry for the search fail

**Comment by finalhit** [comment]
Here are the missing rules for images with captions, hope they will be added directly to plugin:

`{"rules": [
	{
		"class": "CaptionRule",
		"selector" : "p.wp-caption-text"
	},    
	{
	"class": "ImageRule",
	"selector" : "div.wp-caption",
	"properties" : {
		"image.url" : {
			"type" : "string",
			"selector" : "img",
			"attribute": "src"
		},
		"image.caption" : {
			"type" : "element",
			"selector" : "p.wp-caption-text"
		}
	}    
 }   
]}
`

**Comment by everton-rosario** [comment]
@Singletrackmark Is this still an issue for you?
Ill close this issue for now, if needed, please reopen this issue or file another one.

Thanks for using Instant Articles.

**Comment by jeremyclarke** [comment]
@everton-rosario Why did you close this ticket without adding that transformation to the defaults? Almost all WP sites use images with captions, it's inscrutible to me that this plugin wouldn't support captions and floated captions by default.

**Comment by everton-rosario** [comment]
There was no response regarding this topic @jeremyclarke.


Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

**Comment by jeremyclarke** [comment]
This report is about any image inserted with a caption, which is done on almost all WP sites. Do you get that? It's like supporting paragraphs. 

 You can re-create the "problem" by creating a post, uploading an image, typing in a caption, then inserting it. 

Here is my source markup:

`<div id="attachment_22553" style="width: 800px" class="wp-caption alignnone"><img class="wp-image-22553 size-large" src="http://dev.advocacy/wp-content/uploads/2016/08/DSCF7239-800x552.jpg" alt="alt text" width="800" height="552" srcset="https://dev.advocacy/wp-content/uploads/2016/08/DSCF7239-800x552.jpg 800w, https://dev.advocacy/wp-content/uploads/2016/08/DSCF7239-400x276.jpg 400w, https://dev.advocacy/wp-content/uploads/2016/08/DSCF7239-768x530.jpg 768w" sizes="(max-width: 800px) 100vw, 800px" />
<p class="wp-caption-text">caption</p>
</div>
<div style="display: block !important; margin:0 !important; padding: 0 !important" id="wpp_popup_post_end_element"></div>
`

Here is my Transformed Markup:

`
<html>
  <head>
    <link rel="canonical" href="http://dev.advocacy/2016/08/16/test-ia/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article><header><h1>test ia</h1><time class="op-published" datetime="2016-08-16T22:09:37+00:00">August 16th, 10:09pm</time><time class="op-modified" datetime="2016-08-16T22:09:37+00:00">August 16th, 10:09pm</time><address>[...]</address></header></article>
  </body>
</html>
`

**Comment by everton-rosario** [comment]
Hey @jeremyclarke thanks for raising this issue you we're facing.
I've reproduced it here with your details and now It is out as a PR.

If you can't wait for it to be merged in next release, just add these lines to your custom transformation rules.


Follow this sequence to add this rule configuration: 
1. Click on the InstantArticles menu Item (usually it stays in the left menu bar)
2. It will open the InstantArticles plugin settings page.
3. Scroll down to find the section called: "Publishing Settings"
4. Enable the checkbox "Enable custom transformer rules"
5. Enter the rules within the common code as below:
```
{ "rules": [
    {
        "class": "CaptionRule",
        "selector" : "p.wp-caption-text"
    }
]}
```

**Comment by everton-rosario** [comment]
@philipjohn waiting your review and merge.
