### ISSUE TITLE
ACF Fields getting pushed to Instant Articles backend

### ISSUE THREAD

**Issue by emanuelet** [Automattic/facebook-instant-articles-wp#207]
Hi,
I wanted to report that I had an issue with a deployment on my production environment where I updated ACF from version 4.4 to 5.3 (with all the changes included) and the Instant Articles plugin version 2.9. What happened is that the plugin has pushed to Instant Articles backend all my custom fields as they were regular posts.
I'm not talking of fields that were included inside posts but the Custom fields themselves.

Luckily, I didn't had Auto-publish enabled so now I removed them, but I wanted to warn who is about to make a similar upgrade

**Comment by kevinlisota** [comment]
There are certain plugins like ACF, Gravity Forms, Woocommerce, for example, that use custom post types as data storage. Instant Articles plugin seems to not care and publishes all custom post types. There is potentially useless and even security issues around this for some of these plugins. Hopefully this gets addressed soon in this plugin.

**Comment by ioniklabs** [comment]
I had the same issue, you can use the remove_filter method to detach the Instant Articles on _save_post_ hook if your conditions aren't met. For my application I only needed articles with a _post_type_ of _post_ to be submitted.

Instant Articles sets the priority of their hook to 10 so I have used a value of 5 to ensure it is executed before theirs.

Hope this helps :)

`add_action( 'save_post', 'disable_fb_instant_article', 5, 2 );`

`function disable_fb_instant_article( $post_id, $post ) {`
`  if ( $post->post_type != 'post' ) {`
`    remove_filter( 'save_post', 'Instant_Articles_Publisher::submit_article' );`
`  }`
`}`

**Comment by emanuelet** [comment]
Will test it and let you know. Cheers
