### ISSUE TITLE
RSS feed doesn't respect WP feed length setting

### ISSUE THREAD

**Issue by brettdorrans** [Automattic/facebook-instant-articles-wp#208]
Feed URL: http://glasgowliving.today/?feed=instant-articles

This feed is only displaying 9 items, although under WordPress Admin -> Settings -> Reading -> Syndication Feed Shows the most Recent I have set the value to 50.

There appears to be no way to alter this via the plugin settings page.

Additionally, I have tried changing line 167 of facebook-instant-articles.php to increase the limit from 10 to 20 with no effect (is the RSS feed cached? I've disabled all caching plugins):

$query->set( 'posts_per_rss', 20 );

Even weirder, if I place this RSS feed into the 'production' URL, but also into 'development' in Facebook's Instant Articles settings page, it pulls different articles! In a different order! The development pulls 20 articles as expected, but production continues to pull 9.

Very strange!

Any ideas?

**Comment by brettdorrans** [comment]
Running the following on the database appeared to update the feed - so it does appear to be a caching issue:

DELETE FROM `wp_options` WHERE `option_name` LIKE ('_transient%_feed_%')

I still think the plugin should respect the WP setting for RSS feed length.

**Comment by stuartshields** [comment]
Read the code, change it in the plugin if you want to but there is a reason for it, as Facebook requires a 10 posts for Instant Articles approval. 

Here it is in the code:
https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L161

**Comment by brettdorrans** [comment]
My point is that changing it in the code does not change the output.
