### ISSUE TITLE
Parser used image alt like image caption, but need use a content inside [caption][/caption]

### ISSUE THREAD

**Issue by mrZherart** [Automattic/facebook-instant-articles-wp#212]
Parser used image alt like image figcaption, but need use a content inside [caption][/caption]

[caption id="attachment_2866" align="alignnone" width="702"]<img class="wp-image-2866 size-full" src="URL" alt="ALTERNATIVE" width="702" height="473" /> SOME CAPTION TEXT [/caption]

After image showed ALTERNATIVE text

But need showed a SOME CAPTION TEXT

**Comment by everton-rosario** [comment]
@mrZherart Is this still a problem with the latest SDK version?

Please double check and feel free to reopen this issue or file another ones.
