### ISSUE TITLE
Parser cutting content

### ISSUE THREAD

**Issue by massayoshi** [Automattic/facebook-instant-articles-wp#214]
Just installed the plugin and it seems that the parser stops when it finds the closing `</div>` for `<div class="container">` it's like that because the person who coded the theme, in order to make use of the full width image he had to close the container then open it again afterwards. I'm pretty sure there are other right ways to do that. But not being a front-end developer kinda makes it harder for me.

[example url](http://riscafaca.com.br/historia/a-ultima-familia-indios-juma/)

**edit:** perhaps it's the same issue as https://github.com/Automattic/facebook-instant-articles-wp/issues/210

**Comment by everton-rosario** [comment]
@massayoshi As we can see here, this example article looks fine in Instant Article.
Is this still a problem for you?

Please feel free to reopen this issue or open a new one.
