### ISSUE TITLE
It's not showing <pre> codes in the article

### ISSUE THREAD

**Issue by mycodingtricks** [Automattic/facebook-instant-articles-wp#216]
I found that all the <pre> codes in my articles are not showing up in Facebook instant articles.

What to do?

**Comment by FewKinG** [comment]
pre tags are not recognized by the default set of transformer rules, so they get stripped out when the post gets transformed into Instant Article markup. If you want to include them, you can for example turn them into Instant Article paragraphs, using this custom transformer rule:

```
{
  "class": "ParagraphRule",
  "selector": "pre"
}
```

However, this will of course no longer be pre-formatted text when displayed as Facebook Instant article. As far as I know, Facebook doesn't support pre-formatted text blocks in its articles, so you won't be able to do anything about that.

**Comment by everton-rosario** [comment]
@mycodingtricks Thanks for use Instant Articles. 
@FewKinG, thats exactly how it should be done, thanks.

Im closing this issue, feel free to reopen if anything needed.

**Comment by faruqsandi** [comment]
Thanks for letting me reopen this issues.

Transforming pre tag to ParagraphRule is nice, but it kinda reduces readability. Especially if we switch single line of code with a single line of the paragraph frequently.

I read this [Displaying code in Facebook instant articles 📱](https://codingislove.com/displaying-code-facebook-instant-articles/) and found out that iframe will show pre tag as is should be.

How to do this with transformer rules?

Thank you in advance.

**Comment by Jany-M** [comment]
I second @faruqsandi's request.
How do achieve an actual code embed through Transformer Rules, as referenced in that post?
`ParagraphRule` is not appropriate for code / pre embeds.

@everton-rosario
