### ISSUE TITLE
Facebook videos not embedding properly

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#217]
FB video embeds aren't showing up in our Instant Articles.  We use Jetpack and just have this URL pasted in the article:
https://www.facebook.com/CaitlynJenner/videos/1556514417981739/

but it doesn't appear in the IA that is published to FB via the API.   I see that you have code for this in the plugin, but it doesn't appear to work.

Seperately, if I use the full embed code, I get an error saying this isn't a supported embed (and the video won't play on Facebook. 
<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FCaitlynJenner%2Fvideos%2Fvb.1450224708610711%2F1556514417981739%2F%3Ftype%3D3&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>

**Comment by webprom** [comment]
When changing op-social class to op-interactive, video placeholder is shown but it can't play on tap. Weird.

Facebook video was embedded with iframe code. `<iframe style="border: none; overflow: hidden;" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2F381022878750448%2Fvideos%2F439687349550667%2F&amp;width=680&amp;show_text=false&amp;appId=562106627282565&amp;height=344" width="680" height="344" frameborder="0" scrolling="no"></iframe>`

> With op-social it gives this error: Webview with op-social class without any supported embed type: When using op-social class on a webview, it must have a supported embed inside it e.g. Instagram, Twitter, Facebook, Youtube, etc. We didn't find any here.

**Comment by everton-rosario** [comment]
@sgatz and @webprom Please check that op-social is being deprecated.
Please use op-interactive, instead.
https://developers.facebook.com/docs/instant-articles/reference/embeds

Are you still seing this issue?

Feel free to reopen the issue.
