### ISSUE TITLE
Post Editor Stuck in 'Saving Draft' Mode

### ISSUE THREAD

**Issue by mayankgarg99** [Automattic/facebook-instant-articles-wp#219]
After activating the plugin, i am unable to post articles easily. After writing some content, post editor goes into saving draft mode. Buttons like publish, save draft becomes inactive.
![fb-instant-error](https://cloud.githubusercontent.com/assets/19153346/14960442/499c62b2-10b2-11e6-824e-433906a97f9e.jpg)

After deactivating the plugin i am not facing this issue. So the plugin has some issue with wordpress posts.

**Comment by everton-rosario** [comment]
@mayankgarg99 @HammyHavoc Are you still facing this issue?
Can you reproduce on the latest version so far (now it is v3.3.3)?

Im closing this for awhile. Reopening if error reported.
