### ISSUE TITLE
how to incorporate third-party video  (<script>)

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#220]
on our site, use the following player.

<script src="//cdn.playwire.com/bolt/js/zeus/embed.js" type="text/javascript" data-config="//config.playwire.com/1009112/videos/v2/4789919/zeus.json" data-height="100%" data-width="100%"></script>

How to display it in the instant artikles?

**Comment by everton-rosario** [comment]
@lubimow Do you have more details about the issue you are facing?

For custom players, you should use the op-interactive tag:
https://developers.facebook.com/docs/instant-articles/reference/embeds

Im closing this issue. Feel free to reopen, if needed.

**Comment by lubimow** [comment]
@everton-rosario I have seen instructions. The question is how to do it automatically? 
to each news it will automatically appear.
