### ISSUE TITLE
Facebook Compliant Tags Being Filtered Out

### ISSUE THREAD

**Issue by alexdelgado** [Automattic/facebook-instant-articles-wp#221]
Hey -

I've had to add the following rules to the ignore list even though they are facebok compliant.

`{
  "rules": [
    {
      "class": "PassThroughRule",
      "selector": "figure.op-social"
    },
    {
      "class": "PassThroughRule",
      "selector": "figure.op-slideshow"
    },
    {
      "class": "PassThroughRule",
      "selector": "figure.op-ad"
    }
  ]
}`

For some reason however, ".op-ad" is replaced with ".op-social". I'm not sure what's going, but it would be great to have it working..

**Comment by everton-rosario** [comment]
@alexdelgado Is this still happening to you?

op-social have been deprecated, so the only one that will work will be the op-interactive.

Can you double check with the latest version of the SDK?
Please feel free to reopen this issue, or open a new one.
