### ISSUE TITLE
Error 32

### ISSUE THREAD

**Issue by octium8** [Automattic/facebook-instant-articles-wp#223]
Hello
I tried to install the plugin and when I wanted to activate it I got this:

Warning: require(/home/mysite/public_html/mysite/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/mysite/public_html/mysite/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

Fatal error: require(): Failed opening required '/home/mysite/public_html/mysite/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/mysite/public_html/mysite/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

What to do??

**Comment by kdagnall** [comment]
Same here.

**Comment by everton-rosario** [comment]
@octium8 Is this still a problem for you?

Please reopen the issue if needed.
