### ISSUE TITLE
Twitter Embeds in Regular Posts Broken

### ISSUE THREAD

**Issue by donaldG** [Automattic/facebook-instant-articles-wp#225]
Hi, we've noticed that Twitter embeds in normal WP blog posts are broken and we've narrowed it down to this plugin.  Specifically this filter here: https://github.com/Automattic/facebook-instant-articles-wp/blob/master/embeds.php#L25-L55 

If we comment out the filter our Tweets embed properly. I'm currently trying to figure out a solution and will update this ticket if I'm able to figure that out soon.

To be clear I do not mean Tweets that are in the Instant Articles feed. I just mean embedded Tweets on regular ol' posts.

**Comment by donaldG** [comment]
It appears doing something like this fixes it:
`function is_this_fb_ia_query( $query ) {
	if ( $query->is_feed( INSTANT_ARTICLES_SLUG ) ) {
		add_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10, 4 );
	}
}
add_action( 'pre_get_posts', 'is_this_fb_ia_query', 10, 1 );`

Although that could be terribly wrong but it appears to be working for me locally. I'm hesitant to do a Pull Request as this may not be legit.

**Comment by stuartshields** [comment]
@donaldG Did you try to resolve this issue with rules? The plugin deliberately removes oembed code and resets it in most cases. I'm thinking rules will fix it.

**Comment by donaldG** [comment]
I didn't :/ Just wanted a quick fix to satiate our marketing department. I
understand it deliberately removes oembed code but it seems like it should
only do that if the post is actually in the feed itself & otherwise it
shouldn't have an affect. I could just be entirely misunderstanding this.

**Comment by stuartshields** [comment]
@donaldG So it's happening outside of the Instant Articles feed as well?

**Comment by donaldG** [comment]
@stuartshields yeah, it's actually ONLY happening outside the Instant Articles feed. So that's why I wrote that little if/else check that appears to be working. Saying, if this is actually in the feed then apply the filter change, otherwise leave it alone.

**Comment by stuartshields** [comment]
@donaldG I'm interested in why this would be happening. Do you have any plugins that change the way oembeds are done for Twitter?

**Comment by donaldG** [comment]
@stuartshields nah, not that I'm aware of. We did have a vendor that wrote some code for the way oembeds are handled for Instagram. We kept having issues with only some of the IG embeds working (prior to Instant Articles plugin) and it seemed that an empty response from Instagram was being cached so this was put together.

```
    add_filter( 'embed_maybe_make_link' , 'change_embed_maybe_make_link' , 10 , 2 );
    function change_embed_maybe_make_link( $output, $url  ) {
        //Return output if it is not instagram
        if( !stristr( $url , 'instagram') || empty( $url ) ){
            return $output;
        }
        $post = get_post();
        $post_ID = ( ! empty( $post->ID ) ) ? $post->ID : null;
        $attr = array(  );
        $attr = wp_parse_args( $attr, wp_embed_defaults( $url ) );
        $key_suffix = md5( $url . serialize( $attr ) );
        $cachekey = '_oembed_' . $key_suffix;
        $cachekey_time = '_oembed_time_' . $key_suffix;
        $html = wp_oembed_get( $url, $attr );
        if( empty( $html )   ){
            return $output;
        }
        if( !empty( $post_ID ) ){
            update_post_meta( $post_ID, $cachekey, $html );
            update_post_meta( $post_ID, $cachekey_time, time() );
        }
        
        return  $html;
    }
```
Think that's the culprit? Nothing else seems to be affected.

**Comment by donaldG** [comment]
Got the update on the plugin this morning and this issue persists. I dropped my fix back into the plugin for the time being.

**Comment by stuartshields** [comment]
@donaldG The issue I've noticed with Instagram and twitter is that their embed JS doesn't contain `https:` which causes facebook to throw up errors. I'm actually going to create a Pull Request that fixes my issue. I'd be interested in seeing if you could try out my fix to get your issue resolved.

**Comment by donaldG** [comment]
@stuartshields totally! Is your fix in a PR now?

**Comment by stuartshields** [comment]
@donaldG Here is the PR https://github.com/Automattic/facebook-instant-articles-wp/pull/290 If you wouldn't mind testing it that way I know for sure it works the way we want it to.

**Comment by donaldG** [comment]
@stuartshields didn't do the trick for me :/ Is the problem not related to the embeds.php file? It seems that section is missing something?

**Comment by donaldG** [comment]
I really want to get this fixed, ha. I'm to the point now where I can resubmit our feed, after tweaking loads of our own custom shortcodes and such, but this is the only thing hindering me. It appears my fix I posted above (https://github.com/Automattic/facebook-instant-articles-wp/issues/225#issuecomment-216637477) doesn't actually work. @stuartshields had any other ideas/thoughts on this? I'm feeling pretty stuck after looking further into this. It appears that regardless of whether I'm in the instant articles feed my twitter embeds are transformed.

**Comment by donaldG** [comment]
@stuartshields HOLY CRAP I THINK I JUST FOUND OUR ISSUE. When embedding a tweet if the URL is like this: https://twitter.com/peta/status/711932888216838146?ref_src=twsrc%5Etfw with that "?ref=..." parameter then it breaks. If I take that off then it's fine. 

I'm not sure where exactly that ?ref param is coming from but that seems to be true culprit.

**Comment by donaldG** [comment]
Closing, finally found a friggin' plugin in our code that's causing the issue. The plugin helps handle special characters in Tweets (not sure it's needed anymore?) and converts the Tweet to base64 encode then saves it & outputs it.
