### ISSUE TITLE
My post not publish yet and without any error show

### ISSUE THREAD

**Issue by KhalidAlmallahi** [Automattic/facebook-instant-articles-wp#226]
Hello ,,,

I have problem in my Facebook instant articles by using WordPress.

The  problem is show me like this picture : 

http://s32.postimg.org/4cacindnp/Capture.png

And some post show me this error : 

http://s32.postimg.org/y0qi7ldr9/Capture.png

When open to edit and show error, its show me: 

> General Errors: Empty Instant Article: The Instant Article does not have any content.

But the content already have content, why this plugin not get the content ?!

Now How can solved this problem ,

**Comment by stuartshields** [comment]
@KhalidAlmallahi What happens when you go to: yourdomain.com/instant-articles (change yourdomain.com to the domain you want to see the articles on). Do you see anything after `</header>`

**Comment by KhalidAlmallahi** [comment]
@stuartshields  yes i see my body of article <p>...............</p>

**Comment by KhalidAlmallahi** [comment]
@stuartshields  Any Updates ?

**Comment by KhalidAlmallahi** [comment]
I will delete this plugin in my site 

its not work good

**Comment by everton-rosario** [comment]
I hope you can Install the latest version of plugin + SDK and double check if you still reproduce the error.

We feel sorry for the inconvenience.
