### ISSUE TITLE
"Log" are appearing in Development, empty articles

### ISSUE THREAD

**Issue by yofisim** [Automattic/facebook-instant-articles-wp#227]
Hi,

plugin is working correctly.
But for some reason, I see the post I want as instant articles, but I also see Log posts, caming from nowhere, and who are absolutely empty.

**Comment by everton-rosario** [comment]
@yofisim I didn't get the issue.
Can you share few steps/screenshots so we can get better contextualized?

Thanks for using Instant Articles.

I'll close the issue for now, please reopen when you get more detailed info.
