### ISSUE TITLE
Jetpack Photon & Emded shortcodes interopability

### ISSUE THREAD

**Issue by diplatis** [Automattic/facebook-instant-articles-wp#228]
Hi,

I'm using Jetpack Photon and I get the following warning in the Facebook Instant Articles dashboard:
General Warnings: Repeating Cover Image and First Image: The cover image and the image 'http://i2.wp.com/(hidden domain)/wp-content/uploads/2015/03/picture.jpg' seem to be the same or almost the same image. Please consider removing or replacing one of the images.

As a result the same image gets displayed twice in the Instant Article and it's caused by the Photon parameter ?fit=565%2C292. How can I correct this?

Also, the youtube videos are not being displayed in the Instant Articles by just placing the youtube link in the post. Jetpack converts the link to the emded code but it is not showing in the Instant Article.

**Comment by stuartshields** [comment]
@diplatis You know you can do it without Jetpack? WordPress automatically embeds the video from the URL these days. I'd suggest disabling that within Jetpack and see if that fixes the issue. If it doesn't can you paste an example of the YouTube embed on the website, I'll see if I can get a rule to work for you.

**Comment by diplatis** [comment]
@stuartshields I disabled it as you told and it works fine. Thanks!
What about the Photon Image mix-up? Any idea?

**Comment by demoive** [comment]
Just logging a similar issue (of duplicate image within the Instant Article) here since a solution (albeit a hacky one) is suggested in the same discussion: https://wordpress.org/support/topic/same-image-displayed-twice?replies=6

**Comment by diplatis** [comment]
Can you give me some guidance on using preg_replace, which file to edit etc?

Anyway, the point is to make this plugin fully compatible natively with Jetpack features such as Photon, Image Galleries etc.

**Comment by everton-rosario** [comment]
@diplatis is this still an issue?

Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Closing this, and reopen when you provide more info.

Thanks for using Instant Articles.
