### ISSUE TITLE
Check for enpoint

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#23]
Is there an equivalent function to call similar to the wp-amp plugin (is_amp_endpoint()) where we can check if it is the Facebook Instant Articles endpoint?

Something like is_fbia_enpoint()?

I would like to use this for when a custom shortcode I created gets displayed. If it is a FBIA page, then I would alter the output to be FBIA friendly.

**Comment by philipjohn** [comment]
There isn't, but as the plugin uses WordPress' standard feed system it's super simple to add a check using this code:

`is_feed( 'instant-articles' )`

You may choose to use the define instead, though, in case you change the feed slug:

`is_feed( INSTANT_ARTICLES_SLUG )`

**Comment by kkranzo** [comment]
Okay, great.

Is that because there isn't actually an endpoint page like with wp-amp (since this just produces a FBIA compliant feed)?

**Comment by philipjohn** [comment]
Yep! While the two do similar things, they expose the content from WordPress in a different way. FBIA is built on RSS feeds whereas AMP produces slimmed-down HTML.

**Comment by kkranzo** [comment]
Great, thanks!

**Comment by kkranzo** [comment]
Also, since it is using Wordpress' standard feed system, would the current code that I have for my main feed below be applied to this feed as well?

```
function exclude_category($query) {
	if ( $query->is_feed ) {
		$categoryExcludeName = get_category_by_slug('exclude-homepage');
		$categoryExclude = $categoryExcludeName->term_id;
		$query->set('cat', '-' . $categoryExclude);
	}
return $query;
}
add_filter('pre_get_posts', 'exclude_category');
```

**Comment by kkranzo** [comment]
Or would I have to add the below to the if statement

`|| $query->is_feed( INSTANT_ARTICLES_SLUG)`
