### ISSUE TITLE
Plugin Activation Setup Error

### ISSUE THREAD

**Issue by Asif2BD** [Automattic/facebook-instant-articles-wp#230]
I am using this WordPress plugin, and always getting error 404 while returning from Facebook Authentication.

The url like this

http://domain.tld/wp-admin/admin.php?page=instant-articles-settings&code=LONG_CODE_1&state=SHORT_CODE_1#_=_

is being converted like this

http://domain.tld/wp-admin/SHORT_CODE_1&tab=profile#_=_

What could have caused it? I tried disabling any plugin that might affect how WordPress handle request or API call.

**Comment by everton-rosario** [comment]
The domain.tld is returning 404 for me as well.

You can use the strategy of localtest.me: https://wordpress.org/support/topic/how-to-copy-wordpress-site-to-local-test-server

Then you have to add wp.localtest.me to your facebook redirect link.


Feel free to reopen this issue if needed.
