### ISSUE TITLE
Integration support: Instagram Embeds

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#234]
Add default support for the markup for Instagram Embeds.

**Source Markup**
```html
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="6" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
  <div style="padding:8px;">
    <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:62.5% 0; text-align:center; width:100%;">
      <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
    </div>
    <p style=" margin:8px 0 0 0; padding:0 4px;">
      <a href="https://www.instagram.com/p/BAXbKP1POQe/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">📸 @natthaponwuttipetch</a>
    </p>
    <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">
      A photo posted by Ann Hathairat Vidhyaphum (@annvidh) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2016-01-10T16:56:06+00:00">Jan 10, 2016 at 8:56am PST</time>
    </p>
  </div>
</blockquote>
```

References:
https://wordpress.org/support/topic/instagram-embeds-not-wrapped-in-op-social-tags?replies=4

**Comment by katsar0v** [comment]
Still no development on this issue... Problem persist

**Comment by everton-rosario** [comment]
@katsar0v We still have this on the backlog to be implemented. If you can help us with some PR we are here to help.

**Comment by jlapitan** [comment]
behavior of the Instagram embeds from WP to instant articles result to something like this. `<figure><img
src="http://instagr.am/p/ux0_RmB9W8/media/?size=l"/></figure>` but sometimes the figure element is not generated.

**Comment by everton-rosario** [comment]
@jlapitan Do you have a repro-steps when you see it not being rendered?

**Comment by jlapitan** [comment]
@everton-rosario i noticed it when testing posts with instagram embed and save as drafts, got no steps to determine why sometimes on published posts, it does not convert to img.


In relation to this bug, can we have something like this 

[jetpack fb and yt fix](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/compat/class-instant-articles-jetpack.php)

[instagram over-ride](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/instagram.php)


I think there is a conflict with jetpack oembeds.

**Comment by everton-rosario** [comment]
@katsar0v add this new Rule to your `rules-configuration.json`:

```
    {
        "class": "InteractiveRule",
        "selector" : "blockquote.instagram-media",
        "properties" : {
            "interactive.iframe" : {
                "type" : "element",
                "selector" : "blockquote"
            }
        }
    }
```

**Comment by everton-rosario** [comment]
@jlapitan There will be new configuration for jetpack and full coverage of it on the next release of this plugin. 
Keep up to date on the Pull requests and this repo.

**Comment by jlapitan** [comment]
@everton-rosario i tried the new rule, and it renders blank instagram post. will this be the default rule for IG on the next release?

[Screenshots](https://www.dropbox.com/sh/322m91gdx8kane5/AABqQDHlqxFqn5gZFB1gx5i5a?dl=0)

**Comment by everton-rosario** [comment]
@jlapitan yeah, we also figured out this issue.
We had to work further on this issue to include sibling elements (There was a missing <source> element with javascript code that wasn't being processed.)

Can you try it now, please? We have those checked in.
Make sure you are on the SDK and WP plugin branch: instagram-embed

**Comment by everton-rosario** [comment]
@jlapitan For your environment setup:

Clone both repositories into your developer folder (ex: ~/instant-articles).

```
git clone git@github.com:Automattic/facebook-instant-articles-wp.git
git clone git@github.com:facebook/facebook-instant-articles-sdk-php.git
```


Build both source folders:
```
cd facebook-instant-articles-sdk-php
composer install

cd ../facebook-instant-articles-wp
composer install
```


Now remove the build from your WordPress, so it will include the code you've just built.
```
rm -rf vendor/facebook/facebook-instant-articles-sdk-php
ln -s ~/facebook-instant-articles-sdk-php vendor/facebook/facebook-instant-articles-sdk-php
```


and now you can create a link inside your /wp-content/plugins to your folder 
```
ln -s ~/facebook-instant-articles-wp wp-content/plugins/facebook-instant-articles-wp
```

**Comment by jlapitan** [comment]
@everton-rosario i followed all the instructions above, and did make sure i am on instagram-embed branch, when i tried to edit posts, the FB instant articles metabox just keeps on loading and on debug i can see an error 500 from admin-ajax

**Comment by everton-rosario** [comment]
@jlapitan, can you share here more info about your problem?

I need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

**Comment by jlapitan** [comment]
@everton-rosario i think the problem is the way i link the fb instant articles to wp-content, cause WP is trying to load the js files
from this url:
http://localhost/wp-content/plugins/home/facebook-instant-articles-wp/js/instant-articles-meta-box.js

**Comment by everton-rosario** [comment]
For local development/test, as localhost, we recommend you to use wp.localtest.me domain.
You need to:

1. Add to your "/etc/hosts" file
2. And tweak the configuration as any of [these instructions](https://codex.wordpress.org/Running_a_Development_Copy_of_WordPress)

**Comment by jlapitan** [comment]
Hi @everton-rosario i haven't setup properly my localhost yet, but i got a followup question, when using the jetpack shortcode for embedding instagram posts, it removes the siblings element(which is the script tag for embed),  will the updated code include the `platform.instagram.com/en_US/embeds.js`

**Comment by everton-rosario** [comment]
Im working on this issue in this very same moment, @jlapitan 

The code is fresh out of oven here on this [PR](https://github.com/facebook/facebook-instant-articles-sdk-php/pull/155), if you can help test it, would be awesome.

**Comment by jlapitan** [comment]
@everton-rosario I have successfully setup my localhost, used the latest master branch,  but when i go to advance settings i have this issue. [screenshot](http://awesomescreenshot.com/0ab63in8ce)

And where can I find the transformer rules used in the instagram-embed branch?

**Comment by everton-rosario** [comment]
@jlapitan Sorry for the long wait.

This are the rules you should use:
```
      {
          "class": "InteractiveRule",             "class": "InteractiveRule",
          "selector" : "blockquote.instagram-media",
          "properties" : {
              "interactive.iframe" : {
                  "type" : "multiple",
                  "children": [
                      {
                          "type": "element",
                          "selector": "blockquote"
                      }, {
                          "type": "sibling-element",
                          "selector": "blockquote"
                      }
                  ]
              }
          }
      }, {
          "class": "IgnoreRule",
          "selector" : "script"
      }
```

**Comment by samichamoun** [comment]
Is this an outstanding issue?

**Comment by jlapitan** [comment]
@samichamoun embed is working but actual image from IG is not loading, what I am doing is edit wordpress Jetpack plugin to remove the bug

**Comment by someguy9** [comment]
I'm still having this issue 😦

**Comment by someguy9** [comment]
Somewhat fixed, had to modify the rules in the rules-configuration file

{
        "class": "InteractiveRule",
        "selector" : "figure.op-interactive",
        "properties" : {
            "interactive.iframe" : {
                "type" : "multiple",
                "children": [
                    {
                        "type": "element",
                        "selector": "blockquote"
                    }, {
                        "type": "next-sibling-element-of",
                        "selector": "blockquote"
                    }
                ]
            }
        }
}

{
        "class": "ImageRule",
        "selector" : "figure:not(.op-interactive)",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            }
        }
}

**Comment by everton-rosario** [comment]
@someguy9 Is this something we should incorporate into the rules-configuration for anyone?
Can you send this as a PullRequest?

**Comment by someguy9** [comment]
@everton-rosario I don't know if this only affected me but I'll make a pull request!
