### ISSUE TITLE
Facebook crawler hits while editing post draft and caches a 404

### ISSUE THREAD

**Issue by Aioros** [Automattic/facebook-instant-articles-wp#237]
Hi,
since we were still having an old issue where, with this plugin, posts shared on FB often resulted in a cached 404 by the Facebook crawler, I resorted to monitoring the server's access_log to find out when the crawler landed on our posts.
I found out that happens (weirdly) the first time a user opens a draft for editing. As soon as the page is loaded, we receive a visit from "facebookexternalhit" looking for the final URL of the article. The server redirects it to the draft URL (/?p=xxxx) which of course ends up in a 404.

I couldn't track down the reason for such an early visit from the crawler yet. It only (and always) happens when the plugin is active, and it messes with the ability to share the post later, since users have to run it through the FB debugger and scrape it again every time.

Is there a known reason for this behaviour?

**Comment by Aioros** [comment]
Sorry for the double post, I just found out the reason for the crawler's early hit: it's the meta box in the edit post page.
When a user opens a draft for editing, the meta box asks FB about an IA with the final canonical url, and the crawler arrives, caching the dreaded 404.

I'm going to try and remove the meta box on our sites somehow, but this should probably be looked into.

**Comment by ChrisBegley** [comment]
I've also experienced this issue with this plugin activated

**Comment by nicolinuxfr** [comment]
Same here. I have to use the debugger every time to crawl the correct informations.

**Comment by kevinlisota** [comment]
+1 for this issue. We had to turn off the plugin because it was messing up ability to immediately share a new WP article on FB.

**Comment by Aioros** [comment]
Have you tried removing the meta box in the post editing page?
I used this in my functions.php:

```
remove_action( 'add_meta_boxes', array( 'Instant_Articles_Meta_Box', 'register_meta_box' ) );
remove_action( 'wp_ajax_instant_articles_meta_box', array( 'Instant_Articles_Meta_Box', 'render_meta_box' ) );
```

**Comment by MLRobbins** [comment]
We are seeing this as well. [paging @chrisackermann] seems @Aioros has a workaround for this problem as well - which is a pretty significant problem. As a news org, we are publishing all day long and this has significantly impacted our social sharing capabilities, on Facebook. Any update?

**Comment by MLRobbins** [comment]
@Aioros we've tried the workaround you recommend, and we're still getting 404s and having to rescrape URLs via the FB debugger to get them to display properly when shared via URL. Has the Automattic/FB plugin dev team looked into this issue yet?

**Comment by Aioros** [comment]
I should take a closer look into the meta box code, but it seems to me that this is more of a weird behaviour on Facebook's side than a bug. I would suggest, as a way of working around this, that the meta box should only check for the article status after the first time the post has been published, but this would probably mean saving more post metas, which would be a debatable choice for a workaround.

Would it make sense to ask this to the people at the [PHP SKD](https://github.com/facebook/facebook-instant-articles-sdk-php) project?

**Comment by nicolinuxfr** [comment]
In the meantime, your "fix" @Aioros is working fine. No more meta box, but at least the crawler works as expected.

**Comment by chrisackermann** [comment]
Thanks for reporting and sorry for the headache. The right approach here is to force a re-scrape when the article is being taken live, using this endpoint:

`POST /?id={object-instance-id or object-url}&amp;scrape=true`

as documented here: https://developers.facebook.com/docs/sharing/opengraph/using-objects#update

We should address this in the PHP SDK though, so @Aioros, would you mind opening an issue on the repo there?  Thanks!

**Comment by kevinlisota** [comment]
@chrisackermann I'm not sure if this is the right approach. Here are the issues I see:

1) The canonical URL may actually change at time of publish. In fact, in our workflow, it's not unusual to change the title & URL at the end of the editing process, prior to publishing.
2) I you tie a re-scrape to the article's publish event, it is entirely possible that in a few second interval while that is happening, WP may not serve the article yet. Our site is high-traffic, and there are front-end caches that get built on new articles, along with a number of things that happen on the save_post event. While it is nearly instantaneous, there could be odd behaviors here if within millseconds the FB scraper is sent looking for the new article and it isn't there yet.

I actually think there should be no FB scraping of anything until a public canonical URL is published and resolves on WP.

**Comment by Aioros** [comment]
I have to say I'm not sure either. Before deactivating the meta box I tried forcing a rescrape, but it was a bit of a hit and miss; I'm not sure why, but I suppose that @kevinlisota has a point with timings and possible oddities. Then again, I'm really not an expert here, so I trust the devs on this, but the rescrape solution should definitely be tested carefully.

**Comment by chrisackermann** [comment]
Thanks for the additional input.  @diegoquinteiro and I are looking at an alternative solution and we'll provide an update shortly.

**Comment by CastenettoA** [comment]
It seems not yet resolved in the new version of plugin.
Following @Aioros advice I have to add this code to function.php
`if(is_admin()){
	remove_action('add_meta_box', array( 'Instant_Articles_Meta_Box', 'register_meta_box' ));
	remove_action( 'wp_ajax_instant_articles_meta_box', array( 'Instant_Articles_Meta_Box', 'render_meta_box' ) );
}
`

**Comment by Lindstromer** [comment]
+1 on this problem to be fixed. It creates a lot of extra work for a editors/publisher having to scrape articles multiple times a day.

@CastenettoA you missed the plural in the action call. It's supposed to be 'add_meta_boxes' like in Aioros code. Oterwhise the meta box will be there but without any content.
