### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#24]
Is there a way to add additional templates for custom post types/post styles?

**Comment by philipjohn** [comment]
Take a look at the `instant_articles_render_post_template` filter which will allow you to load a different template based on each individual post.

**Comment by kkranzo** [comment]
Okay, thanks.

So how would I set that up in my functions.php file to use my own template.php file within my theme rather than the plugins file?

**Comment by kkranzo** [comment]
Please let me know as I would like to add analytics and ads to that custom template as well.
