### ISSUE TITLE
Rogue closing </p> tag in Source Markup

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#241]
An unexpected closing paragraph tag is being added to the source markup.

**Editor Content**
```html
<div class="article_image">
  <img src="https://jpeg.org/images/jpegls-home.jpg" alt="" />
  <div class="image_description">My image description</div>
</div>
```

**Generated Source Markup**
```html
<div class="article_image">
  <img src="https://jpeg.org/images/jpegls-home.jpg" alt="" /></p>
  <div class="image_description">My image description</div>
</div>
```

(note the closing `</p>` tag after the image)

**Comment by demoive** [comment]
Update, this reproduces in a vanilla installation of WordPress (v4.5.1) with no plugins activated so not related to this plugin.

**Comment by everton-rosario** [comment]
Since it doesn't apply to this plugin, the transformer ignores the empty paragraph.

Closing.
