### ISSUE TITLE
Emoji/emoticons display full-screen width on instant articles

### ISSUE THREAD

**Issue by withlovee** [Automattic/facebook-instant-articles-wp#242]
Hi, I'm using the instant article 2.8 and I've came across a problem with emoticons.

I'm using Wordpress's default emoticons in my old posts and they're showing on instant articles like this:
![On instant articles](https://cloud.githubusercontent.com/assets/1861082/15095807/44443004-1505-11e6-8c0f-c954e56b5eeb.png) On instant articles

![On web view](https://cloud.githubusercontent.com/assets/1861082/15095819/c81570dc-1505-11e6-855b-3698bb94268c.png) On web view

Is there a way to filter them out since small/in-inline images does not seem to be supported. I've also had a problem with my client's site where she uses animated emoticons and facebook says her video (.gif file) is too small.

**Comment by everton-rosario** [comment]
@withlovee we dont support in-line images, like emoticons, on Instant Articles yet.

Thanks for raising this case.
We will check if this will be available soon.

Keep posted.

**Comment by withlovee** [comment]
@everton-rosario thanks!
I was thinking if we could override the emoticon settings, replacing converting string to <img> with converting string to empty string. Will that work? I might try it on my website.

**Comment by everton-rosario** [comment]
Yes that would work.

Also you can replace the PNG img, by the emoji UTF-8 code (for the inline images that represent an emoticon).

I've checked if we will have any time soon the inline-images, and this wont be available anytime soon on Instant Articles.

I recommend you to use the emoji characters.


Feel free to reopen this, if still having a problem.

Thanks for using Instant Articles.
