### ISSUE TITLE
Fatal Error Triggered on Activation

### ISSUE THREAD

**Issue by Jake-Grafenstein** [Automattic/facebook-instant-articles-wp#244]
Hello,

Plugin installs fine, but when you try to activate it within your WordPress account, it triggers a fatal error because it cannot find certain files. See the error message below:

Warning: require(/www/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /www/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32 Fatal error: require(): Failed opening required '/www/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /www/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

Best,
Jake

**Comment by EthanGould** [comment]
I am having the same issue after updating composer. Any thoughts?

**Comment by everton-rosario** [comment]
@Jake-Grafenstein @EthanGould can you guys try this again with the newest version of SDK and Plugin?

This should be fixed.

Please, reopen this issue if it still happens to you. Also provide a little more details about the issue.

**Comment by EthanGould** [comment]
Was able to get it working, had something todo with missing dependencies I think. Thanks!
