### ISSUE TITLE
Cant see all pages in plugin pages selector

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/facebook-instant-articles-wp#245]
I log-in to the app and only cant see 2 pages in the page selector, but i am admin of a lot of pages and i signed up this pages for the instant articles.

![sin-titulo-1](https://cloud.githubusercontent.com/assets/1310626/15126450/791f03a4-1608-11e6-8199-133d31b2bcce.jpg)

**Comment by katsar0v** [comment]
Maybe the page does not have access to instant articles yet

**Comment by everton-rosario** [comment]
This will be fixed in the new release 3.1 within the new wizard flow that is on branch https://github.com/Automattic/facebook-instant-articles-wp/tree/new_flow

@matiasbenedetto @katsar0v 

Sorry for the long wait for this to be solved.
