### ISSUE TITLE
Avoid class="interactive" to make things work

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#247]
Consider avoiding the dependency on wrapping things in `<div class="interactive">` in order to get them to work. There have been multiple instances reported related to this:

#140 
#141 
#109 
https://wordpress.org/support/topic/op-social-class-without-any-supported-embed-type

**Comment by everton-rosario** [comment]
The problem isn't with the `<div class="interactive">`, there is no way to make transformer to understand the code that should be transformed.
This container (without any formating) tag, works as an indicator so the transformer can process the amount of code inside the div as an op-interactive component tag.
