### ISSUE TITLE
<div class="embed"> wrapping embeds on non-instant articles. 

### ISSUE THREAD

**Issue by kitwestneat** [Automattic/facebook-instant-articles-wp#249]
It appears as if embeds.php strips out all embed filters from other plugins, and adds its own filters, one of which wraps the embed in a &lt;div class="embed"&gt; tag. The problem is that it looks as if embeds.php is run regardless of whether or not the request is for an instant feed.

**Comment by dashaluna** [comment]
What's the status with this?

**Comment by timjacobi** [comment]
Marking this as duplicate of #337 which has more details.
