### ISSUE TITLE
Facebook Video/Post embeds not working. 

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/facebook-instant-articles-wp#25]
Which is ironic :) 

I worked this around with following code -

```
static function wire_fb_embed_handlers() {
	wp_embed_register_handler( 'facebook-ia-post', JETPACK_FACEBOOK_EMBED_REGEX, [ __CLASS__, 'ia_fb_embed_handler' ] , 0 );
	wp_embed_register_handler( 'facebook-ia-video', JETPACK_FACEBOOK_VIDEO_ALTERNATE_EMBED_REGEX, [ __CLASS__, 'ia_fb_embed_handler' ] , 0 );
}

static function ia_fb_embed_handler( $matches, $attr, $url ) {
	$class = wp_in( '/posts/', $url ) ? 'post' : 'video';
	return sprintf( '<div class="fb-%s" data-allowfullscreen="true" data-href="%s" data-width="%d"></div>', esc_attr( $class ), esc_url( $url ), (int) Helper::get_content_width( 'ia' ) );
}
```

Obviously, this needs to be cleaned up since I have all kinds of helpers which are probably not needed + a check to see if Jetpack is activated

**Comment by philipjohn** [comment]
Thanks @rinatkhaziev - do you have an example to point us at? :)

**Comment by rinatkhaziev** [comment]
@philipjohn I just updated the original comment, it covers links like https://www.facebook.com/rinat.khaziev/posts/10208586784288538 and https://www.facebook.com/coslive/videos/10153831160106648/

**Comment by philipjohn** [comment]
@rinatkhaziev How does the above fix work out for you?

**Comment by rinatkhaziev** [comment]
@philipjohn works like a charm! 

Closing this one.

**Comment by rinatkhaziev** [comment]
@philipjohn when are you planning to merge this into wp.com?
