### ISSUE TITLE
Custom Post Type - custom post meta fields in Transformer rules

### ISSUE THREAD

**Issue by herbco** [Automattic/facebook-instant-articles-wp#250]
Hi Guys

I spoke to your team at the Dev Garage today about this issue and was advised to make a Github post.
Many Wordpress sites have Custom Post Types and these include custom metadata fields which a site may render on the front end as part of its content. However, because this data is not is not included in the standard Wordpress post content field, it can't be accessed via the Transformer rules (as far as I know) and included in Instant Articles markup. For example, our site (herb.co) has a video Custom Post Type where a separate meta field holds the YouTube Embed Code for the content. This means the video embed doesn't appear in the final IA markup, flagging the article as invalid.

It would be great if the plugin could:
- Allow the inclusion / exclusion of selected Custom Post Types in the feed. Publishers may not want every post type made available on the feed.
- Be able to transform/add metadata fields into the IA post body. For example, with our video post type, we could choose to have the YouTube embed code at the top of IA post content body.

Cheers
Lucas Young
CTO, HERB

**Comment by jordanlittle** [comment]
I'll second this.

I have several custom post types set up (slideshow, infographic, etc) that, when being edited, don't display the Facebook Instant Articles output metabox.

I've found where I can modify the query to get it working on the public-side, but I still haven't found a way to get a full feeling of "support" for custom post types in the admin.

Any advice appreciated and many thanks on the plugin – works great.

**Comment by everton-rosario** [comment]
@herbco @jordanlittle You can use our post type filter:

```
add_filter( 'instant_articles_post_types', func_to_filter_post );
```

As you can see we do this filtering and this is configurable as you want. So any pre-processing before the article is transformed is allowed.
I'd recommend you guys to apply this.

We also provide a bunch of filters and actions to adapt the content you are transforming.
