### ISSUE TITLE
Audience network - white ad?

### ISSUE THREAD

**Issue by katsar0v** [Automattic/facebook-instant-articles-wp#253]
After putting a placement ID, I get an white ad, has anyone had this already?

**Comment by yjeanrenaud** [comment]
jup, me too. I followed the fb docs how to create an app and add support for the audience network to it, but I get no ads and the placement keeps on status "Enabled for testing".
I also noticed the code deployed in the ia articles by the plugin is different from the one facebook actually supplies. maybe this is the cause?

**Comment by katsar0v** [comment]
I think this is connected with Instant Articles itself, still quite buggy overall

**Comment by everton-rosario** [comment]
@katsar0v and @yjeanrenaud Are you still facing the same issues?
Can you provide few snippets of code so we can double check and try to reproduce?

Thanks.
