### ISSUE TITLE
New FB-Issue: HTML Embeds Require Valid Width / Height

### ISSUE THREAD

**Issue by withoutfield** [Automattic/facebook-instant-articles-wp#256]
Recently there is a new Error-Message on Embeds, FB is missing "Valid Width / Height" for op-social an op-interactive Embeds.

op-social:

`<figure class="op-social"><iframe src="https://www.youtube.com/embed/QfTKLpdA5Fc?feature=oembed"></iframe></figure>
`
`**HTML Embeds Require Valid Width: HTML Embeds require a valid integer width in order to be displayed properly.**
`
`**HTML Embeds Require Valid Height: HTML Embeds require a valid integer height in order to be displayed properly.**`

op-interactive:

`<figure class="op-interactive"><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/197538395&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true" class="no-margin"></iframe></figure>
`
`**HTML Embeds Require Valid Width: HTML Embeds require a valid integer width in order to be displayed properly.**
`
`**HTML Embeds Require Valid Height: HTML Embeds require a valid integer height in order to be displayed properly.**`

Plugin Version 2.10

**Comment by samichamoun** [comment]
Has a patch been made for this?

**Comment by bewarem** [comment]
I have the same problem when i try to embed vimeo video

**Comment by samichamoun** [comment]
Any update on this? Still receiving this error on every post which includes a video

**Comment by withoutfield** [comment]
Still not fixed, but if I understand it right, the fix will come with the next Update.

**Comment by pnoeric** [comment]
The patch on issue #258 (presumably scheduled for the next release) did the job for me. You can edit your rules-configuration.json file to manually apply this patch and it will add width/height to your embeds.  https://github.com/Automattic/facebook-instant-articles-wp/pull/258

**Comment by samichamoun** [comment]
@pnoeric - I tried using that already and I still get the width error. As others have said, you cant reference "width".

**Comment by everton-rosario** [comment]
@samichamoun Can you open another issue, also consider sharing here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Also the warning messages you are dealing with.
