### ISSUE TITLE
Additional setting option to apply a global footer

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#261]
This feature request is to add an additional option in the settings to set a footer which would apply to all articles.

Example use case: Useful for copyright information.

Reference:
https://wordpress.org/support/topic/footer-110?replies=1
https://wordpress.org/support/topic/footer-customization-4/
https://wordpress.org/support/topic/customizing-footer-5/

**Comment by cudaja** [comment]
We're waiting for this feature. Impressum / about information in the footer are legally required in Germany and this issue is a blocker for us. 
cheers,

**Comment by apollosk** [comment]
This feature is a must. Please consider it for your next plugin update.
Kudos to the authors!

**Comment by demoive** [comment]
I've tagged this with the `help wanted` label and placed in the next milestone to bring attention from the community. It would involve:

- Adding a new setting option (e.g. [`/wizard/class-instant-articles-option-analytics.php`](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/wizard/class-instant-articles-option-analytics.php#L40))
- Injecting it's value during the construction of the Instant Articles document (see: [`add_analytics_from_settings()`](https://github.com/Automattic/facebook-instant-articles-wp/blob/f4d3bb5c35d48f3c6d1ff240010fd563d50a3983/class-instant-articles-post.php#L810))

In the mean time, a workaround *does* exist: #335
