### ISSUE TITLE
Request: Validator for unpublished articles

### ISSUE THREAD

**Issue by davydelbeke** [Automattic/facebook-instant-articles-wp#267]
I'd love to be able to validate if my article is valid for Facebook Instant Articles before publishing it online. 
I'm asking this because I had an empty Instant Article because one of my writers wrote a span around a div. Dirty code and Facebook Articles didn't like that. Is it possible to do this every time the author saves the article as a concept? 

Thanks!

**Comment by jeremyclarke** [comment]
THIS IS COMPLETE!!!

New version tells you what's invalid in your post and also has the option to not publish articles that don't validate. 

CLOSE THIS TICKET!

**Comment by everton-rosario** [comment]
This have been completed few versions ago! 
Thanks again for noticing @jeremyclarke .

BTW, your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.
