### ISSUE TITLE
Support publishing via XML-RPC

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#268]
Posts and pages created/saved in [WordPress via XML-RPC](https://codex.wordpress.org/XML-RPC_Support) are published ("pushed") with empty content to Facebook for Instant Articles.

To reproduce, create a new post through a weblog client (e.g. [Blogo](https://getblogo.com)).

Reference:
https://wordpress.org/support/topic/instant-articles-empty-when-using-xml-rpc

**Comment by larsschenk** [comment]
Since version 2.11 of the plugin, this issue is solved.
Articles created or updated with XML-RPC do result now in correct FB IA! Thanks.+

**Comment by demoive** [comment]
Confirmed to have been resolved in #257 by https://github.com/Automattic/facebook-instant-articles-wp/pull/257/commits/cce67efe8bb401ed37b3d0188e4cf028a4fe1a44 in [v2.11](https://github.com/Automattic/facebook-instant-articles-wp/releases/tag/2.11). The root cause of the problem (empty content) was causing the same problem with scheduled posts.
