### ISSUE TITLE
Can't populate related articles in footer

### ISSUE THREAD

**Issue by ericescalante** [Automattic/facebook-instant-articles-wp#269]
Hi, thanks for creating this great plugin! I'm experiencing a bit of on issue though. I can't get related articles to display with this rules:

```
    {
      "class": "footerRule",
      "selector": "footer"
    },
    {
      "class": "FooterRelatedArticlesRule",
      "selector": "ul"
    },    
    {
      "class": "RelatedItemRule",
      "selector": "li",
      "properties": {
        "related.url": {
          "type": "string",
          "selector": "a",
          "attribute": "href"
        }
      }
    }
```

The markup has a UL with 3 links wrapped in LIs :)
Thanks a bunch!

**Comment by ericescalante** [comment]
Closing it myself. Went around the rule-based parsing and just added them on a `instant_articles_transformed_element` filter by hand ^_^

```
  $footer = $ia->getFooter();
  $footer->withRelatedArticles(
    RelatedArticles::create()
        ->addRelated(RelatedItem::create()->withUrl($urls[0]))
        ->addRelated(RelatedItem::create()->withUrl($urls[1]))
        ->addRelated(RelatedItem::create()->withUrl($urls[2]))
    );
```

**Comment by krispy1298** [comment]
Thoughts on re-opening this to work towards a more seamless solution?

**Comment by thejavangumalli** [comment]
Any solution for this with transformation rules yet?

**Comment by everton-rosario** [comment]
@thejavangumalli Can you give more details on your issue?

Please, can you share here more info about your transformation problem?

I need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

**Comment by thejavangumalli** [comment]
@everton-rosario Article body has this warning

Source Markup:
`<a href="http://rdcnewsadvice.staging.wpengine.com/news/trends/test-u-s-cities-athletes-won-olympic-medalse/" title="Test &#8211; Which U.S. Cities’ Athletes Won the Most Olympic Medalse?"><figure class="no-caption"><img width="798" height="448" src="http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Jupiter, FL" srcset="http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582.jpg 798w, http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582-300x168.jpg 300w, http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582-145x81.jpg 145w, http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582-628x354.jpg 628w, http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582-506x284.jpg 506w, http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582-290x164.jpg 290w" sizes="(max-width: 798px) 100vw, 798px" /><figcaption><p class="credit">realtor.com</p></figcaption></figure></a><p>Despite the tabloid-worthy antics of swimmer <strong>Ryan Lochte </strong>and his pals, star American athletes—including fellow swimmer <strong>Michael Phelps</strong> and gymnast <strong>Simone Biles</strong>—made their country proud this month at the Olympics in Rio.</p>
`

Transformed Markup:
`<html>
  <head>
    <link rel="canonical" href="http://rdcnewsadvice.staging.wpengine.com/news/trends/test-u-s-cities-athletes-won-olympic-medalse/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.5.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="3.2.2"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.5.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="Realtor.com"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://rdcnewsadvice.staging.wpengine.com/wp-content/uploads/2016/05/Jupiter-FL-e1463610524582.jpg"/>
          <figcaption>Jupiter, FL</figcaption>
        </figure>
        <h1>Test – Which U.S. Cities’ Athletes Won the Most Olympic Medalse?</h1>
        <time class="op-published" datetime="2016-11-18T21:09:58-05:00">November 18th, 9:09pm</time>
        <time class="op-modified" datetime="2016-11-18T21:09:58-05:00">November 18th, 9:09pm</time>
        <address><a>Shivadeepthi Chilukuri</a></address>
      </header>
      <p>Despite the tabloid-worthy antics of swimmer <b>Ryan Lochte </b>and his pals, star American athletes—including fellow swimmer <b>Michael Phelps</b> and gymnast <b>Simone Biles</b>—made their country proud this month at the Olympics in Rio.</p>
      <p>U.S. athletes brought home 121 Olympic medals in the 2016 Games—by far the most of any country. That breaks down into 46 gold, 37 silver, and 38 bronze winners. But there was a lot of local pride, too. So which cities got the most bragging rights out of their hometown heroes?</p>
      <p>California cities led the medal-earning pack: At final count, 57 medals, nearly half of what U.S. athletes won, came from California, according to <a href="http://www.citylab.com/work/2016/08/cities-with-the-most-olympic-medals/497414/?utm_source=nl__link6_082516">The Atlantic’s CityLab</a>.The data came from <b>Patrick Adler</b> of the Toronto-based Martin Prosperity Institute, which focuses on economic prosperity. That’s enough to put the state in fourth place internationally if it seceded and became its own country. (There are already movements afoot in the blue state to do just that if Republican <b>Donald Trump</b> wins the presidency.)</p>
      <p>Sports stars from Los Angeles netted 28 medals. To put that into perspective, if the City of Angels (and celebrities) was its own nation, that tally would have put it in 10th place <i>in the world</i>. The city, which hosted the 1932 and 1984 Olympic Games, is hoping for a trifecta if it gets to host the 2024 Summer Games.</p>
      <p>Elite San Franciscan athletes took the silver with 19 medals, while New York City got the third spot on the podium with 16 medals.</p>
      <p>Baltimore and San Diego competitors each earned 10 medals. Six of Baltimore’s count were won by the world-record-shattering Phelps (although he recently <a href="http://www.realtor.com/news/celebrity-real-estate/michael-phelps-buys-arizona-home/">relocated to Scottsdale, AZ</a>). Miami contestants took home nine, Dallas Olympians won eight, and Colorado Springs, CO, athletes earned seven. (Colorado Springs is home to the flagship U.S. Olympic Training Center.)</p>
      <p>Athletic challengers hailing from Chicago; Boston; Portland, OR; Houston; and Washington, DC, brought five medals back to each city.</p>
      <p>It’s important to note that most of the medalists came from the bigger and more heavily populated cities where top coaches and training facilities are often based.</p>
      <p>For instance, the 155-acre Chula Vista Olympic Training Center is located right next to San Diego (which also scored high on the medal count) and is a little over two hours away from Los Angeles (depending on that dreaded traffic). Athletes in primarily summer sports like archery, beach volleyball, field hockey, rowing, soccer, tennis, and track and field, as well as many more, can live and train on the campus. (A similar facility with a greater focus on winter sports is at Lake Placid, NY.)</p>
    </article>
  </body>
</html>`

Transformation of the post body seems to be good. 
However, the problem is we have related stories and they are not being sent to facebook.

**Comment by everton-rosario** [comment]
@thejavangumalli 
Is this <a href> with link to `http://rdcnewsadvice.staging.wpengine.com/news/trends/test-u-s-cities-athletes-won-olympic-medalse/` the related article?

**Comment by thejavangumalli** [comment]
@everton-rosario If you see the article at the above url, it has 3 related articles at the bottom in the header. But the transformed article doesn't have the related article section in it. How do I force instant article plugin to send related articles info to facebook.

**Comment by everton-rosario** [comment]
@thejavangumalli Is this the section you've mentioned?

```
<footer class="entry-footer col-lg-9 col-lg-offset-3">
                <div class="related-tags">
            <div class="stories half">
                            <div id="related-stories">
                <h4>Related Stories:</h4>
                                    <p>
                        <span></span><br>
                        <a href="http://www.realtor.com/news/celebrity-real-estate/michael-phelps-buys-arizona-home/">Olympic Star Michael Phelps Purchased a Desert Dream Home (With Pool)</a>
                    </p>
                                    <p>
                        <span></span><br>
                        <a href="http://www.realtor.com/news/trends/will-olympics-rescue-or-ruin-rio-housing-market/">Will the Olympics Rescue or Ruin Rio’s Housing Market?</a>
                    </p>
                                    <p>
                        <span></span><br>
                        <a href="http://www.realtor.com/news/celebrity-real-estate/hope-solo-selling-washington-home/">U.S. Soccer Star Hope Solo Selling Her $1.85M Washington Home</a>
                    </p>
                            </div>
                        </div>
                    </div>
        <!-- search for "rdc-community-cta" -->
        <div class="line"></div>
        <div class="rdc-community-cta">
              <p class="title">Need more info on this subject?</p>
              <p class="description"></p>
              <a href="http://community.realtor.com" data-omtag="trends:article:community:learn-more">
                <button class="btn btn-lg">Get answers in House Talk</button>
              </a>
            </div>
	</footer><!-- .entry-footer -->
```

Was this available in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box within **Source Markup**?

**Comment by thejavangumalli** [comment]
Yes that's the section  It's not available in the source markup..

**Comment by everton-rosario** [comment]
If this is not yet available at that box, means it is getting included after our plugin and transformation runs.

To make this right included, you will need to use same @ericescalante approach, by adding a filter/action and then including it into the article programatically.

**Comment by nickkos101** [comment]
@ericscalante any chance you could show us your hook and filter?
