### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by iamali** [Automattic/facebook-instant-articles-wp#272]
I'm unable to activate the plugin. I downloaded the zip from here, uploaded with no problem, clicked activate and I got this error:

`Warning: require(/var/www/vhosts/norburychurch.org.uk/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/norburychurch.org.uk/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32 Fatal error: require(): Failed opening required '/var/www/vhosts/norburychurch.org.uk/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/norburychurch.org.uk/httpdocs/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32`

**Comment by GOT1878** [comment]
Just to second this, I'm having the same issue.

**Comment by OPPtester** [comment]
I just tested by installing the plugin on my test site and was able to install/activate. I did this from within the admin Panel...plugins->add new....

Running WP 4.5.2

**Comment by diegoquinteiro** [comment]
Please download the plugin binary from the releases page. If you downloaded the source code directly, please notice you need to run `composer install` on your plugin root to get the dependencies, as stated in the README.
