### ISSUE TITLE
Problem with Jetpack Publicize and scheduled posts

### ISSUE THREAD

**Issue by diplatis** [Automattic/facebook-instant-articles-wp#276]
I experience the following problem with scheduled posts and jetpack publicize:
When the scheduled post gets published it gets autoposted to my facebook page but with no opengraph image (should be the featured image). Also, I can see the post in Facebook's Instant Articles Production dashboard as Live (and no errors generated) but when I try to read it in facebook app there is no Instant Article, just usual link to my website post.

Wordpress: 4.5.2
Jetpack: 4.0.2
Instant Articles: 2.11

**Comment by bbgdesigner** [comment]
I have same issue... but i think if come from feature image rule.

**Comment by everton-rosario** [comment]
@diplatis and @bbgdesigner sorry for the long wait.

The image that is used as a featured image, is the one marked on the open graph web version that can be accessed from your canonical url of article.

In other words:
1. You have one web article on link: http://example.com/my_article_1
2. Facebook scraper will perform an get on your canonical URL of ingested article (http://example.com/my_article_1)
3. Facebook scraper will look for the og:image meta tag (`<meta property="og:image" content="http://example.com/my_article_1/featured.png" />)`
4. Check any web article on [Facebook Developers debugger](https://developers.facebook.com/tools/debug)



If you guys have any doubts or if the issue persists, reopen or ping again on this thread so we can have further information.


If you have more doubts regarding this topic, please share some more info:

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"
