### ISSUE TITLE
Custom rule for youtube embed not work.

### ISSUE THREAD

**Issue by MattiaConfalonieri** [Automattic/facebook-instant-articles-wp#278]
here may page http://www.piccolericette.net/piccolericette/spiedini-di-asparagi-e-bacon/

and here my custom rule

`{
    "rules":
    [
        {
            "class": "SocialEmbedRule",
            "selector" : "div.video-shortcode",
            "properties" : {
                "socialembed.url" : {
                    "type" : "string",
                    "selector" : "iframe",
                    "attribute": "src"
                }
            }
        }
    ]
}`

i really don't understand why don't work... please help me.

**Comment by MattiaConfalonieri** [comment]
Any idea?

**Comment by stuartshields** [comment]
@MattiaConfalonieri Try this:

```
{ "rules": [ { "class": "SocialEmbedRule", "selector" : "//div[@class='video-shortcode' and iframe]", "properties" : { "socialembed.url" : { "type" : "string", "selector" : "iframe", "attribute": "src" } } } ] }
```

**Comment by MattiaConfalonieri** [comment]
Unfortunately it does not work,

**Comment by stuartshields** [comment]
@MattiaConfalonieri How about this one:

```php
{ 
	"rules": 
	[{
		"class": "SocialEmbedRule",
        "selector" : "//div.video-shortcode[iframe]",
        "properties" : {
            "socialembed.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "socialembed.iframe" : {
                "type" : "children",
                "selector" : "iframe"
            },

        }
    }] 
}

**Comment by MattiaConfalonieri** [comment]
Thanks for the help but not work... custom rules for me not work properly in the plugin...

**Comment by stuartshields** [comment]
@MattiaConfalonieri After adding the custom rules, your clicking update from within the actual post screen itself to update the article? I'm interested in working out why this isn't working for you

**Comment by MattiaConfalonieri** [comment]
yes yes i update the post, but nothing appear in the instant article...

**Comment by stuartshields** [comment]
@MattiaConfalonieri  I also noticed this in your code for your videos:

`<iframe title=$title width="620" height="349" src="http://www.youtube.com/embed/e3POHO89YhM" frameborder="0" allowfullscreen></iframe>` notice `title` has `$title` maybe this is causing the issue?

**Comment by MattiaConfalonieri** [comment]
I remove `title=$title` but nothing change, i try your two code and the mine...

**Comment by jamestylerpatton** [comment]
Forgive me I don't know at all how these custom rules work, but could it not be working because the selector is looking for the class `.video-shortcode` but you're trying to target the iframe, which doesn't have that class?
