### ISSUE TITLE
Images are not seen

### ISSUE THREAD

**Issue by overpress** [Automattic/facebook-instant-articles-wp#281]
After the latest updates of the plugin images in our instant article unseen. Why?

![img_1155](https://cloud.githubusercontent.com/assets/17315030/15407173/ecb8ccc4-1e09-11e6-83fd-fbcca190ab63.PNG)

**Comment by overpress** [comment]
Up

**Comment by diegoquinteiro** [comment]
Hi,

Can you share the debug information from the Transformer? It is shown in the bottom of the post screen, in the Instant Articles metabox. We need the original markup and the transformed one to check why your images aren't showing up.

Thank you,
Diego

**Comment by overpress** [comment]
Hi @diegoquinteiro,

here's what we wrote:

 It wasn't possible to submit your article

The server responded with the following messages:

Could Not Download Image: Your image from URL http://overpress.it/wp-content/uploads/2016/06/AXON-7-3.jpg could not be downloaded with an error code 403. Please check to make sure image at http://overpress.it/wp-content/uploads/2016/06/AXON-7-3.jpg is active and loads correctly at that URL.
Could Not Download Image: Your image from URL http://overpress.it/wp-content/uploads/2016/06/AXON-7-2.jpg could not be downloaded with an error code 403. Please check to make sure image at http://overpress.it/wp-content/uploads/2016/06/AXON-7-2.jpg is active and loads correctly at that URL.
Could Not Download Image: Your image from URL http://overpress.it/wp-content/uploads/2016/06/AXON-7.jpg could not be downloaded with an error code 403. Please check to make sure image at http://overpress.it/wp-content/uploads/2016/06/AXON-7.jpg is active and loads correctly at that URL.
Could Not Download Image: Your image from URL http://overpress.it/wp-content/uploads/2016/06/AXON-7.jpg could not be downloaded with an error code 403. Please check to make sure image at http://overpress.it/wp-content/uploads/2016/06/AXON-7.jpg is active and loads correctly at that URL.

**Comment by overpress** [comment]
But in the feed of Instant Article we see all images. Here it is -> http://overpress.it/feed/instant-articles

**Comment by overpress** [comment]
Anybody can help us?

**Comment by overpress** [comment]
Even after you have updated the plugin to version 3.0 same problem.

The Transformed Markup, however, appears to be correct. Here it is:

`<html>
  <head>
    <link rel="canonical" href="http://overpress.it/2016/07/12/pokemon-go-fenomeno-videoludico/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://overpress.it/wp-content/uploads/2016/07/sddefault.jpg"/>
        </figure>
        <h1>Pokémon GO: il nuovo fenomeno videoludico</h1>
        <time class="op-published" datetime="2016-07-12T19:59:30+02:00">July 12th, 7:59pm</time>
        <time class="op-modified" datetime="2016-07-13T10:07:11+02:00">July 13th, 10:07am</time>
        <address><a>Marco Simile</a>Classe 1991, appassionato di Videogames fin dalla tenerà età, venne iniziato alla via del gamer da un Sega Mega Drive, per poi passare al Nintendo 64 e successivamente alla PlayStation. Studente, collezionista di Console, Videogames, Manga e Comics, sognatore, lettore, scrittore, amante della buona musica, e cinefilo doc. I suoi generi videoludici preferiti sono gli RPG in tutte le salse e gli Action-Adventure.</address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=1645375885720388_1695574737367169&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>Impazza la<b> Pokémon GO</b> mania. Dopo il boom del <b>1996</b>, avvenuto grazie al lancio dei primi due titoli <b>Pokémon</b> in Giappone (<b>Rosso </b>e<b> Verde</b>), a distanza di ben 20 anni il famoso brand dei simpatici mostriciattoli tascabili ritorna a cavalcare l’onda del successo grazie alla nuova applicazione dedicata: <b>Pokémon GO</b>.</p>
      <p>Nata dalla collaborazione tra <b>Niantic</b>, <b>Game Freak</b>, <b>The Pokémon Company</b> e <b>Nintendo</b>, e sviluppata per dispositivi<b> iOS</b> e <b>Android</b>, Pokémon GO realizzerà il sogno di ogni amante dei Pocket Monsters, permettendoci di intercalarci nei panni di un allenatore di Pokémon e di catturare le creature, allevarle, farle evolvere, e farle combattere. L’unica cosa di cui abbiamo bisogno è un dispositivo, <b>smartphone</b> o <b>tablet</b>, che monti un sistema operativo iOS o Android, aggiornato alle versioni più recenti. L’applicazione sfrutta la <b>fotocamera</b>, il <b>3G/4G</b>, il <b>GPS</b> e le tecnologie di <b>realtà aumentata</b>, in modo che, camminando in casa, per strada, nei boschi, in prossimità di corsi d’acqua e persino nei mari, ci sarà possibile incontrare diverse specie di Pokémon da catturare.<b> Il segreto è muoversi il più possibile, camminare, esplorare luoghi sconosciuti, e tenere sempre sott’occhio il GPS che ci indicherà dove potremo trovare determinate specie di Pokémon.</b> In prossimità di un Pokémon ci verrà data la possibilità di ingaggiare battaglia per provare a catturarlo: a quel punto si attiverà la fotocamera e, grazie alla realtà aumentata, vedremo la creatura muoversi nel nostro mondo.</p>
      <figure>
        <img src="http://img1.voltaico.lavozdegalicia.es/wp-content/uploads/2016/06/PokemonGO-ejemplo-1.jpg"/>
      </figure>
      <p>Seppur al momento sia disponibile ufficialmente solo in pochi paesi, negli Stati Uniti, a pochi giorni dal lancio, ha già riscosso parecchio successo e si è garantito una buona fetta di giocatori. Risulta installato sul <b>5.16%</b> di tutti i dispositivi Android, superando anche una app molto utilizzata quale <b>Tinder</b>. E, di tutti questi dispositivi, oltre il <b>60%</b> la utilizza quotidianamente registrando un numero di utenti attivi che si sta avvicinando molto ad un social network importante come <b>Twitter</b>. Per finire, stando ai dati, il tempo medio di utilizzo giornaliero è pari a <b>43 minuti e 23 secondi</b>, maggiore rispetto ad App molto affermate tra cui <b>WhatsApp, Instagram, SnapChat </b>e<b> Messenger</b>.</p>
      <figure>
        <img src="http://overpress.it/wp-content/uploads/2016/07/236966_1a.jpg"/>
      </figure>
      <p>Il successo riscosso finora dalla app è così clamoroso che ha anche fatto<b> aumentare notevolmente il valore delle azioni Nintendo</b>. L’incremento è stato infatti del <b>23%</b>, battendo ogni record esistente e superando anche il picco registrato nel <b>1983</b>, producendo ricavi pari a <b>14,04 milioni di dollari</b>. Se è riuscito a fare questo in così pochi giorni, chissà dove potrà arrivare in futuro, anche con il rilascio di nuovi contenuti.</p>
      <blockquote>
Nintendo having their best day since 1983 as <a href="https://twitter.com/hashtag/PokemonGo?src=hash">#PokemonGo</a> takes over the world<a href="https://twitter.com/hashtag/MoverOverMario?src=hash">#MoverOverMario</a> <a href="https://t.co/9XnHeumMSx">pic.twitter.com/9XnHeumMSx</a>
— David Ingles (@DavidInglesTV) <a href="https://twitter.com/DavidInglesTV/status/752303662215618560">11 luglio 2016</a>
</blockquote>
      <p>Secondo quanto riportato dal <b>Wall Street Journal</b>, la release nel nostro continente avverrà <b>“nel giro di pochi giorni”</b>. A questo punto non ci resta che aspettare.</p>
    </article>
  </body>
</html>`

References to this article->http://overpress.it/2016/07/12/pokemon-go-fenomeno-videoludico/

As you can see the third picture, the one with the chart, you correctly configured but returns the following error -> Could Not Download Image: Your image from URL http://overpress.it/wp-content/uploads/2016/07/236966_1a.jpg could not be downloaded with an error code 403. Please check to make sure image at http://overpress.it/wp-content/uploads/2016/07/236966_1a.jpg is active and loads correctly at that URL.

why?

**Comment by everton-rosario** [comment]
Im investigating this, @overpress

**Comment by overpress** [comment]
Thanks @everton-rosario

**Comment by everton-rosario** [comment]
@overpress Do you have any access log from your web server that serves this image `http://overpress.it/wp-content/uploads/2016/07/sddefault.jpg`?

Our scrapper is receiving a 403 response while trying to fetch from your web server.

Context:
Every new Instant Article posted, we pre-fetch all resources, so it is stored into Facebook CDN. 
Check if your image server logs, returns a 403 response code for our Facebook Instant Article scrapper robot.

**Comment by everton-rosario** [comment]
@overpress Im getting success on this, now.
Can you double check please?

**Comment by overpress** [comment]
Nope :( This article don't show the image on instant article -> http://overpress.it/2016/07/12/pokemon-go-fenomeno-videoludico/

**Comment by overpress** [comment]
@everton-rosario understand the problem: the CloudFlare CDN. How can I bypass the problem without being forced to disable cloudflare?

**Comment by everton-rosario** [comment]
@overpress Considering that this will be served from Facebook CDN, you don't need to use a CDN for the Instant Articles HTML markup. You can just point to the webserver that is working now.
Considering this you could only serve images from this CloudFlare CDN to your web version. 

Within the Instant Articles you need to be sure every content is accessible by our scrappers.

**Comment by overpress** [comment]
How do I do this? Us the CDN we on all the site, and as a result it ends up also on Instant Article.

**Comment by everton-rosario** [comment]
The case you've reported, is now working flawlessly on Instant Articles.
```html
<!doctype html><html><head><link rel="canonical" href="http://yourdomain"/><meta charset="utf-8">
<meta property="op:generator" content="facebook-instant-articles-sdk-php">
<meta property="op:generator:version" content="1.3.0">
<meta property="op:generator:application" content="facebook-instant-articles-wp">
<meta property="op:generator:application:version" content="2.11">
<meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php">
<meta property="op:generator:transformer:version" content="1.3.0">
<meta property="op:markup_version" content="v1.0">
<meta property="fb:use_automatic_ad_placement" content="true">
<meta property="fb:article_style" content="default">
</head>
<body><article><header><figure><img src="http://overpress.it/wp-content/uploads/2016/07/sddefault.jpg"></figure><h1>Pokémon GO: il nuovo fenomeno videoludico</h1>
<time class="op-published" datetime="2016-07-12T19:59:30+02:00">July 12th, 7:59pm</time><time class="op-modified" datetime="2016-07-13T10:07:11+02:00">July 13th, 10:07am</time><address>
<a>Marco Simile</a>Classe 1991, appassionato di Videogames fin dalla tenerà età, venne iniziato alla via del gamer da un Sega Mega Drive, per poi passare al Nintendo 64 e successivamente alla PlayStation. Studente, collezionista di Console, Videogames, Manga e Comics, sognatore, lettore, scrittore, amante della buona musica, e cinefilo doc. I suoi generi videoludici preferiti sono gli RPG in tutte le salse e gli Action-Adventure.</address>
<h3 class="op-kicker">Games</h3>
<figure class="op-ad"><iframe src="https://www.facebook.com/adnw_request?placement=1645375885720388_1695574737367169&amp;adtype=banner300x250" width="300" height="250"></iframe></figure></header><p>Impazza la<b> Pokémon GO</b> mania. Dopo il boom del <b>1996</b>, avvenuto grazie al lancio dei primi due titoli <b>Pokémon</b> in Giappone (<b>Rosso </b>e<b> Verde</b>), a distanza di ben 20 anni il famoso brand dei simpatici mostriciattoli tascabili ritorna a cavalcare l’onda del successo grazie alla nuova applicazione dedicata: <b>Pokémon GO</b>.</p>
<p>Nata dalla collaborazione tra <b>Niantic</b>, <b>Game Freak</b>, <b>The Pokémon Company</b> e <b>Nintendo</b>, e sviluppata per dispositivi<b> iOS</b> e <b>Android</b>, Pokémon GO realizzerà il sogno di ogni amante dei Pocket Monsters, permettendoci di intercalarci nei panni di un allenatore di Pokémon e di catturare le creature, allevarle, farle evolvere, e farle combattere. L’unica cosa di cui abbiamo bisogno è un dispositivo, <b>smartphone</b> o <b>tablet</b>, che monti un sistema operativo iOS o Android, aggiornato alle versioni più recenti. L’applicazione sfrutta la <b>fotocamera</b>, il <b>3G/4G</b>, il <b>GPS</b> e le tecnologie di <b>realtà aumentata</b>, in modo che, camminando in casa, per strada, nei boschi, in prossimità di corsi d’acqua e persino nei mari, ci sarà possibile incontrare diverse specie di Pokémon da catturare.<b> Il segreto è muoversi il più possibile, camminare, esplorare luoghi sconosciuti, e tenere sempre sott’occhio il GPS che ci indicherà dove potremo trovare determinate specie di Pokémon.</b> In prossimità di un Pokémon ci verrà data la possibilità di ingaggiare battaglia per provare a catturarlo: a quel punto si attiverà la fotocamera e, grazie alla realtà aumentata, vedremo la creatura muoversi nel nostro mondo.</p>
<figure><img src="http://img1.voltaico.lavozdegalicia.es/wp-content/uploads/2016/06/PokemonGO-ejemplo-1.jpg"></figure><p>Seppur al momento sia disponibile ufficialmente solo in pochi paesi, negli Stati Uniti, a pochi giorni dal lancio, ha già riscosso parecchio successo e si è garantito una buona fetta di giocatori. Risulta installato sul <b>5.16%</b> di tutti i dispositivi Android, superando anche una app molto utilizzata quale <b>Tinder</b>. E, di tutti questi dispositivi, oltre il <b>60%</b> la utilizza quotidianamente registrando un numero di utenti attivi che si sta avvicinando molto ad un social network importante come <b>Twitter</b>. Per finire, stando ai dati, il tempo medio di utilizzo giornaliero è pari a <b>43 minuti e 23 secondi</b>, maggiore rispetto ad App molto affermate tra cui <b>WhatsApp, Instagram, SnapChat </b>e<b> Messenger</b>.</p>
<figure><img src="http://overpress.it/wp-content/uploads/2016/07/236966_1a.jpg"></figure><p>Il successo riscosso finora dalla app è così clamoroso che ha anche fatto<b> aumentare notevolmente il valore delle azioni Nintendo</b>. L’incremento è stato infatti del <b>23%</b>, battendo ogni record esistente e superando anche il picco registrato nel <b>1983</b>, producendo ricavi pari a <b>14,04 milioni di dollari</b>. Se è riuscito a fare questo in così pochi giorni, chissà dove potrà arrivare in futuro, anche con il rilascio di nuovi contenuti.</p>
<blockquote>
Nintendo having their best day since 1983 as <a href="https://twitter.com/hashtag/PokemonGo?src=hash">#PokemonGo</a> takes over the world<a href="https://twitter.com/hashtag/MoverOverMario?src=hash">#MoverOverMario</a> <a href="https://t.co/9XnHeumMSx">pic.twitter.com/9XnHeumMSx</a>
— David Ingles (@DavidInglesTV) <a href="https://twitter.com/DavidInglesTV/status/752303662215618560">11 luglio 2016</a>
</blockquote>
<p>Secondo quanto riportato dal <b>Wall Street Journal</b>, la release nel nostro continente avverrà <b>“nel giro di pochi giorni”</b>. A questo punto non ci resta che aspettare.</p>
<footer></footer></article></body>
</html>
```

**Comment by everton-rosario** [comment]
Do you have any other case failing?
This is the only way we can dig more, to find out what is going on with your CDN.

**Comment by overpress** [comment]
Yes, now I've disabled for three hours CloduFlare:) However, I would like to reactivate CloudFlare in the coming hours.

**Comment by everton-rosario** [comment]
Please, be sure you have your CDN configured properly so we have access thru our scrapper.
Do you have any support from them? Try reaching them out.

**Comment by overpress** [comment]
I think I've solved by blocking the services of CloudFlare on feed/instant-article. 

View your kindness in giving us support I wanted to ask another thing: some of our post we have a photo gallery. Find it here --> http://overpress.it/2016/04/15/ikea-bicicletta/

how can we integrate it in instant article showing a carousel pictures? That "Transformation rules" should I enter?

**Comment by overpress** [comment]
See this image -> 
![schermata 2016-07-13 alle 21 31 15](https://cloud.githubusercontent.com/assets/17315030/16817050/31770a76-4941-11e6-8727-ddedbfb19f8d.jpg)

**Comment by everton-rosario** [comment]
@overpress You will have to add this rules right after the PassThroughRule with the "body".
```json
            {
                "class": "PassThroughRule",
                "selector" : "a.slide-gallery-image-link"
            },
            {
                "class": "PassThroughRule",
                "selector" : "figure.td-slide-galery-figure"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-slide-item"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-slider"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-doubleSlider-1"
            },
            {
                "class": "IgnoreRule",
                "selector" : "div.td-gallery-slide-top"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.post_td_gallery"
            },
```


And this other 2, you can add by the end of your rules file.
```json
            {
                "class": "SlideshowImageRule",
                "selector" : "img",
                "properties" : {
                    "image.url" : {
                        "type" : "string",
                        "selector" : "img",
                        "attribute": "src"
                    },
                    "caption.title" : {
                        "type" : "string",
                        "selector" : "img",
                        "attribute": "data-caption"
                    }
                }
            },
            {
                "class": "SlideshowRule",
                "selector" : "div.td-slider"
            }
```

**Comment by everton-rosario** [comment]
Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by overpress** [comment]
Hi @everton-rosario, i plugged everything well but doesn't seem to work. 

`{ "rules": 
[
{
                "class": "PassThroughRule",
                "selector" : "a.slide-gallery-image-link"
            },
            {
                "class": "PassThroughRule",
                "selector" : "figure.td-slide-galery-figure"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-slide-item"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-slider"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.td-doubleSlider-1"
            },
            {
                "class": "IgnoreRule",
                "selector" : "div.td-gallery-slide-top"
            },
            {
                "class": "PassThroughRule",
                "selector" : "div.post_td_gallery"
            },

            {
                "class": "SlideshowImageRule",
                "selector" : "img",
                "properties" : {
                    "image.url" : {
                        "type" : "string",
                        "selector" : "img",
                        "attribute": "src"
                    },
                    "caption.title" : {
                        "type" : "string",
                        "selector" : "img",
                        "attribute": "data-caption"
                    }
                }
            },
            {
                "class": "SlideshowRule",
                "selector" : "div.td-slider"
            }
]
}`

We published this item with Gallery -> http://overpress.it/2016/07/14/napoli-nuova-maglia-2016-2017-firmata-kappa/

The error that gives us is this 👇

<img width="682" alt="schermata 2016-07-14 alle 11 47 12" src="https://cloud.githubusercontent.com/assets/17315030/16835372/bd943de0-49b8-11e6-9f09-8ae45deaaa2e.png">

**Comment by everton-rosario** [comment]
Well, those warnings are just because you are not treating the `<style>` tag and the other `<div>`.

The transformer will raise warnings to any tag that you didn't cover with your rules.
This is why we have the PassThroughRule and the IgnoreRule.

The **script** can be set to use the ignore:
```
{
    "class": "IgnoreRule",
    "selector": "script"
}
```
and the **div** probably will be a PassThroughRule:
```
{
    "class": "PassThroughRule",
    "selector": "div.td-slide-on-2-columns"
}
```

**Comment by overpress** [comment]
@everton-rosario ok, now gallery work but we have these alert:

<img width="963" alt="schermata 2016-07-14 alle 18 12 13" src="https://cloud.githubusercontent.com/assets/17315030/16846903/9bff50c6-49ee-11e6-93d2-189b78b65aca.png">

**Comment by everton-rosario** [comment]
`<br>` and '<style>` in the context of Slideshow can be safely ignored:
add this rule to your rules-configuration.json:

```
{
    "class": "IgnoreRule",
    "selector": "br"
}
{
    "class": "IgnoreRule",
    "selector": "style"
}
```

`<div class="td-doubleSlider-2">` This should be verified if this tag or any other tag inside it contains content that should be transformed. If not, also add an IgnoreRule for it:

```
{
    "class": "IgnoreRule",
    "selector": "div.doubleSlider-2"
}
```

**Comment by overpress** [comment]
Thank you so much for all the help @everton-rosario . Now we no longer alerts. We send Facebook for approval. We know if we approve :)

**Comment by mintaras** [comment]
I am having same issue.. @overpress How did you managed to block the services of CloudFlare on feed/instant-article?

Thanks

**Comment by PaoloPhino** [comment]
Ciao @overpress :)
ho lo stesso tuo problema con CloudFlare, ho provato a creare una regola ma evidentemente non è impostata giusta. Come avete risolto questo problema? Grazie mille ;)

**Comment by PaoloPhino** [comment]
Hi @everton-rosario and @diegoquinteiro :)

I have a very similar problem to the one @overpress reported
the code of my instant articles is create correctly, but when the Facebook scraper tries to download the images for my instant articles, it gives error 502
the problem is related to the fact that I use a CDN (CloudFlare) and for some reason Facebook can not download images from CloudFlare cache.

If I create a rule that bypass the cache for all the images, or if I shut down CloudFlare, and try again to save an Instant Article, Facebook can download the images with no problem, but that's not a permanent solution cause it would affect my website in a negative way.

The rule @overpress mentioned to bypass cache for URL mydomain.it/feed/instant-articles it doesn't work.

I also created a rule to whitelist this IP range: AS32934 that should allow Facebook scrapers to visit my website, but still that doesn't change the problem.
Is the Facebook crawler for instant articles inside this IP range or does it have a different IP? 

I talked to CloudFlare customer service and they are trying to help me but they don't see 502 errors in their logs... they asked me this:

"ask them how is their crawler performing the HTTP request (FULL request headers, e.g. URL , headers) in order to trigger the 502 error? If possible, it would be great if FB can provide us with the FULL HTTP response headers e.g. CF-RayID"

Thanks for the help ;)
Bye

**Comment by boslmreds** [comment]
i got issue Error 403 for my feature image. Eventhough in web is still fine

**Comment by PaoloPhino** [comment]
Unfortunately no...
I have to manually disable CloudFlare when I work on Instant Articles and re-enable it when I'v finished

**Comment by bajpangosh** [comment]
Use RSS feed URL "https://yoursite.com/feed/instant-articles"
