### ISSUE TITLE
JetPack Slideshow Rule Cannot be defined

### ISSUE THREAD

**Issue by djrules24** [Automattic/facebook-instant-articles-wp#289]
Here's my slideshow data code, How do I create a Transformation rule for the same.

```
<div id="gallery-58713-2-slideshow" class="slideshow-window jetpack-slideshow slideshow-black" data-trans="fade" data-autostart="1" data-gallery="[{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023739\/1.jpg&quot;,&quot;id&quot;:&quot;58714&quot;,&quot;title&quot;:&quot;1&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023750\/Onion-Vada-Adukkala.jpg&quot;,&quot;id&quot;:&quot;58715&quot;,&quot;title&quot;:&quot;Onion-Vada-Adukkala&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023806\/3-2.jpg&quot;,&quot;id&quot;:&quot;58716&quot;,&quot;title&quot;:&quot;3 (2)&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023850\/23-onoinvada.jpg&quot;,&quot;id&quot;:&quot;58718&quot;,&quot;title&quot;:&quot;23-onoinvada&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023858\/359c2bae04b1baeaa70e4b8607fa1840.jpg&quot;,&quot;id&quot;:&quot;58719&quot;,&quot;title&quot;:&quot;359c2bae04b1baeaa70e4b8607fa1840&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023914\/IMG_1417-660x440.jpg&quot;,&quot;id&quot;:&quot;58720&quot;,&quot;title&quot;:&quot;IMG_1417-660\u0026#215;440&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;}]" itemscope itemtype="http://schema.org/ImageGallery"></div>
```

**Comment by stuartshields** [comment]
@djrules24 No code?

**Comment by djrules24** [comment]
Sorry about that, didnt include the code quotes. Here you go.

`<div id="gallery-58713-2-slideshow" class="slideshow-window jetpack-slideshow slideshow-black" data-trans="fade" data-autostart="1" data-gallery="[{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023739\/1.jpg&quot;,&quot;id&quot;:&quot;58714&quot;,&quot;title&quot;:&quot;1&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023750\/Onion-Vada-Adukkala.jpg&quot;,&quot;id&quot;:&quot;58715&quot;,&quot;title&quot;:&quot;Onion-Vada-Adukkala&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023806\/3-2.jpg&quot;,&quot;id&quot;:&quot;58716&quot;,&quot;title&quot;:&quot;3 (2)&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023850\/23-onoinvada.jpg&quot;,&quot;id&quot;:&quot;58718&quot;,&quot;title&quot;:&quot;23-onoinvada&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023858\/359c2bae04b1baeaa70e4b8607fa1840.jpg&quot;,&quot;id&quot;:&quot;58719&quot;,&quot;title&quot;:&quot;359c2bae04b1baeaa70e4b8607fa1840&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;},{&quot;src&quot;:&quot;https:\/\/s3-ap-southeast-1.amazonaws.com\/hungryforever\/wp-content\/uploads\/2016\/05\/23023914\/IMG_1417-660x440.jpg&quot;,&quot;id&quot;:&quot;58720&quot;,&quot;title&quot;:&quot;IMG_1417-660\u0026#215;440&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;itemprop&quot;:&quot;image&quot;}]" itemscope itemtype="http://schema.org/ImageGallery"></div>`

**Comment by stuartshields** [comment]
What's the rules you tried to apply?

**Comment by djrules24** [comment]
The slidehow rule.

Even a static image rule is fine as well.

**Comment by stuartshields** [comment]
@djrules24 try the following rules:

```php
{
    "rules":
    [{
        "class": "SlideshowImageRule",
        "selector" : "div.gallery-row",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "data-orig-file"
            },
            "caption.title" : {
                "type" : "string",
                "selector" : "figcaption"
            }
         }
    },{
        "class": "SlideshowRule",
        "selector" : "div.tiled-gallery"
    }]
}

**Comment by stuartshields** [comment]
@djrules24 I think I have found an issue with the above rule, it'll only show the one image from the gallery since it's trying to grab it from `div.gallery-row`. I'm going to work more on this rule tonight.

**Comment by djrules24** [comment]
Koolio.

**Comment by stuartshields** [comment]
@djrules24 Unfortunately due to Jetpack slideshow requiring JavaScript enabled. The plugin looks like it'll need to support the Jetpack slideshow properly. I'll look into creating this and maybe you can test it so we can get it merged.

**Comment by nicolinuxfr** [comment]
I'm using Jetpack gallery as well, so if you need tests, don't hesitate !

**Comment by djrules24** [comment]
Alright.
What if we can make it into a single image rule, but how do we process the next image.

**Comment by stuartshields** [comment]
@djrules24 If you select it as a tiled-gallery the following rule will work. But for the Jetpack-slideshow itself, we'll need to build some custom code.

```json
{
    "rules":
    [{
        "class": "SlideshowImageRule",
        "selector" : "div.gallery-group",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "data-orig-file"
            }
         }
    },{
        "class": "SlideshowRule",
        "selector" : "div.tiled-gallery div.gallery-row"
    }]
}

**Comment by nicolinuxfr** [comment]
Why would you need the slideshow ? It's an Instant Article features and it works well already !

Right now, I have this rule, but only the first image of a gallery is displayed in the IA. So I edit the article myself to add all other pictures, which is a pain.

`{ "class": "SlideshowImageRule", "selector" : "div.gallery-row","properties" : {"image.url" : { "type" : "string", "selector" : "img", "attribute": "data-orig-file"}, "caption.title" : { "type" : "string", "selector" : "div.tiled-gallery-caption"} } }, { "class": "SlideshowRule", "selector" : "div.tiled-gallery" } ]`

I will try your rule and see if it's better.

**Comment by stuartshields** [comment]
@nicoleckohler Because Jetpack has it's own slideshow that formats the code differently. We need to add support for it.

**Comment by nicolinuxfr** [comment]
It works great ! I don't need more, at least I don't think so… :-)

(If you wish to see what it does, here's an example : https://voiretmanger.fr/chef-table-gelb-netflix/)

**Comment by everton-rosario** [comment]
@djrules24 @stuartshields @nicolinuxfr On the master version that will be released soon we have the fix for this compatibility for the Jetpack plugin components.

Can you guys help to check it?
