### ISSUE TITLE
Some tags/inline styles are not being filtered out; Facebook is stripping out content

### ISSUE THREAD

**Issue by doubleswirve** [Automattic/facebook-instant-articles-wp#29]
Hello,

We're having an issue where some/all of the body content pasted into WordPress from another text editor (e.g., Word, Google Doc) is being stripped by Facebook because wrapper `span` tags and inline styles are still present in the Instant feed.

Here's an example snippet of such content:

```html
<p><span style="font-weight:400;">It’s no wonder drivers in Bangalore </span><a href="http://www-03.ibm.com/press/us/en/pressrelease/35359.wss"><span style="font-weight:400;">rank</span></a><span style="font-weight:400;"> as the angriest and most stressed-out in all of India: According to a </span><i><span style="font-weight:400;">Quartz</span></i><span style="font-weight:400;"> study, it </span><a href="http://qz.com/280082/the-true-cost-of-bangalores-traffic-gridlock-to-indias-it-industry-is-staggering/"><span style="font-weight:400;">takes</span></a><span style="font-weight:400;"> the southern city’s average tech worker at least two hours to commute to work through Bangalore’s crowded, disorganized streets each day. </span></p>
```

I've suggested to our edit team that they clear formatting upon pasting (as we don't want inline styles on the website); however, just wanted to raise with you guys in case there was a way to automatically filter such markup/attributes out.

Thanks!

**Comment by bjornjohansen** [comment]
You should of course clean up the code before it goes into the database, but if it’s already there, I suggest you use the standard WordPress filter `the_content` to clean it up. It works on both the regular web pages and Instant Articles.

**Comment by doubleswirve** [comment]
Thanks for the quick response!

I might be misunderstanding, but this is how the content is being output on the site, via `the_content()` helper, and the Instant feed. Here's a screenshot of the site:

<img width="783" alt="screen shot 2016-03-07 at 11 29 39 am" src="https://cloud.githubusercontent.com/assets/863571/13580833/d51c02d8-e458-11e5-8c86-9e2902bb9a62.png">

For both the web and the feed, shouldn't the `the_content` filter already have been applied?

**Comment by bjornjohansen** [comment]
Yes, the `the_content` filter have already been applied. You need to write a custom filter and apply it to clean up your messy markup.
Or much better: fix it in the database.
