### ISSUE TITLE
Problem with infogram plugin

### ISSUE THREAD

**Issue by Esther27** [Automattic/facebook-instant-articles-wp#291]
Hi,

we use infogram graphs for our WP articles and we usually inserted them via the responsive embed link. However, as this was not recognized by facebook for our instant articles we tried an alternative way, namely embedding the graph via the infogram plugin. This also didn't work, in our instant articles the infogram graph is simply not shown. Does anyone have a solution or tip to this problem?

Thx a lot!

**Comment by stuartshields** [comment]
@Esther27 Quick question for you, have you checked the RSS feed to see what the output of the code is? just add /instant-articles to the end of your domain (change instant-articles if you changed the name of the RSS feed for Instant Articles). If so can you paste the code here and I'll check it out.

**Comment by Esther27** [comment]
Hi @stuartshields! thanks for the reply!

this is the code output of the infogram graph:

<script id="infogram_0_949b4acc-21fa-410c-898c-6a5a63524188" title="AnTuTu Sony Xperia X" src="//e.infogr.am/js/embed.js?bud" type="text/javascript"></script>

**Comment by stuartshields** [comment]
@Esther27 No code was outputted... Make sure to use ` for opening and closing

**Comment by stuartshields** [comment]
@Esther27 Do you have any surrounding div tags? What Rules are you using to display it?

**Comment by Esther27** [comment]
no I don't have any surrounding div tags.  We already had the infogram graph working, so I thought there is no need to have any rules.....

**Comment by stuartshields** [comment]
@Esther27 You'll need rules to get it to work.

**Comment by Esther27** [comment]
ok @stuartshields. That's the problem, I don't know how to set up such rules. If you have an idea, maybe you could post it here? Thanks a lot!

**Comment by stuartshields** [comment]
@Esther27 Let me think about it and see what I can do for you.

**Comment by stuartshields** [comment]
@Esther27 I'm still thinking about this, as I don't have a infogram account, is there anyway you can send me a URL to a page that has the infogram? Also I can see an issue that my PR fixes https://github.com/Automattic/facebook-instant-articles-wp/pull/290 that we might run into even when we get the rules in place. Basically the script src is using `//` instead of `https://`.

**Comment by Esther27** [comment]
Hi @stuartshields! Thx for your reply! Yes, here is a URL where we have an infogram graph: http://www.a1blog.net/2016/05/20/sony-xperia-x-test/#Leistung

**Comment by stuartshields** [comment]
@Esther27 Try this:
```{
    "rules":
    [{           
	    "class": "InteractiveRule",
	    "selector" : "//div.interactive",
	    "properties" : {
	        "interactive.iframe" : {
	            "type" : "children",
	            "selector" : "div.interactive"
	        }
	    }  
	}]
}```

**Comment by Esther27** [comment]
@stuartshields: I inserted the rule but unfortunately is still doesn't show the graph in the pages manager app view of the instant article :(

**Comment by stuartshields** [comment]
@Esther27  I'll have another look tonight if I get time.

**Comment by everton-rosario** [comment]
@Esther27 Is this still happening to you?

Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

I'll close for now, and reopen with the complete info so I can help to fix that for you.
