### ISSUE TITLE
Is Automattic actively developing this plugin?

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/facebook-instant-articles-wp#292]
I see little in the way of commit activity over the past month and a quickly growing issues list that isn't being addressed.

What is Automattic's commitment to this plugin? Or do we need to rely on community-sourced fixes and our own workarounds for stuff?

**Comment by stuartshields** [comment]
@kevinlisota I think this plugin was developed in partnership between Facebook and Automattic. I'd wait and see what happens over next few weeks. While I don't personally work for either, if you have any fixes you want, let me know and I'll create a pull request so we can atleast get something happening.

**Comment by everton-rosario** [comment]
@kevinlisota and @stuartshields This is an open source project where Automattic owns the repository.

We are getting the best help we can to keep it up and running.
