### ISSUE TITLE
Div tags around images prevents inclusion in feed

### ISSUE THREAD

**Issue by Jake-Grafenstein** [Automattic/facebook-instant-articles-wp#293]
It seems that whenever an image is encapsulated in a div tag, the image is ignored when the plugin parses the article. I know this to be true because when I add a basic image to a post, the image can render correctly in Facebook. Captioned images are encapsulated in div tags and thus are completely ignored by your plugin. This seems like it would be a pretty simple fix.

**Comment by stuartshields** [comment]
@Jake-Grafenstein Have you looked at adding rules for this?

```
{
    "rules":
    [{
        "class": "ImageRule",
        "selector": "//p[a[img]]|//a[img]|//div[img]",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            }
        }
    }]
}
```

**Comment by everton-rosario** [comment]
You can also add a ByPassRule for the selector of the <div> tag.
