### ISSUE TITLE
Analytics Embed Code Invalid

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#297]
Hi there, 

I tried to insert comscore and Alexa tracking code into the Analytics Embed code section but I have received the error " Invalid HTML markup provided for custom analytics tracker code". 

Anyone met the same issue or have any idea?

**comscore**
```
<script>
  var _comscore = _comscore || [];
  _comscore.push({ c1: "2", c2: "11111111" });
  (function() {
    var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
    s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
    el.parentNode.insertBefore(s, el);
  })();
</script>
<noscript>
<img src="http://b.scorecardresearch.com/p?c1=2&c2=11111111&cv=2.0&cj=1" />
</noscript>
```

**Alexa**
```
<script type="text/javascript">
_atrk_opts = { atrk_acct:"bd5Ei1a4ZP00MC", domain:"tantannews.com",dynamic: true};
(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();
</script>
<noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=bd5Ei1a4ZP00MC" style="display:none" height="1" width="1" alt="" /></noscript>
```

**Comment by stuartshields** [comment]
Hi @CarsonLee27 You don't need to worry about the <noscript> tags, as the App itself supports JS so the tracking code works.

```javascript
<script>
  var _comscore = _comscore || [];
  _comscore.push({ c1: "2", c2: "11111111" });
  (function() {
    var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
    s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
    el.parentNode.insertBefore(s, el);
  })();
</script>
<script type="text/javascript">
_atrk_opts = { atrk_acct:"bd5Ei1a4ZP00MC", domain:"tantannews.com",dynamic: true};
(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();
</script>

**Comment by CarsonLee27** [comment]
Okay. Basically you have removed the 

<noscript>
<img src="http://b.scorecardresearch.com/p?c1=2&c2=11111111&cv=2.0&cj=1" />
</noscript>

and 

<noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=bd5Ei1a4ZP00MC" style="display:none" height="1" width="1" alt="" /></noscript>

Right? Okay. I just proceed with the code you provide then =D THank you so much @stuartshields =D

**Comment by stuartshields** [comment]
@CarsonLee27 Yes that's all I have done.

**Comment by CarsonLee27** [comment]
Cool =D

**Comment by sushant0077** [comment]
Hello stuartshields,
I am facing the same issue " Invalid HTML markup provided for custom analytics tracker code". for my below GTM code. Can you please help me out . Thank you.

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WGSSZRV7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WGSSZRV7');</script> 

As per above comment i removed the noscript but still i am getting the same error.

**Comment by stuartshields** [comment]
@sushant0077 try the following:

```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-WGSSZRV7');</script>
```

You don't need to include the noscript code.

**Comment by sushant0077** [comment]
@stuartshields  thanks for your quick reply.. i tried it but still showing the same error."Invalid HTML markup provided for custom analytics tracker code";

**Comment by phpmypython** [comment]
@sushant0077 
I've been dealing with this issue myself and ended up finding the real issue you're having.

It comes from the fact that they are loading the value of the embed code field into DOMDocument through the following method.
```(php)
if (isset($field_values['embed_code_enabled']) && $field_values['embed_code_enabled']) {
                        $document = new DOMDocument();
                        $fragment = $document->createDocumentFragment();
                        if (!@$fragment->appendXML($field_values[$field_id])) {
                            add_settings_error(
                              'embed_code',
                              'invalid_markup',
                              'Invalid HTML markup provided for custom analytics tracker code'
                            );
                        }
                    }
```

If the text is not valid XML then the load will fail as will the saving of the value resulting in the error.

The cause of the tag not validating is actually the occurrence of a ```&``` inside of a string in the tag that's not the only issue i ran across though i also had to make sure that vars were being initialized individually instead of defining multiple using a comma. The final code you need to use is below.

```(html)
<script>(function (w, d, s, l, i) {w[l] = w[l] || [];w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});var f = d.getElementsByTagName(s)[0];var j = d.createElement(s);var dl = l != 'dataLayer' ? "&amp;l=" + l : '';j.async = true;j.src ='//www.googletagmanager.com/gtm.js?id=' + i + dl;f.parentNode.insertBefore(j, f);})(window, document, 'script', 'dataLayer', 'GTM-WGSSZRV7');</script>
```

**Comment by sushant0077** [comment]
@phpmypython 
 
Finally its working for me.. A huge thanks to you..:)

**Comment by phpmypython** [comment]
Very welcome 👍
