### ISSUE TITLE
Google Analytics appear (not set) with API code 

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#298]
Have encounter issue with integration of Google Analytics in Instant Article. (withMonsterInsight plugin/without - direct insert GA). 

In Google Analytics Real Time -> Content, it display the (not set) at the Page title column. Realise it display auth.php?api_key=xxxxxxxx

Anyone have similar issue or any idea? 

Thank you. 

<img width="1045" alt="screen shot 2016-05-26 at 1 41 41 pm" src="https://cloud.githubusercontent.com/assets/4049250/15573266/4c527e0a-2378-11e6-9a4b-3b4cf67eba8b.png">

**Comment by stuartshields** [comment]
@CarsonLee27 Can you paste a code snippet here

**Comment by CarsonLee27** [comment]
Here you go. 
```
<figure class="op-tracker"><iframe><!-- This site uses the Google Analytics by MonsterInsights plugin v5.4.9 - Universal enabled - https://www.monsterinsights.com/ -->
<script type="text/javascript">
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

	__gaTracker('create', 'UA-45317251-1', 'auto');
	__gaTracker('set', 'forceSSL', true);
	__gaTracker('set', 'anonymizeIp', true);
	__gaTracker('require', 'displayfeatures');
	__gaTracker('require', 'linkid', 'linkid.js');
	__gaTracker('send','pageview');

</script><!-- / Google Analytics by MonsterInsights --></iframe></figure>
```

Do let me know if you need more info =D thank you so much @stuartshields

**Comment by stuartshields** [comment]
@CarsonLee27 Give me until Monday and I'll see what I can do for you :)

**Comment by CarsonLee27** [comment]
@stuartshields  sure bro ~~ thank you so much !!!

**Comment by stuartshields** [comment]
@CarsonLee27 I've sent this ticket to Monster Insights and hopefully they'll check it out and reply.

**Comment by CarsonLee27** [comment]
Cool. 
Thank you so much. 

Actually we have tried use without Monster Insights. but the results was same.

**Comment by everton-rosario** [comment]
@CarsonLee27 Have you debugged your tracking code?
You can do it using a remote Javascript console.
Like this one: http://jsconsole.com/remote-debugging.html

**Comment by herbco** [comment]
Hi Guys

Is there a resolution to this issue yet?

**Comment by everton-rosario** [comment]
@herbco Use the debugger I've mentioned so you can debug your code that runs into iframe (within Instant Article):
http://jsconsole.com/remote-debugging.html

Im closing this issue with no response for 7 days of @CarsonLee27.

@stuartshields can you post here the link for the issue you've opened to Monster Insights?
