### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by technosailor** [Automattic/facebook-instant-articles-wp#299]
Just an FYI-

Unit tests are failing. While the plugin works fine, failure to have passing unit tests throw CircleCI for a loop. Unfortunately, it looks like some of the failures are from the Facebook SDK too so not sure how much control you have but it would be good to fix or remove the tests.

**Comment by stuartshields** [comment]
@technosailor Can you post that over at the SDK - https://github.com/facebook/facebook-instant-articles-sdk-php

**Comment by everton-rosario** [comment]
@technosailor Have you posted it to SDK?
Can you please file an issue within the SDK project with repro steps and more details please?

SDK lies here: https://github.com/facebook/facebook-instant-articles-sdk-php

thanks

**Comment by everton-rosario** [comment]
All unit tests on SDK are ok.

Thanks for flagging this.
