### ISSUE TITLE
Using instant articles with qTranslate in Wordpress

### ISSUE THREAD

**Issue by miguelfspinto** [Automattic/facebook-instant-articles-wp#303]
When creating the instant articles, the tags [:pt] and [:] are appearing in title and content. I suggest a field where we can strip some expressions when transforming the content into instant articles.

**Comment by stuartshields** [comment]
@miguelfspinto Does the site support english as a language? I've tested the plugin and I don't have the issue your reporting. What settings are you using?

**Comment by miguelfspinto** [comment]
​Hi Stuart,

The website is in Portuguese and Spanish. I am using qTranslate-X to manage
internationalization in posts. The way this plugin manage i18n is adding
tags for each language in the post_title and post_content fields. The tags
are like [:pt] and [:es].

The problem is during the generation of instant article code because this
tags are not being striped, so the article title appears something like
this: [:pt] {post title} [:]

I hope I was able to explain my problem. My recommendation is to create an
text input, where we can place some expressions to be removed during
transformation. I could write something like this [:pt], [:es], [:] and it
would strip this expressions from my content.

Thank you.

Best regards,
Miguel Pinto




















​

**Comment by stuartshields** [comment]
@miguelfspinto I can see the issue you're having. I'm working on something else at the moment but when I'm done I'll look into the translating issue for you.

**Comment by miguelfspinto** [comment]
Thank you very much for the help. :)

Best regards,
Miguel Pinto

**Comment by miguelfspinto** [comment]
Dear Stuart,

We are evaluationg possible solutions. Do you have a time estimated to
correct this issue in this plugin?
Thank you.

BR,
Miguel Pinto

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by everton-rosario** [comment]
@miguelfspinto Is it possible for you to add a hook pre-processor so it stripes out this [pt:] tags?

**Comment by miguelfspinto** [comment]
I already did it. Thank you.
BR,
Miguel Pinto

**Comment by everton-rosario** [comment]
@miguelfspinto Is the issue fixed?

Im closing this for now. Feel free to reopen or file a new issue.
