### ISSUE TITLE
HTML Embeds Require Valid Width & Height

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#304]
For embeds im getting this error:

```
<figure class="op-social"><iframe src="https://www.youtube.com/embed/rJ657zjzE8w?feature=oembed&amp;cc_lang_pref=es&amp;hl=es&amp;showinfo=0&amp;rel=0&amp;autohide=1&amp;modestbranding=1&amp;iv_load_policy=3"></iframe></figure><p>Here is the text</i>.</p>
HTML Embeds Require Valid Width: For embeds with no inner HTML within iframe tags, we recommend specifying both width and height on the iframe element. Learn more in Interactive under Format Reference in the Instant Article documentation.
HTML Embeds Require Valid Height: For embeds with no inner HTML within iframe tags, we recommend specifying both width and height on the iframe element. Learn more in Interactive under Format Reference in the Instant Article documentation.
```

**Comment by stuartshields** [comment]
@gabu69 Can you confirm the YouTube videos on a normal post contain the width and height?

**Comment by gabu69** [comment]
Yup:

`<div class="embed"><iframe width="500" height="281" src="https://www.youtube.com/embed/rJ657zjzE8w?feature=oembed&#038;cc_lang_pref=es&#038;hl=es&#038;showinfo=0&#038;rel=0&#038;autohide=1&#038;modestbranding=1&#038;iv_load_policy=3" frameborder="0" allowfullscreen></iframe></div>`

**Comment by stuartshields** [comment]
@gabu69 Try the following rule:

```json
{
    "rules":
	[{
        "class": "SocialEmbedRule",
        "selector" : "iframe",
        "properties" : {
            "socialembed.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "socialembed.iframe" : {
                "type" : "children",
                "selector" : "iframe"
            },
            "socialembed.caption" : {
                "type" : "element",
                "selector" : "figcaption"
            },
            "socialembed.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "socialembed.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }]
}

**Comment by samichamoun** [comment]
The suggested fix does not work. Upon adding this, it now looks as though the plugin is wrapping two iframes around it.

Here's the output in IA when using the rules above:

`<figure class="op-social"><iframe width="620" height="465"><iframe width="620" height="465" src="https://www.youtube.com/embed/T8VLOtKyYj4?feature=oembed" frameborder="0" allowfullscreen=""/></iframe></figure>`

The error message is:
Multiple iframe tags found: Only one iframe tag can be used. Please remove additional iframe tags.
Webview with op-social class without any supported embed type: When using op-social class on a webview, it must have a supported embed inside it e.g. Instagram, Twitter, Facebook, Youtube, etc. We didn't find any here.

Unsure why we would need custom rules for this given it affects all video players?

**Comment by Ycfx** [comment]
@samichamoun I have the same error, did you find a solution ?
