### ISSUE TITLE
Full Custom Templates

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#31]
How would I set up in my functions.php file to use my own template.php file within my theme rather than the template.php file the plugin uses?

**Comment by bjornjohansen** [comment]
Use the filter [instant_articles_render_post_template](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/class-instant-articles-post.php#L624).

**Comment by kkranzo** [comment]
Okay, I gathered that. However, there is no documentation or example for how that would be done. Can you please provide an example and then place it in the readme, etc. like how the wp-amp plugin has a ton of examples? Thanks.
