### ISSUE TITLE
Pages Not Showing During Page Selection

### ISSUE THREAD

**Issue by sweetsickshit** [Automattic/facebook-instant-articles-wp#312]
Hello just have a quick question. 

The Wordpress Plugin was integrated correctly (I guess) for Instant Articles with Facebook, and I could see two Pages populating for me to select which one to publish my Instant Articles. I have over 10 Pages, and I am admin on all these Pages, but for the two showing, I am actually the Page Owner. So Pages where I admin on (but not the Page Owner) are not showing despite having the Instant Article feature enabled already on Facebook. Any idea why this is so?

**Comment by stuartshields** [comment]
@sweetsickshit Did you go in and click Update on the posts that aren't showing up?

**Comment by vajrasar** [comment]
I can confirm the same issue. https://github.com/Automattic/facebook-instant-articles-wp/issues/315

It is not showing pages where we are Admins. Only the pages where we are Owners are listed.

**Comment by sweetsickshit** [comment]
Hey @stuartshields , it's not so much of the post, but the Page where I want to publish the articles to aren't showing up for me to select when using the plugin. Do I have to be the Page owner as well before I can use the plugin for Instant Articles to that particular Page?

**Comment by everton-rosario** [comment]
This will be fixed on the new release that is being out next week: https://github.com/Automattic/facebook-instant-articles-wp/tree/new_flow
