### ISSUE TITLE
SocialEmbedRule not working with youtube video loaded by iframe api

### ISSUE THREAD

**Issue by jamestylerpatton** [Automattic/facebook-instant-articles-wp#314]
I'm trying to use a custom transformer rule to insert my youtube videos into my instant articles. I'm using the Youtube iframe API, so I'm not sure if that's why it's not working.

Here is the HTML that's added and shown in the source:
```html
<div class="video-embed">
    <div id="player_AzYNcH8eLAM" data-videoid="AzYNcH8eLAM" data-vidurl="https://www.youtube.com/embed/AzYNcH8eLAM" class="video-iframe"></div>
</div>
```

After the Youtube javascript code runs, this is what's shown in the browser:
```html
<div class="video-embed">
    <iframe id="player_AzYNcH8eLAM" data-videoid="AzYNcH8eLAM" data-vidurl="https://www.youtube.com/embed/AzYNcH8eLAM" class="video-iframe" frameborder="0" allowfullscreen="1" title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/AzYNcH8eLAM"></iframe>
</div>
```

Here is the custom transformer rule code I've added:
```
{
    "rules":
    [{
        "class": "SocialEmbedRule",
        "selector" : "div.video-iframe",
        "properties" : {
            "socialembed.url" : {
                "type" : "string",
                "selector" : "div.video-iframe",
                "attribute": "data-vidurl"
            }
        }
    }]
}
```

I've tried switching the selectors with the iframe instead of the div, and I've tried using `div.video-embed` as the parent selector, but nothing works.

Also, would it make a difference that the video is hard-coded or inserted with a custom field instead of being added through the Wordpress content editor?

---

** Version Info **

* Plugin version: 2.11
* WordPress version: 4.5.1
* PHP version: 5.4.16

**Comment by stuartshields** [comment]
Hi,
Did you try the following:

```
{
    "rules":
    [{
        "class": "SocialEmbedRule",
        "selector" : "//div[@class='video-embed' and iframe]",
        "properties" : {
            "socialembed.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "data-vidurl"
            }
        }
    }]
}
```

**Comment by jamestylerpatton** [comment]
@stuartshields Yeah I tried that and it didn't work.
Would Instant Articles see it as an iframe if the video isn't loaded until the youtube iframe api script runs? 

If it helps, I'm using this method of loading the video https://developers.google.com/youtube/iframe_api_reference#Getting_Started.

**Comment by fahmi182** [comment]
@jamestylerpatton you can try this https://gist.github.com/fahmi182/a66b4117fa24dc588006d2b0dcae7774

**Comment by jamestylerpatton** [comment]
I just found out that it isn't that the custom transformer rule that isn't working, but that the youtube code is being added through a custom field. 

I had to add an extra action to the plugin code to get it to work.

In class-instant-articles-post.php, I added this to line 674:
`
do_action( 'instant_articles_before_article_content', $this );
`

and added this to my functions.php file:
```php
use Facebook\InstantArticles\Elements\SocialEmbed;
function incl_video($ia_post) {
	$instant_article = $ia_post->instant_article;
	$post_id = $ia_post->get_the_id();
	$iframe_string = get_post_meta( $post_id, 'video_embed_code', true );
	if($iframe_string){
		preg_match('/src="([^"]+)"/', $iframe_string, $match);
		$video_url = $match[1];
		$instant_article->addChild( SocialEmbed::create()->withSource($video_url)->withWidth(640)->withHeight(390) );
	}
}
add_action( 'instant_articles_before_article_content', 'incl_video' );
```

I would have used the `instant_articles_after_transform_post` action but I needed the video to display before the content.

**Comment by everton-rosario** [comment]
@jamestylerpatton Looks like the transformer is good.
Just be sure you change your SocialEmbedRule to InteractiveRule, since the Social is being deprecated.

Feel free to reopen this issue, or to open another one.
