### ISSUE TITLE
Not listing Pages where we are Admins

### ISSUE THREAD

**Issue by vajrasar** [Automattic/facebook-instant-articles-wp#315]
I had a same conversation over facebook chat and they also acknowledge the issue in this.

We did everything by the steps but the problem is that the plugin do not list facebook pages where we are Admins. It only allows us to choose pages where we are Page Owners. 

Attaching the screenshot of the same. In the screenshot you can see that we are getting only two pages for selection, whereas we are Admins of over 10 pages on facebook.

Screenshot: http://goo.gl/4VR4ha

**Comment by everton-rosario** [comment]
This will be fixed on the next release: https://github.com/Automattic/facebook-instant-articles-wp/tree/new_flow

Sorry for the long wait.
