### ISSUE TITLE
RTL has to be added manually for each and every post

### ISSUE THREAD

**Issue by nitays** [Automattic/facebook-instant-articles-wp#317]
# Steps required to reproduce the problem

When you have RTL content all over the website and you want that each and every article that you create will be RTL supported.
# Expected Result
- Having a button that enables auto RTL for all existent articles and for future articles
# Actual Result
- Having to apply the RTL markup for each and every post

---

*\* Version Info **
- Plugin version: 2.11
- WordPress version: 4.5.2 
- PHP version: n\a

**Comment by ahmedabdailla** [comment]
Fix On Line [676]
Replace 
`		$result = $document->loadHTML( '<!doctype html><html><body>' . $content . '</body></html>' );
`
with
`$result = $document->loadHTML( '<!doctype html><html dir="rtl"><body>' . $content . '</body></html>' );`

**Comment by nitays** [comment]
@ahmedabdailla will it apply the RTL markup for my existing posts too or only for the new ones?

**Comment by ahmedabdailla** [comment]
only for the new ones but you can just click update on every post you wrote before and it will fix to this post you just updated

**Comment by nitays** [comment]
@ahmedabdailla It doesn't work... is `class-instant-articles-post.php` the right file?

**Comment by nitays** [comment]
?

**Comment by ahmedabdailla** [comment]
yeah it supposed to work

**Comment by demoive** [comment]
Support for RTL is being added to the SDK in https://github.com/facebook/facebook-instant-articles-sdk-php/pull/176
