### ISSUE TITLE
problem with the output from the photo gallery

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#319]
I have a problem. I use the plug-in Gallery Carousel Without JetPack for the Gallery on the website. For proper display of thumbnails in the record I have set up a special display of photo size. 205x205 px

`add_filter( 'shortcode_atts_gallery', 'meks_gallery_atts', 10, 3 );
function meks_gallery_atts( $output, $pairs, $atts ) {
$output['size'] = 'gallery'; 
return $output;
} `
But now in my facebook photos transferred 205x205. how to do so, that would appear in the news and in the miniatures 205/205 facebook selected for full-size photos?
see screen: http://screenshot.net/07l3iz0

** Version Info **

* Plugin version: 2.11
* WordPress version: 4.5.2
* PHP version: 7.0.7

**Comment by chaselivingston** [comment]
Duplicate #133
