### ISSUE TITLE
wp.com: feed throws 404 when site is in "Discourage search engines from indexing this site" mode

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/facebook-instant-articles-wp#32]
The issue surfaces when site visibility is set to "Discourage search engines from indexing this site" on wp.com

It only happens for FB's crawler UA:
facebookexternalhit/1.1
facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)

I traced it back to core's wp-includes/functions.php do_feed():
```
if ( ! has_action( "do_feed_{$feed}" ) ) {
  wp_die( __( 'ERROR: This is not a valid feed template.' ), '', array( 'response' => 404 ) );
}
```

I also tried various workarounds - explicitly set robots.txt to allow /feed/instant-articles/ , adding a dummy callback to action 'do_feed_instant-articles' but to no avail.

I can't reproduce neither locally in vip quickstart nor on our standalone servers using the same theme/plugins 

Attn: @philipjohn

**Comment by philipjohn** [comment]
This is fixed in v2.11 :)
