### ISSUE TITLE
Readme.txt should be renamed to readme.md

### ISSUE THREAD

**Issue by cjmlgrto** [Automattic/facebook-instant-articles-wp#33]
Readme file is currently a ``.txt`` file. It should be renamed such that the extension is ``.md`` to better utilise GitHub's markdown formatting.

**Comment by Poliuk** [comment]
WordPress.org Plugin repository needs a readme.txt. I guess both files are needed.

**Comment by philipjohn** [comment]
Yep, WordPress.org needs readme.txt. As Github shows the readme.txt there's little benefit in duplicating the file to readme.md. It might be worth doing when it can be automated instead.
