### ISSUE TITLE
how to add  built-in Facebook Likes

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#332]
tell me how to enable the built-on Facebook Likes under each photo?

I tried to register it in the plugin settings - does not work.

`{ "rules": [{ "class": "ImageRule", "selector": "img", "properties": { "image.url": { "type": "string", "selector": "img", "attribute": "src" }, "image.caption": { "type": "element", "selector": "img[@alt]" }, "image.like" : { "type" : "exists", "selector" : "img" }, "image.comments" : { "type" : "exists", "selector" : "img" } } }] }`

**Comment by sebids** [comment]
I'm using this in my own plugin or functions.php:

```
add_filter('instant_articles_transformed_element', function (InstantArticle $article) {
	foreach ($article->getChildren() as $child) {
		if ($child instanceof Image) {
			$child->enableLike()->enableComments();
		}
	}

	return $article;
});
```

**Comment by lubimow** [comment]
@sebids does not work. that's what I had
all plugin stopped working: http://screenshot.net/2o3q7fg

**Comment by everton-rosario** [comment]
@lubimow Do you have any Log from your WordPress log file?

The @sebids solution works well. We will add a configuration setup within the Rules.json, in a new feature soon. Until there, @sebids solution can be a work around.

**Comment by lubimow** [comment]
@everton-rosario  a log to provide? what exactly?

**Comment by everton-rosario** [comment]
The logs that your web server holds. 
Check which web server you are using (apache for example) and grab/check any log that are there, if this error still persists.
