### ISSUE TITLE
conflict gallery "carousel" with the plugin

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#333]
I have a problem. I use the plug-in Gallery Carousel Without JetPack for the Gallery on the website. For proper display of thumbnails in the record I have set up a special display of photo size. 205x205 px 

add_filter( 'shortcode_atts_gallery', 'meks_gallery_atts', 10, 3 ); 

function meks_gallery_atts( $output, $pairs, $atts ) { 

$output['size'] = 'gallery'; 

return $output; 

} 

But now in my facebook photos transferred 205x205. how to do so, that would appear in the news and in the miniatures 205/205 facebook selected for full-size photos? 

I'm using the latest version of WordPress and plugins

**Comment by chaselivingston** [comment]
Duplicate #133

**Comment by everton-rosario** [comment]
A possible exit to your problem, is to add some attribute in the `<img>` tag that will tell the Transformer where the full qualified images are.

This will need you to change the structure of the gallery in WP

Something like:
```
<img src="https://i2.wp.com/image.inforesist.org/uploads/ 2016/07/13690871_1780827238798654_7370197519545611216_n.jpg? resize=205%2C205&#038;ssl=1" original_url="https://i2.wp.com/image.inforesist.org/uploads/ 2016/07/13690871_1780827238798654_7370197519545611216_n.jpg"/>
```

Then, on your rules, you can grab the "original_url" attribute, instead of "src" by overriding the configuration of the rule:
```
{
        "class": "SlideshowImageRule",
        "selector" : "figure.gallery-item",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "original_url"
            }
        }
    }
```


Let me know if this works for you.

**Comment by lubimow** [comment]
@everton-rosario Tell me, where do I insert this code?
`{
        "class": "SlideshowImageRule",
        "selector" : "figure.gallery-item",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "original_url"
            }
        }
    }`

**Comment by everton-rosario** [comment]
@lubimow 

Follow this sequence to add this rule configuration: 
1. Click on the InstantArticles menu Item (usually it stays in the left menu bar)
2. It will open the InstantArticles plugin settings page.
3. Scroll down to find the section called: "Publishing Settings"
4. Enable the checkbox "Enable custom transformer rules"
5. Enter the rules as below:
```
{ "rules": [
    {
        "class": "SlideshowImageRule",
        "selector" : "figure.gallery-item",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "original_url"
            }
        }
    }
]}
```

**Comment by lubimow** [comment]
Did you say: https://www.dropbox.com/s/2kfp2qysz5f9hs6/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-07-16%2010.34.06.png?dl=0

There are mistakes. Links to photos missing:
https://www.dropbox.com/s/xog4wohvccenlfk/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-07-16%2010.33.38.png?dl=0

**Comment by everton-rosario** [comment]
@lubimow have you changed your HTML markup to have the field original_url?
To make this rule work, your HTML will need to have all images like this one:

`<img src="https://i2.wp.com/image.inforesist.org/uploads/ 2016/07/13690871_1780827238798654_7370197519545611216_n.jpg? resize=205%2C205&#038;ssl=1" original_url="https://i2.wp.com/image.inforesist.org/uploads/ 2016/07/13690871_1780827238798654_7370197519545611216_n.jpg"/>`

**Comment by lubimow** [comment]
@everton-rosario I did as you said. this does not work

**Comment by everton-rosario** [comment]
Can you share the html the transformer is receiving?
There must be something wrong.

**Comment by everton-rosario** [comment]
@lubimow I cant see the image URL in another field. 
The only one on this markup is the `<img src="img_url_resized_to_205px"/>`

As I've mentioned before you will need to add a new field having the bigger resolution image, to be used within InstantArticles.


If you dont add a new field like this: 
`<img src="img_url_resized_to_205px" original_url="img_url_original" />`
The rule won't work.

For the markup you've sent me, this is the only rule that would work:

```
{ "rules": [
    {
        "class": "SlideshowImageRule",
        "selector" : "figure.gallery-item",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            }
        }
    }
]}
```

**Comment by lubimow** [comment]
I do not know what to do. I write the code that you sent to me, but I still Vigee link to the following: 
    <img src="https://i0.wp.com/****/5976655_16b2846.jpg?resize=205%2C205&amp;ssl=1"/>

This code can be said that the register to allow for instant articles are not displayed small photos?
```
add_filter( 'shortcode_atts_gallery', 'meks_gallery_atts', 10, 3 );

function meks_gallery_atts( $output, $pairs, $atts ) {

$output['size'] = 'gallery';

return $output;

}
```

**Comment by everton-rosario** [comment]
One other thing you can do is to remove anything after the question mark on your image:

From:
`<img src="https://i0.wp.com/****/5976655_16b2846.jpg?resize=205%2C205&amp;ssl=1"/>`
to:
`<img src="https://i0.wp.com/****/5976655_16b2846.jpg"/>` 
before sending to InstantArticles.

To do that, simply use this Rule: 
[https://gist.github.com/everton-rosario/d436e83a02d181a661653b99e997732b](https://gist.github.com/everton-rosario/d436e83a02d181a661653b99e997732b)

Don't forget to add the rule set configuration using "CustomSlideshowImageRule": 
```
{ "rules": [
    {
        "class": "CustomSlideshowImageRule",
        "selector" : "figure.gallery-item",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            }
        }
    }
]}
```

**Comment by lubimow** [comment]
sorry for the stupid question. where to download a file CustomSlideshowImageRule.php?

**Comment by everton-rosario** [comment]
You save it under src/Facebook/InstantArticles/Transformer/Rules

**Comment by lubimow** [comment]
This it is a plugin for wordpress? 
or just on the site to create a new folder?

**Comment by lubimow** [comment]
i save file  CustomSlideshowImageRule.php to
wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Rules

nothing works (((

https://www.dropbox.com/s/cnu66b21kzfpvrd/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-07-18%2019.40.33.png?dl=0

**Comment by everton-rosario** [comment]
What is the output?

**Comment by lubimow** [comment]
https://www.dropbox.com/s/18245igmntd6x22/output.xml?dl=0

**Comment by everton-rosario** [comment]
This format I cant read.

I need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Also show me the warning messages shown after the transformation process.

**Comment by lubimow** [comment]
https://www.dropbox.com/s/czshgeg746kb6hu/output.txt?dl=0
