### ISSUE TITLE
Is there a way we can make an image a link?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#334]
Just tried doing the following

`<a href="http://google.com"><img src="someimage.jpg" /></a>`

Noticed that the plugin strips the <a> tag out which led me to ask, is there a way to actually do this?

**Comment by everton-rosario** [comment]
Instant Articles does not support link in images, since a tap in an image leads to a detailed view of that image (like big screen with panning using gyroscope).

We recommend that content linked use the standard <a href...> tags within your article text.

Thanks for using Instant Articles.

**Comment by samichamoun** [comment]
Interesting...

The below screenshot is taken from the "Daily Mail" instant articles. Curious to know what you think is happening here. I had originally thought their "app ad" was hardcoded, as you can clearly see that + a sponsored ad on screen close together.

This app ad seems to always be before the start of their article.

How would they be doing this?

![image1 5](https://cloud.githubusercontent.com/assets/9649880/16548079/1b6781a2-41c6-11e6-8971-2c5701edbee8.PNG)

**Comment by everton-rosario** [comment]
This kind of AD are placed automatically.

You can setup yours just like the documentation better explains here: https://developers.facebook.com/docs/instant-articles/ads


Some example you can add to your markup:
```
<head>
...
<meta property="fb:use_automatic_ad_placement" content="true">
</head>
<body>
  <article>
     <header>
         <figure><img src="your_header_img_url"></figure>
         <h1>Your Header Title</h1>
            <address>
                The author
            </address>

<section class="op-ad-template">
    <figure class="op-ad">
       <iframe style="border:0;margin:0;padding:0;" height="250" width="300">
          <script type="text/javascript">
              // your ad script
          </script>
          <div>
              // your ad markup 
           </div>
       </iframe>
     </figure>
     <figure class="op-ad">
         <iframe style="border:0;margin:0;padding:0;" height="250" width="300">
            <script type="text/javascript">
               ....
            </script>
            <div> ...  </div>
        </iframe>
     </figure>
    <figure class="op-ad op-ad-default">
       <iframe style="border:0;margin:0;padding:0;" height="250" width="300">
          <script type="text/javascript">
           ... 
          </script>
          <div>
          </div>
       </iframe>
    </figure>
  </section>
</header>

```

**Comment by samichamoun** [comment]
Cool thanks, i will take a look at that. 

Do you think the Daily Mail screenshot above would be in violation of FB terms? I wouldn't have thought two ads could be placed that close to each other (one house ad + one IA ad).

**Comment by everton-rosario** [comment]
This is something not encouraged, indeed.

We are making this platform to be the best possible to every single person in Facebook. This way, anything that can be annoying or against the terms & conditions will have to be fixed.
