### ISSUE TITLE
Japanese post title is corrupted. $title needs to be helped by mb_convert_encoding() as with $content in Instant_Articles_Post::to_instant_article()

### ISSUE THREAD

**Issue by kawarano** [Automattic/facebook-instant-articles-wp#339]
Post content is converted by `$content = mb_convert_encoding( $content, 'HTML-ENTITIES', get_option( 'blog_charset' ) )` before DOMDocument in class-instant-articles-publisher.php, but post title is not converted. So Japanese post title is corrupted.

---

** Version Info **

* WordPress version: WordPress.com VIP

**Comment by everton-rosario** [comment]
@kawarano Thanks for using Instant Articles. Can you send us a pull request with the fix you found?
