### ISSUE TITLE
Generate WP.org plugin header image

### ISSUE THREAD

**Issue by philipjohn** [Automattic/facebook-instant-articles-wp#34]
Let's make our WP.org page look pretty.

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by bjornjohansen** [comment]
@chricarls is working on the banner and icons.

**Comment by bjornjohansen** [comment]
@chricarls had to let this one go, but was able to draft an idea for the icons first. GitHub doesn’t support SVGs, so here’s a link to Dropbox: https://www.dropbox.com/s/so8qq9mgbl2ocwn/wpia.svg?dl=0

If anyone else wants to help out, it will be appreciated.
