### ISSUE TITLE
Automatic Images with likes and comments data-feedback

### ISSUE THREAD

**Issue by rawzefr** [Automattic/facebook-instant-articles-wp#340]
# Steps required to reproduce the problem

I tried with every rule posible on the guide to enable the option for likes and comments options on images, slideshows, and videos, but it doesn't seem to work at all. The plugin should come with this option enable as a default
# Expected Result

Images with like and comment options on Instant Articles
# Actual Result

Nothing

---

*\* Version Info **
- Plugin version: 2.11
- WordPress version: 4.5.3
- PHP version: 5.4

**Comment by everton-rosario** [comment]
@rawzefr Thanks for using Instant Articles.
We have this same issue reported 2 other times.
There were some of them that could make it work as a workaround. Check it here: https://github.com/Automattic/facebook-instant-articles-wp/issues/36

**Comment by rawzefr** [comment]
what if wordpress wraps it for some reason in a div tag instead of a figure tag? I tried to apply that rule #36 with my selectors but still nothing happening.
