### ISSUE TITLE
UTF8 not working or different language not working

### ISSUE THREAD

**Issue by dhakalsuresh** [Automattic/facebook-instant-articles-wp#344]
1.Test in different language is not working, i just see text as "?????????????????"  format, which is completely not readable
- 
  ![capture](https://cloud.githubusercontent.com/assets/8805646/16529182/940c3332-3feb-11e6-8f21-ed344d64386d.PNG)

*\* Version Info **
- Plugin version: 2.11 
- WordPress version: 4.5.3
- PHP version: 5.5.35

**Comment by philipjohn** [comment]
Could you provide some more information on the steps to reproduce this please?

Are you using any translation plugins?

Are you using a specific locale for your WordPress install?

Also, please provide the exact versions - "latest" will change, so we need the exact versions this occurs in at the time of reporting.

**Comment by dhakalsuresh** [comment]
I'm just using some front-end plugins,
SoundCloud Shortcode,
WP Subtitle,
Image Upload Widget,
Responsive Menu

I tried to remove all plugins but it's looks same . here is the link how it's looks in rss feed: http://nepalsandesh.com/feed/instant-articles

Wordpress Version : Version 4.5.3

**Comment by sakatam** [comment]
Hi @dhakalsuresh, I have been trying to reproduce this but with no luck. Could you provide detailed info about the database as well? Please run the following commands on mysql cli, and put the result here? 

```sql
SHOW VARIABLES LIKE "version%";
```

```sql
SHOW CREATE TABLE wp_posts;
```

Thank you in advance for your help!

**Comment by dhakalsuresh** [comment]
if i replace `render ` function in `feed-template.php` file with `get_the_content()` , it's fetch the real data.
`<![CDATA[<?php echo $instant_article_post->to_instant_article()->render(); ?>]]>`

Hello @sakatam, Here is what i saw with your query.
1. 
`version	5.5.43-37.2-log
version_comment	Percona Server (GPL), Release rel30.2, Revision 38...
version_compile_machine	x86_64
version_compile_os	Linux`

2. `CREATE TABLE `wp_posts` (
 `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',
 `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_content` longtext NOT NULL,
 `post_title` text NOT NULL,
 `post_excerpt` text NOT NULL,
 `post_status` varchar(20) NOT NULL DEFAULT 'publish',
 `comment_status` varchar(20) NOT NULL DEFAULT 'open',
 `ping_status` varchar(20) NOT NULL DEFAULT 'open',
 `post_password` varchar(20) NOT NULL DEFAULT '',
 `post_name` varchar(200) NOT NULL DEFAULT '',
 `to_ping` text NOT NULL,
 `pinged` text NOT NULL,
 `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_content_filtered` longtext NOT NULL,
 `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
 `guid` varchar(255) NOT NULL DEFAULT '',
 `menu_order` int(11) NOT NULL DEFAULT '0',
 `post_type` varchar(20) NOT NULL DEFAULT 'post',
 `post_mime_type` varchar(100) NOT NULL DEFAULT '',
 `comment_count` bigint(20) NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`),
 KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
 KEY `post_parent` (`post_parent`),
 KEY `post_author` (`post_author`),
 KEY `post_name` (`post_name`(191))
) ENGINE=MyISAM AUTO_INCREMENT=201629 DEFAULT CHARSET=utf8`
