### ISSUE TITLE
Replace depreciated <op-social> tag with <op-interactive>

### ISSUE THREAD

**Issue by pnoeric** [Automattic/facebook-instant-articles-wp#346]
The [FB documentation page for `<op-social>`](https://developers.facebook.com/docs/instant-articles/reference/social) states that it is completely depreciated and should not be used, looks like `<op-interactive>` is the tag for all embeds.

Version 2.11 of FB IA Wordpress Plugin

**Comment by everton-rosario** [comment]
@pnoeric Thanks for your input.

This was deprecated on the SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/133

Certify you get the latest version of the SDK. Thanks.

**Comment by pnoeric** [comment]
Hi @everton-rosario -- I'm just using the Facebook/Wordpress plugin, and I have the latest version, 2.11 (as [made available here](https://wordpress.org/plugins/fb-instant-articles/))? 

So I guess this means an older (outdated) version of the SDK is baked into the current release?

**Comment by everton-rosario** [comment]
We released the WordPress plugin v3.0.1 yesterday.
Can you update and check if this still reproduces?

Reopen the issue in case it still happens to you. 

Thanks.
