### ISSUE TITLE
Turn off check for empty post content

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#35]
I have certain post types/styles that have empty post content in them because I am using custom fields. This is fine because I am using a custom template to actually output content in the feed, so it will not be an issue on Facebook's end. However, since the plugin checks to see if the content is empty and then doesn't show that post in the feed if that is the case, those posts I want to appear in the feed are not appearing.

Is there a way to turn off the below?

```
if ( $query->is_main_query() && $query->is_feed( INSTANT_ARTICLES_SLUG ) ) {
		global $wpdb;
		$where .= " AND {$wpdb->posts}.post_content NOT LIKE ''";
	}
```
What would I place in my functions.php file to turn that off?

**Comment by kkranzo** [comment]
Actually, I just went ahead and removed the filter like below and that took care of it.

`remove_filter( 'posts_where' , 'instant_articles_query_where', 10, 2 );`

**Comment by bjornjohansen** [comment]
Just make sure you don’t send in any posts with empty body to Facebook.
