### ISSUE TITLE
Prepend Social Embed Element from Custom Field

### ISSUE THREAD

**Issue by jamestylerpatton** [Automattic/facebook-instant-articles-wp#350]
I have a custom field that takes the url from a youtube video embed code and places it before the content on my site. However, since these videos are added using custom fields, they aren't added to my instant articles feed, so I added this code to my functions.php file:

```php
use Facebook\InstantArticles\Elements\SocialEmbed;

function incl_video($ia_post) {
	$instant_article = $ia_post->instant_article;
	$post_id = $ia_post->get_the_id();
	$iframe_string = get_post_meta( $post_id, 'video_embed_code', true );
	if($iframe_string){
		preg_match('/src="([^"]+)"/', $iframe_string, $match);
		$video_url = $match[1]; // returns video url
		$instant_article->addChild( SocialEmbed::create()->withSource($video_url)->withWidth(640)->withHeight(390) );
	}
}
add_action( 'instant_articles_after_transform_post', 'incl_video' );
```

This adds the video to the end of the content, and I'm wondering if there's a way to add it **before** the content without directly editing the plugin code, which is what I'm doing on one of my sites as a workaround.

---

** Version Info **

* Plugin version: 2.11
* WordPress version: 4.5.1

**Comment by jacobarriola** [comment]
@jamestylerpatton I ran into the same issue with wanting to put in a YouTube embed for video post formats. The embed came from a custom field.

What I used was the `instant_articles_content` filter, which then allowed me to prepend my YouTube video before the content.

```
add_filter('instant_articles_content', 'your_function', 10);
your_function($content) {
  $iframe_string = .........;
  $content = $iframe_string . $content;
  return $content;
};
```

Hope that helps!

**Comment by everton-rosario** [comment]
@jacobarriola Thanks for the support here.

Feel free to join our FB group:  https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by jamestylerpatton** [comment]
@jacobarriola Thanks, but that didn't actually work for me.

I used this code:
```php
add_filter('instant_articles_content', 'your_function', 10);
function your_function($content) {
  $iframe_string = 'youtube ';
  $content = $iframe_string . $content;
  return $content;
};
```
and updated one of my posts but nothing changed.

Does this work with version 3.0.1 of the plugin?

Thanks for helping!

**Comment by jacobarriola** [comment]
Hey @jamestylerpatton, 

Sorry, the `$iframe_string = 'youtube ';` was just a placeholder for you to fetch your custom field. I was assuming you already know how to grab the field.  Looking at your code, looks like your grabbing the url via the `get_post_meta()` function. Does that make sense?

**Comment by jamestylerpatton** [comment]
@jacobarriola I thought I could use the string "youtube" as a test and it would be added in but it didn't.
But adding the iframe did work!

Thanks again

**Comment by jacobarriola** [comment]
Awesome! Glad it worked out. 🎉
