### ISSUE TITLE
Keep getting "Invalid JSON provided for custom rules code"

### ISSUE THREAD

**Issue by markbattistella** [Automattic/facebook-instant-articles-wp#351]
**Steps required to reproduce the problem**

1. Added the following custom rule: `{ "rules": [ "class": "InteractiveRule", "selector" : "div.video-container", "properties" : { "interactive.iframe" : { "type" : "children", "selector" : "div.video-container" } } ] }`
2. Go to save the settings
3. Error mentioned above

---

I have the following markup:

`<div class="video-container"><div class="fluid-box"><div class="flex-box sixteen-nine"><iframe src="https://www.youtube.com/embed/########" frameborder="0"></iframe></div></div></div>`

Adding the above custom code causes the error, and can't figure out how to rectify.

**Comment by diegoquinteiro** [comment]
Hi!

Your JSON is actually invalid. This is what you needed:

```javascript
{ "rules": [ 
        { 
            "class": "InteractiveRule", 
            "selector" : "div.video-container", 
             "properties" : { 
                   "interactive.iframe" : 
                         { "type" : "children", "selector" : "div.video-container" } 
             } 
        } 
    ] 
}
```

You forgot to enclose the rule in `{...}` =)
