### ISSUE TITLE
Error : The <figure> element has an unsupported class value in the class=op- tag

### ISSUE THREAD

**Issue by adssen** [Automattic/facebook-instant-articles-wp#352]
Hi folks,

Why do I keep getting the following error message when clicking update button?

 It wasn't possible to submit your article

The server responded with the following messages:

Unsupported Class: The <figure> element has an unsupported class value in the class=op- tag. For more information on the class values supported in <figure> element you're using, refer to the Format Reference of the Instant Articles documentation.
Empty Articles: You have one or more articles without any content.

Thanks in advance
---

** Version Info **

* Plugin version: 2.11
* WordPress version: 4.5.3
* PHP version: 5.5

**Comment by everton-rosario** [comment]
Hey @adssen, do you have more info?
You can toggle the meta-box, and click on the "Toggle debug information" and post here the Source Markup and Transformed markup.

Reopen the issue when you have these infos, please.
