### ISSUE TITLE
Only One Production Article, Publishing Keep Overwriting The Existing One

### ISSUE THREAD

**Issue by eversionsystems** [Automattic/facebook-instant-articles-wp#357]
# Steps required to reproduce the problem

1. Publish a post in WordPress
2. Post appears in Facebook Production Articles
3. Publishing another post overwrites the existing Production Article in the list

# Expected Result
* A new production article should be generated.

# Actual Result
* Existing Production Article keep getting overwritten with the new one so that I only ever have one production article.

---

** Version Info **

* Plugin version: 3.0
* WordPress version: 4.5.3
* PHP version: 5.6.21

<img width="764" alt="2016-07-13_17-52-56" src="https://cloud.githubusercontent.com/assets/20215473/16796594/b3ce712c-4922-11e6-9d4f-3560645a7ddd.png">

**Comment by everton-rosario** [comment]
@eversionsystems Do you have more info?

Double check if the post you are saving have a different canonical URL. This is the key index for any Instant Article. 

If this wasn't your problem, please, reopen this, with the more detailed info.

**Comment by eversionsystems** [comment]
The canonical URL is distinct and matches the post's URL from my WordPress blog.  What additional information do you need?

**Comment by eversionsystems** [comment]
I can't reopen this issue....

**Comment by everton-rosario** [comment]
@eversionsystems  Can you share here the 2 canonical URL's that seem to have the same content?

**Comment by eversionsystems** [comment]
The issue is not with the urls, the issue is that I can only ever have one instant article at a time.  Publishing new articles just deletes the old one.  The canonical URL's are always unique.

**Comment by everton-rosario** [comment]
@eversionsystems With the URLs I can check into the system what is going on on your Instant Articles registration.
Also with the Instant Articles markup I can reproduce the error. 

We dont have any kind of feature to have only 1 at a time. Never faced this overwriting Instant Articles bug. This is why I need more info.

**Comment by eversionsystems** [comment]
<link rel="canonical" href="https://beatthegrind.com/travel-blog/chachani-mountain-peru/"/>
<link rel="canonical" href="https://beatthegrind.com/travel-blog/santa-cruz-trek-peru/"/>

Two URL's that were produced when I updated articles on my blog.

**Comment by everton-rosario** [comment]
@eversionsystems You have few problems with the configurations of your OpenGraph objects.

You'll have to:
(1) Fix your Open Graph tags (make sure each article has a single og:url pointing to the right page)
You will find this in the ojbect debugger: 
`https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fbeatthegrind.com%2Ftravel-blog%2Fchachani-mountain-peru%2F`
`https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fbeatthegrind.com%2Ftravel-blog%2Fsanta-cruz-trek-peru%2F`

(2) Scrape the URLs in the Open Graph debugger and confirm each one has the correct unique URL (urls for the debugger are above)

(3) Submit the articles again


Let me know if this works for you.

**Comment by eversionsystems** [comment]
Ah you are a legend I have some custom code that was hard coded in my functions.php!!  Thanks very much for your help!
