### ISSUE TITLE
HTML Embeds Require Valid Width / Height - Still outstanding

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#363]
@everton-rosario - fresh ticket as you requested.

The warning I receive is as follows:

> HTML Embeds Require Valid Width: For embeds with no inner HTML within iframe tags, we recommend specifying both width and height on the iframe element. Learn more in Embeds under Format Reference in the Instant Articles documentation.

Source markup as follows:

`<div class="embed"><iframe width="620" height="349" src="https://www.youtube.com/embed/s1tN0ggNreA?feature=oembed" frameborder="0" allowfullscreen></iframe></div>`

Transformed markup as follows:

`      <figure class="op-interactive">
        <iframe src="https://www.youtube.com/embed/s1tN0ggNreA?feature=oembed" class="no-margin" height="349"></iframe>
      </figure>`

As you can see, the width is not carrying over.

**Comment by everton-rosario** [comment]
Hi @samichamoun, sorry about this. It was my fault to not include the new features/configuration to grab the width and height attributes from your original html markup.

To accomplish that, please, update your **rules-configuration.json** with this one:
https://raw.githubusercontent.com/Automattic/facebook-instant-articles-wp/master/rules-configuration.json

It includes in all **InteractiveRule** the height and width selector.

```
    interactive.height: {
        type: "int",
        selector: "iframe",
        attribute: "height"
    },
    interactive.width: {
        type: "int",
        selector: "iframe",
        attribute: "width"
    },
```

Let me know if this works for you.

Thanks for using Instant articles.

Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by samichamoun** [comment]
Hi @everton-rosario unfortunately I still dont think that resolves the issue. I've actually been going back and forth with people in a number of threads about this and never seem to get a final answer on it. I have my own custom transformer set up as follows:

`{ "rules":
	[{
		"class": "InteractiveRule",
		"selector": "//div[@class='interactive' and iframe]",
		"properties": { 
			"interactive.height": { 
				"type": "int", 
				"selector": "iframe", 
				"attribute": "height" 
			},
			"interactive.width": { 
				"type": "int", 
				"selector": "iframe", 
				"attribute": "width" 
			},
			"interactive.url": {
				"type": "string",
				"selector": "iframe",
				"attribute": "src"
			}
		}
	},
	{
		"class": "InteractiveRule",
		"selector": "//div[@class='embed' and iframe]",
		"properties": { 
			"interactive.height": { 
				"type": "int", 
				"selector": "iframe", 
				"attribute": "height" 
			},
			"interactive.width": { 
				"type": "int", 
				"selector": "iframe", 
				"attribute": "width" 
			},
			"interactive.url": {
				"type": "string",
				"selector": "iframe",
				"attribute": "src"
			}
		}
	}
]}`

You can see I'm using interactive.width and it doesn't do anything.

https://github.com/Automattic/facebook-instant-articles-wp/issues/196 <-- here you can see it was suggested that "width" doesnt work, and instead I should be using "column-width". I couldnt get this working either and never got a response in that thread.

Any ideas mate?

**Comment by everton-rosario** [comment]
Your source markup:

```
        <div class="embed">
            <iframe width="620" height="349" src="https://www.youtube.com/embed/s1tN0ggNreA?feature=oembed" frameborder="0" allowfullscreen></iframe>
        </div>
```

The appropriated rule to trasform should be like:

```
    {
        "class": "InteractiveRule",
        "selector" : "//div[@class='embed' and iframe]",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            }
        }
    }
```


The transformed into Instant Article makrup is(note the existent **width** and **height** properties):
```
      <figure class="op-interactive">
        <iframe>
            <iframe width="620" height="349" src="https://www.youtube.com/embed/s1tN0ggNreA?feature=oembed" frameborder="0" allowfullscreen=""/>
        </iframe>
      </figure>
```


The test executing as expected lies into this PR of the SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/145

**Comment by samichamoun** [comment]
Just saw there is a fresh update (I was using 2.11) and it seems like my videos are now updating correctly! Thank you!
