### ISSUE TITLE
Update to Like, Comment, and Share Functionality

### ISSUE THREAD

**Issue by thangdvx** [Automattic/facebook-instant-articles-wp#364]
"When people read articles on Facebook, they often want to react to, comment on, and share what they've read with their friends. To enable this behavior within Instant Articles, we are introducing support for Like, Comment, and Share buttons both at the bottom of an Instant Article and on media that appears within your articles (photos videos, slideshows, and GIFs).

Beginning July 14 on iOS and July 21 on Android, these feedback buttons will be automatically added to your articles and to media assets embedded within your articles. If you wish to remove these buttons from either surface, admins can easily do so in the Feedback Settings section starting today. Read below for more details."

https://developers.facebook.com/ia/blog/post/2016/06/28/update-to-like-comment-share/

**Comment by everton-rosario** [comment]
@thangdvx Do you need any support on this?

This is accessible thru your facebook page.
