### ISSUE TITLE
htmlParseEntityRef: no name in Entity

### ISSUE THREAD

**Issue by Cistoran** [Automattic/facebook-instant-articles-wp#365]
Hey all,

This plugin started randomly throwing 3 warning messages whenever I re-publish something that's already been published before. Below is are the three warning messages.

```
Warning: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1 in /home/edmidentity/edmidentity.com/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 624
Warning: Cannot modify header information - headers already sent by (output started at /home/edmidentity/edmidentity.com/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php:624) in /home/edmidentity/edmidentity.com/wp-admin/post.php on line 197
Warning: Cannot modify header information - headers already sent by (output started at /home/edmidentity/edmidentity.com/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php:624) in /home/edmidentity/edmidentity.com/wp-includes/pluggable.php on line 1167
```

[Here's a screenshot of the page being displayed.](http://imgur.com/5EXnEhu)

Here is the 624 line of code it seems to have issues with.

`$document->loadHTML( '<?xml encoding="' . $blog_charset . '" ?><h1>' . $title . '</h1>' );`

I looked through a few things but couldn't determine why it's having issues with this in particular. I'm updated to the latest WordPress(4.5.3) and the latest version of Instant Articles for WP (3.0.1) but the issue still occurs. If I disable the plugin the Warnings disappear (obviously).

Any help would be greatly appreciated.

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version: 4.5.3
* PHP version:

**Comment by everton-rosario** [comment]
@Cistoran Try to enclose this loadHTML call like this:

```
        libxml_use_internal_errors(true);
        $document = new \DOMDocument();
        $document->loadHTML($html_file);
        libxml_use_internal_errors(false);
```

Let me know if it works for you.
