### ISSUE TITLE
Varnish and /feed/instant-articles

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#37]
I have varnish 4 and cache pages for 30 minutes, saw facebook scrappes the /feed/instant-articles every 3 minutes

Should we not cache /feed/instant-articles then?

**Comment by bjornjohansen** [comment]
You should either skip caching your instant articles feed URL (default: /feed/instant-articles), set the TTL to 3 minutes for the feed URL, or purge the cache (ban the cached item) when your content is updated.
