### ISSUE TITLE
Depreciated tag error

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#370]
> op-social tag is deprecated. Use op-interactive instead: op-social is now deprecated. Please use <figure class="op-interactive"> for all web and social embeds. Learn more in Embeds under Format Reference in the Instant Articles documentation.

Will there be a patch for this soon?

**Comment by everton-rosario** [comment]
@samichamoun Yes. This is already on master of the SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/133

You can already use this one, by cloning the repo. Otherwise you will have it on next version planned to August 8th.

**Comment by samichamoun** [comment]
FYI - update available now (3.01) appears to have resolved this also?

**Comment by everton-rosario** [comment]
Always use the latest version.
