### ISSUE TITLE
qTranslate X with Facebook Instant Article

### ISSUE THREAD

**Issue by tennyy** [Automattic/facebook-instant-articles-wp#372]
Hi,

We are using qTranslate X for a multi-language wordpress site.

When I post the article and to using "Instant Articles for WP" auto publish to Facebook and I found the all language tags appear in the title.

![screenshot_20160720-144630](https://cloud.githubusercontent.com/assets/20552547/16977774/ae13f6f4-4e8a-11e6-9744-c64c5f03cd3e.jpg)

But the content only show single language seems normally.

How can I fix the title with only single language?

Thanks!

**Comment by everton-rosario** [comment]
Hello @tennyy, thanks for using Instant Articles.
We still dont have support to qTranslate X plugin.
One workaround I've seen some people doing is to add a filter hook. Check this thread: https://github.com/Automattic/facebook-instant-articles-wp/issues/303

We will have this supported in the next 2 months.
