### ISSUE TITLE
Have TestUnit running, on CI and well documented

### ISSUE THREAD

**Issue by everton-rosario** [Automattic/facebook-instant-articles-wp#373]
# Test environment

We need to have a working  workflow for tests: 
1. All developers should have testing environment running easily (Kind of self building script is a good one). 
2. To be running on Travis CI for every new PullRequest on the repo.
3. Add a step-by-step documentation on how to setup the testing environment.

**Comment by philipjohn** [comment]
I've set up Travis and made the necessary tweaks to `.travis.yml`.

It looks like the existing tests our outdated, so we should think about what we need to change/add.

**Comment by everton-rosario** [comment]
@philipjohn Thanks.
Yep, probably we will need to refactor and restructure the existing tests and to create new ones.

**Comment by sakatam** [comment]
@philipjohn & @everton-rosario I made a quick change just to make the CI green by removing some fatal parts. Please give it a glance and accept if it looks ok.

**Comment by everton-rosario** [comment]
@sakatam loved this!
LGTM
