### ISSUE TITLE
Gallery Problem

### ISSUE THREAD

**Issue by kodbilenadam** [Automattic/facebook-instant-articles-wp#377]
# Steps required to reproduce the problem

1. Add new post and add gallery.

# Expected Result

* Galleries shown in instant articles

# Actual Result

* No gallery shown in instant articles

---

Example:
http://www.doctorwho.web.tr/yeni-doctor-who-boyama-kitabi.html

http://www.doctorwho.web.tr/yeni-doctor-who-boyama-kitabi.html/instant-articles

** Version Info **

* Plugin version:   3.0.1 
* WordPress version:  4.5.3
* PHP version:  5.5.18

**Comment by everton-rosario** [comment]
@kodbilenadam  
Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

I'll reopen with that info.

**Comment by kodbilenadam** [comment]
Source Markup:
`<p>Yetişkin boyama kitaplarının, beyin için en iyi ve rahatlatıcı aktivite olduğu bilimsel olarak kanıtlanmıştır. Buna rağmen fişler, vergiler, dosyalar veya diğer yetişkin işi şeyler resimli değil. Biz de neden sevdiğimiz TV programlarını renklendirmeyelim dedik. Artık BBC&#8217;nin resmi Doctor Who boyama kitabında renkli bir yolculuğa çıkma zamanı.</p>
<p>En sevdiğiniz Zaman Lordunu, çeşitli yol arkadaşlarını, TARDIS&#8217;i, düşmanları, uzay ve zaman sahnelerini içeren 96 sayfalık fazlaca detay içeren bir kitap. Öyle ki bu kitap için koca bir kutu boyama kalemlerine ihtiyacınız olabilir. Rassilon Başkanlığı için turuncu tonları, Ağlayan Melekler ve Siber Adamlar için gri ve gümüş renklerinin onlarca tonunu kullanmak zorunda kalabilirsiniz veya doğaçlama yapıp pembe bir Siber Adam da yapabilirsiniz, hayal gücünüze kalmış.</p>
<p>Doctor Who&#8217;nun yeni sezonu için önümüzde daha bir yıla yakın bir süre varken bu kitap sizin kesinlikle meşgul edecektir. Tabii eğer tarihteki en hızlı renklendirici değilseniz.</p>
<p>Doctor Who boyama kitabı 23 Şubat&#8217;ta piyasaya sürüldü. <a href="http://www.penguinrandomhouse.com/books/537409/doctor-who-coloring-book-by-illustrated-by-james-newman-gray-lee-teng-chew-and-jan-smith/9780399542299/" target="_blank">Buradan</a> bir kopyasını sipariş edebilirsiniz.</p>
<style type='text/css'>
			#gallery-1 {
				margin: auto;
			}
			#gallery-1 .gallery-item {
				float: left;
				margin-top: 10px;
				text-align: center;
				width: 33%;
			}
			#gallery-1 img {
				border: 2px solid #cfcfcf;
			}
			#gallery-1 .gallery-caption {
				margin-left: 0;
			}
			/* see gallery_shortcode() in wp-includes/media.php */
		</style>
<div id='gallery-1' class='gallery galleryid-938 gallery-columns-3 gallery-size-thumbnail'>
<dl class='gallery-item'>
<dt class='gallery-icon portrait'>
				<a href='http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg' data-rel="lightbox-gallery-1"><img src="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1218" srcset="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?resize=150%2C150 150w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?resize=298%2C300 298w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?resize=160%2C160 160w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?resize=320%2C320 320w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg?w=625 625w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1218'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon landscape'>
				<a href='http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg' data-rel="lightbox-gallery-1"><img src="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1228" srcset="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg?resize=150%2C150 150w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg?resize=160%2C160 160w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg?resize=320%2C320 320w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/tardis-by-cass.jpg?zoom=3&amp;resize=150%2C150 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1228'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon portrait'>
				<a href='http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg' data-rel="lightbox-gallery-1"><img src="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1227" srcset="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg?resize=150%2C150 150w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg?resize=160%2C160 160w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg?resize=320%2C320 320w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/first_doctor___doctor_who_coloring_book_by_syaoranlover5-d9wljyc.jpg?zoom=3&amp;resize=150%2C150 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1227'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<p><br style="clear: both" />
<dl class='gallery-item'>
<dt class='gallery-icon portrait'>
				<a href='http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg' data-rel="lightbox-gallery-1"><img src="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1226" srcset="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=150%2C150 150w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=298%2C300 298w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=768%2C774 768w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=1016%2C1024 1016w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=160%2C160 160w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?resize=320%2C320 320w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/dr-who-adult-colouring_fullwidth-3.jpg?w=1138 1138w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1226'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon landscape'>
				<a href='http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg' data-rel="lightbox-gallery-1"><img src="http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1225" srcset="http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg?resize=150%2C150 150w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg?resize=160%2C160 160w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg?resize=320%2C320 320w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-colouring-book-6.jpg?zoom=3&amp;resize=150%2C150 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1225'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon landscape'>
				<a href='http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg' data-rel="lightbox-gallery-1"><img src="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1224" srcset="http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg?resize=150%2C150 150w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg?resize=160%2C160 160w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg?resize=320%2C320 320w, http://i1.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/9238331_orig.jpg?zoom=3&amp;resize=150%2C150 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1224'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<p><br style="clear: both" />
<dl class='gallery-item'>
<dt class='gallery-icon landscape'>
				<a href='http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg' data-rel="lightbox-gallery-1"><img src="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1223" srcset="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?resize=150%2C150 150w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?resize=300%2C300 300w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?resize=160%2C160 160w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?resize=320%2C320 320w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-9369-1454014100-1.jpg?w=625 625w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1223'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon portrait'>
				<a href='http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg' data-rel="lightbox-gallery-1"><img src="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1221" srcset="http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg?resize=150%2C150 150w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg?resize=160%2C160 160w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg?resize=320%2C320 320w, http://i0.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-2112-1454014155-2.jpg?zoom=3&amp;resize=150%2C150 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1221'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<dl class='gallery-item'>
<dt class='gallery-icon landscape'>
				<a href='http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg' data-rel="lightbox-gallery-1"><img src="http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=150%2C150" class="attachment-thumbnail size-thumbnail" alt="Doctor Who Boyama Kitabı" aria-describedby="gallery-1-1220" srcset="http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=150%2C150 150w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=300%2C300 300w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=768%2C768 768w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=160%2C160 160w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?resize=320%2C320 320w, http://i2.wp.com/www.doctorwho.web.tr/wp-content/uploads/2016/07/doctor-who-coloring-book-2.jpg?w=960 960w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1" /></a>
			</dt>
<dd class='wp-caption-text gallery-caption' id='gallery-1-1220'>
				Doctor Who Boyama Kitabı
				</dd>
</dl>
<p><br style="clear: both" />
		</div>
`
Transformed Markup

`<html>
  <head>
    <link rel="canonical" href="http://www.doctorwho.web.tr/yeni-doctor-who-boyama-kitabi.html"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article><header><figure><img src="http://www.doctorwho.web.tr/wp-content/uploads/2016/07/enhanced-27473-1454014188-9.jpg"/><figcaption>Doctor Who Boyama Kitabı</figcaption></figure><h1>Yeni Doctor Who boyama kitabı</h1><time class="op-published" datetime="2016-07-25T16:00:30+03:00">July 25th, 4:00pm</time><time class="op-modified" datetime="2016-07-25T18:31:15+03:00">July 25th, 6:31pm</time><address><a href="https://www.facebook.com/nedime.bozkir" rel="facebook">Nedime Bozkır</a>2010 yılından beri Doctor Who ve DoktoRose hayranı. Çevirmen adayı. DoctorWho.web.tr yazarı.</address></header><p>Yetişkin boyama kitaplarının, beyin için en iyi ve rahatlatıcı aktivite olduğu bilimsel olarak kanıtlanmıştır. Buna rağmen fişler, vergiler, dosyalar veya diğer yetişkin işi şeyler resimli değil. Biz de neden sevdiğimiz TV programlarını renklendirmeyelim dedik. Artık BBC’nin resmi Doctor Who boyama kitabında renkli bir yolculuğa çıkma zamanı.</p><p>En sevdiğiniz Zaman Lordunu, çeşitli yol arkadaşlarını, TARDIS’i, düşmanları, uzay ve zaman sahnelerini içeren 96 sayfalık fazlaca detay içeren bir kitap. Öyle ki bu kitap için koca bir kutu boyama kalemlerine ihtiyacınız olabilir. Rassilon Başkanlığı için turuncu tonları, Ağlayan Melekler ve Siber Adamlar için gri ve gümüş renklerinin onlarca tonunu kullanmak zorunda kalabilirsiniz veya doğaçlama yapıp pembe bir Siber Adam da yapabilirsiniz, hayal gücünüze kalmış.</p><p>Doctor Who’nun yeni sezonu için önümüzde daha bir yıla yakın bir süre varken bu kitap sizin kesinlikle meşgul edecektir. Tabii eğer tarihteki en hızlı renklendirici değilseniz.</p><p>Doctor Who boyama kitabı 23 Şubat’ta piyasaya sürüldü. <a href="http://www.penguinrandomhouse.com/books/537409/doctor-who-coloring-book-by-illustrated-by-james-newman-gray-lee-teng-chew-and-jan-smith/9780399542299/">Buradan</a> bir kopyasını sipariş edebilirsiniz.</p></article>
  </body>
</html>`

**Comment by everton-rosario** [comment]
@kodbilenadam What is the gallery plugin/component you are using?

**Comment by kodbilenadam** [comment]
@everton-rosario Only Carousel provided by Jetpack.

**Comment by everton-rosario** [comment]
@kodbilenadam Check my PR: #378

**Comment by kodbilenadam** [comment]
Thank you for responding. I have already these rules:
```
{
    "rules":
    [{
        "class": "SocialEmbedRule",
        "selector" : "//p[iframe]",
        "properties" : {
            "socialembed.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "socialembed.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "socialembed.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            },
            "socialembed.iframe" : {
                "type" : "children",
                "selector" : "iframe"
            },
            "socialembed.caption" : {
                "type" : "element",
                "selector" : "figcaption"
            }
        }
	}]
}
```

I am adding the rules you did on #378 but when I click save changes button it says "Invalid JSON provided for custom rules code" error appears. :(

**Comment by everton-rosario** [comment]
Im wondering how your environment is set.
Have you copy/pasted the diff? How have you ingested the new configuration?
