### ISSUE TITLE
Galleries with no rules defined

### ISSUE THREAD

**Issue by ChequePata** [Automattic/facebook-instant-articles-wp#380]
# Steps required to reproduce the problem

1. Place a gallery inside a post
2. Publish the post

# Expected Result

* This post was transformed into an Instant Aticle with no warnings

# Actual Result

No rules defined for style in the context of InstantArticle
No rules defined for div class="td-slide-on-2-columns" in the context of InstantArticle

---

** Version Info **

* Plugin version:  3.0.1
* WordPress version: 4.5.3
* PHP version: 5.3.29

Hello everyone, I hope you're having a great day. I'm new to this, so I hope I'm not asking an inane question. I get the error message posted above in any post that has galleries in it. 
I'm using the Newspaper 6 theme.
I'm using the TagDiv Slide Gallery Slideshow, that came with the theme
This is the Toggle debug information:

Source Markup:
<code><pre>
&lt;p&gt;&nbsp;&lt;/p&gt;
&lt;style type="text/css"&gt;
&lt;p&gt;                    #td_uid_1_5796c98993369  .td-doubleSlider-2 .td-item1 {
                        background: url(http://lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris-02-80x60.jpg) 0 0 no-repeat;
                    }
                    #td_uid_1_5796c98993369  .td-doubleSlider-2 .td-item2 {
                        background: url(http://lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris-80x60.jpg) 0 0 no-repeat;
                    }
                &lt;/style&gt;
&lt;div id="td_uid_1_5796c98993369" class="td-slide-on-2-columns"&gt;
&lt;div class="post_td_gallery"&gt;
&lt;div class="td-gallery-slide-top"&gt;
&lt;div class="td-gallery-title"&gt;&lt;/div&gt;
&lt;div class="td-gallery-controls-wrapper"&gt;
&lt;div class="td-gallery-slide-count"&gt;&lt;span class="td-gallery-slide-item-focus"&gt;1&lt;/span&gt; de 2&lt;/div&gt;
&lt;div class="td-gallery-slide-prev-next-but"&gt;
                                    &lt;i class = "td-icon-left doubleSliderPrevButton"&gt;&lt;/i&gt;&lt;br /&gt;
                                    &lt;i class = "td-icon-right doubleSliderNextButton"&gt;&lt;/i&gt;
                                &lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;div class = "td-doubleSlider-1 "&gt;
&lt;div class = "td-slider"&gt;
&lt;div class = "td-slide-item td-item1"&gt;
&lt;figure class="td-slide-galery-figure td-slide-popup-gallery"&gt;
                            &lt;a class="slide-gallery-image-link" href="http://i2.wp.com/lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris-02.jpg" title="2016 07 20 Omar Ortega y senadora Iris 02"  data-caption="Senadora Iris toma la palabra , mientras Omar Ortega preside la reunión del Congreso de la Unión"  data-description=""&gt;&lt;br /&gt;
                                &lt;img src="http://i2.wp.com/lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris-02.jpg?w=640" alt="" data-recalc-dims="1"&gt;&lt;br /&gt;
                            &lt;/a&gt;&lt;/p&gt;
&lt;figcaption class = "td-slide-caption td-gallery-slide-content"&gt;
&lt;div class = "td-gallery-slide-copywrite"&gt;Senadora Iris toma la palabra , mientras Omar Ortega preside la reunión del Congreso de la Unión&lt;/div&gt;
&lt;/figcaption&gt;
&lt;/figure&gt;&lt;/div&gt;
&lt;div class = "td-slide-item td-item2"&gt;
&lt;figure class="td-slide-galery-figure td-slide-popup-gallery"&gt;
                            &lt;a class="slide-gallery-image-link" href="http://i1.wp.com/lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris.jpg" title="2016 07 20 Omar Ortega y senadora Iris"  data-caption="Omar Ortega y Senadora Iris Vianey sostienen cruz simbólica en protesta por feminicidios. Gráfica de celular  "  data-description=""&gt;&lt;br /&gt;
                                &lt;img src="http://i1.wp.com/lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris.jpg?w=640" alt="" data-recalc-dims="1"&gt;&lt;br /&gt;
                            &lt;/a&gt;&lt;/p&gt;
&lt;figcaption class = "td-slide-caption td-gallery-slide-content"&gt;
&lt;div class = "td-gallery-slide-copywrite"&gt;Omar Ortega y Senadora Iris Vianey sostienen cruz simbólica en protesta por feminicidios. Gráfica de celular  &lt;/div&gt;
&lt;/figcaption&gt;
&lt;/figure&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;div class = "td-doubleSlider-2"&gt;
&lt;div class = "td-slider"&gt;
&lt;div class = "td-button td-item1"&gt;
&lt;div class = "td-border"&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;div class = "td-button td-item2"&gt;
&lt;div class = "td-border"&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;/p&gt;&lt;/div&gt;
&lt;p&gt;Ciudad de México 20 de Julio.- La Comisión Permanente del Congreso de la Unión demandó el gobernador del Estado de México, Eruviel Ávila Villegas, dar un informe detallado de lo hecho por su administración para frenar los feminicidios y las acciones de violencia contra las mujeres. También se pide un informe a los municipios del Estado de México en donde se estableció la alerta de género, así como a las acciones emprendidas por la Secretaría de Gobernación.&lt;/p&gt;
&lt;p&gt;El punto de acuerdo fue sometido a consideración de la Comisión Permanente por el diputado federal Omar Ortega, quien también es presidente del PRD en el Estado de México. Entre los municipios obligados a entregar un informe se encuentran : Ecatepec, Nezahualcóyotl, Tlalnepantla, Toluca, Chimalhuacán, Naucalpan, Tultitlán, Ixtapaluca, Valle de Chalco, Cuautitlán Izcalli y Chalco.&lt;/p&gt;
&lt;p&gt;En la tribuna sostuvo que no se percibe que la alerta de género esté frenando los atentados contra las mujeres, por el contrario  &#8220;los criminales siguen arrojando cadáveres de mujeres en baldíos, basureros, camellones, ríos, canales y otros lugares, lo que evidencia que la acción no ha tenido resultado&#8221;.&lt;/p&gt;
&lt;p&gt;&#8220;Diversas agrupaciones civiles, dijo, realizaron acciones para llamar la atención sobre el incumplimiento y exigir resultados, acciones entre las que se incluyeron la colocación de cruces rosas en los sitios donde eran tirados o encontrados los cuerpos de las víctimas.&#8221; sin embargo autoridades municipales, como las de Chimalhuacán, de forma arbitraria han retirado las cruces que simbolizan que en ese lugar se cometió un feminicidio.&lt;/p&gt;
&lt;p&gt;Por eso en esta ocasión la senadora Iris Vianey portó en la sesión una cruz que es un símbolo de protesta en contra de los feminicidios.&lt;/p&gt;
&lt;p&gt;El líder del PRD en el Estado de México destacó que las cruces han sido recolocadas por las asociaciones civiles pues forman parte de una reparación simbólica hacia las víctimas y sus familias, dado que hasta en la reparación legal han fallado también las autoridades.&lt;/p&gt;
&lt;p&gt;También propuso y se aprobó exhortar a los poderes legislativos de las entidades federativas a homologar la normatividad para prevenir, atender y sancionar cualquier tipo de violencia contra las mujeres -incluidos el delito de feminicidio y la violencia feminicida- contemplados en la Ley General de Acceso de las Mujeres a una Vida Libre de Violencia y en Código Penal Federal.&lt;/p&gt;
&lt;p&gt;&nbsp;&lt;/p&gt;
</code></pre>
Transformed Markup:
<code><pre>
&lt;html&gt;
  &lt;head&gt;
    &lt;link rel="canonical" href="http://lector24.com/blog/2016/07/21/eruviel-debe-informar-feminicidios-pide-comision-permanente/"/&gt;
    &lt;meta charset="utf-8"/&gt;
    &lt;meta property="op:generator" content="facebook-instant-articles-sdk-php"/&gt;
    &lt;meta property="op:generator:version" content="1.3.0"/&gt;
    &lt;meta property="op:generator:application" content="facebook-instant-articles-wp"/&gt;
    &lt;meta property="op:generator:application:version" content="2.11"/&gt;
    &lt;meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/&gt;
    &lt;meta property="op:generator:transformer:version" content="1.3.0"/&gt;
    &lt;meta property="op:markup_version" content="v1.0"/&gt;
    &lt;meta property="fb:article_style" content="default"/&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;article&gt;
      &lt;header&gt;
        &lt;figure&gt;
          &lt;img src="http://lector24.com/wp-content/uploads/2016/07/2016-07-20-Omar-Ortega-y-senadora-Iris-02.jpg"/&gt;
          &lt;figcaption&gt;Senadora Iris toma la palabra , mientras Omar Ortega preside la reunión del Congreso de la Unión&lt;/figcaption&gt;
        &lt;/figure&gt;
        &lt;h1&gt;Eruviel debe informar sobre feminicidios, pide Comisión Permanente.&lt;/h1&gt;
        &lt;time class="op-published" datetime="2016-07-21T06:40:46+00:00"&gt;July 21st, 6:40am&lt;/time&gt;
        &lt;time class="op-modified" datetime="2016-07-25T20:23:05+00:00"&gt;July 25th, 8:23pm&lt;/time&gt;
        &lt;address&gt;&lt;a&gt;Lector 24&lt;/a&gt;Empresa con más de 20 años de experiencia en el ambiente editorial&lt;/address&gt;
      &lt;/header&gt;
      &lt;p&gt; &lt;/p&gt;
      &lt;p&gt;Ciudad de México 20 de Julio.- La Comisión Permanente del Congreso de la Unión demandó el gobernador del Estado de México, Eruviel Ávila Villegas, dar un informe detallado de lo hecho por su administración para frenar los feminicidios y las acciones de violencia contra las mujeres. También se pide un informe a los municipios del Estado de México en donde se estableció la alerta de género, así como a las acciones emprendidas por la Secretaría de Gobernación.&lt;/p&gt;
      &lt;p&gt;El punto de acuerdo fue sometido a consideración de la Comisión Permanente por el diputado federal Omar Ortega, quien también es presidente del PRD en el Estado de México. Entre los municipios obligados a entregar un informe se encuentran : Ecatepec, Nezahualcóyotl, Tlalnepantla, Toluca, Chimalhuacán, Naucalpan, Tultitlán, Ixtapaluca, Valle de Chalco, Cuautitlán Izcalli y Chalco.&lt;/p&gt;
      &lt;p&gt;En la tribuna sostuvo que no se percibe que la alerta de género esté frenando los atentados contra las mujeres, por el contrario  “los criminales siguen arrojando cadáveres de mujeres en baldíos, basureros, camellones, ríos, canales y otros lugares, lo que evidencia que la acción no ha tenido resultado”.&lt;/p&gt;
      &lt;p&gt;“Diversas agrupaciones civiles, dijo, realizaron acciones para llamar la atención sobre el incumplimiento y exigir resultados, acciones entre las que se incluyeron la colocación de cruces rosas en los sitios donde eran tirados o encontrados los cuerpos de las víctimas.” sin embargo autoridades municipales, como las de Chimalhuacán, de forma arbitraria han retirado las cruces que simbolizan que en ese lugar se cometió un feminicidio.&lt;/p&gt;
      &lt;p&gt;Por eso en esta ocasión la senadora Iris Vianey portó en la sesión una cruz que es un símbolo de protesta en contra de los feminicidios.&lt;/p&gt;
      &lt;p&gt;El líder del PRD en el Estado de México destacó que las cruces han sido recolocadas por las asociaciones civiles pues forman parte de una reparación simbólica hacia las víctimas y sus familias, dado que hasta en la reparación legal han fallado también las autoridades.&lt;/p&gt;
      &lt;p&gt;También propuso y se aprobó exhortar a los poderes legislativos de las entidades federativas a homologar la normatividad para prevenir, atender y sancionar cualquier tipo de violencia contra las mujeres -incluidos el delito de feminicidio y la violencia feminicida- contemplados en la Ley General de Acceso de las Mujeres a una Vida Libre de Violencia y en Código Penal Federal.&lt;/p&gt;
      &lt;p&gt; &lt;/p&gt;
    &lt;/article&gt;
  &lt;/body&gt;
&lt;/html&gt;
</code></pre>

If there is a way to use native Jetpack galleries instead of the theme's one, I'm willing to do it. 

Have a nice day

**Comment by everton-rosario** [comment]
@ChequePata You can use this as your custom rules:

```
{
    "rules":
    [{
      "class" : "IgnoreRule",
      "selector": "div.td-gallery-slide-top"
    },
    {
      "class" : "IgnoreRule",
      "selector": "style"
    },
    {
      "class" : "IgnoreRule",
      "selector": "div.td-button"
    },
    {
      "class" : "PassThroughRule",
      "selector": "div.td-doubleSlider-1"
    },
    {
      "class" : "PassThroughRule",
      "selector": "div.td-slide-on-2-columns"
    },
    {
      "class" : "PassThroughRule",
      "selector": "div.td-doubleSlider-2"
    },
    {
      "class" : "PassThroughRule",
      "selector": "div.td-slider"
    },
    {
      "class" : "PassThroughRule",
      "selector": "div.td-slide-item"
    },
    {
      "class": "SlideshowRule",
      "selector" : "div.post_td_gallery"
    },
    {
      "class": "SlideshowImageRule",
      "selector" : "div.td-slide-item",
      "properties" : {
        "image.url" : {
          "type" : "string",
          "selector" : "a.slide-gallery-image-link",
          "attribute": "href"
        },
        "caption.title" : {
          "type" : "string",
          "selector" : "div.td-gallery-slide-copywrite"
        }
      }
    }
]
}
```


Follow this sequence to add this rule configuration: 
1. Click on the InstantArticles menu Item (usually it stays in the left menu bar)
2. It will open the InstantArticles plugin settings page.
3. Scroll down to find the section called: "Publishing Settings"
4. Enable the checkbox "Enable custom transformer rules"
5. Enter the rules within the common code as above
