### ISSUE TITLE
Image in post not displaying 

### ISSUE THREAD

**Issue by adavize4u** [Automattic/facebook-instant-articles-wp#381]
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

*Pulling image from the article and publish in instant article.

# Actual Result

* I'm getting an instant article without image even though i input image in the article.
Though, image will pick up only when input in feature attachment

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version:  wordpress 4.5.3
* PHP version:  5.5

**Comment by everton-rosario** [comment]
@adavize4u Are you using some plugin to get your image in?

Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Will reopen after further info.

**Comment by adavize4u** [comment]
Yes, i use custom plugin to display image in my article without imputing it via featured image but in inside the article.

**Source markup**

<div id="attachment_23208" style="width: 610px" class="wp-caption aligncenter"><img class="size-large wp-image-23208" src="http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister-600x400.jpg?fit=600%2C400" alt="President Buhari with Foreign Minister of the Islamic Republic of Iran H.E. Dr. Mohammad Javad Zarif and H.E. Mr. Morteza Rahimi Zarchi Ambassador of Iran to Nigeria at the Statehouse on 25th July 2016." srcset="http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=600%2C400 600w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=300%2C200 300w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=400%2C267 400w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=768%2C512 768w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=200%2C133 200w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?w=960 960w" sizes="(max-width: 600px) 100vw, 600px" data-recalc-dims="1" />
<p class="wp-caption-text"><em>President Buhari with Foreign Minister of the Islamic Republic of Iran H.E. Dr. Mohammad Javad Zarif and H.E. Mr. Morteza Rahimi Zarchi Ambassador of Iran to Nigeria at the Statehouse on 25th July 2016.</em></p>
</div>
<p>President Muhammadu Buhari has expressed great respect for the economic recovery of Ira through the use of diversification. He said that his government is carefully understudying the experiences Iran and other countries that have thrived in adversity.</p>
<p>Receiving a Special Envoy from the President of Islamic Republic of Iran at the State House, Mohammad Javad Zarif, President Buhari said the Iranian economy remains an inspiration for Nigeria in the deployment of technology to harness and export gas, grow food for the populace and promote entrepreneurship in education.</p>
<p>“The progress made by Iran within a short period of 30 years is really commendable. Within the period, you have been able to harness gas flaring, and you are now exporting. You have recorded strides in security, manufacturing, agriculture and technology.</p>
<p>“You have also achieved a lot in nuclear research. I must also congratulate you for successfully negotiating with America and the European countries on the development of your nuclear energy,’’ he said.</p>
<p>The President noted that Nigeria had all the potentials for growing into a great economy through more inclusive planning, consistency in government policies and commitment to the realization of development targets.</p>
<p>“In Nigeria, we are learning. We are learning the hard way through hardship, and we are learning very quickly on how to explore other sectors of the economy like gas, solid minerals and agriculture for growth.</p>
<p>“We are grateful for your support and cooperation in opening up the Nigerian economy for diversification,’’ President Buhari told the envoy.”</p>
<p>The Iranian envoy, who is also the Minister of Foreign Affairs, assured the support of the Iranian government of the ongoing restructuring of the Nigerian economy.</p>
<p>“We are very keen to see a better and stronger relationship with Nigeria, which is the largest country in Africa and a major global player.”</p>
<p>Zarif said that he came into Nigeria with a delegation of more than 70 members of the Iranian business community who had already started discussions in investing in sectors like banking, education, scholarship, agriculture, energy, tourism and technology development.
<div id="adsense"><center><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><br />
<br />
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2019846461392926"
     data-ad-slot="4566777081"
     data-ad-format="auto"></ins><br />
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></p>
<figure class="op-ad">
  <iframe width="320" height="50" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=1747218905493838_1762830373932691&adtype=banner320x50"></iframe><br />
</figure>
<p></center></div></p>


**Transformed markup**

<html>
  <head>
    <link rel="canonical" href="http://www.greenbreporters.com/home/national/buhari-admires-irans-economic-recovery-diversification.html"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Buhari Admires Iran’s Economic Recovery Through Diversification</h1>
        <time class="op-published" datetime="2016-07-25T21:36:43+00:00">July 25th, 9:36pm</time>
        <time class="op-modified" datetime="2016-07-26T01:03:30+00:00">July 26th, 1:03am</time>
        <address><a>Greenbarge Reporters</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=740638885974123_1080837911954217&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>President Muhammadu Buhari has expressed great respect for the economic recovery of Ira through the use of diversification. He said that his government is carefully understudying the experiences Iran and other countries that have thrived in adversity.</p>
      <p>Receiving a Special Envoy from the President of Islamic Republic of Iran at the State House, Mohammad Javad Zarif, President Buhari said the Iranian economy remains an inspiration for Nigeria in the deployment of technology to harness and export gas, grow food for the populace and promote entrepreneurship in education.</p>
      <p>“The progress made by Iran within a short period of 30 years is really commendable. Within the period, you have been able to harness gas flaring, and you are now exporting. You have recorded strides in security, manufacturing, agriculture and technology.</p>
      <p>“You have also achieved a lot in nuclear research. I must also congratulate you for successfully negotiating with America and the European countries on the development of your nuclear energy,’’ he said.</p>
      <p>The President noted that Nigeria had all the potentials for growing into a great economy through more inclusive planning, consistency in government policies and commitment to the realization of development targets.</p>
      <p>“In Nigeria, we are learning. We are learning the hard way through hardship, and we are learning very quickly on how to explore other sectors of the economy like gas, solid minerals and agriculture for growth.</p>
      <p>“We are grateful for your support and cooperation in opening up the Nigerian economy for diversification,’’ President Buhari told the envoy.”</p>
      <p>The Iranian envoy, who is also the Minister of Foreign Affairs, assured the support of the Iranian government of the ongoing restructuring of the Nigerian economy.</p>
      <p>“We are very keen to see a better and stronger relationship with Nigeria, which is the largest country in Africa and a major global player.”</p>
      <p>Zarif said that he came into Nigeria with a delegation of more than 70 members of the Iranian business community who had already started discussions in investing in sectors like banking, education, scholarship, agriculture, energy, tourism and technology development.
</p>
    </article>
  </body>
</html>

**Comment by adavize4u** [comment]
`**Source markup**

<div id="attachment_23208" style="width: 610px" class="wp-caption aligncenter"><img class="size-large wp-image-23208" src="http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister-600x400.jpg?fit=600%2C400" alt="President Buhari with Foreign Minister of the Islamic Republic of Iran H.E. Dr. Mohammad Javad Zarif and H.E. Mr. Morteza Rahimi Zarchi Ambassador of Iran to Nigeria at the Statehouse on 25th July 2016." srcset="http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=600%2C400 600w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=300%2C200 300w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=400%2C267 400w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=768%2C512 768w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?resize=200%2C133 200w, http://i1.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/07/Buhari-and-Iranian-foriegn-minister.jpg?w=960 960w" sizes="(max-width: 600px) 100vw, 600px" data-recalc-dims="1" />
<p class="wp-caption-text"><em>President Buhari with Foreign Minister of the Islamic Republic of Iran H.E. Dr. Mohammad Javad Zarif and H.E. Mr. Morteza Rahimi Zarchi Ambassador of Iran to Nigeria at the Statehouse on 25th July 2016.</em></p>
</div>
<p>President Muhammadu Buhari has expressed great respect for the economic recovery of Ira through the use of diversification. He said that his government is carefully understudying the experiences Iran and other countries that have thrived in adversity.</p>
<p>Receiving a Special Envoy from the President of Islamic Republic of Iran at the State House, Mohammad Javad Zarif, President Buhari said the Iranian economy remains an inspiration for Nigeria in the deployment of technology to harness and export gas, grow food for the populace and promote entrepreneurship in education.</p>
<p>“The progress made by Iran within a short period of 30 years is really commendable. Within the period, you have been able to harness gas flaring, and you are now exporting. You have recorded strides in security, manufacturing, agriculture and technology.</p>
<p>“You have also achieved a lot in nuclear research. I must also congratulate you for successfully negotiating with America and the European countries on the development of your nuclear energy,’’ he said.</p>
<p>The President noted that Nigeria had all the potentials for growing into a great economy through more inclusive planning, consistency in government policies and commitment to the realization of development targets.</p>
<p>“In Nigeria, we are learning. We are learning the hard way through hardship, and we are learning very quickly on how to explore other sectors of the economy like gas, solid minerals and agriculture for growth.</p>
<p>“We are grateful for your support and cooperation in opening up the Nigerian economy for diversification,’’ President Buhari told the envoy.”</p>
<p>The Iranian envoy, who is also the Minister of Foreign Affairs, assured the support of the Iranian government of the ongoing restructuring of the Nigerian economy.</p>
<p>“We are very keen to see a better and stronger relationship with Nigeria, which is the largest country in Africa and a major global player.”</p>
<p>Zarif said that he came into Nigeria with a delegation of more than 70 members of the Iranian business community who had already started discussions in investing in sectors like banking, education, scholarship, agriculture, energy, tourism and technology development.
<div id="adsense"><center><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><br />
<br />
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2019846461392926"
     data-ad-slot="4566777081"
     data-ad-format="auto"></ins><br />
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></p>
<figure class="op-ad">
  <iframe width="320" height="50" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=1747218905493838_1762830373932691&adtype=banner320x50"></iframe><br />
</figure>
<p></center></div></p>


**Transformed markup**

<html>
  <head>
    <link rel="canonical" href="http://www.greenbreporters.com/home/national/buhari-admires-irans-economic-recovery-diversification.html"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Buhari Admires Iran’s Economic Recovery Through Diversification</h1>
        <time class="op-published" datetime="2016-07-25T21:36:43+00:00">July 25th, 9:36pm</time>
        <time class="op-modified" datetime="2016-07-26T01:03:30+00:00">July 26th, 1:03am</time>
        <address><a>Greenbarge Reporters</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=740638885974123_1080837911954217&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>President Muhammadu Buhari has expressed great respect for the economic recovery of Ira through the use of diversification. He said that his government is carefully understudying the experiences Iran and other countries that have thrived in adversity.</p>
      <p>Receiving a Special Envoy from the President of Islamic Republic of Iran at the State House, Mohammad Javad Zarif, President Buhari said the Iranian economy remains an inspiration for Nigeria in the deployment of technology to harness and export gas, grow food for the populace and promote entrepreneurship in education.</p>
      <p>“The progress made by Iran within a short period of 30 years is really commendable. Within the period, you have been able to harness gas flaring, and you are now exporting. You have recorded strides in security, manufacturing, agriculture and technology.</p>
      <p>“You have also achieved a lot in nuclear research. I must also congratulate you for successfully negotiating with America and the European countries on the development of your nuclear energy,’’ he said.</p>
      <p>The President noted that Nigeria had all the potentials for growing into a great economy through more inclusive planning, consistency in government policies and commitment to the realization of development targets.</p>
      <p>“In Nigeria, we are learning. We are learning the hard way through hardship, and we are learning very quickly on how to explore other sectors of the economy like gas, solid minerals and agriculture for growth.</p>
      <p>“We are grateful for your support and cooperation in opening up the Nigerian economy for diversification,’’ President Buhari told the envoy.”</p>
      <p>The Iranian envoy, who is also the Minister of Foreign Affairs, assured the support of the Iranian government of the ongoing restructuring of the Nigerian economy.</p>
      <p>“We are very keen to see a better and stronger relationship with Nigeria, which is the largest country in Africa and a major global player.”</p>
      <p>Zarif said that he came into Nigeria with a delegation of more than 70 members of the Iranian business community who had already started discussions in investing in sectors like banking, education, scholarship, agriculture, energy, tourism and technology development.
</p>
    </article>
  </body>
</html>`

**Comment by everton-rosario** [comment]
@adavize4u what is the plugin you are using?

**Comment by adavize4u** [comment]
"Get the image"

**Comment by everton-rosario** [comment]
Is it this one: `https://wordpress.org/plugins/get-the-image/`?

**Comment by adavize4u** [comment]
Yes sir

**Comment by everton-rosario** [comment]
@adavize4u This is now supported.

Can you test using the PR #385, please?

**Comment by adavize4u** [comment]
Sorry for replying lately. 
Still having little problem:
1. Sometimes, text striped from the transform post, making our facebook update useless.
2. Image mostly appear when article published with new image, but old image picked from the site uploads, it sometimes not displaying image.

**Comment by everton-rosario** [comment]
Same case as the other Issue. Please share with us the transformed and the pre-transformer markup, @adavize4u

**Comment by adavize4u** [comment]
# SORRY FOR REPLYING LATELY. HERE IS THE BOTH SOURCE AND TRANSFORMED MARKUP

**SOURCE MARKUP**

<p><img class="aligncenter size-full wp-image-21136" src="http://i2.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/05/Emma-Bello.jpg?fit=284%2C177" alt="Emma Bello" data-recalc-dims="1" />An amalgamation of youth groups in Taraba state under the auspices of PDP 100 percent loyalists have thrown their weight behind Mr. Emmanuel Bello for the position of the National Publicity Secretary of the Peoples Democratic Party (PDP).<br />
The group said that Bello, who was the former commissioner of information in the state, possess the needed qualities for the position.<br />
In a statement, the leader of the group, Hon. Dennis Shima said: &#8220;we are delighted to endorse the candidature of Hon Emmanuel Bello for the position of the National Publicity Secretary of our great party. We note with deep humility that Emmanuel Bello, while he held similar roles in Taraba state performed creditably well, displaying high level loyalty to the party and his principal. As an accomplished journalist, it is our belief that Bello comes to the contest with sterling qualities of a news man who has also worked in government cycles where he was first a special adviser on Media and twice a commissioner of information. He has also been prepared by his principled stand at the most trying period of the state&#8217;s history where he became famous for stubbornly standing by ailing former Governor Danbaba Suntai. This was at the time it was easier to compromise loyalty.&#8221;<br />
It would be recalled that the Makarfi-led PDP has zoned the position of National Publicity Secretary to the North Central even as the party said viable candidates can still contest positions, irrespective of the zoning formula.<br />
Emmanuel Bello, a former editor with leadership newspaper among other newspapers, has not officially declare for the position yet.<br />
A source close to him said that the 45 year old former commissioner is currently consulting with stakeholders in the state.
<div id="adsense"><center><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><br />
<br />
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2019846461392926"
     data-ad-slot="4566777081"
     data-ad-format="auto"></ins><br />
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br />
</center></div></p>


**TRANSFORMED MARKUP**

<html>
  <head>
    <link rel="canonical" href="http://www.greenbreporters.com/home/national/politics/taraba-youth-groups-endorse-emmanuel-bello-pdp-national-publicity-secretary.html"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.3.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="2.11"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.3.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Taraba Youth Groups Endorse Emmanuel Bello For PDP National Publicity Secretary</h1>
        <time class="op-published" datetime="2016-08-06T21:33:06+00:00">August 6th, 9:33pm</time>
        <time class="op-modified" datetime="2016-08-06T21:33:06+00:00">August 6th, 9:33pm</time>
        <address><a>Greenbarge Reporters</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=740638885974123_1080837911954217&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <figure>
        <img src="http://i2.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/05/Emma-Bello.jpg?fit=284%2C177"/>
      </figure>
    </article>
  </body>
</html>

**Comment by everton-rosario** [comment]
@adavize4u I noticed that all your content is inside same <p> tag.

Is it possible for you to change this structure?
Something like:
```
<p>
  <img class="aligncenter size-full wp-image-21136" src="http://i2.wp.com/www.greenbreporters.com/home/wp-content/uploads/2016/05/Emma-Bello.jpg?fit=284%2C177" alt="Emma Bello" data-recalc-dims="1" />
</p>
<p>
  An amalgamation of youth groups in Taraba state under the auspices of PDP 100 percent loyalists have thrown their weight behind Mr. Emmanuel Bello for the position of the National Publicity Secretary of the Peoples Democratic Party (PDP).<br />
  The group said that Bello, who was the former commissioner of information in the state, possess the needed qualities for the position.
</p>
  <br />
<p>In a statement, the leader of the group, Hon. Dennis Shima said: &#8220;we are delighted to endorse the candidature of Hon Emmanuel Bello for the position of the National Publicity Secretary of our great party. We note with deep humility that Emmanuel Bello, while he held similar roles in Taraba state performed creditably well, displaying high level loyalty to the party and his principal. As an accomplished journalist, it is our belief that Bello comes to the contest with sterling qualities of a news man who has also worked in government cycles where he was first a special adviser on Media and twice a commissioner of information. He has also been prepared by his principled stand at the most trying period of the state&#8217;s history where he became famous for stubbornly standing by ailing former Governor Danbaba Suntai. This was at the time it was easier to compromise loyalty.&#8221;
</p>
  <br />
<p>It would be recalled that the Makarfi-led PDP has zoned the position of National Publicity Secretary to the North Central even as the party said viable candidates can still contest positions, irrespective of the zoning formula.
</p>
  <br />
<p>
Emmanuel Bello, a former editor with leadership newspaper among other newspapers, has not officially declare for the position yet.
</p>
  <br />
<p>
  A source close to him said that the 45 year old former commissioner is currently consulting with stakeholders in the state.
</p>
<div id="adsense">
  <center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <br />
    <!-- NEW RESPONSIVE AD -->
    <br />
    <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-2019846461392926"
       data-ad-slot="4566777081"
       data-ad-format="auto"></ins>
    <br />
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    <br />
  </center>
</div>
```

**Comment by everton-rosario** [comment]
Using adsense is not allowed.
You will get reproved by review. You should use [Audience Network](https://web.facebook.com/business/news/audience-network?_rdr) or any inhouse solution that you might already have.

Here you have a working version of this transforming rules.

Add this to your rules.json:
```
    {
       "class": "AdRule",
       "selector": "div#adsense",
       "properties": {
          "ad.embed": {
              "type": "element",
              "selector": "div"
          }
       }
    }
```

And use latest version of [SDK](https://github.com/facebook/facebook-instant-articles-sdk-php/releases/latest)

**Comment by Tilakbhattacharya** [comment]
Hello, 

I am using Instant article plugin in my wordpress site, my articles are getting approved but it's not pulling up the image

**Source markup**
#<p>We truly need to acknowledge Mumbai police for the way they have superbly taken care of Varun Dhawan&#8217;s selfie case toward the beginning of today. They are careful and are extremely worried about our well-being. The way they give it a second thought, is sufficient to get them an enormous fan following.</p>
<p><img class="alignnone size-medium wp-image-22178" src="https://socialchull.com/wp-content/uploads/2017/11/1255-300x278.jpg" srcset="https://socialchull.com/wp-content/uploads/2017/11/1255-300x278.jpg 300w, https://socialchull.com/wp-content/uploads/2017/11/1255.jpg 600w" sizes="(max-width: 300px) 100vw, 300px" /></p>
<p>In the event that despite everything you didn&#8217;t comprehend what we are discussing, given us a chance to reveal to you that, we are alluding to their Twitter handle. We are a major aficionado of their imaginative and minding tweets.</p>
<p>Today morning, Varun Dhawan got an ideal lesson from Mumbai police with respect to street well-being. We should likewise acknowledge how Varun Dhawan immediately understood his error and apologized on his Twitter handle. On the off chance that you have missed the discussion, read it immediately;</p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">.<a href="https://twitter.com/Varun_dvn?ref_src=twsrc%5Etfw">@Varun_dvn</a> These adventures surely work on D silver screen but certainly not on the roads of Mumbai! U have risked ur life,ur admirer’s &amp; few others. V expect better from a responsible Mumbaikar &amp; youth icon like U! An E-Challan is on d way 2 ur home. Next time, V will B harsher <a href="https://t.co/YmdytxspGY">pic.twitter.com/YmdytxspGY</a></p>
<p>— Mumbai Police (@MumbaiPolice) <a href="https://twitter.com/MumbaiPolice/status/933570850292461568?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">My apologies &#x1f64f; Our cars weren’t moving since we were at a traffic signal and I didn’t want to hurt the sentiment of a fan but next time I’ll keep safety in mind and won’t encourage this. <a href="https://t.co/MEJk56EksG">https://t.co/MEJk56EksG</a></p>
<p>— Varun Dhawan (@Varun_dvn) <a href="https://twitter.com/Varun_dvn/status/933585803716038656?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">Quite a galactic coincidence for the photographer to be on the same signal to capture your gesture, in a good intent nevertheless risky. Leaning out even in a stationary vehicle can be distracting for others considering your popularity. Glad you took our message in d right spirit <a href="https://t.co/jKqosfH6V3">https://t.co/jKqosfH6V3</a></p>
<p>— Mumbai Police (@MumbaiPolice) <a href="https://twitter.com/MumbaiPolice/status/933606783175753728?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">“Galactic coincidence”&#8230;&#8230;Admire the person sitting behind this twitter handle</p>
<p>— Vivek Kumar Singh (@_vksingh_) <a href="https://twitter.com/_vksingh_/status/933607849061580802?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">Must be following <a href="https://twitter.com/ShashiTharoor?ref_src=twsrc%5Etfw">@ShashiTharoor</a> closely</p>
<p>— PulpendiCulal (@4thusername) <a href="https://twitter.com/4thusername/status/933609330871476224?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">Must be following <a href="https://twitter.com/ShashiTharoor?ref_src=twsrc%5Etfw">@ShashiTharoor</a> closely</p>
<p>— PulpendiCulal (@4thusername) <a href="https://twitter.com/4thusername/status/933609330871476224?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">This tweet shud be read at some &#8220;Literature festival&#8221;..Galactic Co incidence&#8230;&#x1f44f;&#x1f44f;&#x1f44f; absolute legend&#8230;the linguist behind this tweet..where art thou??</p>
<p>— Kumar Gaurav (@inkkpott) <a href="https://twitter.com/inkkpott/status/933616804458463233?ref_src=twsrc%5Etfw">November 23, 2017</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>


Transformed markup
#<html>
  <head>
    <link rel="canonical" href="https://socialchull.com/indeed-even-after-apology-mumbai-police-left-1-more-tweet-for-varun-twitter-is-loving-it/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="scdefault"/>
  </head>
  <body>
    <article><header><figure><img src="https://socialchull.com/wp-content/uploads/2017/11/Untitled.png"/></figure><h1>Indeed, even After Apology, Mumbai Police Left 1 More Tweet For Varun. Twitter Is Loving It!!</h1><time class="op-published" datetime="2017-11-23T17:10:50+00:00">November 23rd, 5:10pm</time><time class="op-modified" datetime="2017-11-23T17:10:50+00:00">November 23rd, 5:10pm</time><address><a>Shagun Bharti</a></address><figure class="op-ad"><iframe src="https://www.facebook.com/adnw_request?placement=1561675547247976_1561675563914641&amp;adtype=banner300x250" width="300" height="250"></iframe></figure></header><p>We truly need to acknowledge Mumbai police for the way they have superbly taken care of Varun Dhawan’s selfie case toward the beginning of today. They are careful and are extremely worried about our well-being. The way they give it a second thought, is sufficient to get them an enormous fan following.</p><p>In the event that despite everything you didn’t comprehend what we are discussing, given us a chance to reveal to you that, we are alluding to their Twitter handle. We are a major aficionado of their imaginative and minding tweets.</p><p>Today morning, Varun Dhawan got an ideal lesson from Mumbai police with respect to street well-being. We should likewise acknowledge how Varun Dhawan immediately understood his error and apologized on his Twitter handle. On the off chance that you have missed the discussion, read it immediately;</p><blockquote>
<i>.<i>@Varun_dvn</i> These adventures surely work on D silver screen but certainly not on the roads of Mumbai! U have risked ur life,ur admirer’s &amp; few others. V expect better from a responsible Mumbaikar &amp; youth icon like U! An E-Challan is on d way 2 ur home. Next time, V will B harsher <i>pic.twitter.com/YmdytxspGY</i></i>
<i>— Mumbai Police (@MumbaiPolice) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>My apologies 🙏 Our cars weren’t moving since we were at a traffic signal and I didn’t want to hurt the sentiment of a fan but next time I’ll keep safety in mind and won’t encourage this. <i>https://t.co/MEJk56EksG</i></i>
<i>— Varun Dhawan (@Varun_dvn) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>Quite a galactic coincidence for the photographer to be on the same signal to capture your gesture, in a good intent nevertheless risky. Leaning out even in a stationary vehicle can be distracting for others considering your popularity. Glad you took our message in d right spirit <i>https://t.co/jKqosfH6V3</i></i>
<i>— Mumbai Police (@MumbaiPolice) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>“Galactic coincidence”……Admire the person sitting behind this twitter handle</i>
<i>— Vivek Kumar Singh (@_vksingh_) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>Must be following <i>@ShashiTharoor</i> closely</i>
<i>— PulpendiCulal (@4thusername) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>Must be following <i>@ShashiTharoor</i> closely</i>
<i>— PulpendiCulal (@4thusername) <i>November 23, 2017</i></i></blockquote><blockquote>
<i>This tweet shud be read at some “Literature festival”..Galactic Co incidence…👏👏👏 absolute legend…the linguist behind this tweet..where art thou??</i>
<i>— Kumar Gaurav (@inkkpott) <i>November 23, 2017</i></i></blockquote></article>
  </body>
</html>
