### ISSUE TITLE
Updating already published posts result in error

### ISSUE THREAD

**Issue by chrisadas** [Automattic/facebook-instant-articles-wp#382]
# Steps required to reproduce the problem

1. Publish a post, and checked that article was submitted to Instant Articles successfully
2. Make changes
3. Click Update

# Expected Result

Post updated on WordPress site, and Instant Articles updated on Facebook

# Actual Result

The following error message, as well as the changes not being saved.

> Warning: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1 in /BASE/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 624
> 
> Warning: Cannot modify header information - headers already sent by (output started at /BASE/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php:624) in /home/finiwise/public_html/wp-admin/post.php on line 197
> 
> Warning: Cannot modify header information - headers already sent by (output started at /BASE/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php:624) in /BASE/public_html/wp-includes/pluggable.php on line 1167

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version: 4.5.3
* PHP version:

**Comment by everton-rosario** [comment]
@chrisadas please check if this will fix your issue:

```
		$title = $this->get_the_title();
		if ( $title ) {
			$document = new DOMDocument();
                        libxml_use_internal_errors(true);
			$document->loadHTML( '<?xml encoding="' . $blog_charset . '" ?><h1>' . $title . '</h1>' );
                        libxml_use_internal_errors(false);
			$transformer->transform( $header, $document );
		}


```


On the file class-insntant-articles-post.php (line 624)

**Comment by chrisadas** [comment]
Yes, that fixed it for me. Thanks, Everton!

**Comment by everton-rosario** [comment]
@chrisadas Can you file a PR with this change?

**Comment by chrisadas** [comment]
Never done PR before, hope I did it correctly.

**Comment by everton-rosario** [comment]
Its perfect!
Thanks for that!

Hope you can join our FB group:
https://web.facebook.com/groups/629655867187397/

**Comment by mdruhul68** [comment]
Thats what showing me. can anyone please tell me to what i have to do.  

 Warning:  Cannot modify header information - headers already sent by (output started at /home2/collegec/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:522) in /home2/collegec/public_html/wp-admin/post.php on line 231


Warning:  Cannot modify header information - headers already sent by (output started at /home2/collegec/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:522) in /home2/collegec/public_html/wp-includes/pluggable.php on line 1281


Warning:  Cannot modify header information - headers already sent by (output started at /home2/collegec/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:522) in /home2/collegec/public_html/wp-includes/pluggable.php on line 1284

**Comment by mdruhul68** [comment]
@everton-rosario 
please tell me the solution
