### ISSUE TITLE
Cannot activate

### ISSUE THREAD

**Issue by fagnerssantos** [Automattic/facebook-instant-articles-wp#390]
I have read all the activation issues here. But still not found how to solve. I have installed from wordpress repository. After the installation, this error message appears:

Parse error: syntax error, unexpected T_FUNCTION in /home/storage/b/cc/a0/ypropaganda1/public_html/novo_gremiolibertador/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 18

*\* Version Info **
- Plugin version: 3.0.1
- WordPress version: 4.5.1
- PHP version: 5.2.17

Please, explain that for a wordpress user, not a developer.

(sorry for the bad english, this is not my native language).

**Comment by everton-rosario** [comment]
Hey @fagnerssantos, thanks for your reach out.

Is it possible for you to upgrade to a newer PHP version?
Our plugin and SDK were designed and developed in a way it only supports version 5.4 or superior. 

Unfortunately we have no plans to be compliant with lower PHP versions than 5.4.

PS: your english is great!

**Comment by aidanashby** [comment]
I have this same problem running PHP 5.6, same error message on attempting activation.
Plugin version 3.0.1
WP version 4.6

**Comment by everton-rosario** [comment]
@aidanashby Sorry for the long wait. Closed threads are out of our focus.
Can you still reproduce with the latest version release: 3.3.3?

Thanks.

**Comment by aidanashby** [comment]
Yes, in a Wordpress multisite on Bluehost, running PHP 5.6.
`Parse error: syntax error, unexpected T_FUNCTION in /xxx/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 18`

**Comment by everton-rosario** [comment]
@aidanashby Looks like we have an issue on this file that this older version of Wordpress won't recognize inline functions as callback.

Code with this error:
```
if ( version_compare( PHP_VERSION, '5.4', '<' ) ) {
	add_action(
		'admin_notices',
		function () {
			echo '<div class="error"><p>' .
				esc_html__( 'Instant Articles for WP requires PHP 5.4 to function properly. Please upgrade PHP or deactivate Instant Articles for WP.', 'instant-articles' ) . '</p></div>';
		}
	);
	return;
}
```

Suggestion for fix:
```
function echo_invalid_php_version() {
	echo '<div class="error"><p>' .
		esc_html__( 'Instant Articles for WP requires PHP 5.4 to function properly. Please upgrade PHP or deactivate Instant Articles for WP.', 'instant-articles' ) . '</p></div>';
}
 
if ( version_compare( PHP_VERSION, '5.4', '<' ) ) {
	add_action(
		'admin_notices',
		'echo_invalid_php_version'
	);
	return;
}
```

Can you edit this file and check if this works for you?

**Comment by aidanashby** [comment]
Now it's saying
`Instant Articles for WP requires PHP 5.4 to function properly. Please upgrade PHP or deactivate Instant Articles for WP.`
but I'm very definitely running 5.6.

**Comment by aidanashby** [comment]
My bad, looks like the host default php version is being overridden by Wordpress somewhere, perhaps htaccess. I'll go back to the drawing board.

**Comment by everton-rosario** [comment]
Can you send a Pull request with that fix?
It will be cool. Let me know if you need some help with it.

**Comment by aidanashby** [comment]
Could do with some help on that one please.

**Comment by everton-rosario** [comment]
@aidanashby Already created the PR. this is how it looks like #616
