### ISSUE TITLE
Option to disable instant articles for certain categories

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#396]
Is there any way to add an option to disable instant articles for certain categories?

Can this feature be added? This would be a major help rather than proceding to disable them manually when published

**Comment by everton-rosario** [comment]
@gabu69 Sorry for the long wait.

What do you mean by disabling for some certain categories? The Instant Articles transformation is applied only to "POST".
The code is open, so you can adapt anyway you like.

The method called every time a post is update is this one:
`public static function submit_article( $post_id, $post )`

File:
`class-instant-articles-publisher.php:line~38`

If you think your setting should be global and shared with community, submit to us your Pull Request!

Thanks for using and sharing your knowledge in Instant Articles.

**Comment by gabu69** [comment]
Good day

Yea sorry for not explaining it properly. 

Lets say I have 5 categories in my website:  
1) Cars
2) Computers
3) General talk
4) Geeky stuff
5) Whatever 5

And I dont want to enable instant articles for articles that have a category 2 (computers) or 5 (whatever 5). Is there any way to add a function to disable instant articles for articles that are in certain category?

This would be quite useful for some of us

**Comment by everton-rosario** [comment]
@gabu69 gotcha!

Unfortunately we don't have any kind of configuration like this and in the short term we are not looking forward to have a feature like this supported in this plugin.

The best place you could change is the one I've mentioned before on this very same thread.

```
                // Don't submit if article is from a category I don't want to submit to Instant Articles
                $categories = get_the_category( $post->ID );
                foreach ( $categories as $category ) {
                        if ( 'excluded category name' === $category->name ) {
                               return;
                        }
                }
```


Check how it would be like within the full method:
```
        /**
	 * Submits article to Instant Articles.
	 *
	 * @param string $post_id The identifier of post.
	 * @param Post   $post The WP Post.
	 */
	public static function submit_article( $post_id, $post ) {

		// Don't process if this is just a revision or an autosave.
		if ( wp_is_post_revision( $post ) || wp_is_post_autosave( $post ) ) {
			return;
		}

                // Don't submit if article is from a category I don't want to submit to Instant Articles
                $categories = get_the_category( $post->ID );
                foreach ( $categories as $category ) {
                        if ( 'excluded category name' === $category->name ) {
                               return;
                        }
                }

		// Don't process if this post is not published
		if ( 'publish' !== $post->post_status ) {
			return;
		}

		// Only process posts
		$post_types = apply_filters( 'instant_articles_post_types', array( 'post' ) );
		if ( ! in_array( $post->post_type, $post_types ) ) {
			return;
		}

		// Transform the post to an Instant Article.
		$adapter = new Instant_Articles_Post( $post );

		$article = $adapter->to_instant_article();

		// Skip empty articles or articles missing title.
		// This is important because the save_post action is also triggered by bulk updates, but in this case
		// WordPress does not load the content field from DB for performance reasons. In this case, articles
		// will be empty here, despite of them actually having content.
		if ( count( $article->getChildren() ) === 0 || ! $article->getHeader() || ! $article->getHeader()->getTitle() ) {
			return;
		}

		// Instantiate an API client.
		try {
			$fb_app_settings = Instant_Articles_Option_FB_App::get_option_decoded();
			$fb_page_settings = Instant_Articles_Option_FB_Page::get_option_decoded();
			$publishing_settings = Instant_Articles_Option_Publishing::get_option_decoded();

			$dev_mode = isset( $publishing_settings['dev_mode'] )
				? ( $publishing_settings['dev_mode'] ? true : false )
				: false;

			if ( isset( $fb_app_settings['app_id'] )
				&& isset( $fb_app_settings['app_secret'] )
				&& isset( $fb_page_settings['page_access_token'] )
				&& isset( $fb_page_settings['page_id'] ) ) {

				$client = Client::create(
					$fb_app_settings['app_id'],
					$fb_app_settings['app_secret'],
					$fb_page_settings['page_access_token'],
					$fb_page_settings['page_id'],
					$dev_mode
				);

				// Don't process if contains warnings and blocker flag for transformation warnings is turned on.
				if ( count( $adapter->transformer->getWarnings() ) > 0
				  && isset( $publishing_settings['block_publish_with_warnings'] )
					&& $publishing_settings['block_publish_with_warnings'] ) {

					// Unpublishes if already published
					$client->removeArticle( $article->getCanonicalURL() );
					delete_post_meta( $post_id, self::SUBMISSION_ID_KEY );
					return;
				}

				if ( $dev_mode ) {
					$published = false;
				} else {
					// Any publish status other than 'publish' means draft for the Instant Article.
					$published = true;
				}

				try {
					// Import the article.
					$submission_id = $client->importArticle( $article, $published );
					update_post_meta( $post_id, self::SUBMISSION_ID_KEY, $submission_id );
				} catch ( Exception $e ) {
					// Try without taking live for pages not yet reviewed.
					$submission_id = $client->importArticle( $article, false );
					update_post_meta( $post_id, self::SUBMISSION_ID_KEY, $submission_id );
				}
			}
		} catch ( Exception $e ) {
			Logger::getLogger( 'instantarticles-wp-plugin' )->error(
				'Unable to submit article.',
				$e->getTraceAsString()
			);
		}
	}
```

**Comment by maiross** [comment]
Hello @everton-rosario  
Could you let me know where I have to specify the excluded category?

**Comment by everton-rosario** [comment]
this `get_the_category( )` call is just an abstraction example. 
There are few different ways of getting the tags you have for your articles. Here is a [generic google result I just found about setting tags](https://themeisle.com/blog/categories-and-tags-in-wordpress/).

You can also use the post categories. Here is a [few examples from WP dev site](https://developer.wordpress.org/reference/functions/wp_get_post_categories/)

**Comment by maiross** [comment]
I understand but I am not a PHP developer. I am looking for simple way to exclude all post of one of my categories from being auto converted to instant articles.

I tried to add your code to class-instant-articles-publisher.php and change 'excluded category name' with the name of the category that I want to exclude but is not working. When I debug the URL the post is transformed to IA immediately.
