### ISSUE TITLE
Cannot get `instant_articles_cover_media` filter to work.

### ISSUE THREAD

**Issue by krispy1298** [Automattic/facebook-instant-articles-wp#398]
Trying to get a video as the Header / Cover Media.

Inside Class:
```php
add_filter( 'instant_articles_cover_media', array($this, 'paInstantArticlesCustomCoverMedia'), 20, 2 );
```

```php
  function paInstantArticlesCustomCoverMedia($cover_media, $id) {
    if ( get_field('header_video', $id) ) {
      $cover_media->type = 'video';
      $cover_media->src = get_field('header_video', $id);
    } else {
      $featured_image_data = self::get_the_featured_image($id);
      if ( isset( $featured_image_data['src'] ) && strlen( $featured_image_data['src'] ) ) {
        $cover_media->type = 'image';
        $cover_media->src = $featured_image_data['src'];
        $cover_media->caption = $featured_image_data['caption'];
      }
    }
    return $cover_media;
  }
```

No changes, no matter how drastic I make them, change the code in the "Transformed Markup" panel.

**Comment by menzow** [comment]
Hello Krispy,

I just checked out the source for this project and see that in `class-instant-articles-post.php`  on line `663` the media for the header is initialised.

There's also a function in the same file called: `Instant_Articles_Post::get_cover_media` which is where the filter is applied, but this function is currently not implemented.

I completed the function, implemented it and created a pull request. #402 

You can manually update the class with the changes I made and update your filter like this:

```
function paInstantArticlesCustomCoverMedia($cover_media, $id) {
	if ( get_field('header_video', $id) ) {
		$video_url = get_field('header_video', $id);
		$cover_media = \Facebook\InstantArticles\Elements\Video::create()->withURL($video_url );
	}
	return $cover_media;
}

**Comment by everton-rosario** [comment]
This looks awesome to me @menzow .
I've already "accepted" the PR, but it must be merged by @philipjohn as we agreed on the release process of this plugin.

I'll mark this issue as closed, since your PR fixes it.

Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by krispy1298** [comment]
Thank you @menzow! 👍
