### ISSUE TITLE
Don't process if this post is password protected

### ISSUE THREAD

**Issue by rolandinsh** [Automattic/facebook-instant-articles-wp#405]
# Steps required to reproduce the problem

1.  Publish password protected post
2.  Check instant article feed on facebook

# Expected Result

* excluded password protected post

# Actual Result

* included password protected post

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version:  4.5.3
* PHP version: 7.0.8

**Comment by everton-rosario** [comment]
Nice case @rolandinsh.

I've checked your PR #406 which was nice, but missing to remove the Instant Article if it was already published. 

Can you help test it?
The PR is #420

Closing the issue. If you find any issue, please reopen it.

Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.
