### ISSUE TITLE
Unable to activate on WP due to fatal error

### ISSUE THREAD

**Issue by jlolive** [Automattic/facebook-instant-articles-wp#410]
I downloaded Zip file from Github, uploaded to WP, but when I try to activate the plugin I get this error message:

Warning: require(D:\Inetpub\tusker\Geografica\wp-content\plugins\facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in D:\Inetpub\tusker\Geografica\wp-content\plugins\facebook-instant-articles-wp-master\facebook-instant-articles.php on line 26

Fatal error: require(): Failed opening required 'D:\Inetpub\tusker\Geografica\wp-content\plugins\facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.;C:\php\pear') in D:\Inetpub\tusker\Geografica\wp-content\plugins\facebook-instant-articles-wp-master\facebook-instant-articles.php on line 26

** Version Info **

* Plugin version: 3.0.1
* WordPress version: 4.5.3

**Comment by everton-rosario** [comment]
Make sure you run this command:
```
composer install
```

And have Composer installed on your environment to do so.

Here you have a step-by-step on how to set your environment up for development: 
[Development Environment](https://github.com/Automattic/facebook-instant-articles-wp#development-environment)

Feel free to reopen or send more questions here.
