### ISSUE TITLE
Use Instant Articles on Pages 

### ISSUE THREAD

**Issue by ssoertel** [Automattic/facebook-instant-articles-wp#411]
Is there a way to add the Instant Article areas to my pages too? We have written articles on a bunch of pages that we would like to share. 

---

** Version Info **

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by bjornjohansen** [comment]
Yes, there’s a filter, `instant_articles_post_types`, that you can use to select which post types that should be included. [It is documented here](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L187).

**Comment by ssoertel** [comment]
I understand that, but how do I add it to actual pages in wordpress along with it being on posts?





Thanks,
-----------
Sam Oertel |  Web Designer








 Advertising®  |  WE BRAND. WE MARKET. WE ADVERTISE. WE SOCIALIZE.®

sam@blackdogadvertising.com <x-msg://32/john@blackdogadvertising.com> |  p 305.253.8388 |  f 305.253.8304

8771 SW 129th Terrace  Miami FL  33176

Check out my latest blog post by clicking here <http://www.blackdogadvertising.com/miami-advertising-blog>.

Visit our website at: http:// <http:/>www.BlackdogAdvertising.com/ <http://www.blackdogadvertising.com/>
Fan us on FaceBook:   http:// <http:/>www.facebook.com/BlackDogAd <http://www.facebook.com/BlackDogAd>
Follow us on Twitter:   http:// <http:/>www.twitter.com/BlackDogAd <http://www.twitter.com/BlackDogAd>
Watch us on Youtube:  http:// <http:/>www.youtube.com/BlackdogAdvertising <http://www.youtube.com/BlackdogAdvertising>
Let’s chat on Skype:   sam-blackdog


This message and any attachments are privileged and/or confidential. If you are not the intended recipient, or if you are responsible for delivering it to the intended recipient, you are hereby notified that any review, use, disclosure, distribution, or copying of the communication is not authorized, allowed, or intended by the sender. If you have received this communication in error, please contact the sender by reply e-mail and destroy all copies of this e-mail and its attachments.

**Comment by technosailor** [comment]
@ssoertel we had to register the metabox in a standalone plugin. You can take the plugin's code, and just change the post type until there's a more scaleable approach from the core plugin.

**Comment by jasonblackdog** [comment]
Hello @bjornjohansen and @technosailor . We tried adding this filter to our functions.php file but the metabox still does not display on our 'page' post types. Is there something we're doing wrong?

`add_filter( 'instant_articles_post_types', 'add_post_types', 10,1 );
function add_post_types($post_type_array){
    $post_type_array = array();
    array_push($post_type_array,'post');
    array_push($post_type_array,'page');
   return $post_type_array;
}`

Your help with this is greatly appreciated! Thank you!

**Comment by everton-rosario** [comment]
Thanks for filing a new issue.
Old closed issues are really hard to get attention.
Jumping to the other thread #472
