### ISSUE TITLE
missing captions

### ISSUE THREAD

**Issue by nitakoi** [Automattic/facebook-instant-articles-wp#424]

**Comment by nitakoi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21288976/18035232/ef1fecce-6d7b-11e6-8f13-7b3bee2f480a.jpg)

**Comment by everton-rosario** [comment]
@nitakoi Have you figured out this issue?
Can you provide more info for people facing the very same issue?

Thanks.
