### ISSUE TITLE
Add a conditional or filter which can be checked to process content only for instant articles feed

### ISSUE THREAD

**Issue by goldenapples** [Automattic/facebook-instant-articles-wp#426]
I've been trying to attach some filters to the_content on Instant Articles only. Currently I'm doing this by checking `is_feed( INSTANT_ARTICLES_SLUG )` in my filter function.

However, in order to do this, I've had to disable the Instant Articles Publisher submit_article function, as the condition isn't true then, and short of doing a debug backtrace, there isn't a straightforward way of knowing at that point whether the content filter is being run for an instant article or some other view.

It would be very nice if there was either:
- a separate filter registered, something like `instant_articles_content`, which is processed before `the_content` in `Instant_Articles_Post::get_the_content()`, or
- a conditional function like `is_instant_article()`; which returns true when called from a filter on an instant article and false otherwise. 

Having either one of these in place would enable processing instant article content before transformation, which would be helpful in many circumstances.

**Comment by diegoquinteiro** [comment]
There is now a filter `instant_article_content`. See: https://github.com/Automattic/facebook-instant-articles-wp/blob/master/class-instant-articles-post.php#L349

**Comment by goldenapples** [comment]
Thanks! Unfortunately, that doesn't work for my use cases, as I need something that can either run before 'the_content', or disable some of the normal filters on the_content when in Instant Article context.

Cases in point: 

* I have shortcodes which need to output different markup in Instant Articles than they do in web views. There's currently no way of doing this other than to disable the Instant Article publisher and the meta box on the post, because otherwise there's no way to determine whether the content filter is being run for an instant article or not.

* I want to be able to split the content before wpautop in order to insert ads or related article links at certain points in the content, and these rules and the markup inserted will be different on Facebook than on the web. Currently there's no way to attach a filter to Instant Article content before wpautop, because it's forcibly added before processing the content even if you disable it.

I'll prepare a pull request with the idea I had for this - probably creating an `is_instant_article()` conditional which can be checked and will return true if processing an article for a feed or for the Publisher.
