### ISSUE TITLE
Updated to 3.1.1 and having a Facebook Error

### ISSUE THREAD

**Issue by kellemar** [Automattic/facebook-instant-articles-wp#427]
# Steps required to reproduce the problem

1. Update to new version of Instant Articles 3.1.1
2. Reload the Wordpress Plugin Page
3. Can't re-authorize the plugin to FB since I'm stuck on the error.

# Expected Result
 
* Should display my list of plugins 

# Actual Result

* Shows the Error: " Facebook\Exceptions\FacebookResponseException thrown 
Error validating access token: The session has been invalidated because the user has changed the password."

---

** Version Info **

* Plugin version: 3.1.1
* WordPress version: 4.5.3 
* PHP version: 5.6

**Comment by everton-rosario** [comment]
@kellemar Thanks for flagging. We've seen this is related to https://github.com/facebook/facebook-instant-articles-sdk-php/issues/167.

Can you run `composer update && composer install` within your plugin directory?

This should download the version 1.5.0 of SDK, which is the correct one.

**Comment by everton-rosario** [comment]
@philipjohn will release a new patch fix with this released version of SDK.
