### ISSUE TITLE
All images are getting a <p><a href="www.example.jpg"></a></p> bracket since last update

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#429]
Since yesterday update to the plugin all images are getting a <p></p> bracket within them making them to not being displayed in facebook

Please fix this asap

Example

<p><a href="http://www.example.com/wp-content/uploads/2016/08/Toilet-Humor-2.jpg"></a></p>

The HTML element does not contain any text: Avoid including empty HTML elements

**Comment by everton-rosario** [comment]
@gabu69 Thanks for flagging this.
We are working to have a patch fix for this.

If you can, please run `composer update && composer install` within your plugin directory folder.

Another option is to download the latest version from master, which has the latest fix.

we will wait for @philipjohn to release this fix.

**Comment by gabu69** [comment]
Ahhh thanks

How can I download the latest version from master?

**Comment by everton-rosario** [comment]
To test, make sure you are on latest version of SDK and the WP Plugin.
[Instructions on how to do this setup](https://github.com/Automattic/facebook-instant-articles-wp#development-environment).

**Comment by gabu69** [comment]
What about for the people who cant do this SDK install and just depend on the WP plugin updates?

**Comment by gabu69** [comment]
I can confirm this bug is still in 3.1.2
Is there any fix or custom rules?

**Comment by everton-rosario** [comment]
@gabu69 Can you provide more details? 
Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

**Comment by gabu69** [comment]
Source markup

<p>La idea de &#8220;menos es más&#8221; sólo es cierta para algunas personas, pero aquellos que siguen esta corriente artística pugnan por reducir lo general a lo esencial despojándolo de elementos sobrantes. La idea es construir con el mínimo número de elementos posibles.</p><div class='code-block code-block-5' style=''><div class="full-adsense" style="float:none;text-align:center;margin: 3rem 0;">

<style type="text/css">
.adslot_1 { width: 100%; height: 280px; }
@media (min-width:500px) { .adslot_1 { width: 336px; height: 280px; } }
</style>
<ins class="adsbygoogle adslot_1"
    style="display:inline-block;"
    data-ad-client="ca-pub-1826128735587518"
    data-ad-slot="2408515785"
    data_ad_region = "test"></ins>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

</div>
</div>
<p>Lo interesante <span style="line-height: 1.5">para qu</span><span style="line-height: 1.5">ienes han </span><span style="line-height: 1.5">decidido ad</span><span style="line-height: 1.5">optar esta fil</span><span style="line-height: 1.5">osofía de vida, </span><span style="line-height: 1.5">aunque sea en u</span><span style="line-height: 1.5">n tatuaje, es que han optado por eliminar lo innecesario para ser felices y alcanzar la realización personal. Esta idea la llevan a cada plano de sus vidas, incluso  la decisión de tatuarse una imagen el alguna parte de su cuerpo.</span></p>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388.jpg"><img class="alignnone wp-image-90524 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388-730x253.jpg" alt="Tatuajes" width="730" height="253" srcset="//www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388-730x253.jpg 730w, //www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388-400x139.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388.jpg 1327w" sizes="(max-width: 730px) 100vw, 730px" /></a></p>
<p>Aunque siempre habrá quienes prefieran los tatuajes más grandes, que llamen la atención o que abarquen gran parte del cuerpo, una de las tendencias que esta en boga son precisamente los tatuajes minimalistas, que consiste en elegir sólo un par de palabras, líneas o figuras simples de tamaño pequeño.</p>
<p>Si estás decidida a tatuar una imagen en tu cuerpo pero quieres algo sutil y al mismo tiempo llamativo, esto es lo que estabas buscando; y si aún no te decides, checa estas imágenes que seguramente terminarán por convencerte de la idea.</p>
<h2>1. Avión de papel</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8.jpg"><img class="alignnone wp-image-90521 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8-700x700.jpg" alt="Tatuaje de avión de papel en la espalda. " width="700" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8-700x700.jpg 700w, //www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8-400x400.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8.jpg 1080w" sizes="(max-width: 700px) 100vw, 700px" /></a></p>
<h2>2. Varios elementos, un sólo significado</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4.jpg"><img class="alignnone wp-image-90515 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4-667x700.jpg" alt="Tatuaje del símbolo de infinito, una pluma y la palabra familia. " width="667" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4-667x700.jpg 667w, //www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4-400x420.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4.jpg 915w" sizes="(max-width: 667px) 100vw, 667px" /></a></p>
<h2>3. Flechas</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-ca7e856af8804da0e185d5b3c8dbe5a9.jpg"><img class="alignnone wp-image-90360 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-ca7e856af8804da0e185d5b3c8dbe5a9.jpg" alt="Tatuaje de dos flechas encontradas. " width="515" height="587" srcset="//www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-ca7e856af8804da0e185d5b3c8dbe5a9.jpg 515w, //www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-ca7e856af8804da0e185d5b3c8dbe5a9-400x456.jpg 400w" sizes="(max-width: 515px) 100vw, 515px" /></a></p>
<h2>4. Figuras geométricas</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-2433b481dddcfcc93400888cd48783b7.jpg"><img class="alignnone wp-image-90361 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-2433b481dddcfcc93400888cd48783b7.jpg" alt="Tatuaje de triángulos. " width="564" height="637" srcset="//www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-2433b481dddcfcc93400888cd48783b7.jpg 564w, //www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-2433b481dddcfcc93400888cd48783b7-400x452.jpg 400w" sizes="(max-width: 564px) 100vw, 564px" /></a></p>
<h2>5. Naturaleza</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-74e64e2705a4a8c627708a7860a8a2de.jpg"><img class="alignnone wp-image-90363 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-74e64e2705a4a8c627708a7860a8a2de.jpg" alt="Naturaleza en un tatuaje. " width="564" height="376" srcset="//www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-74e64e2705a4a8c627708a7860a8a2de.jpg 564w, //www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-74e64e2705a4a8c627708a7860a8a2de-400x267.jpg 400w" sizes="(max-width: 564px) 100vw, 564px" /></a></p>
<h2>6. Arco y flecha</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-724f12659fb202259eb315c931db8fb0.jpg"><img class="alignnone wp-image-90366 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-724f12659fb202259eb315c931db8fb0.jpg" alt="Tatuaje de arco y flecha. " width="564" height="564" srcset="//www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-724f12659fb202259eb315c931db8fb0.jpg 564w, //www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-724f12659fb202259eb315c931db8fb0-400x400.jpg 400w" sizes="(max-width: 564px) 100vw, 564px" /></a></p><div class='code-block code-block-7' style=''><div class="full-adsense" style="float:none;text-align:center;margin: 3rem 0;">

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:336px;height:280px"
     data-ad-client="ca-pub-1826128735587518"
     data-ad-slot="9765630588"
     data_ad_region = "test"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>


</div></div>
<h2>7. Para la buena suerte</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-713dc85fe1db2f89ffaf16cd2862e43d.jpg"><img class="alignnone wp-image-90367" src="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-713dc85fe1db2f89ffaf16cd2862e43d.jpg" alt="Tatuaje de tréboles." width="531" height="793" srcset="//www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-713dc85fe1db2f89ffaf16cd2862e43d.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-713dc85fe1db2f89ffaf16cd2862e43d-369x550.jpg 369w" sizes="(max-width: 531px) 100vw, 531px" /></a></p>
<h2>8. Las bendiciones de la vida</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat13-665x665.jpg"><img class="alignnone wp-image-90527 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat13-665x665.jpg" alt="Tatuaje abajo del hombro. " width="665" height="665" srcset="//www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat13-665x665.jpg 665w, //www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat13-665x665-400x400.jpg 400w" sizes="(max-width: 665px) 100vw, 665px" /></a></p>
<h2>9. Una pluma</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playgro...orea2-57adc3bc77749__700.jpg"><img class="alignnone wp-image-90381 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playgro...orea2-57adc3bc77749__700.jpg" alt="Tatuaje de una pluma. " width="700" height="641" srcset="//www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playgro...orea2-57adc3bc77749__700.jpg 700w, //www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playgro...orea2-57adc3bc77749__700-400x366.jpg 400w" sizes="(max-width: 700px) 100vw, 700px" /></a></p>
<h2>10. Una flor</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/tattooblend.com-minimal-marigold-tattoo.jpg"><img class="alignnone wp-image-90382 size-full" src="http://www.okchicas.com/wp-content/uploads/2016/08/tattooblend.com-minimal-marigold-tattoo.jpg" alt="Tatuaje de una flor. " width="635" height="634" srcset="//www.okchicas.com/wp-content/uploads/2016/08/tattooblend.com-minimal-marigold-tattoo.jpg 635w, //www.okchicas.com/wp-content/uploads/2016/08/tattooblend.com-minimal-marigold-tattoo-400x399.jpg 400w" sizes="(max-width: 635px) 100vw, 635px" /></a></p>
<h2>11. Diente de león</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14.jpg"><img class="alignnone wp-image-90383 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14-652x700.jpg" alt="Tatuaje de diente de león. " width="652" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14-652x700.jpg 652w, //www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14-400x430.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14.jpg 700w" sizes="(max-width: 652px) 100vw, 652px" /></a></p>
<h2>12. Bambú</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8.jpg"><img class="alignnone wp-image-90513 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8-662x700.jpg" alt="Tatuaje de bamboo. " width="662" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8-662x700.jpg 662w, //www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8-400x423.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8.jpg 700w" sizes="(max-width: 662px) 100vw, 662px" /></a></p>
<h2>13. Una palabra</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280.jpg"><img class="alignnone wp-image-90514 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280-700x700.jpg" alt="Tatuaje de una palabra. " width="700" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280-700x700.jpg 700w, //www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280-400x400.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280.jpg 1000w" sizes="(max-width: 700px) 100vw, 700px" /></a></p>
<h2>14. Símbolos</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1.jpg"><img class="alignnone wp-image-90517 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1-660x700.jpg" alt="Tatuaje en otro idioma. " width="660" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1-660x700.jpg 660w, //www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1-400x424.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1.jpg 1508w" sizes="(max-width: 660px) 100vw, 660px" /></a></p>
<h2>15. Líneas</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1.jpg"><img class="alignnone wp-image-90519 size-large" src="http://www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1-700x700.jpg" alt="Tatuaje de una línea." width="700" height="700" srcset="//www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1-700x700.jpg 700w, //www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1-400x400.jpg 400w, //www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1.jpg 1000w" sizes="(max-width: 700px) 100vw, 700px" /></a></p>

<div style="font-size:0px;height:0px;line-height:0px;margin:0;padding:0;clear:both"></div>






Transformed markup
<html>
  <head>
    <link rel="canonical" href="http://www.okchicas.com/moda/tatuajes-minimalistas-menos-mas/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.5.0"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="3.1"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.5.0"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://www.okchicas.com/wp-content/uploads/2016/08/tatuajes-minimalistas.jpg"/>
        </figure>
        <h1>15 Ideas originales de tatuajes minimalistas que demuestran que ‘menos es más’</h1>
        <time class="op-published" datetime="2016-08-26T13:16:39-05:00">August 26th, 1:16pm</time>
        <time class="op-modified" datetime="2016-09-02T09:55:50-05:00">September 2nd, 9:55am</time>
        <address><a>Fabiola Gurrola</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=476532999216237_477543569115180&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>La idea de “menos es más” sólo es cierta para algunas personas, pero aquellos que siguen esta corriente artística pugnan por reducir lo general a lo esencial despojándolo de elementos sobrantes. La idea es construir con el mínimo número de elementos posibles.</p>
      <p>Lo interesante para quienes han decidido adoptar esta filosofía de vida, aunque sea en un tatuaje, es que han optado por eliminar lo innecesario para ser felices y alcanzar la realización personal. Esta idea la llevan a cada plano de sus vidas, incluso  la decisión de tatuarse una imagen el alguna parte de su cuerpo.</p>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/46efd607ce81f37fb0903d782f8f9388.jpg"></a>
      </p>
      <p>Aunque siempre habrá quienes prefieran los tatuajes más grandes, que llamen la atención o que abarquen gran parte del cuerpo, una de las tendencias que esta en boga son precisamente los tatuajes minimalistas, que consiste en elegir sólo un par de palabras, líneas o figuras simples de tamaño pequeño.</p>
      <p>Si estás decidida a tatuar una imagen en tu cuerpo pero quieres algo sutil y al mismo tiempo llamativo, esto es lo que estabas buscando; y si aún no te decides, checa estas imágenes que seguramente terminarán por convencerte de la idea.</p>
      <h2>1. Avión de papel</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8.jpg"></a>
      </p>
      <h2>2. Varios elementos, un sólo significado</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4.jpg"></a>
      </p>
      <h2>3. Flechas</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-ca7e856af8804da0e185d5b3c8dbe5a9.jpg"></a>
      </p>
      <h2>4. Figuras geométricas</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-2433b481dddcfcc93400888cd48783b7.jpg"></a>
      </p>
      <h2>5. Naturaleza</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-74e64e2705a4a8c627708a7860a8a2de.jpg"></a>
      </p>
      <h2>6. Arco y flecha</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-724f12659fb202259eb315c931db8fb0.jpg"></a>
      </p>
      <h2>7. Para la buena suerte</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/es.pinterest.com-713dc85fe1db2f89ffaf16cd2862e43d.jpg"></a>
      </p>
      <h2>8. Las bendiciones de la vida</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat13-665x665.jpg"></a>
      </p>
      <h2>9. Una pluma</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playgro...orea2-57adc3bc77749__700.jpg"></a>
      </p>
      <h2>10. Una flor</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/tattooblend.com-minimal-marigold-tattoo.jpg"></a>
      </p>
      <h2>11. Diente de león</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea14.jpg"></a>
      </p>
      <h2>12. Bambú</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/boredpanda.com-minimal-tattoos-playground-tat2-korea8.jpg"></a>
      </p>
      <h2>13. Una palabra</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/65.media_.tumblr.com-tumblr_o1nm97Y4ua1uto4s4o1_1280.jpg"></a>
      </p>
      <h2>14. Símbolos</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-d61f859f-d728-45f3-b953-27053271ec32-1.jpg"></a>
      </p>
      <h2>15. Líneas</h2>
      <p>
        <a href="http://www.okchicas.com/wp-content/uploads/2016/08/41.media_.tumblr.com-tumblr_o1jybp8dsv1tcv6r5o1_1280-1.jpg"></a>
      </p>
      <figure class="op-tracker">
        <iframe>
          <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50556850-6', 'auto');
ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>
        </iframe>
      </figure>
    </article>
  </body>
</html>


And this are the errors in fb instant
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/antidepresivo.net-tat8.jpg"></a></p>
<h2>2. Varios elementos, un sólo significado</h2>
<p><a href="http://www.okchicas.com/wp-content/uploads/2016/08/alienstattoos.com-956eaa16-fc70-4099-90ca-ffc3385c6ab4.jpg"></a></p>



Please let me know cause this is a HUGE bug that doesnt display images

**Comment by fahmi182** [comment]
Any update on this? i think this is important..

**Comment by gabu69** [comment]
this is extremelly important, articles become obsolete for publishers who rely on images

**Comment by mpechjr** [comment]
Any update would be appreciated. Thanks.

**Comment by gabu69** [comment]
Any fix for this?

Instant articles are inusable now since this last update

**Comment by gabu69** [comment]
Im trying to downgrade to 3.0 but i simply get this error:  


Warning: require(/var/www/site.com/public_html/wp-content/plugins/facebook-instant-articles-wp-3.0/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/site.com/public_html/wp-content/plugins/facebook-instant-articles-wp-3.0/facebook-instant-articles.php on line 26

**Comment by fahmi182** [comment]
@gabu69 i think, better remove a href from your image manually then wait dev update this plugin, image works perfectly if you remove a href from your image articles.. :)

**Comment by bactisme** [comment]
So this plugin can break all the articles images during 3 months and no developper care ?

**Comment by bactisme** [comment]
2 month to release a fix that broke all the articles ?

**Comment by gabu69** [comment]
In my case I had to roll back to Version 3.0 👎

**Comment by diegoquinteiro** [comment]
@bactisme @gabu69 is this still happening in 3.2.1 ?

Let me understand if I got this right: are you saying all images are now put inside paragraphs on IA?

**Comment by gabu69** [comment]
@diegoquinteiro  I personally havent tested 3.2.1, but 3.2.0 had the issue still.

Are you changing this till 3.4? I think this is a major bug that should be fixed asap even in the minor updates, ill check tomorrow if its still happening in 3.2.1

**Comment by diegoquinteiro** [comment]
@gabu69 I've put a PR out for this issue; It'll go out with 3.3 today.

**Comment by gabu69** [comment]
Thanks a lot @diegoquinteiro .

When will the 3.3 update be released/available in the wordpress plugin directory?
