### ISSUE TITLE
No rules defined for img class in context of Anchor

### ISSUE THREAD

**Issue by adeparker** [Automattic/facebook-instant-articles-wp#431]
Hi all,

I'm getting the below issue with my articles:

No rules defined for `<img class="alignnone size-full">` in the context of Anchor

HTML codes is below:

`<p><a href="file.jpeg"><img title="wp-1395505014234" class="alignnone size-full" alt="image" src="file.jpeg" /></a></p>`

Can anyone suggest a custom rule please which can overcome this?

Thanks in advance

Ade

**Comment by remino** [comment]
Funny. Just ran into that issue about a few hours ago too.

Here's the custom transform rule I tried:

```
{
  "rules":
  [
    {
      "class": "PassThroughRule",
      "selector": "//a[descendant::img]"
    }
  ]
}
```

Fortunately, you can use not only CSS selectors, but also XPath selectors. What the above is doing is simply making the transformer go through the content of links containing images like if they weren't there, thus only process the images within.

I also need to test this more on my side to be sure. Either way, hope this helps.

**Comment by adeparker** [comment]
Thanks @remino. Solved the problem brilliantly

**Comment by cmunozgar** [comment]
Hi all,

I have the same error but can't figure it out:

I have the following paragraph and i want to the the ImageRule for Instant Articles

<p><a href="http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3.jpg" class="fancybox photoswipe" rel="group" title="LA INTERMINABLE ESPERA"><img class="aligncenter size-full wp-image-91311" src="http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3.jpg" alt="espera3" width="770" height="513" srcset="http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3.jpg 770w, http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3-550x366.jpg 550w, http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3-768x512.jpg 768w, http://www.tendenciasfashionmag.com/wp-content/uploads/2016/09/espera3-610x406.jpg 610w" sizes="(max-width: 770px) 100vw, 770px" /></a></p>

**Comment by remino** [comment]
@cmunozgar 

Have you tried adding the custom transformer rule above in your Instant Articles settings? The settings form should be at `/wp-admin/admin.php?page=instant-articles-wizard` and look like this once you have entered the rule:

![screen shot 2016-09-02 at 20 36 28](https://cloud.githubusercontent.com/assets/29999/18202743/15f917ec-714d-11e6-91ce-9e57af7c0eb3.jpg)

**Comment by cmunozgar** [comment]
Hi @remino,

Yes i did insert that custom rule and still have the same problem.

Here are my custom transformer rules:

`{
    "rules":
    [{
        "class": "TextNodeRule"
    }, {
        "class": "PassThroughRule",
        "selector": "html"
    }, {
        "class": "PassThroughRule",
        "selector": "head"
    }, {
        "class": "PassThroughRule",
        "selector": "body"
    }, {
        "class": "IgnoreRule",
        "selector": "h2 br"
    }, {
        "class": "IgnoreRule",
        "selector": "h3 br"
    }, {
        "class": "PassThroughRule",
        "selector" : "code"
    },{
        "class": "PassThroughRule",
        "selector" : "del"
    },{
        "class": "PassThroughRule",
        "selector" : "mark"
    }, {
        "class": "PassThroughRule",
        "selector" : "span"
    }, {
        "class": "ParagraphRule",
        "selector": "p"
    }, {
        "class": "LineBreakRule",
        "selector": "br"
    }, {
        "class": "PassThroughRule",
        "selector": "//a[descendant::img]"
    }, {
        "class": "AnchorRule",
        "selector": "a",
        "properties": {
            "anchor.href": {
                "type": "string",
                "selector": "a",
                "attribute": "href"
            },
            "anchor.rel": {
                "type": "string",
                "selector": "a",
                "attribute": "rel"
            }
        }
    }, {
        "class": "BoldRule",
        "selector": "b"
    }, {
        "class": "BoldRule",
        "selector": "strong"
    }, {
        "class": "ItalicRule",
        "selector": "i"
    }, {
        "class": "ItalicRule",
        "selector": "em"
    }, {
        "class": "PassThroughRule",
        "selector": "h2 br"
    }, {
        "class": "PassThroughRule",
        "selector": "h3 br"
    }, {
        "class": "BlockquoteRule",
        "selector": "blockquote"
    }, {
        "class": "PassThroughRule",
        "selector": "blockquote h2"
    }, {
        "class": "PassThroughRule",
        "selector": "blockquote h3"
    }, {
        "class": "PassThroughRule",
        "selector": "blockquote p"
    }, {
        "class": "ImageInsideParagraphRule",
        "selector": "img",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            }
        }
    },{
        "class": "ImageRule",
        "selector": "img",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            }
        }
    }, {
        "class": "ListItemRule",
        "selector" : "li"
    }, {
        "class": "ListElementRule",
        "selector" : "ul"
    }, {
        "class": "ListElementRule",
        "selector" : "ol"
    }, {
        "class": "BlockquoteRule",
        "selector" : "blockquote"
    }, {
        "class": "H1Rule",
        "selector" : "h1",
        "properties" : {
            "h1.class" : {
                "type" : "string",
                "selector" : "link",
                "attribute": "class"
            }
        }
    }, {
        "class": "H1Rule",
        "selector" : "title"
    }, {
        "class": "H2Rule",
        "selector" : "h2",
        "properties" : {
            "h2.class" : {
                "type" : "string",
                "selector" : "link",
                "attribute": "class"
            }
        }
    }, {
        "class": "H2Rule",
        "selector" : "h3,h4,h5,h6"
    }, {
        "class": "InteractiveRule",
        "selector" : "iframe",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "iframe"
            }
        }
    }, {
        "class": "InteractiveRule",
        "selector" : "div.embed",
        "properties" : {
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "div.embed"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveRule",
        "selector" : "div.interactive",
        "properties" : {
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "div.interactive"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveRule",
        "selector" : "//div[@class='embed' and iframe]",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            }
        }
    }, {
        "class": "InteractiveRule",
        "selector" : "//div[@class='interactive' and iframe]",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "iframe"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveRule",
        "selector" : "table",
        "properties" : {
            "interactive.iframe" : {
                "type" : "element",
                "selector" : "table"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "table",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveInsideParagraphRule",
        "selector" : "iframe",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    },{
        "class": "InteractiveInsideParagraphRule",
        "selector" : "div.embed",
        "properties" : {
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "div.embed"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveInsideParagraphRule",
        "selector" : "div.interactive",
        "properties" : {
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "div.interactive"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveInsideParagraphRule",
        "selector" : "//div[@class='embed' and iframe]",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            }
        }
    }, {
        "class": "InteractiveInsideParagraphRule",
        "selector" : "//div[@class='interactive' and iframe]",
        "properties" : {
            "interactive.url" : {
                "type" : "string",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.iframe" : {
                "type" : "children",
                "selector" : "iframe",
                "attribute": "src"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "iframe",
                "attribute": "width"
            }
        }
    }, {
        "class": "InteractiveInsideParagraphRule",
        "selector" : "table",
        "properties" : {
            "interactive.iframe" : {
                "type" : "element",
                "selector" : "table"
            },
            "interactive.height" : {
                "type" : "int",
                "selector" : "table",
                "attribute": "height"
            },
            "interactive.width" : {
                "type" : "int",
                "selector" : "table",
                "attribute": "width"
            }
        }
    }, {
        "class": "SlideshowImageRule",
        "selector" : "figure",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            },
            "caption.title" : {
                "type" : "string",
                "selector" : "figcaption"
            }
        }
    }, {
        "class": "SlideshowRule",
        "selector" : "div.gallery"
    }, {
        "class": "CaptionRule",
        "selector" : "figcaption"
    }, {
        "class": "ImageRule",
        "selector" : "figure",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            }
        }
    }, {
        "class": "VideoRule",
        "selector" : "div.wp-video",
        "containsChild": "video",
        "properties" : {
            "video.url" : {
                "type" : "string",
                "selector" : "source",
                "attribute": "src"
            },
            "video.type" : {
                "type" : "string",
                "selector" : "source",
                "attribute": "type"
            }
        }
    }]
}`

**Comment by remino** [comment]
I'm not sure why it isn't working. Although, for clarity, can you edit your comment and wrap multi-code with three backticks (\`\`\`) instead of one (\`)? Should help format the code and make it easier for those who want to lend a hand and may have the answer.

**Comment by cmunozgar** [comment]
Sorry for that @remino. I just edited the comment.

Is there any priority on the rules?

**Comment by remino** [comment]
Much better, thanks.

I'm also new at these so I'm still not sure how the rules work. But from what I can understand from my tests, the priority is a bit like CSS, so `//a[descendant::img]` is more “precise” than just `a` and therefore should take priority, but I'm not sure.

What happens if you swap these rules:

```
    }, {
        "class": "PassThroughRule",
        "selector": "//a[descendant::img]"
    }, {
        "class": "AnchorRule",
        "selector": "a",
        "properties": {
            "anchor.href": {
                "type": "string",
                "selector": "a",
                "attribute": "href"
            },
            "anchor.rel": {
                "type": "string",
                "selector": "a",
                "attribute": "rel"
            }
        }
    }, {
```

into this?

```
    }, {
        "class": "AnchorRule",
        "selector": "a",
        "properties": {
            "anchor.href": {
                "type": "string",
                "selector": "a",
                "attribute": "href"
            },
            "anchor.rel": {
                "type": "string",
                "selector": "a",
                "attribute": "rel"
            }
        }
    }, {
        "class": "PassThroughRule",
        "selector": "//a[descendant::img]"
    }, {
```

**Comment by cmunozgar** [comment]
Brilliant! That did work!

Many thanks @remino!

**Comment by remino** [comment]
Huh. So I guess the priority works differently then I thought.

You're welcome!

**Comment by everton-rosario** [comment]
@remino Thanks for all the help you provided here in this thread :-)

The order of applying rules are:
1. The configuration on settings
2. Any Plugin compatibility
3. Rules in rules.json (default bundle with plugin)

All rules are applied bottom -> up

So firstly the initial rule that tries to be applied is the last one in the settings.


Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by donaldG** [comment]
I know this issue is closed now, forgive me. What I'm experiencing with this rule is that it disregards the anchor wrapping the image. That's not ideally what I'd like to happen. Is that possible within the Instant Articles realm of markup? I'm guessing not since they don't show an example of it here: https://developers.facebook.com/docs/instant-articles/reference/image

**Comment by everton-rosario** [comment]
No image can be wrapped into an anchor tag.
"Clickable image" is not allowed, since click on image works as "Zoom in" operation.

Any link should be a text only, within the Instant Articles.

Is that what you were aiming to, @donaldG ?

**Comment by donaldG** [comment]
Yup! Exactly and I realized you can't do that. So no worries!

**Comment by VagnerAlanis** [comment]
Hello everyone,
I'm getting the problem below with my post articles made not WordPress:

- No rules defined for <hr> in the context of InstantArticle
- No rules defined for <img class = "alignleft wp-image-18"> in the context of Anchor


Here's the link to an example article:
Http://clubedomateoficial.com.br/saiba-a-caring-importance/?preview_id=5514&preview_nonce=f0418cadf5&_thumbnail_id=5515&preview=true


Can anyone suggest a custom rule, please, who can overcome this?

thanks in advance

Vagner Alanis

**Comment by VagnerAlanis** [comment]
Hello everyone,
I'm getting the problem below with my post articles made not WordPress:

- No rules defined for <hr> in the context of InstantArticle
- No rules defined for <img class = "alignleft wp-image-18"> in the context of Anchor

Here's the link to an example article:
Http://clubedomateoficial.com.br/saiba-a-caring-importance/?preview_id=5514&preview_nonce=f0418cadf5&_thumbnail_id=5515&preview=true


Can anyone suggest a custom rule, please, who can overcome this?

thanks in advance

Vagner Alanis

**Comment by VagnerAlanis** [comment]
Hello everyone,
I'm getting the problem below with my post articles made not WordPress:

(  No rules defined for <hr> in the context of InstantArticle )
(  No rules defined for <img class = "alignleft wp-image-18"> in the context of Anchor )


Here's the link to an example article:
Http://clubedomateoficial.com.br/saiba-a-caring-importance/?preview_id=5514&preview_nonce=f0418cadf5&_thumbnail_id=5515&preview=true


Can anyone suggest a custom rule, please, who can overcome this?

thanks in advance

Vagner Alanis

**Comment by VagnerAlanis** [comment]
Hello everyone,
I'm getting the problem below with my post articles made not WordPress:

`No rules defined for <hr> in the context of InstantArticle`

`No rules defined for <img class="alignleft wp-image-18"> in the context of Anchor`


Here's the link to an example article:
Http://clubedomateoficial.com.br/saiba-a-caring-importance/?preview_id=5514&preview_nonce=f0418cadf5&_thumbnail_id=5515&preview=true


Can anyone suggest a custom rule, please, who can overcome this?

thanks in advance

Vagner Alanis

**Comment by markZu** [comment]
No rules defined for <div class="shareaholic-canvas"> in the context of InstantArticle 
??????????????????

**Comment by markZu** [comment]
`No rules defined for <div class="shareaholic-canvas"> in the context of InstantArticle`

????????????

**Comment by ruspandi** [comment]
Please help me?

**Comment by ruspandi** [comment]
Please help me!

No rules defined for <img class="aligncenter snax-figure-content attachment-large size-large"> in the context of Bold
