### ISSUE TITLE
bookmark links "Incorrect URL" answer from server

### ISSUE THREAD

**Issue by mokipedia** [Automattic/facebook-instant-articles-wp#434]
Hello Community,
I have tried to find a related issue but failed.
My Website uses bookmark links for ToC.
Because these are not actual links the server naturally tells me they are faulty.
But how can i pass them?
# Steps required to reproduce the problem
1.  Make Post like:

`<h2>ToC</h2>
<ul>
<li>
   <a href="#1"><strong>Blau, blau, blau blüht das Smartphone</strong></a>
</li>
<li>
</ul>`
and the bookmark itself:
`<h2><a id="1"></a>Blau, blau, blau blüht das Smartphone</h2>`
2. let FB complain about the bad URL
## Any help will be much appreciated!

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6

**Comment by diegoquinteiro** [comment]
That should be fixed in 3.2+, please update and re-open this issue if that still happens. 

Thank you,
Diego
