### ISSUE TITLE
Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by mazilia** [Automattic/facebook-instant-articles-wp#438]
# Steps required to reproduce the problem
1. wp-admin/admin.php?page=instant-articles-wizard
2.  
3. 
# Expected Result
- Page should appear as normal
# Actual Result
- Fatal error: Can't use function return value in write context in /home/_mywebsiteUSER_/public_html/wp-content/plugins/fb-instant-articles/wizard/templates/wizard-template.php on line 101

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6
- PHP version:  5.4.45 

I think the problem is linked to the PHP version , because the page works well with versions less.

![error](https://cloud.githubusercontent.com/assets/20703586/18225499/1f4c8128-71eb-11e6-9fb6-cda067146007.PNG)

**Comment by foo71** [comment]
I am getting the same error.
Wordpress 4.6
Plugin: Version 3.1.2

**Comment by donaldG** [comment]
I have a Pull Request in to fix this: 
https://github.com/Automattic/facebook-instant-articles-wp/pull/433

**Comment by foo71** [comment]
Thanks, problem solved.
