### ISSUE TITLE
how to reset wizard?

### ISSUE THREAD

**Issue by abrahams** [Automattic/facebook-instant-articles-wp#440]
I enter the wrong app details in wizard and now I'm stuck. I tried uninstalling the plugin but it does not work

**Comment by everton-rosario** [comment]
You just need to click on the Edit(pencil) button, on the top most block on the "Instant Articles" admin menu.

1. In the left nav bar, look for the "Instant Articles" item.
2. Click on the pencil on the top most block, right next to your app ID
[https://www.dropbox.com/s/0kvhlisfzbmz35u/reset-config.png?dl=0](url)
