### ISSUE TITLE
Add a Hook where we can disable Instant Articles for a single post

### ISSUE THREAD

**Issue by matrad** [Automattic/facebook-instant-articles-wp#442]
I've ACF Pro Plugin with some custom fields and we'd like to try the instant Articles Feature for some Articles only.

So we need to publish an article Only if a checkbox is checked.

So the best would be if we can add a hook where we are able to stop publishing a post-ID on Instant Articles.

**Comment by diegoquinteiro** [comment]
Fixed by the aforementioned PR.
