### ISSUE TITLE
wpautop() Preventing multiple youtube embeds and slideshows from working

### ISSUE THREAD

**Issue by technosailor** [Automattic/facebook-instant-articles-wp#443]
Question/Sanity Check.

It seems like the use of `wpautop()` for all content is adding elements that prevent YouTube embeds (using `<figure class="op-interactive">` and `<figure class="op-slideshow">`) from rendering because they are wrapped in `<p>` tags. This seems counter to Facebook's guidelines, but I'm not entirely sure if I'm doing it wrong, dangit.

Thoughts?

**Comment by technosailor** [comment]
I was running an older version. Apparently, the Plugin repo version isn't up to date.

At any rate, upgrading to 3.1 fixed most of my issues, but it still seems like slideshow markup is being ignored.

**Comment by everton-rosario** [comment]
Hopefully this situation never happened after this. We were structuring the release process by that time.

Hope you are still using and enjoying this plugin and Instant articles.

Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.
