### ISSUE TITLE
Visual Composer Shortcodes

### ISSUE THREAD

**Issue by Nmidia** [Automattic/facebook-instant-articles-wp#444]
# Steps required to reproduce the problem
1. Create article using Visual Composer
2. Allow to run through to FBIA
# Expected Result
- A beautifully rendered page
# Actual Result
- You will get a screen full of visual composer short codes

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6.1
- PHP version: 

Hi, this is inline with issue 322 (which you have closed but suggested reopening should problems persist).

I use Visual composer(VC) to build my pages in WP, giving great results.  However, they don't work in FBIA.  You suggest changing the hook so that it runs after VC has finished converting the shortcodes, but didn't provide any guidance on how to do this. 

Any help would be most appreciated.
Thanks

**Comment by abrambailey** [comment]
Would also appreciate a fix for this.

**Comment by abrambailey** [comment]
Thanks for adding to milestone @diegoquinteiro

**Comment by aroundiowa** [comment]
Looking forward to this fix. It's the only thing we are waiting on for FBIA. @diegoquinteiro

**Comment by antoineroffler** [comment]
+1 for the fix, even a easy, short and ugly one

**Comment by Nmidia** [comment]
Unfortunately the only solution was to stop using VC for posts to FBIA.  I implemented Instant Articles Filter, which adds a tick box to posts.  From there, any posts that I wanted to send over to FB I wrote in code rather than VC. 

Unfortunately it is a pain as you loss so much flexibility over art placement etc.  

Would love a work around which I assume would sit in the rules section.

**Comment by Jany-M** [comment]
@diegoquinteiro Also discussed [here](https://github.com/Automattic/facebook-instant-articles-wp/issues/322), but.. closed even though no articulated explanation was provided.

**Comment by abrambailey** [comment]
Almost 1 year later. Sad! ;)

**Comment by texas-ranger** [comment]
Hey, this is my actual solve for the problem.

You can do something like this in your theme function.php
`add_filter('instant_articles_content', function(){
	global $post;
	WPBMap::addAllMappedShortcodes();
	$content = apply_filters( 'the_content', $post->post_content );
	return $content;
});`

you shouldn't forget to add custom transformation rules. I am using something like this
`{ 
    "rules": [
        { "class": "IgnoreRule", "selector": "div.grid-sizer" },
        { "class": "PassThroughRule", "selector": "div[class^='wpb']" },
        { "class": "PassThroughRule", "selector": "div[class^='vc']" }
    ] 
}`

**Comment by Jany-M** [comment]
@timjacobi why did you close this? Has this been addressed?

**Comment by timjacobi** [comment]
@Jany-M The issue was filed against an old version of the plugin. Version 4 of the plugin was a major rewrite which fixed a lot of issues. If this issue still exists please let me know and I will reopen.
