### ISSUE TITLE
facebook-instant-articles-wp fails to process shortcodes in posts

### ISSUE THREAD

**Issue by nicopujol** [Automattic/facebook-instant-articles-wp#446]
# Steps required to reproduce the problem
1.  Many sites rely on plugins that use shortcodes like ZipRecipes/Ziplist, which use structured data and place recipe information inside database tables. In the WordPress post editor shortcodes appear as a line of shortcode that appears as [amd-zlrecipe-recipe:#], which displays the recipe data in structured format to the end users. You can activate one of these plugins, create a recipe. When publishing as an Instant Article using the official plugin the entire recipe content is missing.
2.  We tried another plugin, allfacebook, which uses RSS, and the recipe content does show in Instant Articles. However we're not able to do styling using this plugin and Facebook editors decline the content as looking different from canonical mobile pages.
# Expected Result
- facebook-instant-articles-wp needs to process shortcode data like most plugins do and pass on the styling from the associated css.
# Actual Result
- 100% of the recipe content is missing in the current version.

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6.1
- PHP version: I think 5.7

**Comment by abirnie** [comment]
So many WP plugins rely on shortcodes that it seems kind of silly to make a WP-plugin that doesn't address this.

Any plans to fix this?
