### ISSUE TITLE
Facebook video embed not displaying in Instant Article

### ISSUE THREAD

**Issue by arwelch** [Automattic/facebook-instant-articles-wp#448]
I have a Facebook video embedded in my Wordpress post in the two ways below.
1. `<div class="embed"><div class="fb-video" data-href="https://www.facebook.com/video.php?v=10154531068945719" data-width="500" data-allowfullscreen="true"></div></div>`

```
<figure class="op-interactive">
   <div class="fb-post" data-href="https://www.facebook.com/video.php?v=10154531068945719"></div>
</figure>
```

Both are displaying in the post but not in Instant Articles. What do I need to do to have them display in IA?

**Comment by everton-rosario** [comment]
Hey @arwelch sorry for the really long time to answer.

I've tried out your markup, and your formed `op-interactive` are missing the `<iframe>` and `</iframe>` tags.

Check how it should be:
<figure class="op-interactive">
   <iframe>
       <div class="fb-post" data-href="https://www.facebook.com/video.php?v=10154531068945719"></div>
   </iframe>
</figure>


Can you double check why this is missing the `iframe` tags?


Im closing, but feel free to reopen if you still see this happening.

**Comment by selvambe23** [comment]
Hello Everton-rosario,

help needed below is my html markup but it's not working is any rule i should add in plugin settings page ?
<figure class="op-interactive">
  <iframe>
    <div class="fb-video" data-href="https://www.facebook.com/yanting.ong.58/videos/107621956471250/" data-width="500" data-show-text="false"></div>
 </iframe>
</figure>
