### ISSUE TITLE
Problem with embedding a single tweet

### ISSUE THREAD

**Issue by Mironius** [Automattic/facebook-instant-articles-wp#449]
# Steps required to reproduce the problem

This code is added to our pages to embed a simgle tweet:
```
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">Fewer likes, more learning: <a href="https://twitter.com/hashtag/VC?src=hash">#VC</a> funding shifting towards <a href="https://twitter.com/hashtag/AI?src=hash">#AI</a>, away from social media ► <a href="https://blah.com/CKasTR7vDD">https://blah.com/CKasTR7vDD</a></p>
— TechPORTFOLIO (@TechPORTFOLIO) <a href="https://twitter.com/TechPORTFOLIO/status/769631890101899264">August 27, 2016</a>
<script src="//platform.twitter.com/widgets.js" async="" charset="utf-8"></script>
```

Unfortunately the plugin "doesn’t see" the tweet’s actual source so the tweet’s source is not carried over (not present in the final generated IA code). 
# Expected Result

transformed tweet with image and text of an embedded tweet:

```
<blockquote>
Fewer likes, more learning: <a href="https://twitter.com/hashtag/VC?src=hash">#VC</a> funding shifting towards <a href="https://twitter.com/hashtag/AI?src=hash">#AI</a>, away from social media  <a href="https://t.co/CKasTR7vDD">https://t.co/CKasTR7vDD</a>
— TechPORTFOLIO (@TechPORTFOLIO) <a href="http://twitter.com/TechPORTFOLIO/status/769631890101899264">August 27, 2016</a>
 </blockquote>


HERE SHOULD BE THE TWEET'S DATA (IMAGE AND TEXT OF THE TWEET ) 
```

# Actual Result

```
<blockquote>
Fewer likes, more learning: <a href="https://twitter.com/hashtag/VC?src=hash">#VC</a> funding shifting towards <a href="https://twitter.com/hashtag/AI?src=hash">#AI</a>, away from social media  <a href="https://t.co/CKasTR7vDD">https://t.co/CKasTR7vDD</a>
— TechPORTFOLIO (@TechPORTFOLIO) <a href="http://twitter.com/TechPORTFOLIO/status/769631890101899264">August 27, 2016</a>
 </blockquote>

(no tweet data is added)
```

** Version Info **

* Plugin version: 3.1.2
* WordPress version: 4.5.3
* PHP version:

**Comment by Mironius** [comment]
![fb_ia_twitter](https://cloud.githubusercontent.com/assets/9753122/18391036/900e5664-767a-11e6-9bdf-1289dbca7ba0.jpg)
that's how it looks for FB reviewer

**Comment by Mironius** [comment]
OK, guys-  here is the solution:

1) Copy the URL of tweet.

2) Paste the tweet URL on a line in your article/page (as a plain text) Note : A Tweet link must look like a line, it must be Unlinked.

3) Now Publish it, your tweet will get embedded on your article/page. If it doesn't work for you, Just edit the page and Unlink the Tweet URL.

**Comment by everton-rosario** [comment]
@Mironius Awesome you made through this issue.

Your contributions makes Facebook Instant Articles great!
Please join our group @ Facebook: https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.

**Comment by JeremieMT** [comment]
Hello, seems the game changed again, as I try this solution which didn't work. Does anybody now how to succesfully embed a tweet in a Facebook Notes ?
