### ISSUE TITLE
App id wrong, how to fix this

### ISSUE THREAD

**Issue by iranon78** [Automattic/facebook-instant-articles-wp#453]
# Steps required to reproduce the problem
1. install facebook instant article plugin on wordpress 
2. web site is http://www.eventiatmilano.it/
3. select menu INSTANT ARTICLES
4. select wrong app id, by inserting app name instead of app id
5. press login with facebook
6. caught error "Invalid App ID: eventiatmilano"
7. it's impossible to change wrong app id inserted before, even if I uninstall and reinstall plugin
# Expected Result

Be able to install plugin and fix facebook app id
- 
# Actual Result

I can't insert correct fb app id in plugin settings, even if I uninstall and reinstall wordpress plugin
- 

---

*\* Version Info **
- Plugin version: 3.1.2 
- WordPress version: WordPress 4.4.5
- PHP version: 5.3.29

**Comment by davidewarner** [comment]
I have the same issue - need to reset the API number.

**Comment by iranon78** [comment]
Hi,
Thank you, but how Can I reset the API number?
Best
Paolo

**Comment by mrkaqz** [comment]
need help on this issue too

**Comment by everton-rosario** [comment]
@iranon78 @davidewarner @mrkaqz @davidewarner 
To fix this issue:
* Certify you are using the latest version v3.3.3 of the plugin (so far today - Feb 15th 2017)
* Select side menu "Facebook Instant Articles"
* Click on pencil link just like this [printscreen](https://www.dropbox.com/s/e96t5xz1nxsgzc0/Screen%20Shot%202017-02-15%20at%206.54.34%20PM.png?dl=0)
* Enter the correct APP_ID + APP_SECRET
* Proceed til the end of the wizard.


This should fix your issue.
Let me know if this is still happening to you guys.

**Comment by zoomerge** [comment]
It is still not resolved!
