### ISSUE TITLE
Unable to get past 'login with Facebook' step on Pantheon

### ISSUE THREAD

**Issue by tomharrigan** [Automattic/facebook-instant-articles-wp#454]
# Steps required to reproduce the problem

1. Install, activate plugin
2. Connect app with ID and secret
3. Attempt to login to facebook, accept the dialogue messages on facebook
4. Get redirected back to the setup screen, 'login with facebook' button persists, preventing selection of facebook page

# Expected Result

* Move on to next step so a facebook page can be selected

# Actual Result

* Stuck in limbo, unable to select facebook page. When redirected back to the setup screen, the items contained in the URL are: page (instant-articles-wizard), code, and state

---

** Version Info **

* Plugin version: 3.1.2
* WordPress version: 4.5.3
* PHP version: 5.5.24

**Comment by mskogly** [comment]
I have the same issue, described in this thread:

https://wordpress.org/support/topic/pages_manage_instant_articles/#post-8177224

**Comment by tomharrigan** [comment]
It looks like what is happening is that it fails to generate the access token even though the `code` parameter is being passed back properly. I manually generated an access token with a direct GET request, updated the database options and forced it to go to the next screen, at which point it immediately fatals with `Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookSDKException' with message 'Failed to exchange short-lived access token for long-lived access token.'` 
So the core of the problem, at least what I can tell, seems to be that it can't properly set up the access tokens.

**Comment by demoive** [comment]
Hi @tomharrigan. Thanks for reporting this issue and following up with more details. Your second conclusion about the access token exchange seems to be correct and we've been able to reproduce. PR #458 should fix it and we're working to get a patch out before the next official release.

**Comment by demoive** [comment]
@tomharrigan @mskogly Just dropping a note that v3.1.3 is out and available for download. Upgrading the plugin to the latest version should resolve the problem!

**Comment by mskogly** [comment]
Worked like a charm

Morten Skogly
Prosjektutvikling 
Tlf 41545931

**Comment by imrane** [comment]
This problem persists for me. I'm on 3.1.3.

**Comment by demoive** [comment]
@imrane can you confirm for me what the error message being displayed is? I'm asking because I'm wondering if perhaps it's related to a "changed password" for which we've re-opened #456.

**Comment by mskogly** [comment]
I had to try twice. I removed the app permission to my account and tried again.

**Comment by sumair52** [comment]
same issue
