### ISSUE TITLE
Empty page on plugin settings page on wp multisite

### ISSUE THREAD

**Issue by thangarajj** [Automattic/facebook-instant-articles-wp#459]
# Steps required to reproduce the problem
1. Install on multisite wordpress
2. Activate on all site or just an individual site
3. The link to plugin settings or the initial wizard of plugin ( ie. wp-admin/admin.php?page=instant-articles-wizard ) is showing an empty page. The left side nav is fine, but on the right side all I see is "WordPress 4.6.1 is available! Please update now.". Nothing below it.
# Expected Result
- To see a wizard or settings screen of the plugin
# Actual Result
- Page is empty

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.5.4
- PHP version: 5.4.45

**Comment by diegoquinteiro** [comment]
That should be fixed in 3.2+, please update and re-open this issue if that still happens. 

Thank you,
Diego
