### ISSUE TITLE
Need to change the app connection

### ISSUE THREAD

**Issue by alcaporal** [Automattic/facebook-instant-articles-wp#466]
# Steps required to reproduce the problem

1. I need to change the API ID connected before, it's the wrong api id and it's been used for something else.
2. 
3. 

# Expected Result

* 

# Actual Result

* 

---

** Version Info **

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by everton-rosario** [comment]
You were falling into the case from issue of mapping image from buttons.
