### ISSUE TITLE
Nedd to reset all configurations

### ISSUE THREAD

**Issue by mrkaqz** [Automattic/facebook-instant-articles-wp#467]
Hi,

I have issue with blank page on the wizard.
The issue happen when I done the configurations once and i deceided to deleted the app from the developer.facebook.com then wordpress got blank screen everytime in the IA setting page.

I did the remove and re-install plug-in but it won't help.
Can anyone help how to reset the config back to start?

Screen Shot : https://imgur.com/a/dDZEo
# Steps required to reproduce the problem
1. Done wizard once
2. Deleted App on Facebook Developer Page
3. Back to Wordpress Setting
# Expected Result
- New config wizard screen
# Actual Result
- Blank Screen

---

*\* Version Info **
- Plugin version: 
- WordPress version: 
- PHP version:

**Comment by everton-rosario** [comment]
@mrkaqz Is this still reproducible?
Can you check for any stack traces or errors on your web server log?
This error once reproduced into v.3.0 of plugin. 

Please try it out on v3.3.3 and let us know if this is still reproducible.

Closing, but feel free to reopen with further info.
Thanks for using Instant Articles and our plugin.
