### ISSUE TITLE
Adding to "Page" Post Types

### ISSUE THREAD

**Issue by jasonblackdog** [Automattic/facebook-instant-articles-wp#472]
Hello,
I hope I'm not causing too much trouble re-posting my comments from a closed topic but... We are trying to add the plugin functionality and admin metabox to our 'page' post types. We've tried adding this filter to our functions.php file but the metabox still does not display on our 'page' post types. Is there something we're doing wrong?

```php
add_filter( 'instant_articles_post_types', 'add_post_types', 10,1 ); 
function add_post_types($post_type_array){ 
    $post_type_array = array(); 
    array_push($post_type_array,'post'); 
    array_push($post_type_array,'page'); 
    return $post_type_array; 
}
```

Your help with this is greatly appreciated! Thank you! Referenced from closed topic - #411

**Comment by everton-rosario** [comment]
@jasonblackdog This apply filter you will find into `class-instant-articles-publisher.php`. Between lines 52 and 56 (current master version - 3.3.3).

```
		// Only process posts
		$post_types = apply_filters( 'instant_articles_post_types', array( 'post' ) );
		if ( ! in_array( $post->post_type, $post_types ) ) {
			return;
		}
```


To your code, I guess something like this should be enough:
```
  add_filter( 'instant_articles_post_types', 'add_post_types', 10,1 ); 
  function add_post_types($post_type_array){ 
    array_push($post_type_array,'page'); 
    return $post_type_array; 
  }
```


Feel free to reopen if this doesn't work for you.
