### ISSUE TITLE
Login redirects to login screen.

### ISSUE THREAD

**Issue by j** [Automattic/facebook-instant-articles-wp#477]
Things to note about this issue.  We currently are using PageFrog's instant articles and were wanting to try this plugin.
# Steps required to reproduce the problem
1. Install Plugin
2. Follow exact steps to create a page
3. Input key and secret and login.
# Expected Result
- To be able to edit instant article settings.
# Actual Result
- Get redirected back to the plugin page with this screen.  Clicking advanced shows a never ending loader screen.

![screenshot 2016-09-22 10 48 51](https://cloud.githubusercontent.com/assets/589410/18759631/30248542-80b2-11e6-9ecb-dc2e3107ce94.jpg)

---

*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.4.5
- PHP version: 5.5.30

**Comment by t-mori202** [comment]
I have same problem

**Comment by Aidanwang0309** [comment]
same problem here :(

**Comment by eugenioestrada** [comment]
Same here

**Comment by yumyo** [comment]
same here. Any update/workaround?

**Comment by thejavangumalli** [comment]
Same here. Any update on this?
