### ISSUE TITLE
Remove posts from FBIA publishing

### ISSUE THREAD

**Issue by cmjaimet** [Automattic/facebook-instant-articles-wp#478]
# Steps required to reproduce the problem
1. Publish a regular post that you do not want to have transformed into an Instant Article.
2. 
3. 
# Expected Result
- Post does not get sent to Facebook
# Actual Result
- Post does get sent to Facebook

---

*\* Version Info **
- Plugin version: 1.3
- WordPress version: 4.6.1
- PHP version: 5.x

https://github.com/Automattic/facebook-instant-articles-wp/blob/master/class-instant-articles-publisher.php#L38

Early in this method we would like to insert code like this:

```
// Don't process if custom code sets a blocker
$allow_publish = true;
$allow_publish = apply_filters( 'fbia_allow_publish', $allow_publish, $post_id );
if ( false === $allow_publish ) {
  return;
}
```

This way we can filter out posts that we do not want to make into Instant Articles based on our own requirements.

**Comment by mjangda** [comment]
This is covered in #504
