### ISSUE TITLE
Missing Rule for Images inside Anchor

### ISSUE THREAD

**Issue by LtCmdrKeene** [Automattic/facebook-instant-articles-wp#479]
# Steps required to reproduce the problem
1. Create WordPress post and include at least one picture that links to the media file (to the image itself)
2. Publish
3. Facebook Instant Articles fails with error "No rules defined for <img class="aligncenter size-full wp-image-4190"> in the context of Anchor"
# Expected Result
- Facebook converts image as it would for any other image.
# Actual Result
- Facebook Instant Articles fails with error "No rules defined for <img class="aligncenter size-full wp-image-4190"> in the context of Anchor"

**Comment by fahmi182** [comment]
You can resolved manually remove anchor image, this issue now on milestone 3.2 https://github.com/Automattic/facebook-instant-articles-wp/milestone/6

**Comment by gessgallardo** [comment]
So,  is there no way to add an anchor image in Instant Articles ?

**Comment by diegoquinteiro** [comment]
@gessgallardo Instant Articles currently do not support images in anchors.
