### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Vinodkumarsetty** [Automattic/facebook-instant-articles-wp#482]
# Steps required to reproduce the problem

1. 
![error](https://cloud.githubusercontent.com/assets/19258541/18908593/d38b3b38-858d-11e6-8211-5880652fff83.png)

2. can you help in this error asap

3. email id vinuvinod94@gmail.com

# Expected Result

* 

# Actual Result

* 

---

** Version Info **

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by demoive** [comment]
@Vinodkumarsetty, it appears you installed the plugin by downloading the zip file from the GitHub repo (the directory name in the path of the error ends in `-master`). Can I ask if you've followed the [installation instructions in the README](https://github.com/Automattic/facebook-instant-articles-wp#installation)?

Running `composter install` within the folder should do the trick. If not, let me know and we'll investigate further.
