### ISSUE TITLE
Change order of operation for FBIA publishing

### ISSUE THREAD

**Issue by cmjaimet** [Automattic/facebook-instant-articles-wp#487]
# Steps required to reproduce the problem
1. Add custom meta data to a post that is saved via the save_post action with priority 10 or greater.
2. Publish the post.
# Expected Result
- The correct meta data is included in the Instant Article body content
# Actual Result
- Because the data is saved after the post is processed and sent to Facebook, it is not available to be included when the post is sent. 

We would like the FBIA export to execute later in the save process to ensure that all meta data is available and up to date on send.

```
public static function init() {
  add_action( 'save_post', array( 'Instant_Articles_Publisher', 'submit_article' ), 999, 2 );
}
```

---

*\* Version Info **
- Plugin version: 1.3
- WordPress version: 4.6.1
- PHP version: 5.x

**Comment by pdewouters** [comment]
Seems like I'm experiencing this issue too. Is a fix coming?

**Comment by diegoquinteiro** [comment]
Thanks a lot for reporting, @cmjaimet 

It seems like you have the fix, would you fancy creating a PR for it? We can review/merge it =)

Thank you,
Diego

**Comment by cmjaimet** [comment]
Done.
https://github.com/Automattic/facebook-instant-articles-wp/pull/578
