### ISSUE TITLE
No rules defined for <div class="sharethefacts"> in the context of InstantArticle

### ISSUE THREAD

**Issue by codalpayalshah** [Automattic/facebook-instant-articles-wp#488]
# Steps required to reproduce the problem
1. http://rebootillinois.com/2016/07/26/fact-check-rep-gutierrez-people-crossing/
2. see on midd of page
3. you got share the fact i want to make custom rule for this

**Comment by donaldG** [comment]
Take a look at the documentation here:
https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules

You'll probably need something like:

```{
    "rules":
    [
        {
            "class": "TextNodeRule",
            "selector" : "div.sharethefacts"
        },
    ]
}```

I make no promises that is actually what you need. Please refer to the documentation to see what you actually need in terms of what type of content needs to be rendered
