### ISSUE TITLE
Page selection only returns 25 results without pagination options

### ISSUE THREAD

**Issue by tgemus-rci** [Automattic/facebook-instant-articles-wp#492]
# Expected Result
- Pagination for users pages or list all of them rather than 25
# Actual Result
- Lists 25 max pages without pagination option

---

*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.6.1
- PHP version: 5.6

**Comment by dcarrero** [comment]
anyone can solve this problem? Thanks.

**Comment by tudorached** [comment]
To solve this problem go to:
`wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Client/Helper.php`

and add _&limit=999_ at the line 92

`        // connected to this user
        try {
            $response = $this->facebook->get('/me/accounts?fields=name,id,access_token,supports_instant_articles,picture&limit=999');
`

**Comment by jeremyclarke** [comment]
Just bumped into this. 

Can we change the default? 

Anyone who has more than 25 pages will want to see them all so they can pick the one they need. If pagination can't be added quickly enough I vote you set the default super high and wait for that to cause actual problems. 

As-is this breaks the plugin for us. My coworker needs to set up our dozens of pages on our dozens of sites, he will get confounded the majority of the time by this bug.

**Comment by jeremyclarke** [comment]
Okay. Looked through this with my colleague and here are our conclusions:

* It's not in this plugin per se, but in the SDK from Facebook, meaning you may be unwilling to edit this line on your end. 
* If so someone has to either get them to change it on their end, or add full pagination to this plugin. 

For right now, this is a pretty terrible bug if you have more than 25 pages. Not only is there no way to solve the problem without editing code, but the code in question is the worst kind to edit if you rely on the edit persisting.

**Comment by tgemus-rci** [comment]
I've been working on a patch that will add pagination to this plugin, got a little sidetracked.

I had to first add pagination support to the Facebook Instant Articles SDK, which they accepted here - https://github.com/facebook/facebook-instant-articles-sdk-php/pull/178

I'll try getting the PR up over the weekend for pagination. Might need a refresh as I created the initial one over a month ago.

Cheers!

**Comment by jeremyclarke** [comment]
Awesome! Thanks for putting the time in and doing all the steps to get the SDK working.

**Comment by ExileStudios** [comment]
I have just put in a pull request for a temporary fix for this issue. Hopefully we can get pagination eventually, but my fix will allow loading up to 250 pages for now.

**Comment by jeremyclarke** [comment]
Can we please get a fix for this integrated? I understand it may feel low priority for those with less than 25 pages in their Facebook inventory, but it's devastating for those with more. 

Get in touch with Facebook or work out a forking logic on your side, this shouldn't be something users have to edit each time the plugin is updated :(

**Comment by jeremyclarke** [comment]
Or wait, maybe this patch is obviated by the new "Page ID" workflow? In which case the whole system is irrelevant and this ticket can be closed?
