### ISSUE TITLE
Source Markup Empty

### ISSUE THREAD

**Issue by donaldG** [Automattic/facebook-instant-articles-wp#494]
I'm not struggling with anything specific like transformer rules or shortcodes or anything like that but occasionally, just out of nowhere, the post won't have any Source Markup. I'm not entirely sure how/why that could happen? Once it imports to FB then we have a notice (of course) flagging the post b/c the content is empty. I've updated the post, tried changing some content, etc. I tried it out on our staging server and it seemed to work fine w/ no issues whatsoever. Anyone else experienced anything like this?
# Steps required to reproduce the problem
1. Not sure, haha.
2. Write a post, sometimes it just doesn't transform and the Source Markup is Empty
3. 
# Expected Result
- Source Markup shouldn't be empty.
# Actual Result
- Source Markup is empty

---

*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.6.1
- PHP version:

**Comment by donaldG** [comment]
I did discover another of our posts doing this and the cause was a nasty base64 encoded iframe parameter. However, I still can't recreate the issue on the post that originally caused me to post this. I should note: the per post debugger doesn't mention anything if the source markup is empty. Might be a rad idea to throw in a notice/warning about the source markup being empty.

**Comment by diegoquinteiro** [comment]
If nothing is shown on the left side of the debugger, can you copy/paste the source code (from the post editor, HTML tab) so we can try to reproduce?

**Comment by donaldG** [comment]
Here's a solid example of a post that's not transforming at all (where it says #private-url I've just changed out the regular URL that's normally there to share this content, so please note):

    The Environmental Protection Agency (EPA) is working on adding another tool <a href="#private-url">to its growing toolbox</a> for reducing the number of animals used in cruel, painful pesticide tests. It just announced the launch of a pilot program that asks pesticide companies to submit data from past animal-toxicity studies along with calculations from an equation that predicts a product's overall toxicity.

    The equation adds together the toxicities of the individual ingredients in pesticide formulations to reach a total hazard rating for the product. Currently, the EPA requires that any new pesticide formulation be tested on animals, even though toxicities for the individual ingredients are likely already known.

    <a href="#private-url"><img class="aligncenter size-large wp-image-606363" src="private-url.jpg" alt="" width="602" height="401" /></a>

    The agency says it will use submissions under the pilot program to evaluate how well the equation method works as an alternative to the oral and inhalation toxicity experiments on animals that are currently required.

    Since the EPA receives 200 to 300 applications for new pesticide formulas every year, using the equation could save 5,000 or more animals each year from excruciatingly painful and deadly tests.

    This newest initiative is <a href="#private-url">the latest in a series of efforts to reduce the numbers of animals used in pesticide testing.</a>



I've also got a custom transformer rule to handle the `<a><img>`:
{
	"class": "PassThroughRule",
	"selector": "//a[descendant::img]"
}

So as you can see, there's no unique markup, tags, embeds, etc. but for some reason the box on the left is empty and I don't have any warnings/notices about the markup.

**Comment by donaldG** [comment]
Errr, this is happening to me again and I can't find any rhyme or reason for this...anyone else?

**Comment by donaldG** [comment]
Well, looks like it's specific to my media credit plugin. I'll close this!
