### ISSUE TITLE
Add plugin version to assets for cache invalidation

### ISSUE THREAD

**Issue by apollosk** [Automattic/facebook-instant-articles-wp#499]
# Steps required to reproduce the problem
1. Login to WordPress Dashboard
2. Go to 'Instant Articles' from the right sidebar
3. Click on the link 'Open Advanced Settings now'
# Expected Result
- Advanced Settings should open
# Actual Result
- Nothing happens, except 'Close Advanced Settings' link disappears. Nothing is shown below.

---

*\* Version Info **
- Plugin version: 3.2
- WordPress version: 4.6.1
- PHP version: 7.0.11

**Comment by demoive** [comment]
@apollosk Thanks for reporting this from the [issue in WordPress forum](https://wordpress.org/support/topic/advance-option-is-not-working-after-update/).

I'm unable to reproduce. Can you try refreshing your cache or doing a hard refresh (Cmd+Shift+R). I'm wondering if the updated styles in the CSS file is cached on your browser.

If that doesn't work, can you attach a screenshot of before and after clicking the link?

**Comment by apollosk** [comment]
Thanks for the tip! Clearing both browser and Cloudflare cache did the trick.

**Comment by demoive** [comment]
Thanks. I'm reopening because this is something we can try to avoid in the future. I will update the title of the issue accordingly.

**Comment by demoive** [comment]
Use the plugin version for the `$ver` param in the [`wp_enqueue_style()`](https://developer.wordpress.org/reference/functions/wp_enqueue_style/) and [`wp_enqueue_script()`](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) functions for cache invalidation on every new plugin release.

**Comment by demoive** [comment]
Note, the [`IA_PLUGIN_VERSION`](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L64) constant should contain the [canonical version number](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L7) as well. It is only used to define [`op:generator:application:version`](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/class-instant-articles-post.php#L677) (which is currently out of date).

**Comment by ArtimisK** [comment]
I am having the same problem. The advanced settings is not showing up even after I did a hard refresh ctrl shift f5

**Comment by apollosk** [comment]
Try clearing your browser and CDN (if any) cache.

**Comment by ArtimisK** [comment]
Yes I tried that now when i try to put ad code it shows this error _Invalid HTML markup provided for ad custom embed code_

**Comment by apollosk** [comment]
@ArtimisK, please check you ad code for any invalid HTML markup and then create another issue if the problem persists, as I believe it's unrelated with the one reported here.

**Comment by everton-rosario** [comment]
@apollosk @ArtimisK The PR is up.

Hope you guys can help test and review the PR #622
