### ISSUE TITLE
Include other post types

### ISSUE THREAD

**Issue by bjornjohansen** [Automattic/facebook-instant-articles-wp#50]
Should we add a filter to our query in our current `pre_get_posts` filter ([here](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L135)) to add the possibility to filter what post types we put in the feed?

And while we’re at it: What post types should we include by default? Wouldn’t it make sense to include all public post types?

**Comment by Infini7y** [comment]
+1 on this question

**Comment by mjangda** [comment]
I'd suggest defaulting to post-only and requiring any other post types to register support using `add_post_type_support`. Only downside there is that there's no easy way to get a list of post types with one particular `supports` value so maybe a new filter is better.

**Comment by philipjohn** [comment]
Yep, filter sounds like a good route. I've done that in #305 - review needed please :)
