### ISSUE TITLE
 Uncaught exception 'InvalidArgumentException' error

### ISSUE THREAD

**Issue by anebi** [Automattic/facebook-instant-articles-wp#500]
[error.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/525053/error.txt)
# Steps required to reproduce the problem
1. Activate the plugin and publish a new post
# Expected Result

No errors and blank pages, posts publishing without errors
# Actual Result
## Errors and blank pages during new posts publishing processs

*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.6.1
- PHP version: 5.5.9

**Comment by everton-rosario** [comment]
This is fixed already. Thanks for posting it @anebi
