### ISSUE TITLE
Fatal errors on saving post with no "post_content"

### ISSUE THREAD

**Issue by TinkerWorkshop** [Automattic/facebook-instant-articles-wp#502]
# Steps required to reproduce the problem
1. In Admin panel - Create/Edit post
2. Leave/Delete all of the content in "post_content" WYSIWYG block empty
3. Click save/publish button
# Expected Result
- Save the post with proper content
# Actual Result
- Fatal errors
- Warning: DOMDocument::loadHTML(): Empty string supplied as input in XYZ/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php on line 178
- Warning: Cannot modify header information - headers already sent by (output started at XYZ/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php:178) in XYZ/wp-admin/post.php on line 197
- Warning: Cannot modify header information - headers already sent by (output started at XYZ/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php:178) in XYZ/wp-includes/pluggable.php on line 1174

---

*\* Version Info **
- Plugin version: Version 3.2
- WordPress version: 4.6.1
- PHP version: PHP 5.3.28

**Comment by amjad-eremnews** [comment]
I am also facing the same issue!

**Comment by eremnews** [comment]
I am also facing the same issue.

**Comment by jeremyclarke** [comment]
FWIW this issue can also be triggered by other errors. If $this->get_the_content() returns an empty string. 

I am having an issue with one of our filters on instant_articles_content and it results in empty content. Having these warnings show was a big distraction from the real problem, which the plugin would have warned me about anyway. 

Please fix this unnecessary notice. Clearly there are multiple instances where the content might be empty for both valid and bug-driven reasons.

**Comment by timjacobi** [comment]
Closing as this is a bug in the old version which should be fixed in the latest release.
