### ISSUE TITLE
Ability to disable API publishing/feed publishing via filter

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/facebook-instant-articles-wp#503]
Currently there's no way to arbitrarily disable post submission to Instant Articles either via API or feeds. This is a pretty serious flaw in workflow, people definitely want the ability to have control over that. The first step would be to add a filter hook so that theme/plugin developers could build on top of that. 

Proposed solution is to add `instant_articles_should_submit_post` filter that defaults to `true` (PR incoming).

See #442 #275 #186

**Comment by demoive** [comment]
Thanks for the PR, @rinatkhaziev! This feature request is being tracked in #186. I'll keep your PR attached to that issue for reference.
