### ISSUE TITLE
New Instant Article Update Error - Plugin page not loading + content images not showing

### ISSUE THREAD

**Issue by jaez09** [Automattic/facebook-instant-articles-wp#507]
# Steps required to reproduce the problem
1. I updated to the latest version of instant articles
2. after updating the wordpress plugin page for instant articles & page for installed plugins is not being shown.
   ![image](https://cloud.githubusercontent.com/assets/22997223/19619082/7fa7042e-987b-11e6-8072-1332390d41d5.png)
3. when clicked on the link created after, the images are not loading
   ![14800691_732693006870257_1978146660_n](https://cloud.githubusercontent.com/assets/22997223/19619088/9f063c72-987b-11e6-94ae-fe93b094429a.jpg)
# Expected Result
- need to load plugin page & properly show the images in the content
# Actual Result
- 

---

*\* Version Info **
- Plugin version: 3.2
- WordPress version: 4.5.2
- PHP version: 5.5.9

**Comment by jorenvh** [comment]
Any update on this? I'm having the same issue. 

Side note: I even completely removed the plugin, redownloaded the latest version but after activation I'm still having this issue.
