### ISSUE TITLE
Cant activate plugin 

### ISSUE THREAD

**Issue by hrostek** [Automattic/facebook-instant-articles-wp#508]
# Steps required to reproduce the problem

1. Tried to install the plugin to my Wordpress site
2. Can't activate the plugin:- 
"Plugin could not be activated because it triggered a fatal error."
3. Getting the following error:-
"Warning: require(/home/mobilea1/public_html/thisbusinessopportunity.com/wp-content/plugins/facebook-instant-articles-wp-3.2/vendor/autoload.php): failed to open stream: No such file or directory in /home/mobilea1/public_html/thisbusinessopportunity.com/wp-content/plugins/facebook-instant-articles-wp-3.2/facebook-instant-articles.php on line 26"

# Expected Result

* Can't activate the plugin 

# Actual Result

* nothing because plugin is not activated

** Version Info **

* Plugin version:  Version 3.2
* WordPress version:  WordPress 4.2.2
* PHP version: native (5.6)

**Comment by kevin25** [comment]
I can't activate too.

**Comment by kevin25** [comment]
i figured it out. You should install composer, on the plugin root directory, type composer install or (./composer.phar install)

**Comment by hrostek** [comment]
Hi Keven how can I install composer?

**Comment by everton-rosario** [comment]
@hrostek @kevin25 Wasn't the autoload.php in the installation package by default?
You guys shouldn't need to install the composer. 
Of course installing it and running the `composer install` will fix it.

To install composer, follow [these instructions](https://getcomposer.org/download/)

**Comment by everton-rosario** [comment]
How or where have you guys downloaded the plugin from?
Was from the wordpress.org? (https://wordpress.org/plugins/fb-instant-articles/)
I've double checked it and it have all the needed files for successful activation.

**Comment by everton-rosario** [comment]
@hrostek Do you have more info on your Wordpress log file? Can you try installing the plugin in a new WordPress installation just to double check if the error persists?

Im closing this for now, until you get more info so I can help investigate more and feel free to reopen once you have more info.

Thanks for using IA!

**Comment by kevin25** [comment]
@everton-rosario There is no autoload.php i think. After composing it, i can activate without issue.

**Comment by everton-rosario** [comment]
@kevin25 where have you downloaded the package?
