### ISSUE TITLE
New version 3.2 not working in Arabic websites

### ISSUE THREAD

**Issue by mazilia** [Automattic/facebook-instant-articles-wp#509]
# Steps required to reproduce the problem
1. Posted a new article
2. 
3. 
# Expected Result
- Published successfully to Instant Articles
# Actual Result
-  This post was not yet submitted to Instant Articles.

---

*\* Version Info **
- Plugin version: 3.2
- WordPress version: 4.6.1
- PHP version: 5.4.45

**It was normally working in the previous version**

![capture](https://cloud.githubusercontent.com/assets/20703586/19721056/94129500-9b68-11e6-8d73-122490edbff7.PNG)

and 

Settings do not appear

Stages involved => 

**1.**
![capture2](https://cloud.githubusercontent.com/assets/20703586/19721308/a130f8a2-9b69-11e6-984a-c020b36f333b.PNG)

**2.**
![capture3](https://cloud.githubusercontent.com/assets/20703586/19721312/a4d5dc84-9b69-11e6-97cb-bba34af60d09.PNG)

**Comment by diegoquinteiro** [comment]
Your article contain a warning for having a div we do not understand automatically. You need to provide a custom rule for this div: https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules

What browser are you using? It looks like JS is broken on the admin page. Can you also share if you have any JS errors?

Thank you,
Diego

**Comment by timjacobi** [comment]
Closing as this hasn't been responded to in too long.
