### ISSUE TITLE
Iframes/Embeds still have paragraph tags around them

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#51]
I am receiving several errors in the FBIA validator due to paragraph tags being around the embeds. Can it be setup to remove those tags around iframes/embeds?

Below is an example of what Facebook does not like:

`<p><figure class="op-interactive"><iframe src="http://cache.vevo.com/assets/html/embed.html?video=12345678&amp;autoplay=0" width="500" height="281.25" frameborder="0" allowfullscreen="allowfullscreen"></iframe></figure></p>`

**Comment by bjornjohansen** [comment]
That output doesn’t seem to come from this plugin. The only case where we are using the `interactive` element is for tables. What does your source HTML look like?

**Comment by kkranzo** [comment]
Ah, gotcha.

Yeah, that is the case. Facebook was just pulling in an old cached version of the article.
