### ISSUE TITLE
Submit for review should send only posts that are published and valid

### ISSUE THREAD

**Issue by jeremyclarke** [Automattic/facebook-instant-articles-wp#511]
Haven't gotten to this point myself with the new version, but the bug exists based on this WP forum post. 

https://wordpress.org/support/topic/plugin-is-trying-to-submit-drafts-as-part-of-recent-5-articles/
# Steps required to reproduce the problem
1. Have drafts as the most recent posts when you are ready to submit for review
2. Try to submit, but the posts are drafts, this is definintely not what you want
# Expected Result
- Only published posts would even be considered for submission. 

The report on WP forums had an easy fix which was adding 'post_status' => 'publish' to the WP_Query in Instant_Articles_Wizard_Review_Submission::getArticlesForReview()
# RELATED BUG: Only valid posts should be submitted

Additionally, unless the "Publish articles containing warnings" box is checked, it's completely counter-intuitive that the last 5 posts would be submitted if any of them contain warnings. 

It sounds like currently the setting controls whether posts will be submitted when they contain errors, which makes sense on an ongoing basis. When I'm writing a post I can decide if I want to fix the error (likely removing custom content) or live with the fact that it will never be an IA because this plugin won't submit invalid posts. 

But during the initial submit for review, this is ignored, and whatever posts are recent get submitted. This is really confusing and breaks trust in the setting overall. It's also a huge pain once you figure it out, because you need to line up 5 valid posts before you can submit, which might involve removing custom content from posts where that content is important. 

This second bug was acknowledged by a developer in this WP Forum thread, but I didn't find a ticket for it on GH: https://wordpress.org/support/topic/publish-articles-containing-warnings-setting-doesnt-work/

---

*\* Version Info **

Not sure about version info but looking at the PHP it's absolutely obvious that drafts would be fetched so I doubt versions are relevant.

**Comment by diegoquinteiro** [comment]
Thanks a lot for bringing that up! I'll definitely investigate the first bug.

The second one shouldn't happen in 3.2+ as the "Submit for Review" flow now asks you to fix all warnings of the articles before submitting for review.

**Comment by jeremyclarke** [comment]
Diego, the reason the second part is important is that our site will never naturally have 5 most recent posts all valid. We have too much custom HTML that cannot be handled by the transformations systems (e.g. a div with a heading inside). 

To make our initial submission work we will have to manually remove content from posts before submitting. This is really counter-intuitive and doesn't match the setting that allows invalid posts to be ignored by IA. The initial submitter should ALSO ignore invalid posts, and send along whatever the most recent 5 valid posts are.

**Comment by jeremyclarke** [comment]
FWIW the first part (just adding post_status=publish) is a real no-brainer, not sure why it didn't make it into the most recent release but getting it into the next one would be really nice so I can stop having to insert my patch for it.

**Comment by jeremyclarke** [comment]
Is this still relevant with the changes to the submission process?

If it is, can we integrate the fix? Lots of versions in between. 

If not, should that wizard file be removed? It's still there with the same terrible flaw.
