### ISSUE TITLE
Force OG Re-scrape on post update

### ISSUE THREAD

**Issue by demoive** [Automattic/facebook-instant-articles-wp#514]
Best practice is to force a re-scrape of the OG tags whenever a post is updated.

https://developers.facebook.com/docs/sharing/opengraph/using-objects#update

**Comment by jamilporta** [comment]
Thank you for including this! I'm not sure if the OG tag scrape is failing due to the plugin or a timeout from facebook when reaching the site. Can you see debugging code from my site or do you need access to review this?

**Comment by demoive** [comment]
@jamilporta I don't think it'd be failing because of the plugin, but admittedly I haven't looked in depth yet.

I'm closing this issue out because it makes more sense to make this update within the SDK itself. Reopened here: https://github.com/facebook/facebook-instant-articles-sdk-php/issues/182
