### ISSUE TITLE
Playbuzz integration with IA

### ISSUE THREAD

**Issue by tombuzz** [Automattic/facebook-instant-articles-wp#515]
PB Content can be embedded in two ways:
1. Code snippet (including Script element, that can reside in the head element and div with class="pb_feed") - Doesn't required pb plugin to be installed
2. Shortcodes - Requires pb plugin to be installed
# Issue 1

When pb plugin isn't installed - pb code snippet transformation is not activated. In most cases the code snippet method of embedding is used on cases pb plugin isn't installed resulting in IA pages not including the pb embedded articles.
# Expected Result

PB transformation should be part of the default transformation rules set and not depending on the pb plugin existence. 
# Steps required to reproduce the issue

Embed a playbuzz code snippet without pb plugin installed

Snippet:

```
<script type="text/javascript" src="//cdn.playbuzz.com/widget/feed.js"></script>
<div class="pb_feed" data-embed-by="7cab61df-eb6a-41ae-bd54-8ab76018c04c" data-game="/thesun18/guess-the-celebrity-behind-the-halloween-costume"></div>

```

Selector should be based ONLY on the div.pb_feed (script should be ignored) and transformed into:

```
      <figure class="op-interactive">
        <iframe class="no-margin">
          <script type="text/javascript" src="//cdn.playbuzz.com/widget/feed.js"></script>
          <div class="pb_feed" data-embed-by="7cab61df-eb6a-41ae-bd54-8ab76018c04c" data-game="/thesun18/guess-the-celebrity-behind-the-halloween-costume"></div>
        </iframe>
      </figure>

```

---
# Issue 2

Playbuzz items being embedded with short codes are not being transformed
# Expected Result

To transform short code the same way the raw code snippet works
# Steps required to reproduce Issue

Install PB plugin.
Embed an item using playbuzz plugin (which uses shortcodes)
Published item doesn't contain pb embedded article

*\* Version Info **
- Plugin version: 3.2
- WordPress version: 4.6.1
- PHP version: 5.5.9-1ubuntu4.20

**Comment by everton-rosario** [comment]
@tombuzz Please double check if this PR fixes the issues you were facing.

**Comment by dashaluna** [comment]
@everton-rosario I've checked I've got the code introduced in the linked PR. However, I'm still seeing `No rules defined for <div class="pb_feed"> in the context of InstantArticle` for:

1. URL embed, ex: `http://www.playbuzz.com/kevincastro10/only-4-of-americans-know-the-abbreviations-of-these-27-us-states`
2. `[embed]` shortcode, ex `[embed]http://www.playbuzz.com/valeriemack10/13-things-that-happen-to-people-who-are-learning-another-language[/embed]`

Also, plugin's shortcode `[playbuzz-item]` is being stripped completely.

**Comment by dashaluna** [comment]
Re about `Issue 2` on this ticket.. digging more into Playbuzz plugin, by default it will process the shortcode only for `is_singular()` pages. Unless the plugins' options are configured to process shortcodes everywhere. Ref code: https://github.com/wp-plugins/playbuzz/blob/master/shortcodes.php#L108

So, with default settings, the Playbuzz plugin doesn't convert `[playbuzz-item]` shortcode into markup, it does nothing. That's why it "stripped" from the content before it gets to FB IA processing.

**Comment by tomercplaybuzz** [comment]
@dashaluna Regarding to issue 2, 
To enable processing of shortcodes on IA transformation context, I've added another condition to process shortcodes on admin sections ( is_singular() || is_admin() ).  Checked it with playbuzz-fix brunch and it works great.

**Comment by everton-rosario** [comment]
@dashaluna the `<div class="pb_feed">` is being treated by the rules below.

Also, can you double check if the SDK being used is the latest one (v.1.5.3 or v.1.5.4)?

```
      {
        "class" : "IgnoreRule",
        "selector": "//p/script[contains(@src,'playbuzz')]"
      }, 
      {
        "class": "InteractiveRule",
        "selector" : "div.pb_feed",
        "properties" : {
          "interactive.iframe" : {
            "type" : "multiple",
            "children": [{
                "type": "fragment",
                "fragment": "<script type='text/javascript' src='//cdn.playbuzz.com/widget/feed.js'></script>"
              }, {
                "type": "element",
                "selector": "div.pb_feed"
              }
            ]
          }
        }
      }
```

Im also considering pushing this diff into this very same PR:

```
		if ( $is_playbuzz_active ) {
			add_filter( 'pre_option_playbuzz', function( $option ) {
				if ( is_feed( 'instant-articles' ) ) {
					$option['embeddedon'] = 'all';
				}
				return $option;
			} );
		}

```

**Comment by tomercplaybuzz** [comment]
For Issue-2, we will release in the next few days a Playbuzz WP plugin version that should take care of this issue (see solution on my last comment in this thread).

Also, I've tested the new changes on the playbuzz-fix brunch and it works well.
I notice the following code, is the following code meant to handle issue-2?

`function init( $is_playbuzz_active ) {
  		add_filter( 'instant_articles_transformer_rules_loaded', array( 'Instant_Articles_Playbuzz', 'transformer_loaded' ) );
 		if ( $is_playbuzz_active ) {
 			add_filter( 'pre_option_playbuzz', function( $option ) {
 				if ( is_feed( 'instant-articles' ) ) {
 					$option['embeddedon'] = 'all';
 				}
 				return $option;
 			} );
 		}
 }`

**Comment by tomercplaybuzz** [comment]
We've just released a new version of our plugin v0.9.5 that includes the fix for issue N2.

**Comment by everton-rosario** [comment]
Thanks @tomercplaybuzz .
We are planning to get this into v3.3 this Thursday Dec 15th.

**Comment by tomercplaybuzz** [comment]
@diegoquinteiro Hi Diego, do you have estimation on when v3.3 will be available on wordrpess.org + wordpress vip?

**Comment by everton-rosario** [comment]
@tomercplaybuzz It is available here: https://wordpress.org/plugins/fb-instant-articles/
