### ISSUE TITLE
Facebook Instant Article For Custom Post Type

### ISSUE THREAD

**Issue by gamingdeval** [Automattic/facebook-instant-articles-wp#516]
# Steps required to reproduce the problem
1.  In Wordpress simple post when we are going to publish article there is option to submit auto article to facebook by api
   But in Custom post type there is no option is desplaying so when we are posting via custom post type its not getting images and Ads in Facebook instant Articles. 
# Expected Result
- there is same option to submit article by API for custom post type Too. 
# Actual Result
- 

---

*\* Version Info **
- Plugin version: 3.2
- WordPress version: 4.6.1
- PHP version: 
  ![add new bollywood hd wallpaper wordpress](https://cloud.githubusercontent.com/assets/7044182/19839436/9f670934-9f07-11e6-9483-0faeb3365082.png)
  ![add new post hd wallpaper wordpress](https://cloud.githubusercontent.com/assets/7044182/19839437/9f71987c-9f07-11e6-90f8-a1486f404ac1.png)

**Comment by diegoquinteiro** [comment]
You should use the `instant_articles_post_types` filter to add your custom types to the plugin.

This should be better documented, so I'm keeping this one opened.

Thank you so much for reporting!

**Comment by jacobarriola** [comment]
@diegoquinteiro would you like me to submit a PR to add this to the documentation along with an example? Looking around, seems like the best place would be in the `README.md` file.

Let me know!

**Comment by chrillep** [comment]
?

**Comment by vkama** [comment]
Closing because this is no longer relevant in the 4.x versions.
