### ISSUE TITLE
Multiple feeds

### ISSUE THREAD

**Issue by dashaluna** [Automattic/facebook-instant-articles-wp#518]
Is it possible to generate multiple feeds per website? For example:

1. A feed per `x` category
2. A feed per `y` category
3. Generic / all posts feed

Each feed will have it's own FB page.

I know it's not possible with current Admin UI, but perhaps there are some hooks in code? If not, could you consider this feature please?

Thank you.

**Comment by diegoquinteiro** [comment]
@dashaluna as of now, you have 1:1 website/page mapping.

This is not of our highest priority right now as it is a fairly complicated corner case. If you have the resources and want to give a shot on implementing it, we'll be happy to review it, though.
