### ISSUE TITLE
Missing Image code in Source Markup

### ISSUE THREAD

**Issue by misterson** [Automattic/facebook-instant-articles-wp#519]
Hello,

I just installed FBIA and it integrated with Facebook well, except one issue.
Image in the content is missing.
Note: HTML code is correct.  Image is shown in regular web browsing.

Kindly Advise. Thank you.

# Steps required to reproduce the problem

1. Create any post, and it shows incorrect markup. 
2. 
3. 

# Expected Result

* Source markup should have img tag.

# Actual Result

* No img tag.  So text in FBIA was shown, but image was missing.
Please see attachment for HTML code, and code show in source markup.

---

** Version Info **

* Plugin version: 3.2
* WordPress version: 4.6.1 
* PHP version: 7
![screenshot 2016-11-01 09 40 35](https://cloud.githubusercontent.com/assets/5237567/19878078/50ab8e3a-a017-11e6-95e9-1797bf30c34f.png)
![screenshot 2016-11-01 09 40 18](https://cloud.githubusercontent.com/assets/5237567/19878077/50ab8fca-a017-11e6-8ae6-d27f0ad9f74c.png)

**Comment by diegoquinteiro** [comment]
Hello @misterson,

Thanks for reporting.

Can you please paste here the full content of the debug information (both sides)?

Thank you,
Diego

**Comment by timjacobi** [comment]
Could you please update to the latest version of the plugin and report if the problem still exists?
