### ISSUE TITLE
Batch update all my Instant articles with a new Analytics Tracker?

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#521]
So I want to add comScore DAX Tag (I already have Google analytics and want to add comScore DAX as well).

Is there any way to batch update old Instant articles which are already in publishing tools as published and just have my Google analytics tag?

**Comment by diegoquinteiro** [comment]
Hi @gabu69,

If you already implemented the tag, just upgrade to v4 and all your existing articles should start being updated after Facebook's scrapper cache expires (in about 7 days).

Let me know if that works for you, otherwise just re-open the issue.
