### ISSUE TITLE
UI ability to turn specify which post should be published as an Instant Article (admin)

### ISSUE THREAD

**Issue by YOzaz** [Automattic/facebook-instant-articles-wp#526]
Hi all,

Following our conversation with @diegoquinteiro on "News on Facebook", we have a request for disabling global rule, where all posts (with or without filters) would be published to Instant Articles feed. WP administrators should be able to have a metabox with a checkbox (e.g.), which would include that post.

As an alternative - opposite checkbox, which would deny from publishing into a feed.

We can't use categories or tags, as they are used for different, general, purposes.

This is required as we want only specific posts to be visible as Instant Articles on Facebook, not all of them.

Advice needed...

**Comment by diegoquinteiro** [comment]
Hi, this feature is now available. See this PR for more details: #504 

You have to use the `instant_articles_should_submit_post` filter.

**Comment by YOzaz** [comment]
@diegoquinteiro thanks! Will test it out soon.
