### ISSUE TITLE
Ability to remove children in InstantArticle class

### ISSUE THREAD

**Issue by dashaluna** [Automattic/facebook-instant-articles-wp#529]
Can we have an ability to remove children in InstantArticle class, please.

There are functions: `addChild()` and `unshiftChild()`. However, there is no way to remove a child element.

Real life example: Make the first image from an article content as a header cover. I'm able to grab the first image element from `InstantArticle` object and set it as a header cover.

However, there is no way to remove that image/element from the `InstantArticle` object as `children` property is private and doesn't have a method to remove a child.

**Comment by diegoquinteiro** [comment]
Hi @dashaluna, please report this issue on the SDK instead, as these classes are provided by the SDK: https://github.com/facebook/facebook-instant-articles-sdk-php
