### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by xvilo** [Automattic/facebook-instant-articles-wp#532]
Hi everyone,

I want translate the plugin to the Dutch languages, I saw that there where already some attempts in the pull requests. But once I started I saw there is *a lot* not translate-able since they are not being echoed by the right `i18n` functions. 

Before I start to change everything, is this a feature that should be added? If so, I would be happy to convert all strings to `i18n` usable stuff and create the necessary POT file and also provide the Dutch nl_NL strings in PO and MO format.

**Comment by diegoquinteiro** [comment]
Hello, @xvilo!

Yes, that would be a great addition to our plugin, and I'll be very happy to review and merge a PR for i18n if you create one =)

Thank you so much for the interest and willingness to help!

**Comment by xvilo** [comment]
Great to hear, i'll try to make a start!
