### ISSUE TITLE
Facebook Authentication Exception

### ISSUE THREAD

**Issue by ProvoDev** [Automattic/facebook-instant-articles-wp#536]
Someone removed an admin on our facebook page and it caused this to happen on the instant articles plugin.  From what I have read, this error shows that the user associated with the plugin doesn't have access to the facebook page anymore.  I tried to uninstall the plugin and reinstall it, but I continue to get this error. I'm guessing that some settings for data persists even after reinstalling the plugin, but I'm not sure where those settings or data is stored. What do I need to do to either completely remove this plugin and data or to just add another user for the plugin?

# Steps required to reproduce the problem

1. Admin was removed from the facebook page who was associated with the plugin.

# Actual Result

Fatal error: Uncaught Facebook\Exceptions\FacebookAuthenticationException: The user must be an administrator of the page in order to impersonate it. in /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:106 Stack trace: #0 /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Faceboo in /var/www/universe-sandbox/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 106

---

**Version Info**

* Plugin version: 3.2
* WordPress version: 
* PHP version: 7

**Comment by hubthomas** [comment]
Same problem for me ! I removed the original Wordpress admin user too !

**Comment by oliworx** [comment]
Same problem for me.
