### ISSUE TITLE
How to get P inside Blockquote?

### ISSUE THREAD

**Issue by eustasskid** [Automattic/facebook-instant-articles-wp#537]
Hi, I have a simple problem. Wordpress automatically put `<p>` inside the `<blockquote>`. And FBIA transforms the blockquote as single paragraph only. Since some of my wordpress posts contains blockquotes that have multiple lines, and it looked messed up when transformed to instant articles. I'm thinking about ignoring the blockquotes and only get the `<p>` inside the blockquotes?

What is the correct transformer rule for this?

My markup.
```
<blockquote>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
</blockquote>
```

I want it to look like this in my instant articles (no blockquotes).
```
<p></p>
<p></p>
<p></p>
<p></p>
```

**Comment by everton-rosario** [comment]
Hey @eustasskid if ```blockquote```'s are just container on your markup, simply add this transformation rule below (PassThroughRule) that will suffice for your case.

Follow this sequence to add this rule configuration: 
1. Click on the InstantArticles menu Item (usually it stays in the left menu bar)
2. It will open the InstantArticles plugin settings page.
3. Scroll down to find the section called: "Publishing Settings"
4. Enable the checkbox "Enable custom transformer rules"
5. Enter the rules within the common code as below:
```
{ "rules": [
   {
        "class": "PassThroughRule",
        "selector" : "blockquote"
    }
]}
```


Let me know if this works for you.

**Comment by eustasskid** [comment]
I just tried it now. It does not work. It omits everything inside the blockquote.

**Comment by errand** [comment]
Hey @everton-rosario,
if i'm not mistaken, this would work
{ "rules": [
   {
        "class": "PassThroughRule",
        "selector" : "blockquote p"
    }
]}

But how can i insted keep the tags inside the blockquote?:)
I'm trying to add
{ "rules": [
   {
        "class": "BlockquoteRule",
        "selector" : "blockquote p"
    }
]}
but the whole blockquote omits

**Comment by everton-rosario** [comment]
What do you mean by keeping the tags inside blockquote, @eustasskid ?
I guess the best structure for this to work well would be the other way around.

```
<p><blockquote>...</blockquote></p>
<p><blockquote>...</blockquote></p>
<p><blockquote>...</blockquote></p>
<p><blockquote>...</blockquote></p>
```

Is it possible for you to use this structure?

I guess you will have an easier life by dealing with this markup structure.

**Comment by errand** [comment]
Wow, @everton-rosario , i didn't think it this way! Yeah it's fine for me!
First i wanted to have makup which @eustasskid  wanted to get rid of: paragraphs inside the  blockquote,
but your variant is even better. I hope this code will work (have no opportunity to check)
```

{ "rules": [
   {
        "class": "BlockquoteRule",
        "selector" : "p blockquote"
    }
]} 
```

**Comment by everton-rosario** [comment]
You won't need this rule specification.
You can just erase this config and the regular rules that are already inside your rules-configuration.json should work. Let me know if it is ok for you.

**Comment by errand** [comment]
Hello again, @everton-rosario and thank you for answering :)
Currently i'm using Drupal module and rules are set here 
https://github.com/BurdaMagazinOrg/module-fb_instant_articles/blob/7.x-2.x/fb_instant_articles.module
You can see only one rule there:
```
    array(
      'class' => 'BlockquoteRule',
      'selector' => 'blockquote',
    ),
```
while my markup is:
```
<p>asdf</p>
<blockquote>
  <p>asdf B</p>
  <p>asdf B</p>
</blockquote>
<p>asdf</p>
```
the output totally removes the blockquote and i get 
```
<p>asdf</p>
<p>asdf</p>
```
but if i add extra rule
```
    array(
      'class' => 'PassThroughRule',
      'selector' => 'blockquote p',
    ),
```
the output is:
```
<p>asdf</p>
<blockquote>
  asdf B
  asdf B
</blockquote>
<p>asdf</p>
```
which is better but not perfect because removes markup inside the blockquote.

**Comment by Kelly27** [comment]
Hi, how can I keep the p tag inside blockquote tag? 
`<blockquote>
  <p>abcd</p>
  <p>abcd</p>
</blockquote>`

**Comment by Kelly27** [comment]
Hi, how can I keep the ```<p>``` tag in ```<blockquote>``` tag?
```
<blockquote>
  <p>abcd</p>
  <p>abcd</p>
</blockquote>
```
