### ISSUE TITLE
How to place an Ad in a specific location in the article.

### ISSUE THREAD

**Issue by pdewouters** [Automattic/facebook-instant-articles-wp#541]
I've set Ads to manual and I'd like to insert a single ad into the content after x number of paragraphs. Any pointers on how to achieve this?

**Comment by pdewouters** [comment]
So the documentation says this will be transformed to an ad
```
<figure class="op-ad">
    <iframe height="300" width="250">
    	  <!-- Include full ad code here -->
    </iframe>
</figure>
```

but I see this warning:
<img width="920" alt="screenshot 2016-11-25 12 12 17" src="https://cloud.githubusercontent.com/assets/30460/20625030/6ea53a36-b308-11e6-8221-a7c7517d70da.png">

**Comment by pdewouters** [comment]
I solved this by hooking into `the_content`

**Comment by nsofts** [comment]
Can you show me the code for IA feed, i want to add taboola widget or MGID in instant article. Thank you!

**Comment by iantbarker** [comment]
@pdewouters Can you give me an example of how to hook into the content for the IA feed only? Thanks.

**Comment by pdewouters** [comment]
use the `instant_articles_content` filter. Unfortunately, we reverted back to automatic ad placement, and I don't have the previous code on hand at the moment

**Comment by iantbarker** [comment]
Ok cool. Will try that. Thanks.
