### ISSUE TITLE
Error after activating the Plugin (vendor/autoload.php)

### ISSUE THREAD

**Issue by sebastianbrinkmann76** [Automattic/facebook-instant-articles-wp#542]
I just downloaded the WP-Plugin and uploaded it to my blog (www.journalisten-tools.de). Then trying to activate the Plugin I got the following error message:

wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /homepages/43/d612702806/htdocs/journalisten-tools.de/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 26

This file doesn't exist on GitHub.

**Comment by diegoquinteiro** [comment]
Thank you for reporting. This should be fixed in the 3.2.2 version I just released. Let me know otherwise =)
