### ISSUE TITLE
article publish time missing

### ISSUE THREAD

**Issue by pdewouters** [Automattic/facebook-instant-articles-wp#544]
# Steps required to reproduce the problem

1. publish article to FB
2. open article in FB Pages app

# Expected Result

* see article date and time

# Actual Result

* only date is displayed

---

The RSS feed has this markup:

```
<time class="op-published" datetime="2016-11-28T15:45:36+00:00">November 28th, 3:45pm</time><time class="op-modified" datetime="2016-11-28T15:45:36+00:00">November 28th, 3:45pm</time>
```

**Version Info**

* Plugin version: 3.2.1
* WordPress version: 4.6.1
* PHP version:

**Comment by diegoquinteiro** [comment]
Hello @pdewouters 

Thanks for reporting!

This does not look like a bug in the plugin as it is generating the markup correctly.

Instead, it looks like a design decision on the Instant Articles UI.
