### ISSUE TITLE
Index all Articles?

### ISSUE THREAD

**Issue by ghost** [Automattic/facebook-instant-articles-wp#549]
Hi, is there a Setting with the numbers of indexing Articles in the Feed? In my IA Feed only 10 Articles not all. 

Thank you

**Comment by jakirseu** [comment]
Though it's show only 10 articles, you can fetch old articles too.  If you update your post (Just Edit and Update form WP-admin) it will added on Instant Articles.

**Comment by OtherF** [comment]
Hi @jakirseu,
I have more that 1000 posts.

How to update all of them to add to Instant Articles?

**Comment by jakirseu** [comment]
Go here: WP-Admin > Posts > All Posts. 
From top corner, click on Screen Options. Then from Number of items per page, set something like. 100

And now Select all post. From Bulk Option, select Edit. And then Apply. Then update. You are good to go.

If you set Number of items per page 100, you have to do this 10 times only to update 1000 posts.

**Comment by OtherF** [comment]
@jakirseu yes, it worked previously.
but with the latest version I get error:
```General Errors: Empty Articles: You have one or more articles without any content.```
for all posts that were updated.

But If I update posts one by one - than everything ok!

**Comment by jakirseu** [comment]
I tried few days ago. Not sure about latest update. Sorry.

**Comment by diegoquinteiro** [comment]
@OtherF do you have the latest version?

A proper bulk-update solution is on the works.

**Comment by vkama** [comment]
This issue no longer existis since we are using OG Ingestion now.
