### ISSUE TITLE
Footer related articles title warning - but won't work without title.

### ISSUE THREAD

**Issue by dashaluna** [Automattic/facebook-instant-articles-wp#550]
I'm getting the following notice: `Incorrect Title/Heading in Related Articles: Titles are not supported in the Related Articles footer element. Please remove any title/heading.`

This is because my footer related articles list has got a title `Test rail`:
```
<footer>
    <ul class="op-related-articles" title="Test rail">
        <li>
            <a href="https://thesuncouk-develop.go-vip.co/uncategorized/28180/playbuzz-test/"></a>
        </li>
        ...
    </ul>
</footer>
```

However, if I don't use the `title` then related articles are not set for footer a per code here:
https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Transformer/Rules/FooterRelatedArticlesRule.php#L49

# Steps required to reproduce the problem

1. Original HTML:
```
<footer>
		<ul class="op-related-articles">
			<li><a href="http://example.com"></a></li>
			<li><a href="http://google.com"></a></li>
		</ul>
</footer>
```
2. Transformer Rules:
```
{
    "class" : "FooterRule",
    "selector" : "footer"
  },
  {
    "class" : "RelatedArticlesRule",
    "selector" : "ul.op-related-articles",
    "properties" : {
      "related.title" : {
        "type" : "exists", // tried "string" too
        "selector" : "ul.op-related-articles",
        "attribute" : "title"
      }
    }
  },
  {
    "class" : "FooterRelatedArticlesRule",
    "selector" : "ul.op-related-articles",
    "properties" : {
      "related.title" : {
        "type" : "exists", // tried "string" too
        "selector" : "ul.op-related-articles",
        "attribute" : "title"
      }
    }
  },
  {
    "class" : "RelatedItemRule",
    "selector" : "li",
    "properties" : {
      "related.sponsored" : {
        "type" : "exists",
        "selector" : "li",
        "attribute": "data-sponsored"
      },
      "related.url" : {
        "type" : "string",
        "selector" : "a",
        "attribute" : "href"
      }
    }
  }
```

# Expected Result
```
<footer>
		<ul class="op-related-articles">
			<li><a href="http://example.com"></a></li>
			<li><a href="http://google.com"></a></li>
		</ul>
</footer>
```

# Actual Result

`<footer>` is stripped.

---

**Version Info**

* Plugin version: 3.2
* WordPress version: 4.6.1 
* PHP version: 5.6

**Comment by dashaluna** [comment]
Looks like this is related: https://github.com/facebook/facebook-instant-articles-sdk-php/issues/77

**Comment by demoive** [comment]
@dashaluna Thanks for reporting this issue and finding that it was related to the existing bug within the SDK.

As you can see, we've submitted https://github.com/facebook/facebook-instant-articles-sdk-php/pull/187 which should fix the issue. Although this won't be available in the WordPress plugin until a future release, the changes can be pulled in to the package manually using `composer update` (v1.5.4):

https://packagist.org/packages/facebook/facebook-instant-articles-sdk-php

Specifically, I'll highlight the [relevant changes](https://github.com/facebook/facebook-instant-articles-sdk-php/pull/187/commits/5ba84c05f7c599ba0245bf0368b45857d612aadd) here:

![screen shot 2016-12-01 at 15 18 51](https://cloud.githubusercontent.com/assets/472288/20799417/0b9a68c2-b7da-11e6-92f9-a1b15249fcfd.png)
