### ISSUE TITLE
Debug Facebook Instant Articles in browser

### ISSUE THREAD

**Issue by emanuelet** [Automattic/facebook-instant-articles-wp#551]
Hi,
I tried to answer this question on StackOverflow but I haven't received any anwers. Probably somebody here had encountered the same issue.

According to this page (https://developers.facebook.com/docs/instant-articles/analytics) on the Facebook Instant Articles documentation is possible to debug them in a browser using the following url:

` www.ia-tracker.fbsbx.com/instant_article_test?url=<share-url>`
Now I keep getting the following error:

> Notice The trackers are run in same environment as Instant Articles, except that the base url is different. On Instant article, it's the url, that the user shared.

I tried to use the canonical url, without _http_, with _www_ but nothing worked.

Have someone been able to use this method successfully, and if yes what they mean by "share url"?

**Comment by akeem** [comment]
Hi, 

The intention of this tool is to aid with debugging of tracking code inside of an Instant Article. The share url is a url shared on Facebook (that has an corresponding Instant Article).

Here is a link to the tool with a live IA URL: http://www.ia-tracker.fbsbx.com/instant_article_test?url=https://media.fb.com/2016/12/01/how-instant-articles-benefits-local-news/

The notice that you posted, is a bit weird but to be expected. Using your browser's web inspector here should reveal any of the tracking code provided with the Instant Article and give a bit more insight into possible errors

**Comment by emanuelet** [comment]
I'm not sure that I understand.

Even when I open the link that you posted and inspect with Chrome I get a blank page with that notice.

Is there a particular way that I should open it or something else that I'm missing?

**Comment by akeem** [comment]
This tool is only for debugging analytics tracking code, none of the other IA markup will be available in this tool.

Using Chrome's Developer Tools you should see a script node making the `ia_document` javascript object available for the example page provided.

**Comment by emanuelet** [comment]
Ah ok, sorry for the confusion. I can now see the tracking codes for my articles.

One more question:
I get the following error for the 3 of the scripts:

> Refused to load the script 'https://example.net/tracker.js' because it violates the following Content Security Policy directive: "script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data:".

I'm pretty sure that those scripts are firing and reporting in production.
Could you help understand what's going on here?

**Comment by akeem** [comment]
No worries, I am glad that you are able to see your tracking codes! The tool was created to provide some visibility into tracking code, but it doesn't 100% reflect the state of things running on mobile devices. 

The important thing here is that you are seeing your scripts fire and report in production. The error that you are seeing appears to be related to the host of the tool, and should be addressed.

**Comment by demoive** [comment]
@emanuelet We'll get back to you with more information about the CSP rules for the `fbsbx.com` domain and whether or not they can be altered to accommodate scripts from more domains.

**Comment by Crashthatch** [comment]
There's a debugger for debugging transformer rules in the browser here:

http://fb-instant-articles-debugger.crashthatch.com/

(Full disclosure: self promotion)

**Comment by diegoquinteiro** [comment]
@Crashthatch thanks for developing this tool! Is it open source?

**Comment by Crashthatch** [comment]
Yes- the source is available at https://github.com/Crashthatch/fb-instant-articles-debugger.

**Comment by vytas315** [comment]
I'm getting a similar issue trying to use Google Tag Manager scripts. I can see that google-analytics domain is included but not tag manager. It also does not appear to be triggering in production. Can someone confirm if this is an issue with the debugger or also the reason I'm not seeing hits in production?

> instant_article_test?url=https://mytestsite.com/posts/some-title:8 Refused to load the script 'https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXX' because it violates the following Content Security Policy directive: "script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data: 'self'".

**Comment by everton-rosario** [comment]
@vytas315 Are you using the proper structure for the analytics code?
Can you share some code of the Instant Article created?

It should use the block: 
```
<figure class="op-tracker">
      <iframe src="http://my-url.com/tracker.php"></iframe>
</figure>
```
