### ISSUE TITLE
Fanpage Not Showing In Setting

### ISSUE THREAD

**Issue by FahmiRaazali** [Automattic/facebook-instant-articles-wp#552]
# Steps required to reproduce the problem

1. Had more than 40 fanpage
2. Install & activate plugins
3. Connect with fb app
4. Login to FB

# Expected Result

* All fanpage is there available for user to select

# Actual Result

* Some list of the fanpage is shown but the fanpage that going to be used is not in the list. 
* Expected some button or a way to load other fanpage that is not shown.

---

**Version Info**

* Plugin version: 3.2.2
* WordPress version: 4.6.1
* PHP version: 5.6.28

**Comment by tudorached** [comment]
Check this [https://github.com/Automattic/facebook-instant-articles-wp/issues/492#issuecomment-267582789](url)

**Comment by diegoquinteiro** [comment]
Duplicate of #492
