### ISSUE TITLE
Fatal error: Uncaught exception after changeing FB password

### ISSUE THREAD

**Issue by zamo-icm** [Automattic/facebook-instant-articles-wp#553]
# Steps required to reproduce the problem

1. My instant articles were working fine
2. Changing personal Facebook password

# Expected Result

* a way to redo authentication

# Actual Result
When trying to access wp plugins tab i only get this: (I can't get to my installed plugins page)
* Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: Session does not match current stored session. This may be because the user changed the password since the time the session was created or Facebook has changed the session for security reasons.' in /home/greenet1/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /home/greenet1/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/greenet1/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/greenet1/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\F in /home/greenet1/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89

---
I removed the plugin completly and re installed a fresh version. still the same message 
**Version Info**

* Plugin version: V3.2.2
* WordPress version: 4.6.1
* PHP version: 5.4.8

**Comment by hubthomas** [comment]
Same problem for me after removing the original admin user

**Comment by uziiuzair** [comment]
Is there any fix yet? I had to remove the plugin too.

**Comment by bwagner182** [comment]
I'm having this same issue on at least one of my sites, I had to remove the plugin for the time being which is unfortunate. 

I would also think that if I uninstall and/or delete the plugin I should be given the option to remove the data from the database so that when I reinstall it I can redo the authentication.

**Comment by uziiuzair** [comment]
@bwagner182 actually I did find a fix. Go to yourwebsite.com/wp-admin/options.php
Find the following fields and clear them out.
- `instant-articles-option-fb-app`
- `instant-articles-option-fb-page`
This will force the app to revert to its setup state. 

This fixed the problem for me, hope it does it for you.

**Comment by bwagner182** [comment]
@uziiuzair Thank you for the fix. I had tried deleting all the data from the database and reinstalling the plugin and that still didn't work. Thanks again.

**Comment by SJ04** [comment]
Hello Guys,

I am facing the Same Issue here , can someone please help here.

 php /workflows/facebook-autoupload/index.php
in else condition20170831-007 exists for XMLGraph returned an error: Fatalexception

**Comment by uziiuzair** [comment]
@SJ04 have you tried what I suggested above?

**Comment by SJ04** [comment]
@uziiuzair , Sorry Uziiuzair,

I am using PHP SDK without website plugin. I have just PHP script which perfom the UPLoad of the VIdeo and copyright them
so there is very starnge issue that when i only upload the video it works but with copy right function it doesnt.

I will appreciate any help i am seriously stuck at this shit since 3 days.
