### ISSUE TITLE
Read Timeout on Facebook

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#56]
Experiencing this error in my Facebook /settings/?tab=instant_articles

Read Timeout
Last checked at 1:18PM
There was a timeout and we could not read your article feed. Please reduce the number of articles in your feed file and try again.

My server is extremelly fast and generates as far as I see quickly the feed, is there any way to control how many articles should be outputed?

**Comment by bjornjohansen** [comment]
During the intitial review, Facebook requires 100 articles to accept your application as an Instant Arcticles publisher. But once you’ve been accepted, you may set the constant `INSTANT_ARTICLES_LIMIT_POSTS` to true, to only include posts modified within the last 24 hours in your feed. This is recommended, as Facebook will ignore posts with a modification date older than that anyway.

**Comment by gabu69** [comment]
What if i was just going to send it to review and im getting this error now, what can I do?

**Comment by gabu69** [comment]
Owww

Found it in fb-instant-articles/facebook-instant-articles.php

```
/**
 * Modify the main query for our feed.
 *
 * We want the posts in the modified order, to provide Facebook with content updates even for older posts.
 * Facebook will only import 100 posts at the time.
 * Facebook will only update posts modified within the last 24 hours
 *
 * @param WP_Query  $query  The WP_Query object. Passed by reference.
 */
function instant_articles_query( $query ) {

	if ( $query->is_main_query() && $query->is_feed( INSTANT_ARTICLES_SLUG ) ) {

		$query->set( 'orderby', 'modified' );
		$query->set( '**posts_per_page**', 51 );
		$query->set( '**posts_per_rss**', 51 );
```
