### ISSUE TITLE
Login to Facebook loop

### ISSUE THREAD

**Issue by graylaurenm** [Automattic/facebook-instant-articles-wp#561]
# Steps required to reproduce the problem

1. Input App ID and Secret
2. Click login to Facebook button
3. See warning: "Submit for Login Review
Some of the permissions below have not been approved for use by Facebook.
Submit for review now or learn more."
4. Allow access.

# Expected Result

* Return to website and be taken to step 2, "Select Your Page"

# Actual Result

* Return to website and it asks me to login to Facebook, as before.

---

**Version Info**

* Plugin version: 3.2.2
* WordPress version: 4.6.1
* PHP version: 5.6.28-2+deb.sury.org~precise+1

**Comment by graylaurenm** [comment]
### More information

So I see how to submit approval for those permissions, but it involves more steps than the Facebook help article walks me though. This app is new, but I try setting a fresh one up again next.

**Comment by sumair52** [comment]
same problem with me

**Comment by diegoquinteiro** [comment]
@graylaurenm and @sumair52 please make sure you're logging in with the same user that is an admin or owner of the App you created.

You can ignore if a warning asking for submitting for review is shown in this case.

**Comment by sumair52** [comment]
I am sure that I am logging with the same account I processed the permission and after I give the app permission I reloads the page and can't proced on step 2

**Comment by graylaurenm** [comment]
Thanks for the feedbac, @diegoquinteiro. I only have one Facebook account, so they are definitely the same. Just re-attempted and the loop persists. It asks for permission, I accept, it appears to succeed, but then my site still asks me to log in with Facebook. Could this be something on my site's end?

**Comment by sumair52** [comment]
Did u get solution?

**Comment by graylaurenm** [comment]
I did not. On my staging site, it works with all the same themes and plugins active. On my live site, it doesn't work even if my theme and plugins are all inactive.

**Comment by everton-rosario** [comment]
For the login process to work, your login URL should be the one your admin is under, this way Facebook will successfully redirect you after login. If domains are different (from configured to the one being accessed from) will break the login flow.

Double check our web login documentation, double checking if you missed something to set up, please: 
[https://developers.facebook.com/docs/facebook-login/web](https://developers.facebook.com/docs/facebook-login/web)

**Comment by graylaurenm** [comment]
I'm not really sure what URLs you're referring to, @everton-rosario, can you be more specific? When you say "your login URL should be the one your admin is under" are you referring to my WordPress login URL, e.g. https://www.oncecoupled.com/wp-login.php? This should be the same one my admin is under? As in my WordPress admin area, https://www.oncecoupled.com/wp-admin/? Or are we referring to the app settings? 
<img width="782" alt="screen shot 2016-12-29 at 2 48 47 pm" src="https://cloud.githubusercontent.com/assets/1750577/21554557/2cef6e48-cdd6-11e6-8b6b-69683909906d.png">

If it's helpful to know, I'm on https://www.oncecoupled.com/wp-admin/admin.php?page=instant-articles-wizard, click "Login with Facebook," go through two prompts to give approval there, then am redirected back to https://www.oncecoupled.com/wp-admin/admin.php?page=instant-articles-wizard where nothing has changed.
