### ISSUE TITLE
Rule to embed images 

### ISSUE THREAD

**Issue by pedroramos26** [Automattic/facebook-instant-articles-wp#564]
Hi there , thanks for this awesome plugin! 

I'm having a problem when uploading images to my article and i need always to edit the html code with the <figure> tag. Is there any rule to make this automatic? Also to remove the header image of all articles?

 
Thanks!

**Comment by diegoquinteiro** [comment]
Hello @pedroramos26,

Images should work automatically.

Please inform the version of the plugin and copy/paste the debug information (both sides) shown on the Instant Articles meta-box on the article with the problem so we can investigate.

Thank you for reporting,
Diego

**Comment by timjacobi** [comment]
Closing as this hasn't been responded to in too long.
