### ISSUE TITLE
Transformer rule on "No rules defined for <post> in the context of InstantArticle"

### ISSUE THREAD

**Issue by blackguyinablackroom** [Automattic/facebook-instant-articles-wp#566]
hi, i'm having a problem regarding jetpack and fb instant article plugins
i'm trying to post an fb public post to a wp blog site as a reference for an article but the problem is this message saying "No rules defined for in the context of InstantArticle" whenever i updated it.
i tried to use , it works but my boss doesn't like that method since i can post a twitter post with just the use of URL. Now he wants me to embed it (fb post) like i did on twitter post. As for the jetpack, i installed, activated and connected it to wordpress.com as per the instructions here https://optimizerwp.com/wordpress-embed-guide/, but its always the FB IA that says "No rules defined for in the context of InstantArticle". I've been trying to solve this problem for weeks now and i'm already tired in searching for answers. You guys are my last hope in resolving this problem.

thanks,

**Comment by blackguyinablackroom** [comment]
someone answer me please!!!!!

**Comment by everton-rosario** [comment]
You might be using some plugin that is not compatible with Instant Articles WP Plugin.

Please, can you share here more info about your transformation problem?

I need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

With this in hands I can see the issue you are facing and provide some assistance on how to solve it.


Thanks for using Instant Articles, @blackguyinablackroom .

**Comment by everton-rosario** [comment]
I'll close for now, until we have more info provided.

**Comment by blackguyinablackroom** [comment]
Hello! i print screen the source and transform markup (texts inside the
rectangle) for you to see what happened whenever i update the article. I'm
using only the URL of Facebook embed that i want to post just like what is
suggested here
https://en.support.wordpress.com/facebook-integration/facebook-embeds/.

**Comment by blackguyinablackroom** [comment]
Hi! It's me again

I just want to know if there's a problem with FB InstantArticle and
jetpack....... and if there's a custom transformer rule for post

**Comment by everton-rosario** [comment]
I need you to copy/paste the markup before being transformed in a way I can help you with that.
The copy/paste of facebook story, have you copy/pasted only the oembed link or are you using the shortcode?

Please, to provide the content the plugin is being transformed, follow these steps:

1. click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box
2. then copy and paste both editor's text: "**Source Markup**" and "**Transformed Markup**"

Let me know more details about the issue you are facing.

Happy new year!

**Comment by blackguyinablackroom** [comment]
Hi!!! its me again

this is the fb embed that i posted using iframe

![1](https://cloud.githubusercontent.com/assets/24713233/21833049/760360c6-d7ea-11e6-9db5-8f5cf26a2d0d.png)

it works but my boss doesn't want me to use it. He wants me to find a way
to post fb embed using URL only since i managed to make it work in other
social media apps (twitter, instagram, etc.)

but there's a problem whenever i tried it on fb embed. You can see the
error in this print screen

![2](https://cloud.githubusercontent.com/assets/24713233/21833098/ddd00646-d7ea-11e6-86da-d779d6a16f94.png)

you can see here there's an error saying "No rules defined for <post> in
the context of Paragraph"

I've tried to find for answers but i can't find any.

If there's a custom transformer rule for that error, can you share it with
me?? Please!!! I want to solve this problem

Thanks!! and Happy New Year by the way xD
