### ISSUE TITLE
How do I exclude wordpress posts from being published as IA?

### ISSUE THREAD

**Issue by katsar0v** [Automattic/facebook-instant-articles-wp#567]
This is a general question, as I haven't found a **proper** way to exclude articles, so I want to ask is there a **working** way to exclude articles not being published as IA, because currently with the latest stable version absolutely everything gets published into facebook

**Comment by aurooba** [comment]
I would like to know the answer to this as well!

**Comment by katsar0v** [comment]
Haha, a lot of us would like, I guess.............

**Comment by timjacobi** [comment]
This is currently not possible. I have added it as a feature request in #773.
