### ISSUE TITLE
Transformer rules for Themify Video embed and image slider

### ISSUE THREAD

**Issue by leccestar** [Automattic/facebook-instant-articles-wp#569]
Here are transformer rules for making video embed and image slider with captions work in Themify builder posts:

    { "rules": 
        [
            { "class": "PassThroughRule", "selector": "div"}, 
            { "class": "InteractiveRule", "selector": "div.video-wrap","properties" : 
                { "interactive.iframe" : { "type" : "string", "selector" : "iframe", "attribute": "src"}}},
            { "class": "SlideshowRule", "selector": "ul.themify_builder_slider"},
            { "class": "SlideshowImageRule", "selector": "li", "properties" : 
                { 
                    "image.url" : 
                    { "type" : "string", "selector" : "img", "attribute": "src"
                    },
                    "caption.title" : 
                    { "type" : "string", "selector" : "img", "attribute": "alt"
                    }
                }
            }
        ]
    }

**Comment by DJUK16** [comment]
Will this work with the slider pro plugin or is it just the main Themify builder plugin?

**Comment by leccestar** [comment]
@DJUK16 it is for standard slider and video in the Themify Builder plugin.

Also I updated the code a bit:

{ "rules": 
        [
            { "class": "PassThroughRule", "selector": "div"}, 
            { "class": "InteractiveRule", "selector": "div.video-wrap","properties" : 
                {   "interactive.url" : { "type" : "string", "selector" : "iframe", "attribute": "src"},
                    "interactive.height" : { "type" : "int", "selector" : "iframe", "attribute": "height"},
                    "interactive.width"  : { "type" : "int", "selector" : "iframe", "attribute": "width"}
                }
            },
            { "class": "SlideshowRule", "selector": "ul.themify_builder_slider"},
            { "class": "SlideshowImageRule", "selector": "li", "properties" : 
                { 
                    "image.url" : 
                    { "type" : "string", "selector" : "img", "attribute": "src"
                    },
                    "caption.title" : 
                    { "type" : "string", "selector" : "img", "attribute": "alt"
                    }
                }
            }
        ]
    }

**Comment by DJUK16** [comment]
Did this work successfully for you just im having some issues finding a good way to display images that looks nice both website side and FBIA side.

**Comment by leccestar** [comment]
Yes I'm happy with how it looks on my blog (Themify theme and builder) and how it then looks on FBIA.

**Comment by DJUK16** [comment]
Yeah i just did a test its sending the code correctly to FBIA but sadly isn't showing any images! thank you anyways buddy and thanks for replying

**Comment by diegoquinteiro** [comment]
@leccestar would you be able to create a PR to add this to a compat layer? You can use this PR as an example: #417

**Comment by timjacobi** [comment]
I have created #772 to address this
