### ISSUE TITLE
Can't transform <img data-src> to <img src> with ImageRule

### ISSUE THREAD

**Issue by rslonik** [Automattic/facebook-instant-articles-wp#570]
**I have:**
`<img  class="alignnone size-full wp-image-29397 b-lazy"  src="https://www.site.net/wp-content/uploads/2016/12/carregando.png" data-src="https://www.site.net/wp-content/uploads/2016/12/Snap-2016-10-27-at-06.09.39.png" alt="snap-2016-10-27-at-06-09-39" width="624" height="354" />`

**That is being transformed to:**
`<img src="https://www.site.net/wp-content/uploads/2016/12/carregando.png"/>`

**But I need the `data-src` as `src`. Like this:**
`<img src="https://www.site.net/wp-content/uploads/2016/12/Snap-2016-10-27-at-06.09.39.png"/>`

I've tried [something like the docs say](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules):
```
// Source Markup: <span class="custom-href" data-link="http://example.com">
{
 "class": "AnchorRule",
 "selector": "span.custom-href",
 "properties" : {

   "anchor.href" : {
     "type" : "string",
     "selector" : "span.custom-href",
     "attribute": "data-link"
   }

 }
}
// Generated Markup: <a href="http://example.com">
```

**My ImageRule:**
```
{   
  "class": "ImageRule",  
  "selector": "img.b-lazy",  
  "properties":   
  {     
    "image.url":     
    {
      "type": "string",
      "selector": "img.b-lazy",
      "attribute": "data-src"    
    }   
  } 
}
```

But it's not working. Is it possible to do this king of transformation in ImageRule?

**Version Info**

* Plugin version: 3.2.2
* WordPress version: 4.6.1
* PHP version:  7.0.14-2

**Comment by everton-rosario** [comment]
@rslonik Thanks for using the SDK.

Double check if you set this as the latest rule on your configuration. Also, you can try to remove the selector on the properties list, since the `img` only will do the tricky.

I've just tried this rule setup:
```
  {
      "class": "ImageRule",
      "selector": "img.b-lazy",
      "properties": {
        "image.url": {
          "type": "string",
          "selector": "img",
          "attribute" : "data-src"
        }
      }
  }
```

This was the output generated by this configuration rule:
```
<figure>
        <img src="https://www.site.net/wp-content/uploads/2016/12/Snap-2016-10-27-at-06.09.39.png"/>
</figure>
```

Let me know if this works or not for you.

**Comment by rslonik** [comment]
The problem was another filter I was doing in `the_content`

Checking for the `instant_articles_content` filter and returning before my code, worked. 😄 
```
    if ( ! has_filter( 'the_content', 'instant_articles_content' ) ) 
    {   
        return $content;
    }   
```

Thank you for your attention, @everton-rosario !

**Comment by everton-rosario** [comment]
Thats perfect @rslonik !
Happy holidays!
