### ISSUE TITLE
Slider Issue from website

### ISSUE THREAD

**Issue by charls637** [Automattic/facebook-instant-articles-wp#571]
I Have this sample page that has a simple image, quote, text and slideshow here
http://ednc.staging.wpengine.com/2016/12/25/test-new/ 

I need to know what rules should I applied in order to achieve the slider in instant?

# Expected Result

*  expected in instant must be a slideshow

# Actual Result

* but it turns out that those slideshow images became solo images in instant

BASICALLY my problem is how to achieve the slideshow thing in instant or what should be the rules?
---
MY RULE FOR NOW:
{"rules": 
[
    {
        "class": "PassThroughRule",
        "selector": "div.slideshow_container"
    }, {
        "class": "PassThroughRule",
        "selector": "div.slideshow_content"
    },  {
        "class": "IgnoreRule",
        "selector": "div.slideshow_view"
    }, 
	{"class": "SlideshowImageRule", "selector": "div.slideshow_slide_image", "properties" : 
        { 
			"image.url" : 
			{ "type" : "string", "selector" : "img", "attribute": "src"
			},
			"caption.credit" : 
			{ "type" : "string", "selector" : "div.slideshow_title", "attribute": "alt"
			},
			"caption.title" : 
			{ "type" : "string", "selector" : "div.slideshow_description"
			}
		}
    }
]
}

**Version Info**

* Plugin version: Latest
* WordPress version: 4.7
* PHP version:

**Comment by charls637** [comment]
`<div class="slideshow_container slideshow_container_style-light" style="height: 200px; width: 715px;" data-slideshow-id="34208" data-style-name="style-light" data-style-version="2.3.1" data-slideshow-active="1">
   <div class="slideshow_content" style="width: 715px; height: 200px;">
      <div class="slideshow_view slideshow_currentView" style="width: 715px; height: 200px; left: 0px; top: 0px;">
         <div class="slideshow_slide slideshow_slide_image" style="margin-left: 0px; margin-right: 0px; width: 715px; height: 200px;">
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg" alt="1x2a4875" width="386" height="200" style="margin-left: auto; margin-right: auto; display: block; width: 386px; height: 200px;">
            <div class="slideshow_description_box slideshow_transparent" style="display: block; position: absolute; top: 200px;">
               <div class="slideshow_title">1x2a4875</div>
               <div class="slideshow_description">Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
      <div class="slideshow_view" style="top: 200px; width: 715px; height: 200px; left: -715px;">
         <div class="slideshow_slide slideshow_slide_image" style="margin-left: 0px; margin-right: 0px; width: 715px; height: 200px;">
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg" alt="group16" width="715" height="191" style="margin: 0px; width: 715px; height: 191px;">
            <div class="slideshow_description_box slideshow_transparent" style="display: block; position: absolute; top: 200px;">
               <div class="slideshow_title">group16</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
   <div class="slideshow_controlPanel slideshow_transparent" style="display: none;">
      <ul>
         <li class="slideshow_togglePlay" data-play-text="Play" data-pause-text="Pause"></li>
      </ul>
   </div>
   <div class="slideshow_button slideshow_previous slideshow_transparent" role="button" data-previous-text="Previous" style="display: block;" tabindex="0" title="Previous"><span class="assistive-text hide-text">Previous</span></div>
   <div class="slideshow_button slideshow_next slideshow_transparent" role="button" data-next-text="Next" style="display: block;" tabindex="0" title="Next"><span class="assistive-text hide-text">Next</span></div>
   <div class="slideshow_pagination" style="display: none;" data-go-to-text="Go to slide">
      <div class="slideshow_pagination_center">
         <ul>
            <li class="slideshow_transparent slideshow_currentView" data-view-id="0" role="button" title="Go to slide 1" tabindex="0"><span class="assistive-text hide-text">Go to slide 1</span></li>
            <li class="slideshow_transparent" data-view-id="1" role="button" title="Go to slide 2" tabindex="0"><span class="assistive-text hide-text">Go to slide 2</span></li>
         </ul>
      </div>
   </div>
   
</div>`

**Comment by charls637** [comment]
> <div class="slideshow_container slideshow_container_style-light" style="height: 200px; width: 715px;" data-slideshow-id="34208" data-style-name="style-light" data-style-version="2.3.1" data-slideshow-active="1">

					
		
		<div class="slideshow_content" style="width: 715px; height: 200px;">

			<div class="slideshow_view slideshow_currentView" style="width: 715px; height: 200px; left: 0px; top: 0px;">
				<div class="slideshow_slide slideshow_slide_image" style="margin-left: 0px; margin-right: 0px; width: 715px; height: 200px;">
											<img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg" alt="1x2a4875" width="386" height="200" style="margin-left: auto; margin-right: auto; display: block; width: 386px; height: 200px;">
										<div class="slideshow_description_box slideshow_transparent" style="display: block; position: absolute; top: 200px;">
						<div class="slideshow_title">1x2a4875</div>						<div class="slideshow_description">Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</div>					</div>
				</div>

						<div style="clear: both;"></div></div><div class="slideshow_view" style="top: 200px; width: 715px; height: 200px; left: -715px;">
				<div class="slideshow_slide slideshow_slide_image" style="margin-left: 0px; margin-right: 0px; width: 715px; height: 200px;">
											<img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg" alt="group16" width="715" height="191" style="margin: 0px; width: 715px; height: 191px;">
										<div class="slideshow_description_box slideshow_transparent" style="display: block; position: absolute; top: 200px;">
						<div class="slideshow_title">group16</div>											</div>
				</div>

						<div style="clear: both;"></div></div>
		</div>

		<div class="slideshow_controlPanel slideshow_transparent" style="display: none;"><ul><li class="slideshow_togglePlay" data-play-text="Play" data-pause-text="Pause"></li></ul></div>

		<div class="slideshow_button slideshow_previous slideshow_transparent" role="button" data-previous-text="Previous" style="display: block;" tabindex="0" title="Previous"><span class="assistive-text hide-text">Previous</span></div>
		<div class="slideshow_button slideshow_next slideshow_transparent" role="button" data-next-text="Next" style="display: block;" tabindex="0" title="Next"><span class="assistive-text hide-text">Next</span></div>

		<div class="slideshow_pagination" style="display: none;" data-go-to-text="Go to slide"><div class="slideshow_pagination_center"><ul><li class="slideshow_transparent slideshow_currentView" data-view-id="0" role="button" title="Go to slide 1" tabindex="0"><span class="assistive-text hide-text">Go to slide 1</span></li><li class="slideshow_transparent" data-view-id="1" role="button" title="Go to slide 2" tabindex="0"><span class="assistive-text hide-text">Go to slide 2</span></li></ul></div></div>

		

			</div>

**Comment by charls637** [comment]
> <div class="slideshow_container slideshow_container_style-light" data-slideshow-active="1">
   <div class="slideshow_content" >
      <div class="slideshow_view slideshow_currentView" >
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg" alt="1x2a4875" width="386" height="200" >
            <div class="slideshow_description_box slideshow_transparent" >
               <div class="slideshow_title">1x2a4875</div>
               <div class="slideshow_description">Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
      <div class="slideshow_view"?
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg" alt="group16" width="715" height="191" >
            <div class="slideshow_description_box slideshow_transparent">
               <div class="slideshow_title">group16</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
   <div class="slideshow_controlPanel slideshow_transparent" style="display: none;">
      <ul>
         <li class="slideshow_togglePlay" data-play-text="Play" data-pause-text="Pause"></li>
      </ul>
   </div>
   <div class="slideshow_button slideshow_previous slideshow_transparent" role="button" data-previous-text="Previous" style="display: block;" tabindex="0" title="Previous"><span class="assistive-text hide-text">Previous</span></div>
   <div class="slideshow_button slideshow_next slideshow_transparent" role="button" data-next-text="Next" style="display: block;" tabindex="0" title="Next"><span class="assistive-text hide-text">Next</span></div>
   <div class="slideshow_pagination" style="display: none;" data-go-to-text="Go to slide">
      <div class="slideshow_pagination_center">
         <ul>
            <li class="slideshow_transparent slideshow_currentView" data-view-id="0" role="button" title="Go to slide 1" tabindex="0"><span class="assistive-text hide-text">Go to slide 1</span></li>
            <li class="slideshow_transparent" data-view-id="1" role="button" title="Go to slide 2" tabindex="0"><span class="assistive-text hide-text">Go to slide 2</span></li>
         </ul>
      </div>
   </div>
   
</div>

**Comment by charls637** [comment]
`<div class="slideshow_container slideshow_container_style-light" data-slideshow-active="1">
   <div class="slideshow_content" >
      <div class="slideshow_view slideshow_currentView" >
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg" alt="1x2a4875" width="386" height="200" >
            <div class="slideshow_description_box slideshow_transparent" >
               <div class="slideshow_title">1x2a4875</div>
               <div class="slideshow_description">Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
      <div class="slideshow_view"?
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg" alt="group16" width="715" height="191" >
            <div class="slideshow_description_box slideshow_transparent">
               <div class="slideshow_title">group16</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
   <div class="slideshow_controlPanel slideshow_transparent" style="display: none;">
      <ul>
         <li class="slideshow_togglePlay" data-play-text="Play" data-pause-text="Pause"></li>
      </ul>
   </div>
   <div class="slideshow_button slideshow_previous slideshow_transparent" role="button" data-previous-text="Previous" style="display: block;" tabindex="0" title="Previous"><span class="assistive-text hide-text">Previous</span></div>
   <div class="slideshow_button slideshow_next slideshow_transparent" role="button" data-next-text="Next" style="display: block;" tabindex="0" title="Next"><span class="assistive-text hide-text">Next</span></div>
   <div class="slideshow_pagination" style="display: none;" data-go-to-text="Go to slide">
      <div class="slideshow_pagination_center">
         <ul>
            <li class="slideshow_transparent slideshow_currentView" data-view-id="0" role="button" title="Go to slide 1" tabindex="0"><span class="assistive-text hide-text">Go to slide 1</span></li>
            <li class="slideshow_transparent" data-view-id="1" role="button" title="Go to slide 2" tabindex="0"><span class="assistive-text hide-text">Go to slide 2</span></li>
         </ul>
      </div>
   </div>
   
</div>`

**Comment by charls637** [comment]
``<div class="slideshow_container slideshow_container_style-light" data-slideshow-active="1">
   <div class="slideshow_content" >
      <div class="slideshow_view slideshow_currentView" >
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg" alt="1x2a4875" width="386" height="200" >
            <div class="slideshow_description_box slideshow_transparent" >
               <div class="slideshow_title">1x2a4875</div>
               <div class="slideshow_description">Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
      <div class="slideshow_view"?
         <div class="slideshow_slide slideshow_slide_image" >
            <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg" alt="group16" width="715" height="191" >
            <div class="slideshow_description_box slideshow_transparent">
               <div class="slideshow_title">group16</div>
            </div>
         </div>
         <div style="clear: both;"></div>
      </div>
   </div>
   <div class="slideshow_controlPanel slideshow_transparent" style="display: none;">
      <ul>
         <li class="slideshow_togglePlay" data-play-text="Play" data-pause-text="Pause"></li>
      </ul>
   </div>
   <div class="slideshow_button slideshow_previous slideshow_transparent" role="button" data-previous-text="Previous" style="display: block;" tabindex="0" title="Previous"><span class="assistive-text hide-text">Previous</span></div>
   <div class="slideshow_button slideshow_next slideshow_transparent" role="button" data-next-text="Next" style="display: block;" tabindex="0" title="Next"><span class="assistive-text hide-text">Next</span></div>
   <div class="slideshow_pagination" style="display: none;" data-go-to-text="Go to slide">
      <div class="slideshow_pagination_center">
         <ul>
            <li class="slideshow_transparent slideshow_currentView" data-view-id="0" role="button" title="Go to slide 1" tabindex="0"><span class="assistive-text hide-text">Go to slide 1</span></li>
            <li class="slideshow_transparent" data-view-id="1" role="button" title="Go to slide 2" tabindex="0"><span class="assistive-text hide-text">Go to slide 2</span></li>
         </ul>
      </div>
   </div>
   
</div>

**Comment by everton-rosario** [comment]
@charls637 Thanks for using the SDK.

Check that IgnoreRule will remove the entire HTML node, and Passthrough will just allow the transformer to go into the next inner element.

I've checked your rules and it was misleading the usage of Ignore and PassThrough.

Here it is how you should setup your rules to transform this slideshow:
```
{
      "class": "SlideshowRule",
      "selector": "div.slideshow_container"
  },
  {
      "class": "PassThroughRule",
      "selector": "div.slideshow_content"
  },
  {
      "class": "SlideshowImageRule",
      "selector": "div.slideshow_view",
      "properties": {
          "image.url" : {
              "type": "string",
              "selector": "img",
              "attribute": "src"
          },
          "caption.title" : {
              "type": "string",
              "selector": "div.slideshow_description"
          }
      }
  },
  {
      "class": "IgnoreRule",
      "selector": "div.slideshow_controlPanel"
  },
  {
      "class": "IgnoreRule",
      "selector": "div.slideshow_button"
  },
  {
      "class": "IgnoreRule",
      "selector": "div.slideshow_pagination"
  }
```


This `rules.json` setup will transform to a valid Slideshow like this:
```
      <figure class="op-slideshow">
        <figure>
          <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/1X2A4875.jpg"/>
          <figcaption>Wallace Elementary School in Duplin County. (Photo credit: Todd Brantley/Education NC) September 27, 2016</figcaption>
        </figure>
        <figure>
          <img src="http://ednc.staging.wpengine.com/wp-content/uploads/2016/11/group16-1.jpg"/>
        </figure>
      </figure>
```

Happy holidays.

**Comment by charls637** [comment]
@everton-rosario  thank you for the response, after putting the rules I have the same warning problem.
![error](https://cloud.githubusercontent.com/assets/8040085/21487591/894d8ed4-cc07-11e6-95ba-06a229482844.jpg)

this is the page by the way http://ednc.staging.wpengine.com/2016/12/25/test-new/

**Comment by everton-rosario** [comment]
Hey @charls637, I was checking your markup, and looks like you have some text "free". By free I mean it doesn't stand inside any tag, like <p>/<span>/<blockquote>.

Just enclose the texts within <p> tags, and everything should work.

Same occurs for `1x2a4875Wallace ....` and `group 16`.

**Comment by charls637** [comment]
I am using a slideshow plugin, is there any recommended plugin that you wish me to use? so that it will work flawlessly.

since it's  a plugin i believed it will hard for me to modify.
