### ISSUE TITLE
Infinite throbber when "Submiting for Review"

### ISSUE THREAD

**Issue by JokinC** [Automattic/facebook-instant-articles-wp#572]
# Steps required to reproduce the problem

1. Activate the plugin from Wordpress plugin directory

# Expected Result

* Update the articles and submit for review

# Actual Result

* A throbber appears but it doesn't do anything, even after 3 hours it continues there, and the pluging doesn't submit any article. If I close the tab or I go to anywhere else, the next time that I try to entry in the wizard I get a white screen and I have to delete the "STATE_REVIEW_SUBMISSION" line from instant-articles-current-state from options.php to start again.
![iaf](https://cloud.githubusercontent.com/assets/24792098/21499282/b8af9a14-cc34-11e6-9904-c861c8fc76a8.jpg)

web: thecookinglab.es

---

**Version Info**

* Plugin version: 3.2.2
* WordPress version: 4.7
* PHP version: 5.6.27

**Comment by everton-rosario** [comment]
@JokinC can you check if your page was submitted for review?
To double check it outside the plugin, follow these steps:

1. Access the Facebook user profile page, same you are submitting articles into the Wordpress Plugin (It will be one of the admin of that page)
2. Click on the right top triangle  in the blue bar, and select the page you are using
3. Select "publishing tools" in the white bar (right below the blue bar)
4. Select "Configurations" under the left menu, within the "Instant Articles" section
5. Scroll down a bit, and find the section number 2 "send to review"
6. If the button is enabled, just hit that button.

This will send it to review.

If you need it fast-tracked send me the page ID.

This is a 1 time process, so this should fix once for all, if you already 5 articles published.

Let me know/reopen if this doesn't work for you.
Happy new year!

**Comment by JokinC** [comment]
I try to submit the articles, however, I think there is some kind of error in the transformation of the RSS feed of Instant Articles that doesn't allow the articles to read.

http://thecookinglab.es/feed/instant-articles

The feed is empty after the [CDATA[

The common feed (http://thecookinglab.es/feed/) seems to have all the information.

**Comment by everton-rosario** [comment]
@JokinC Don't mix the submissions.
RSS Feed on the plugin, doesn't require you to submit to review thru the plugin itself.
Submission to review, within the plugin will only work if you configure and setup the usage of API and submit the articles thru the API.

Just to clear this out:
* RSS
Has only one endpoint that you need to setup under your publishing tools, in your Facebook page and send to review from the same publishing tools

* API
API Setup using wizard and requires you to have an APP within Facebook developers console and by setting this up you will be able to use 100% of the plugin to publish articles thru API and submit for review.

**Comment by JokinC** [comment]
@everton-rosario I know, but it seems that the error is caused because the RSS feed of instant-articles is not being correctly created. What can happen?

Just check my feed: [Instant Articles feed](http://thecookinglab.es/feed/instant-articles)

**Comment by everton-rosario** [comment]
Hey @JokinC, 
I see it broken right when it starts to render the article itself: 
'''
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		<title>The Cooking Lab - Instant Articles</title>
		<link>http://thecookinglab.es</link>
		<description>Food lovers &#124; Food bloggers</description>
								<item>
				<title>Angel Food Cake perfecto</title>
				<link>http://thecookinglab.es/2017/01/angel-food-cake-perfecto/</link>
				<content:encoded>
					<![CDATA[
'''

Looks like some exception is being thrown while converting your article. Do you have access to the Wordpress server logs?

If you can please share within this thread so we can learn from this issue and also keep to posterity if somebody else hits this very same issue.

Sorry for the long wait, I was out for 3 weeks.

**Comment by JokinC** [comment]
Hey @everton-rosario 

First of all, thanks for following the error ;)

Where can I find the Wordpress server logs?

In my cPanel the error log is empty. However, in /logs i have .gz files for every month

**Comment by everton-rosario** [comment]
@JokinC it will depend on which server you are using in what OS.
By server I mean the web server hosting the PHP scripts (most likely it is an Apache or jetty or varnish or anything else :-)  )

And depending on the OS (macOS, ubuntu, redhat etc) will vary the path for the logs.

Google for "server name" logs in "yous OS system" and it will show where the log files lies.

**Comment by JokinC** [comment]
@everton-rosario I think that this is the log you were asking ;)

[error_log.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/749190/error_log.txt)

**Comment by everton-rosario** [comment]
@JokinC Looks like in these 2 lines lies the issue:

```
[02-Feb-2017 14:37:41 UTC] PHP Warning:  log4php: It looks like your code is using an __autoload() function. log4php uses spl_autoload_register() which will bypass your __autoload() function and may break autoloading. in /home/thecook/public_html/wp-content/plugins/fb-instant-articles/vendor/apache/log4php/src/main/php/LoggerAutoloader.php on line 22
[02-Feb-2017 14:37:42 UTC] PHP Fatal error:  Class 'DOMDocument' not found in /home/thecook/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 639
```

It is not finding the DOMDocument class, which is something related to your Autoloader.
You can try to change the import or any other class loader in your project to include the SDK + Plugin. 
And check if this error vanishes from log.

Let me know if you find out something here.

**Comment by JokinC** [comment]
@everton-rosario 
YEEEES! You gave me the perfect clue! 
I activated the "dom" extension in the PHP selector of my cPanel and now is working! 
Thanks a lot!

**Comment by everton-rosario** [comment]
@JokinC Im glad it worked!
Can you share here the steps you needed to do to setup this? This way you will be leading by example and helping others troubleshoot this as well.

Thanks for the help! 👍
