### ISSUE TITLE
Transformer rules for foo.gallery

### ISSUE THREAD

**Issue by DJUK16** [Automattic/facebook-instant-articles-wp#574]
Hello, i'm having issues making a Transformer rules for the following foo.gallery plugin.

Is there anyone on here who could help me please it will be quite simple for someone who knows how and will help so many people :) 

**Version Info**

* Plugin version: Latest 
* WordPress version:  Latest
* PHP version: Latest

**Comment by timjacobi** [comment]
Please continue the discussion in #573
