### ISSUE TITLE
No rules defined for fb-root

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#575]
I bet after updating the plugin to appear this error:
`No rules defined for <div> in the context of InstantArticle` (when you hover on the error he writes this: `<div id=”fb-root”></div>`)
`No rules defined for <div class=”fb-post”> in the context of InstantArticle`

what to do?

**Version Info**

* Plugin version: 3.2.2
* WordPress version:  4.7
* PHP version:  7.0.8

**Comment by jppgks** [comment]
@lubimow https://github.com/Automattic/facebook-instant-articles-wp#frequently-asked-questions

**Comment by timjacobi** [comment]
Duplicate of #582
