### ISSUE TITLE
Submit drafts as unpublished to instant articles

### ISSUE THREAD

**Issue by jppgks** [Automattic/facebook-instant-articles-wp#576]
*As a user, I want to be able to preview the generated instant article before my post is published to my website.*

Therefore, it would be nice if drafts would be submitted as unpublished to instant articles.

**Comment by jppgks** [comment]
Hmm, I didn't see #151 before. Looks like there are some differing views in the community 😁

**Comment by jppgks** [comment]
Wouldn't an option in settings to enable/disable this functionality be a solution?

**Comment by diegoquinteiro** [comment]
@jppgks I've commented on your PR =) let's move the conversation there.

**Comment by timjacobi** [comment]
Looks like this is done 👍 
Let's do any follow ups in #151
