### ISSUE TITLE
iOs Problem

### ISSUE THREAD

**Issue by charls637** [Automattic/facebook-instant-articles-wp#581]
I checked instant articles both iOs and Android, why is that in iOs it's not working but in android it works? any ideas

**Version Info**

* Plugin version: new
* WordPress version: new 
* PHP version: new

**Comment by charls637** [comment]
any update?

**Comment by charls637** [comment]
sample article:
https://www.ednc.org/2017/01/27/education-carnage-stir-em-inaugural/

can be viewed in android but not in iOs

**Comment by timjacobi** [comment]
I just tested it in iOS and it works. 
https://imgur.com/a/bNNR9
