### ISSUE TITLE
No rules defined for <div class="fb-post"> 

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#582]
# Steps required to reproduce the problem

after installing the latest version of the plug began to appear errors in posts with embedded put out facebook

```
No rules defined for <div> in the context of InstantArticle
No rules defined for <div class="fb-post"> in the context of InstantArticle
```

---

**Version Info**

* Plugin version: 3.3
* WordPress version: 4.7
* PHP version: 5.7

**Comment by timjacobi** [comment]
It depends on the content that is in your `div`. Can you post an example?

**Comment by timjacobi** [comment]
Also reported in #764 #727 #726 #652 #719 #676 #729 #603 #721 #732 #233
Generally anything containing a `<div>` will fail and we're going to see more issues around this. We should give this top priority.

**Comment by jeremyclarke** [comment]
What kind of solution are you imagining for divs that would apply to all of them?

It's up to users to make sure their custom content works with iA. It's up to this plugin to decide what custom content to support by default, and what to punt to users to fix or to complain to other plugin devs about adding support for this plugin into their plugins. 

You closed #732 even though it had a very precise explanation and a solution. This ticket has neither.

**Comment by jeremyclarke** [comment]
I'm glad for the renewed energy, but is there a roadmap for your plans that justifies closing all those tickets?

**Comment by timjacobi** [comment]
As mentioned above we will go through the referenced issues and make sure they are fixed once we have landed support for `<div>`. If some of them turn out not to be fixed I will reopen them but for now support for `<div>`s will be the top priority since it is a source for a lot of new issues. 

If you can already point out where only support for `<div>` won't be sufficient please leave your comment as you already did and I will reopen those issues like the tumblr related one.

We have reignited the development on this and are hoping to be in a position to lay out a roadmap soon.

**Comment by jeremyclarke** [comment]
Okay, hopefully you saw my reply in #732 about why there can be no global div solution. 

iA is kind of terrible, and most content breaks when put inside it, which is why we can't lump all problems involving divs together. 

I did a wordcamp talk about iA where I went over the ever-nesting complications of handling transformations from WP plugins. Hopefully it will be on wordpress.tv soon.

**Comment by guiwestrup** [comment]
I still have the same problem:
<div> in the context of InstantArticle>
<div class="mc-column content-text active-extra-styles "> in the context of InstantArticle>

This is my rules:
`{
   "rules":[
      {
         "class":"CaptionRule",
         "selector":"p.wp-caption-text"
      },
      {
         "class":"AnchorRule",
         "selector":"a",
         "properties":{
            "anchor.href":{
               "type":"string",
               "selector":"a",
               "attribute":"href"
            }
         }
      },
      {
         "class":"IgnoreRule",
         "selector":"center"
      },
      {
      "class": "PassThroughRule",
      "selector": "//div[descendant::mc-column]"
      },
      {
      "class": "ParagraphRule",
      "selector": "//p[descendant::content-text__container]"
      },
      {
         "class":"IgnoreRule",
         "selector":"div.mc-column content-text active-extra-styles"
      },
      {
         "class":"ParagraphRule",
         "selector":"p.content-text__container"
      },
      {
         "class":"BoldRule",
         "selector":"strong"
      },
      {
         "class":"LineBreakRule",
         "selector":"br"
      },
      {
         "class":"ImageRule",
         "selector":"div.wp-caption",
         "properties":{
            "image.url":{
               "type":"string",
               "selector":"img",
               "attribute":"src"
            },
            "image.caption":{
               "type":"element",
               "selector":"p.wp-caption-text"
            }
         }
      }
   ]
}`

Source Markup:
```
<p>O Carnaval está chegando, e muita gente já começou a se preparar para curtir a folia. E pra quem não quer ir muito longe, pode ficar ligado no que vai rolar nas cidades mais próximas aqui da região!</p>
<p>Dá uma olhadinha no que vai rolar:</p>
<h2>Joinville</h2>
<p>Em 2017 não teve Carnaval em Joinville, mas este ano ele está de volta. Vai contar com apresentações de blocos carnavalescos (Grupo Afoxé Omilodê, Unidos pela Diversidade, Dragões do Samba, Príncipes do Samba, Fusão do Samba, Unidos do Caldeirão e Acadêmicos do Serrinha) e estrutura ao público (grades de segurança, banheiros químicos, equipamentos de som e iluminação).</p>
<p>O desfile está marcado para o dia 10 de fevereiro, a partir das 19h. Vai acontecer na Av. José Vieira (Beira Rio), em um trecho de 200 metros entre estacionamento de cargas do Supermercado Big (início) até esquina com a rua Max Colin (dispersão).</p>
<p>&nbsp;</p>
<h2>Florianópolis</h2>
<p>Se está disposto a viajar até a capital, já pode começar a se programar e fazer a compra dos ingressos. As entradas para os desfiles das escolas de samba começaram a ser vendidas <a href="http://www.ingressorapido.com.br/" target="_blank" rel="noopener">pela internet</a>. Os valores variam de R$ 20 (meia-entrada arquibancadas) até R$ 11 mil (camarote para 44 pessoas).</p>
<div class="mc-column content-text active-extra-styles active-capital-letter" data-block-type="unstyled" data-block-weight="33" data-block-id="2"></div>
<div class="mc-column content-text active-extra-styles " data-block-type="unstyled" data-block-weight="47" data-block-id="3"></div>
<div class="mc-column content-text active-extra-styles " data-block-type="unstyled" data-block-weight="36" data-block-id="4">
<p class="content-text__container " data-track-category="Link no Texto" data-track-links="">Cada entrada dá direito a assistir o desfile de sábado de carnaval, bem como o desfile das campeãs no dia 13 de janeiro, terça-feira. Os desfiles começam às 21h de sábado, com portões abertos às 17h30.</p>
</div>
<div class="mc-column content-text active-extra-styles " data-block-type="unstyled" data-block-weight="16" data-block-id="5">
<p class="content-text__container " data-track-category="Link no Texto" data-track-links="">Conforme a organização, serão disponibilizados outras modalidades de ingresso de camarote a partir da próxima semana.</p>
</div>
<div data-track-category="fim do conteudo" data-track-action="ultimo chunk conteudo" data-track-noninteraction="false" data-track-scroll="entrada completa viewport">
<div class="mc-column content-text active-extra-styles" data-block-type="raw" data-block-weight="39" data-block-id="7">
<ul class="content-unordered-list">
<li>Arquibancadas &#8211; setores 3, 4, 5 e 6 &#8211; R$ 40 inteira e R$ 20 meia entrada</li>
<li>Camarote no prédio Nega Tide &#8211; setor 8 &#8211; R$ 5,5 mil para 22 pessoas e R$ 11 mil para 44 pessoas</li>
</ul>
<h2>São Francisco do Sul</h2>
<p>Na cidade de São Francisco do Sul, algumas praias vão receber a folia. Mas a programação completa vai ser divulgada no fim da tarde desta quinta-feira (18), em coletiva de imprensa organizada pela Prefeitura.</p>
<p>&#8230;</p>
<p>Ficou sabendo de mais alguma cidade aqui perto que vai ter um belo Carnaval? Não deixe de nos informar, assim a gente pode aumentar esta lista! 😉</p>
</div>
</div>
```

And Transformed Markup:

```
<html>
  <head>
    <link rel="canonical" href="https://testers.ocponline.com.br/teste/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.6"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="guiwestrup"/>
  </head>
  <body>
    <article>
      <header>
        <h1>teste</h1>
        <time class="op-published" datetime="2018-01-18T14:04:41-02:00">January 18th, 2:04pm</time>
        <time class="op-modified" datetime="2018-01-18T14:04:41-02:00">January 18th, 2:04pm</time>
        <address><a>Testers OCP</a></address>
      </header>
      <p>O Carnaval está chegando, e muita gente já começou a se preparar para curtir a folia. E pra quem não quer ir muito longe, pode ficar ligado no que vai rolar nas cidades mais próximas aqui da região!</p>
      <p>Dá uma olhadinha no que vai rolar:</p>
      <h2>Joinville</h2>
      <p>Em 2017 não teve Carnaval em Joinville, mas este ano ele está de volta. Vai contar com apresentações de blocos carnavalescos (Grupo Afoxé Omilodê, Unidos pela Diversidade, Dragões do Samba, Príncipes do Samba, Fusão do Samba, Unidos do Caldeirão e Acadêmicos do Serrinha) e estrutura ao público (grades de segurança, banheiros químicos, equipamentos de som e iluminação).</p>
      <p>O desfile está marcado para o dia 10 de fevereiro, a partir das 19h. Vai acontecer na Av. José Vieira (Beira Rio), em um trecho de 200 metros entre estacionamento de cargas do Supermercado Big (início) até esquina com a rua Max Colin (dispersão).</p>
      <p> </p>
      <h2>Florianópolis</h2>
      <p>Se está disposto a viajar até a capital, já pode começar a se programar e fazer a compra dos ingressos. As entradas para os desfiles das escolas de samba começaram a ser vendidas <a href="http://www.ingressorapido.com.br/">pela internet</a>. Os valores variam de R$ 20 (meia-entrada arquibancadas) até R$ 11 mil (camarote para 44 pessoas).</p>
    </article>
  </body>
</html>
```

**Comment by mburak** [comment]
Hi @guiwestrup, you can add a new custom rule to avoid those warnings: `{ "class": "PassThroughRule", "selector": "div" }`

**Comment by guiwestrup** [comment]
@mburak hi, thank you very much, i had tried PassThroughRule previously, maybe i made a mistake.

**Comment by mburak** [comment]
I'm closing it for now. Let us know if that doesn't work for you.

**Comment by jerclarke** [comment]
That is going to "work" but in testing, they better look very carefully at the actual outcome when viewed in Instant Articles (via a mobile app). 

Making all divs use `PassThroughRule` is an unambiguous overkill, and will have wide ranging impacts on the coherence of your content in iA that will be unpredictable. There are all kinds of things that might be wrapped in divs, and often blindly removing those divs will result in the content no longer making sense. 

In many cases it is better to have some posts that just don't get submitted as iA (and thus render using your responsive theme, where the div's should have their intended effect) rather than have them be sent as iA but stripped of their divs, thus creating useless content for facebook users (and which you are unlikely to notice unless you preview every single post in Instant Articles format, which you honestly should do).

**Comment by Presenze** [comment]
My problem con istant article No rules defined for <div class="separator"> in the context of InstantArticle

**Comment by santoshnayak** [comment]
I got the solution. You need to find the class that causing this issue and need to remove it.

for me `<div class="entry-content"> ` this entry content was giving the issue. I went to the text mode of the article and deleted the div with class **entry-content** and the article transformed to the instant article.


Give it a +1 if it solved your issue. 
Thanks
