### ISSUE TITLE
Encoding Issue?

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#583]
# Steps required to reproduce the problem

1. Create Content 
2. Publish 
3. Check on FB production articles

# Expected Result

* Chinese Character Display Fully 

# Actual Result

* Seem like encoding issue - attached image
<img width="756" alt="screen shot 2017-01-11 at 9 17 27 pm" src="https://cloud.githubusercontent.com/assets/4049250/21850210/7646a016-d844-11e6-8a07-91e2311f79e2.png">

Remarks: Only happen to 30% of the article. 

---

**Version Info**

* Plugin version: 3.3
* WordPress version: 4.7
* PHP version: 5.6.5

**Comment by diegoquinteiro** [comment]
Can you give us examples (URLs) of working articles vs broken articles?

**Comment by alshakero** [comment]
@diegoquinteiro it's an FB bug, not your fault I guess. Happened to me and I did was deleting the articles from FB instant articles and by the next fetch they were OK.

It's unrelated to your addon. I faced this with pure RSS.
