### ISSUE TITLE
Missing logo & Unable to submit for review 

### ISSUE THREAD

**Issue by sabrinahui** [Automattic/facebook-instant-articles-wp#584]
Hi, I'm experiencing an issue that I'm unable to submit articles for review as it stated Missing Logo (All articles must include a logo, which you can upload in the Style Editor). But actually I have already created a template with my logo on. (in FB publishing tool page) 
 
Are there any ways to solve this problem? I submit articles via wordpress. 

**Version Info**

* Plugin version: 3.3
* WordPress version: 4.3.4
* PHP version:

**Comment by Fonexie** [comment]
Just upload a logo in the default style created by facebook

**Comment by feudadrien** [comment]
Thank you @Fonexie . It works

**Comment by Fonexie** [comment]
You're welcome bro

**Comment by thegaka** [comment]
Still same problem. I upload a logo on all design but problem didn't solve.

**Comment by nguyenchilong** [comment]
thanks! working

**Comment by idansh** [comment]
Where in wordpress I can do that, upload a logo in the default style, can't find it in the UI.

**Comment by marktwatson** [comment]
You have to do in under publishing tools/Instant Articles/Configuration


[image: photo]
*Mark Watson*
President, Go Viral LLC
530-255-4453 | mark@letsgoviral.co | Skype: marktwatson1 <#>
Create your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by jjsnjan** [comment]
it works
