### ISSUE TITLE
Could Not Download Image (from CDN) - error code 403

### ISSUE THREAD

**Issue by mintaras** [Automattic/facebook-instant-articles-wp#587]
# Steps required to reproduce the problem

1. Post blog article from wordpress
2. 
3. 

# Expected Result

* Make image to show up

# Actual Result

* Image cannot load, error 403 forbidden
* Could Not Download Image: Your image from URL http://www.example.com/wp-content/uploads/2016/08/sbd.jpg could not be downloaded with an error code 403. Please check to make sure image at http://www.example.com/wp-content/uploads/2016/08/sbd.jpg is active and loads correctly at that URL.

---

**Version Info**

* Plugin version: 3.3
* WordPress version: 4.7.1
* PHP version: 5.5.1

**Comment by mintaras** [comment]
I have this notice on Facebook publishing tools:
![screen shot 2017-01-17 at 18 05 43](https://cloud.githubusercontent.com/assets/5816172/22028393/b77c63e6-dcdf-11e6-8db7-417518334b4e.png)

**Comment by mintaras** [comment]
I think this is related https://github.com/Automattic/facebook-instant-articles-wp/issues/281
We are using CDN for images too. How to block the services of CloudFlare on feed/instant-article?

**Comment by zomidaily** [comment]
I receive the same problem (but error code 502) after I enable Cloudflare, here is the error message:

The server responded with the following messages:
Could Not Download Image: Your image from URL https://www.domain.com/wp-content/uploads/2017/03/29coke.jpg could not be downloaded with an error code 502. Please check to make sure image at https://www.domain.com/wp-content/uploads/2017/03/29coke.jpg is active and loads correctly at that URL.

**Comment by boslmreds** [comment]
i got the same issue. error 403. Is that been solved?

**Comment by PaoloPhino** [comment]
Same problem here, but no solution yet...
I have to manually disable CloudFlare when I work on Instant Articles and re-enable it when I'v finished
