### ISSUE TITLE
Article is live under "Production Articles" Tab but did not publish on page

### ISSUE THREAD

**Issue by Vish464** [Automattic/facebook-instant-articles-wp#589]
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

* 

# Actual Result

* 

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by diegoquinteiro** [comment]
Publishing an instant article does not automatically creates a post on your page. It only makes every post on FB with that URL to render as an IA, but you still need to post it on your page if you want.
