### ISSUE TITLE
Custom transformer rules problem.

### ISSUE THREAD

**Issue by MelangeCrew** [Automattic/facebook-instant-articles-wp#594]
# Steps required to reproduce the problem

1. I type and save Custom transformer rules
2. Rules json is valid
3. On post edit page, Facebook Instant Articles load infinitely

# Expected Result

*  On post edit page, Facebook Instant Articles get - Your article was submitted to Instant Articles successfully or problem info

# Actual Result

* On post edit page, Facebook Instant Articles load infinitely 

---

**Version Info**

* Plugin version: 3.3 
* WordPress version: 4.7
* PHP version:  5.6

**Comment by diegoquinteiro** [comment]
Hi @MelangeCrew, thanks for reaching out. Can you please paste your custom transformer rules so I can repo the problem?

**Comment by timjacobi** [comment]
Closing as this hasn't been responded to in too long.
