### ISSUE TITLE
How do I change kicker text?

### ISSUE THREAD

**Issue by nullsmegh** [Automattic/facebook-instant-articles-wp#596]
The kicker text is the category the post it is in. What if I want it to be a custom field?

**Comment by nullsmegh** [comment]
Got it
function change_ia_kicker( $kicker_name, $post_ID ) {
			$kicker_name = get_post_meta($post_ID, 'post-caption-text', true);
    return $kicker_name;
}
add_filter( 'instant_articles_cover_kicker', 'change_ia_kicker', 10, 2 );

**Comment by theRiesgo** [comment]
I am not seeing a solution to this issue, yet it was closed. 
I am having the same issue. Any help?

**Comment by nullsmegh** [comment]
Use the `instant_articles_cover_kicker` hook

**Comment by theRiesgo** [comment]
@nullsmegh do you have an example of how that hook would look? I have found the get_the_kicker() function in class-instant-articles-post.php, but I am just not sure alter it so that it pulls a custom field from the post instead of the category?

**Comment by nullsmegh** [comment]
You would need to return the custom field

**Comment by nullsmegh** [comment]
function setnewkicker( $kicker, $post_id ) {    
    return get_post_meta($post_id, 'key', true);
}
add_filter( 'instant_articles_cover_kicker', 'setnewkicker', 10, 2 );

**Comment by theRiesgo** [comment]
That did it! Thanks a lot for your help @nullsmegh

**Comment by nullsmegh** [comment]
You're welcome

**Comment by nullsmegh** [comment]
You're welcome
