### ISSUE TITLE
3.3.1 Changelog???

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#599]
Good day

What are the changes done from 3.3.0 to 3.3.1???

Thanks a lot
Daniel

**Comment by jeremyclarke** [comment]
Or for 3.2 to 3.3 for that matter. 

This plugin is extremely important to those who use it.

**Comment by diegoquinteiro** [comment]
Thanks for the feedback guys. I'll be automating the creation of a changelog as of the next version. For now you can check the commits made between the tags.

On 3.3.1 these were mostly bugfixes.

**Comment by jeremyclarke** [comment]
Thanks Diego, appreciate it. 

You can imagine how, as we update the plugin on our sites, having that info right there in the updater UI is 1000% more convenient. If it was a link to the set of commits I'd accept that too (welcome it even) but for a lot of users, a user-focused summary is the best choice.

**Comment by timjacobi** [comment]
You can review commits between to versions using the Github compare tool.
https://github.com/Automattic/facebook-instant-articles-wp/compare/4.0.0...Automattic:4.0.5
Just modify the versions in the URL to your needs.
