### ISSUE TITLE
Need to be able to handle embeds/iframes

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#60]
Right now the only embeds that work are the few that utilize Facebook's op-social method (Instagram, Twitter, Facebook, Vine, and Youtube). However, in order for publisher's articles to be approved by Facebook, there needs to be a way to handle other embeds/iframes.

The official response I received from Facebook on how to deal with other embeds/iframes is this:

"For social embeds, you can use an op-social figure if it's static content, or the op-interactive figure if the user should be able to interact with it in any way."

So there needs to be a DOM transformation filter for embeds/iframes that are not on the op-social list. For example, you could start with some of the major players like Tumblr, Vimeo, etc.

**Comment by kkranzo** [comment]
Any update on when this will be added @bjornjohansen?

**Comment by kkranzo** [comment]
And there should be a catch-all that just wraps any iframe tag with a op-interactive figure tag like below:

```
<figure class="op-interactive">
	<iframe>
    <!-- Iframe tag goes here -->
	</iframe>
</figure>
```

**Comment by kkranzo** [comment]
Any update on when this will be added @bjornjohansen or @philipjohn?

**Comment by philipjohn** [comment]
@diegoquinteiro Could you advise on what the best way forward here would be? I know we can filter the content, but is there anything more targeted we can do?

**Comment by everton-rosario** [comment]
@kkranzo We are working on the compatibility of our plugin, to work on more EMBED codes.
Right now, what we recommend is: 
Implement the solution for the embed short code you have using a hook, just like we did in the Plugin code for treating the embeds shortcodes you've mentioned (Facebook, Twitter etc.)

Relating to the current oficial solution, you should use op-interactive (https://developers.facebook.com/docs/instant-articles/reference/embeds)

Feel free to reopen or to file another task.
