### ISSUE TITLE
Check if Instant Article is created/submitted for the post/page

### ISSUE THREAD

**Issue by markovic-nikola** [Automattic/facebook-instant-articles-wp#600]
Hello,
Might be an easy question, but I'm struggling with this.

**How can I check if the post/page is published with Instant Articles?**
I'm developing a plugin where I'm inserting a video as shortcode, but I would like to check first if the post is submitted to IA in order to insert an iframe so it satisfies IA regulations.

Thanks upfront!

**Comment by timjacobi** [comment]
Do you mean if the post already has been submitted to IA while you are editing it or if the post is valid and will be submitted to IA?
