### ISSUE TITLE
rules problem

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#603]
I have several problems with the rules:

1. No rules defined for `<div class="fotorama--wp">` in the context of InstantArticle
Install plugin fotorama
2. No rules defined for `<div>` in the context of InstantArticle
3. No rules defined for `<div class="fb-post">` in the context of InstantArticle
Insert facebook post

---

**Version Info**

* Plugin version: 3.3.1 
* WordPress version: 4.7.2
* PHP version: 7.0.12

**Comment by lubimow** [comment]
@diegoquinteiro Help solve this problem.

**Comment by off-bank** [comment]
Like number 2 above (No rules defined for <div> in the context of InstantArticle), how to convert a div without a class?

**Comment by lubimow** [comment]
@diegoquinteiro Hello. Did not you find a solution to my problem?

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
