### ISSUE TITLE
need help to fix the problem of  RTL direction 

### ISSUE THREAD

**Issue by yaraan** [Automattic/facebook-instant-articles-wp#606]
# Steps required to reproduce the problem

Open any instant article which is already published in our page [https://www.facebook.com/yaraanweb/ ](url)

# Expected Result
we expect to show the Pashto text of facebook instant article in fully RTL direction. 

# Actual Result
but the text is not showing in fully right to left direction.
even the text looks in the right side of the page, but it looks like the text-align is still left to right (ltr). 
 Especially text punctuation in the end of Paragraphs and links still look in LTR direction.
but our website and the facebook Article Style which we created are supporting RTL.

---

**Version Info**

* Plugin version: 3.3.1
* WordPress version:  4.7.2
* PHP version: 5.6.24

**Comment by yaraan** [comment]
![screenshot_2017-02-07-12-22-24](https://cloud.githubusercontent.com/assets/22754661/22727671/6f997c4c-edda-11e6-9d48-b1bf5b50434a.png)
![Uploading Screenshot_2017-02-07-12-25-14.png…]()

**Comment by timjacobi** [comment]
Just verified this on your recent article and it seems to have been fixed. Please report if you're still encountering problems.

**Comment by rajiweb1** [comment]
Hello, i have the same problem.
[https://github.com/timjacobi] : please what can i verify on my articles ?
thanks

**Comment by timjacobi** [comment]
Please post your input HTML and the transformed output and a screenshot of the rendered Instant Article.
