### ISSUE TITLE
[Instant Article] Content is blank

### ISSUE THREAD

**Issue by Veeravaj** [Automattic/facebook-instant-articles-wp#607]
# Steps required to reproduce the problem

Let me explain you step by step as below

1. In the morning of 6 February, we update an article in wordpress. Everything seems ok, our content is live on instant article normally as attached picture 01.jpg.

![01](https://cloud.githubusercontent.com/assets/25628349/22723201/14b6871a-edef-11e6-832c-c83f6ee2a991.jpg)

2. But when we check the code in instant ariticle, we fould that there is no content in this code. There is only heading code and anlytic code as picture 02.jpg.

![02](https://cloud.githubusercontent.com/assets/25628349/22723206/1a8c65ba-edef-11e6-86f3-63a48aa7e0da.jpg)

3. Compare the code between bug content and completed content as picture 03.jpg

![03](https://cloud.githubusercontent.com/assets/25628349/22723212/1fede420-edef-11e6-8c7f-ca2f0e35ada5.jpg)

4. We check this content in mobile (instant article) and we also found that there is no content, it's blank. There is only heading and suggested article as picture 04.jpg

![04](https://cloud.githubusercontent.com/assets/25628349/22723218/2727e010-edef-11e6-98e4-fd21aa0e9471.jpg)

5. We used plugin Instant Article for WP (developed by Facebook).

6. We check the plugin and we found that App has logout as picture 05.jpg 

![05](https://cloud.githubusercontent.com/assets/25628349/22723220/2d8e236a-edef-11e6-9042-69c1d0debdc4.jpg)

7. Then I remember that my team change this facebook accout's password in the morning of 5 February, one day before the problem occured. (That's why the App has logout.)

8. We login the App again but it's still not work.

9. We doubt that why the password was changed on 5Feb (morning) but the problem just occur on 6Feb (morning). On 5 Feb (afternoon) we created a few article and there is no problem.

10. I think the plugin is the cause of problem. So I try to fix this problem with many ways
- Update plugin
- Disable and enable plugin
- Re-install plugin
- Use old version of other website
- Change the App to the new one
All above do not work. 

11. One way to solve it is changing "Instant Article for WP" to other plugin.

Actually I don't want to use other plugin because it's not stable. Please help me, I have no idea to solve it. If you have any questions, please feel free to contact me.

# Expected Result

* The problem is solved, I need to use this plugin.

# Actual Result

* 

---

**Version Info**

* Plugin version: 3.3.1
* WordPress version: 4.7.2 
* PHP version: 5.6.24-0+deb8u1

**Comment by harryshawk** [comment]
I have a similar error. I'm on DreamHost/DreamPress

Plugin 3.3.1
WP 4.7.2
PHP 7.0

You can see the no content error. 

I have developer mode on, this error is visible in: business.facebook.com, Page, Instant Articles, Developer mode. It is the only page that has an error (see below).

![french no content](https://cloud.githubusercontent.com/assets/25712065/22857192/6b5bff56-f06e-11e6-83d4-ea3585c1aeed.png)

However, in the plugin, there are there pages that have errors: <div itemscope... > the section that has the schema code for audio objects. These errors appear within the UI within the PLUGIN but not within the business.facebook.com | Page | etc. as noted above. 
![3 posts have errors](https://cloud.githubusercontent.com/assets/25712065/22857213/ee9e8104-f06e-11e6-9861-a0242525b3fc.png)

![in dev different error set than in wp](https://cloud.githubusercontent.com/assets/25712065/22857214/ee9e85b4-f06e-11e6-9b09-e3f389a91ec7.png)
