### ISSUE TITLE
Constant loading spinner in box on Post page

### ISSUE THREAD

**Issue by stopsatgreen** [Automattic/facebook-instant-articles-wp#613]
Have already installed and run FIA plugin in WP, published some of my posts to Instant Articles. But since recent WP update, when I go into a Posts area in WP I just get the loading spinner in the Instant Articles box and nothing else is shown. Took a look in the console, seems there may be a problem with `instant-articles-meta-box.js`.

<img width="1388" alt="screenshot 2017-02-14 11 28 58" src="https://cloud.githubusercontent.com/assets/98774/22927617/436df56a-f2aa-11e6-9800-b42f41206101.png">

# Steps required to reproduce the problem

1. Connect Wordpress with FIA plugin to Instant Articles publishing on Facebook
2. Visit an add/edit Post area in WP
3. Look in the Facebook Instant Articles box at the bottom of the page

# Expected Result

* Should see information about the post for publishing to Facebook

# Actual Result

* A loading spinner that never resolves. Error in the console.

---

**Version Info**

* Plugin version: 3.3.2
* WordPress version: 4.7.2
* PHP version: 5.6.30

**Comment by diegoquinteiro** [comment]
Hi @stopsatgreen, thanks for reporting. Could you update to 3.3.3 and check if it reproduces?

Also, if possible, can you check if any specific log message is shown on your logs related to this issue?

**Comment by stopsatgreen** [comment]
Upgraded to 3.3.3, no fix. I ran debugging, and seemed it was choking on a custom rule I’d set up — strange, because it had published with that rule before. The rule in question was this:

```
{ "rules": [{
        "class": "HorizontalRule",
        "selector": "hr"
}]}
```

This was the debug log output:

```
[15-Feb-2017 17:23:22 UTC] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Facebook\InstantArticles\Transformer\Rules\HorizontalRule does not exist' in /home/clauacom/public_html/camberwell/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php:301
Stack trace:
#0 /home/clauacom/public_html/camberwell/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php(301): ReflectionMethod->__construct('Facebook\\Instan...', 'createFrom')
#1 /home/clauacom/public_html/camberwell/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(621): Facebook\InstantArticles\Transformer\Transformer->loadRules('{\r\n    "rules":...')
#2 /home/clauacom/public_html/camberwell/wp-content/plugins/fb-instant-articles/meta-box/class-instant-articles-meta-box.php(95): Instant_Articles_Post->to_instant_article()
#3 [internal function]: Instant_Articles_Meta_Box in /home/clauacom/public_html/camberwell/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php on line 301
```
