### ISSUE TITLE
Bloating of WP Options Table with _transient_instantarticles

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/facebook-instant-articles-wp#614]
# Steps required to reproduce the problem

I have now over 1k lines of _transient_instantarticles_mod and _transient_instantarticles_content in wp options table?  Is this normal?  

* Plugin version: 3.3.2
* WordPress version:  4.7.2
* PHP version: 7.0.15

**Comment by diegoquinteiro** [comment]
Hi @Verticalmag, this is normal, transient options are the storage of a cache layer we use to improve performance.

**Comment by Verticalmag** [comment]
Hi @diegoquinteiro, I figured as much but would some of them not expire? Or do you need to keep one for each post unless it was removed from production?

If I publish 1k of IA and make changes do I need to keep all of them?  or would one update reference all?
