### ISSUE TITLE
<sup> should be a common rule by default

### ISSUE THREAD

**Issue by Daweide** [Automattic/facebook-instant-articles-wp#615]
Hi,

I think `<sup>` should be a common rule by default

**Comment by atdr** [comment]
Agree. Had to create a `PassThroughRule` for `<sup>` and `<sub>` almost immediately after installing plugin. Creating a rule would probably be a major deterrent for first-time or non-technical users.

**Comment by everton-rosario** [comment]
@Daweide and @atdr agree with you guys.

**Comment by timjacobi** [comment]
Please track progress of this in #632
