### ISSUE TITLE
Ads - Method to limit how often an ad is shown or Manual placement

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/facebook-instant-articles-wp#618]
# Steps required to reproduce the problem

https://www.verticalmag.com/features/meet-the-king/
 When we publish using the plugin we get our ad displayed many times through the article based on the automatic rules for ad spacing from facebook.

Automatic Ad Placement will be enabled if an article has more than one ad for every 350 words or if ads exceed 15% percent of the total content.

Is it possible to do Manual Placement with the plugin?  Where we can say we want the ad to show only:
a. Once at the top?
b. Top and bottom?

Our issues is with the article mentioned above... the ads become a pain and take away from the story.  We would like them but far fewer displayed through out.  Or the easy option to publish some without ads. 

# Expected Result
- To space ads
- Manual placement
-Button / Checkbox in publishing to either publish with or without ads vs a global variable in the advance options.

**Version Info**

* Plugin version: Version 3.3.3
* WordPress version:  4.7.2
* PHP version: 7......

**Comment by timjacobi** [comment]
Yes this is possible. Please refer to the documentation on ad placement.
https://developers.facebook.com/docs/instant-articles/monetization/ad-placement
