### ISSUE TITLE
Date published vs updated

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#62]
Noticed today this in the RSS feed:

```
				<pubDate>2016-03-16T01:40:29+00:00</pubDate>
				<modDate>2016-03-15T23:49:07+00:00</modDate>
```

Shouldn´t the **modDate** be in this case set at the same as the **pubDate**?

**Comment by gabu69** [comment]
Also I think the <lastBuildDate> is not being updated as soon as new article is being updated

Today I'll monitor all this.

But so far I noticed since yesterday that my RSS was approved, that all my scheduled articles (that were scheduled some days ago) are not ebing indexed inmediatelly by facebook IA.

Shouldn't scheduled published articles modDate shouldnt be updated to mark it as a new update for the RSS?

**Comment by philipjohn** [comment]
It looks like this is expected - the pubDate should show the date when the article was *first published* and the modDate is that date of the most recent modification.

As for the scheduling, we did have an issue there which is fixed in v2.
