### ISSUE TITLE
Add post ID to `instant_articles_content` filter as param

### ISSUE THREAD

**Issue by dashaluna** [Automattic/facebook-instant-articles-wp#621]
Can we please add post ID as parameter to `instant_articles_content` filter here https://github.com/Automattic/facebook-instant-articles-wp/blob/master/class-instant-articles-post.php#L349

I'm facing a specific issue when there is a shortcode in content that's been processed via usage of `new WP_Query()`, `setup_postdata()` and `wp_reset_postdata()`. The global `$wp_query` isn't setup as we're just doing this https://github.com/Automattic/facebook-instant-articles-wp/blob/master/meta-box/class-instant-articles-meta-box.php#L86 instead of setting up global `$wp_query`.

So in this case, when I use`wp_reset_postdata` it doesn't reset to global `$wp_query` as it's never setup. And the `get_the_ID()` ends up being the last ID used in a shortcode query.

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.1
* PHP version: 5.6

**Comment by jeremyclarke** [comment]
Yes please!!! This is super important as right now SO many potential filter uses are impossible. 

We submitted a PR with the fix 19 days ago :)

https://github.com/Automattic/facebook-instant-articles-wp/pull/602

**Comment by timjacobi** [comment]
Closing since PR was merged.
