### ISSUE TITLE
DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/facebook-instant-articles-wp#628]
DOMDocument::loadHTML(): Empty string supplied as input
 Type: PHP Warning Line: 178
 File:  /wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php

Is this a bug or just a null value?

**Comment by dashaluna** [comment]
I'm seeing the same error report in the New Relic.

**Comment by 56miles** [comment]
I'm getting this error as well.

**Comment by abdusfauzi** [comment]
It seems the Transformer function received empty $content in its parameter:

`public function transformString($context, $content, $encoding = "utf-8"){...}`

It could be that somebody created a new Post and saved before any content has been written into the Editor, we submitted empty $content to this function.

**Comment by thomas-dotworx** [comment]
This should also fix #502, right?

**Comment by timjacobi** [comment]
Closing as this is a bug in the old version which should be fixed in the latest release.
