### ISSUE TITLE
Transformer error on <meta> tag

### ISSUE THREAD

**Issue by atdr** [Automattic/facebook-instant-articles-wp#630]
I'm getting transformer errors for `<meta>` tags—despite there being none in the post itself.

The error is `No rules defined for <meta> in the context of InstantArticle` and the HTML that causes it is
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

Normally I'd just add the tag to an `IgnoreRule` but given that other published Instant Articles contain `<meta charset="utf-8"/>`, I'm not sure if it's the right thing to do.

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.2–en_GB
* PHP version: 7.0.15

**Comment by everton-rosario** [comment]
Hey @atdr, have you configured something different on the flow for the transformation process to be triggered?
Those `<meta>` tags, shouldn't be on the source code before transformation happens, unless this is within your article text content.

Is it in the actual article text? If so, please add this IgnoreRule.
Otherwise, make sure you didn't change the order of the transformation process.

One way to check if the content is present or not on the transformation process, just double check by clicking in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**" so I can help more with.

I'll be closing this one, until we get more info. Feel free to reopen.

**Comment by atdr** [comment]
@everton-rosario—
Here's [the markup for an article](https://gist.github.com/atdr/8deb109e223f7d339ba96ed6c5ef0728) that's giving the error. There are no `<meta>` tags in the source markup. Still investigating potential conflicts with other plugins.

**Comment by SoozaV** [comment]
Hi. I have the same problem:

No rules defined for <meta> in the context of Header
No rules defined for <meta> in the context of InstantArticle

and the HTML that causes it is

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

Source Markup: Empty

Transformed Markup:
`<html>
  <head>
    <link rel="canonical" href="http://www.winfifty.com/borrador-automatico/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.5.7"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="3.3.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.5.7"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="true"/>
    <meta property="fb:article_style" content="Winfifty"/>
  </head>
  <body>
    <article><header><h1>Borrador automático</h1><time class="op-published" datetime="2017-06-07T17:44:46-05:00">June 7th, 5:44pm</time><time class="op-modified" datetime="2017-06-07T17:44:46-05:00">June 7th, 5:44pm</time><address><a>admin</a></address><figure class="op-ad"><iframe src="https://www.facebook.com/adnw_request?placement=763707280481668_766129943572735&amp;adtype=banner300x250" width="300" height="250"></iframe></figure></header></article>
  </body>
</html>`

**Comment by mjgritli** [comment]
Hello all, did anyone solve this problem, i'm facing it right now ?

**Comment by atdr** [comment]
@mjgritli—
I didn't manage to pinpoint something that might be changing the transformation process as @everton-rosario suggested might be the case so I went ahead and added `meta` to an `IgnoreRule`. It's not ideal having to use a workaround but unless one of us can pinpoint what might be causing this issue then it's all we can do I think.

**Comment by mjgritli** [comment]
thanx for your reply, could you please point me to how/where can i add the IgnoreRule ?
Thank you again .

**Comment by atdr** [comment]
As per [the FAQs](https://github.com/Automattic/facebook-instant-articles-wp#frequently-asked-questions)

>  **How do I define my own transformer rules so that content from my site is rendered appropriately in an Instant Article?**
>  
>  Your custom rules can be defined in the Settings of this plugin, under: **Plugin Configuration** > **Publishing Settings** > **Custom transformer rules**. More detailed instructions about all the options available is documented in the [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules) section of the Facebook Instant Articles SDK.

If you're new to [transformer rules](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules), this should work to ignore the `meta` tag:
```json
{ "rules" : [
    {
	    "class" : "IgnoreRule",
	    "selector" : "meta"
    }
] }
```

**Comment by swellart** [comment]
Hello all! 
Same problem. First warning appears at the moment when I fill the name field of new post and the second one when you save the content. (you can enter just one word as a content) Plus I can't submit anything to FB even after adding ignore rules and with checked box to submit the articles with warnings. As a result - no warnings after adding ignore rules and nothing submitted.
