### ISSUE TITLE
Article errors with bulk post editor

### ISSUE THREAD

**Issue by atdr** [Automattic/facebook-instant-articles-wp#631]
# Steps required to reproduce the problem

1. Edit multiple posts using WordPress bulk post editor
    - no edits made—bulk editor used to submit posts to IA in large batches
    - have had problems for both ~10 and ~100 posts

Server is on DigitalOcean. Have experienced the problem on both 512MB and 1GB droplets. Would rate-limiting IA updates to reduce potential overload be a solution?

# Expected Result

-  Instant Articles update, or are created (for old posts) in the normal manner

# Actual Result

Various errors, including
- category offset by 1 article i.e. each article had the category label of the previous post
- empty articles
- post excerpt appearing as IA content
- featured image not appearing in article header despite appearing in preview card

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.2–en_GB
* PHP version: 7.0.15

**Comment by everton-rosario** [comment]
Thanks for flagging this issue @atdr 
If you can help us by trying out a PR, I can help you with.
Also, if you haven't joined our FB group, please do so:  https://web.facebook.com/groups/629655867187397/
There we have releases, announcements, events and all exchange between all Open Source tools regarding Instant Articles.
