### ISSUE TITLE
[audio] shortcode/<audio> tag not being transformed

### ISSUE THREAD

**Issue by MarcusWernicke** [Automattic/facebook-instant-articles-wp#636]
I am trying to get the `[audio]` shortcode to work with IA. The `[embed]` shortcode works fine for videos, but when trying to do the same with audio files, I am getting this:

No rules defined for `<audio class="wp-audio-shortcode">` in the context of InstantArticle

The generated audio produced by the [audio] shortcode looks like this:
`<audio class="wp-audio-shortcode" id="audio-5034-1" preload="none" style="width: 100%;" controls="controls"><source type="audio/mpeg" src="https://....mp3?_=1" /><a href="https://....mp3">https://....mp3</a></audio>
`

Am I doing anything wrong?

**Comment by webbasica** [comment]
Same here. They found a bug and disabled the feature. Don't use audio tags

**Comment by timjacobi** [comment]
We don't currently support `<audio>` tags.
