### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by andhikamaheva** [Automattic/facebook-instant-articles-wp#637]
# Steps required to reproduce the problem

1. Active Plugins
2. Configure the Instant Article needs
3. Submit for review

# Expected Result

* Success message after submit review

# Actual Result

* After submit review showing error message **An unknown error occurred**

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version: 7.0.16

**Comment by CallMeJess** [comment]
Did you ever find a fix to this?

**Comment by arbo-hacker** [comment]
Presento el mismo problema, hay algun workaround?

**Comment by andhikamaheva** [comment]
Not yet @CallMeJess, I still have the error.

**Comment by timjacobi** [comment]
This issue was raised against an old version of the plugin. Please update the plugin to the latest version which should fix the issue.
