### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by izzuddinfz** [Automattic/facebook-instant-articles-wp#639]
Using plugin version 3.3.3 on wordpress version 4.7.3 using ServerPilot. Got this error:

Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /srv/users/serverpilot/apps/moshedwp/public/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /srv/users/serverpilot/apps/moshedwp/public/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /srv/users/serverpilot/apps/moshedwp/public/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /srv/users/serverpilot/apps/moshedwp/public/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /srv/users/server in /srv/users/serverpilot/apps/moshedwp/public/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89

# Expected Result

Version 3.0 is working fine.

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version: 6.5

**Comment by timjacobi** [comment]
Please update the plugin to the latest version.
