### ISSUE TITLE
source tag shouldn't have a closing tag

### ISSUE THREAD

**Issue by jmouka** [Automattic/facebook-instant-articles-wp#64]
The Facebook page editor complains when the source tag has a closing tag, e.g. <source src="..."></source>. Their examples show a self-closing tag, though most html examples have only  <source src="...">, no closing, not self-closing.

**Comment by jmouka** [comment]
Facebook's format validator complains about it but it seems to still work, so this isn't a serious issue. I understand this is at the mercy of the DOMDocument class.

**Comment by everton-rosario** [comment]
This should be fixed on master.
Can you double check it, please?
