### ISSUE TITLE
Adding ad density to meta property?

### ISSUE THREAD

**Issue by kevinchin37** [Automattic/facebook-instant-articles-wp#642]
General question - Is it possible to give `fb:use_automatic_ad_placement` the value of `enable=true ad_density=default/medium/low` ( https://developers.facebook.com/docs/instant-articles/monetization/ad-placement#ad-density )? 

When I do `...->addMetaProperty( 'fb:use_automatic_ad_placement', 'enable=true ad_density=default' );` the plugin would change it back to content=true or false. Is it possible to change the value of that particular field?

**Comment by osterkraft** [comment]
@kevinchin37 Did you resolve this? What was your approach to this, by hacking the plugin or adding a hook or similar?

**Comment by kevinchin37** [comment]
@osterkraft We decided to leave it alone since we're using the default value.
