### ISSUE TITLE
Google Maps to Instant Articles

### ISSUE THREAD

**Issue by OtherF** [Automattic/facebook-instant-articles-wp#644]
Hi,

Seems there is no possible to transform Google Maps to Instant Article Maps?

I receive the error:
```
    No rules defined for <div class="googlemaps"> in the context of InstantArticle
```
And here is how the source markup looks like:
```
<div class="googlemaps">
<iframe width="800" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d784919.4459041429!2d116.38777800000001!3d39.7825!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0:0x90a2d702bd664a27!2sBeijing Nanyuan Airport (NAY)!5e0!3m2!1sru!2sau!4v1489324620495">
</iframe>
</div>
```

I don't know if is it possible to extract coordinates from the `src`?

**Comment by timjacobi** [comment]
Hi @OtherF we don't support Google Maps in Instant Articles. Please see https://developers.facebook.com/docs/instant-articles/reference/map on how to embed a map.
