### ISSUE TITLE
No rules defined for <div class="entry-content"> in the context of InstantArticle

### ISSUE THREAD

**Issue by littlesunn** [Automattic/facebook-instant-articles-wp#652]
No rules defined for <div class="entry-content"> in the context of InstantArticle

but i have full article with text picture and etc, please help me

* Plugin version: 3.3.3
* WordPress version: 4.7.3

**Comment by rajumahto** [comment]
hi i am also facing same issue but don't get any solutions .....plz help

**Comment by emlynn8722** [comment]
Any solutions for this? Having the same problem.

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
