### ISSUE TITLE
Youtube Embeds

### ISSUE THREAD

**Issue by anthonykantara** [Automattic/facebook-instant-articles-wp#653]
Hello,

Despite having youtube video embeds in the article, it is not showing in the Instant Article. It is saying:
"No rules defined for <div class="video-container"> in the context of InstantArticle"

So it completely disappears from Instant Article.

If anyone knows how to fix this (before they do), contact me. I'm willing to pay!

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version:

**Comment by timjacobi** [comment]
Please post your HTML mark-up
