### ISSUE TITLE
Footer does not display in markup

### ISSUE THREAD

**Issue by azeneli** [Automattic/facebook-instant-articles-wp#655]
# Steps required to reproduce the problem

I am running into an issue were the footer does not appear in the markup. I was trying to add related articles to the instant article post however I realized that I could not because the footer was not in the template. I checked the template where the styles are located and made sure that everything was right there. I have not been able to find any information as to why the footer is not there. 

# Actual Result

All the tags display but before the closing of the article tag the footer does not show
*`<!doctype html><html><head><meta charset="utf-8"/><meta property="fb:article_style" *content="Styling"/></head><body><article><header><figure></figure></address><figure *class="op-ad"></p><figure class="op-tracker"><iframe>
*</iframe></figure></article></body></html>`

# Expected Result

* I was expecting the footer to be included in the markup, before the closing of the article tag.
*`<!doctype html><html><head><meta charset="utf-8"/><meta property="fb:article_style" *content="Styling"/></head><body><article><header><figure></figure></address><figure *class="op-ad"></p><figure class="op-tracker"><iframe>
*</iframe></figure><footer><ul class="op-related-articles"><li><a href="" /></li></ul></footer>*</article></body></html>`_
---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version:  5.5.9

**Comment by azeneli** [comment]
![screen shot 2017-03-27 at 4 22 03 pm](https://cloud.githubusercontent.com/assets/8780686/24376337/8a1e319e-1309-11e7-86bc-1cbee4977ba1.png)

**Comment by azeneli** [comment]
![screen shot 2017-03-27 at 4 22 27 pm](https://cloud.githubusercontent.com/assets/8780686/24376351/975e6e46-1309-11e7-9b2e-10dc7cbd0e61.png)

**Comment by timjacobi** [comment]
Please post your HTML mark-up.
