### ISSUE TITLE
Make this a default rule

### ISSUE THREAD

**Issue by maslyankov** [Automattic/facebook-instant-articles-wp#658]
If you've defined a common rule which you think this plugin should include by default, tell us about it!
Well,yea:
{"rules": [ { "class": "CaptionRule", "selector" : "p.wp-caption-text" }, { "class": "ImageRule", "selector" : "div.wp-caption", "properties" : { "image.url" : { "type" : "string", "selector" : "img", "attribute": "src" }, "image.caption" : { "type" : "element", "selector" : "p.wp-caption-text" } } } ]}

**Comment by timjacobi** [comment]
Please submit a PR explaining what this rule change is used for
