### ISSUE TITLE
Why I don't get notified when I posted a comment in instant article?

### ISSUE THREAD

**Issue by Kelly27** [Automattic/facebook-instant-articles-wp#659]
Why I don't get notified when I posted a comment in instant article? Even when I tag someone, someone doesn't get notification about the comment too...

# Expected Result
I expect page admin or anyone involved to get notified about the posted comment.

**Comment by timjacobi** [comment]
This is not a problem with this plugin. The plugin only takes your article, converts it to an IA and submits the IA to Facebook.
