### ISSUE TITLE
Fatal Error if deactivated plugin is activated again 

### ISSUE THREAD

**Issue by zceyhun** [Automattic/facebook-instant-articles-wp#660]
If deactivated plugin is activated again after Facebook password has changed, then WP dashboard shows this Fatal Error and WP plugin menu is no longer available. 

Uncaught Facebook\Exceptions\FacebookAuthenticationException: Error validating access token: The session has been invalidated because the user has changed the password. in /nfs/../html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /nfs/../html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /nfs/../html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /nfs/../html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /nfs/c0 in /nfs/../html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89

1- When i activate the plugin, this error message appears and WP plugin menu is unavailable, so FTP is required to delete the plugin and WP plugin menu comes back. 

2- When i downloaded the IA for WP again and activated, the same error occurs.   

So this looks like a fundamental problem and it seems i will not be able to use the plugin until you guys fix it. 

Thank you in advance.

**Comment by timjacobi** [comment]
We can't debug this without any versions specified. Please install the latest version of the plugin and if the problem still exist open a new issue.
