### ISSUE TITLE
How to add Related Articles on the bottom of Instant Articles

### ISSUE THREAD

**Issue by DexxDesign** [Automattic/facebook-instant-articles-wp#661]
# Steps required to reproduce the problem

1.Try to understand the step how to add the "Related Articles" in footer section of Instant Articles
2. 
3. 

# Expected Result

* Related Articles show at the bottom of the Instant Articles

# Actual Result

* Just only show 1 or 2 instant articles in "More from" not lists of "Related Articles"

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.3
* PHP version: 5.6.30

**Comment by nickkos101** [comment]
This is a big problem for me no matter what transform rules I write I cant get this to work.

**Comment by DexxDesign** [comment]
Ohh i just got it.

#1 - Go to facebook page >> publishing tools >> production articles >> click pencil icon on articles list to edit 

#2 - Insert following html code before </article> code:
   <footer>
  <ul class="op-related-articles">
    <li><a href="http://yourwebname.com/article-1/"></a></li>
    <li><a href="http://yourwebname.com/article-1/"></a></li>
    <li><a href="http://yourwebname.com/article-1/"></a></li>
  </ul>
</footer>

#3 - for more info, please refer https://developers.facebook.com/docs/instant-articles/reference/related-articles
