### ISSUE TITLE
received warning and fatal error

### ISSUE THREAD

**Issue by hanafiawang** [Automattic/facebook-instant-articles-wp#665]
# Steps required to reproduce the problem

1. install the plugin only

# Actual Result
Warning: require(/home3/napieda/public_html/90minit.com/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /home3/napieda/public_html/90minit.com/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

Fatal error: require(): Failed opening required '/home3/napieda/public_html/90minit.com/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/opt/php54/lib/php') in /home3/napieda/public_html/90minit.com/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 32

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by timjacobi** [comment]
We cannot debug this without any versions specified. Please install the latest version of the plugin and if the problem still exists open a new issue.
