### ISSUE TITLE
Improve the WP notices in the wizard  template

### ISSUE THREAD

**Issue by afercia** [Automattic/facebook-instant-articles-wp#666]
Some of the WordPress notices (all except the ones with the `inline` CSS class) gets moved via JS under the main heading in the page. For this to work correctly, any page in the admin should have a `wrap` div element which is missing in the `wizard-template.php` file. Instead, it is correctly used in the `template-settings.php` file.

You might consider to just add a `<div class="wrap">` to wrap all the content in `wizard-template.php`.

Screenshots before and after:

![screen shot 2017-04-24 at 09 35 00](https://cloud.githubusercontent.com/assets/1682452/25328045/a10efc34-28d6-11e7-860a-db58da70fa76.png)
![screen shot 2017-04-24 at 09 35 09](https://cloud.githubusercontent.com/assets/1682452/25328046/a10fc9fc-28d6-11e7-9114-f29036e5bc15.png)

**Comment by timjacobi** [comment]
We have recently published a new version of the plugin which does not contain the wizard anymore. Closing.
