### ISSUE TITLE
Video-based header

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#668]
Hi there,

The Facebook documentation states that you can use a video in your header rather than an image: https://developers.facebook.com/docs/instant-articles/reference/cover

Sample code:
`<body>
  <article>
    <header>
       
      <figure>
        <video>
          <source src="http://mydomain.com/path/to/video.mp4" type="video/mp4" />
        </video>
      </figure>
      
      
      <h1> Title </h1>

      
      <address>
        <a>Brandon Diamond</a>
        Brandon is a avid zombie hunter.
      </address>
    </header>
  </article>
</body>`

This video supposedly also will appear on the FB newsfeed instead of the static image. Is there a way to set this up with the current version of the plugin and if not, would this be something you'd consider as a feature request?

**Comment by samichamoun** [comment]
Bump on this... Seems like this is a piece of functionality that has never been used by anyone?

**Comment by pestevez** [comment]
+1

**Comment by demetrox** [comment]
any update?  so far need to change manually in production article

**Comment by gabu69** [comment]
Any update on this? This is really important since raises the CTR by far

**Comment by everton-rosario** [comment]
I have this gist here: https://gist.github.com/everton-rosario/26fe2a14591e603c5db37d4d6dc6ba06
It shows how to implement in the WP integration.

If any of you come with a PR of this being treated from a default video configuration on the header will be great.

**Comment by samichamoun** [comment]
Unsure where this code should be placed @everton-rosario ?
