### ISSUE TITLE
$DOMDocument->saveHTML issue on PHP 5.2.17

### ISSUE THREAD

**Issue by OriginalEXE** [Automattic/facebook-instant-articles-wp#67]
I am unfortunate enough to have to work on PHP 5.2.17 and it looks like `if ( method_exists( $DOMDocument, 'saveHTML' ) ) { // Requires PHP 5.3.6` on line 316 of class-instant-articles-post.php is not working properly, as for some reason that returns true and then I get this error in my feed:
`<b>Warning</b>:  DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in <b>/home/wegofurt/public_html/wp-content/plugins/facebook-instant-articles-wp-master/class-instant-articles-post.php</b> on line <b>317</b><br />`

**Comment by demoive** [comment]
@OriginalEXE, there have been some major releases since this issue was opened and the code bit that you refer to doesn't exist anymore. If you grab the latest version, do you still have issues with your version of PHP?

**Comment by bjornjohansen** [comment]
Unfortunately, the latest version requires PHP 5.4. I believe @diegoquinteiro is working to lower the requirement to PHP 5.3. If you’re on PHP 5.2, you’ll simply have to upgrade PHP to use this plugin.
