### ISSUE TITLE
Instant Article FB - 500 internal server error after click Log in with facebook

### ISSUE THREAD

**Issue by Querllon** [Automattic/facebook-instant-articles-wp#672]
# Steps required to reproduce the problem

1. Trying to setup IA on WP using Instant Article Plugin
2. I'm on the part were I need to login with FB to finish connecting IA-plugin to WP, but keep receiving, 500 internal server error after click Log in with facebook.
3. 

# Expected Result

* After clicking login to facebook this will take you to Facebook, and you will be asked to give the app permission to access your profile information. After giving permissions, you will be redirected back to your WordPress site. Click on the ‘Select Page’ drop down menu to select your Facebook page.

# Actual Result

* (Unable to connect) 500 - Internal Server Error
This is a temporary server error. 
Please try to reload the webpage later. 

Note:
According to my hosting site support team. The issue is caused by the response returned by the Facebook SDK API:

[code][Tue May 09 04:05:21.638288 2017] [http:error] [pid 21792] [client 87.118.135.66:47122] AH02429: Response header name 'ERROR - Facebook SDK returned an error' contains invalid characters, aborting request, referer: https://www.travellersguidephilippines.com/wp-admin/admin.php?page=instant-articles-wizard
---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.4
* PHP version:

**Comment by timjacobi** [comment]
We have recently released a new version of the plugin which doesn't require the FB login anymore.
