### ISSUE TITLE
504 Error on Wordpress Article publish

### ISSUE THREAD

**Issue by J0ker98** [Automattic/facebook-instant-articles-wp#675]
# Steps required to reproduce the problem

1.  Enable the plugin
2. Post an article with a gallery, some images in the content and a paragraph or two of text

# Expected Result

* The article would be published

# Actual Result

* The server will try to load for some time and then give a 504 (Gateway Timed out) error. You'll have to try other times to successfully post the article.

---

**Version Info**

* Plugin version: 3.3.5
* WordPress version: 4.7.4
* PHP version: 5.6.30

**Comment by timjacobi** [comment]
@J0ker98 can you please update the version and let us know if you still see the issue?

**Comment by J0ker98** [comment]
Fixed it some time ago, was a server side issue!
