### ISSUE TITLE
Can't manually set ads, getting invalid selector error

### ISSUE THREAD

**Issue by Salmanman** [Automattic/facebook-instant-articles-wp#677]
Hello, I'm trying to manually insert two iframes as ads, but if I add the tag `<figure class="op-ad">` it shows me the error that I detail below. If I remove the `<figure>` tags, it gets transformed as `<figure class="op-interactive">`.

# Steps required to reproduce the problem

I wrote the following markup and inserted it in an article:
```
<figure class="op-ad">
<iframe src="http://jauria.digital/ad-cabify/" width="600px" height="320px" scrolling="no">
</iframe>
</figure>
```

# Expected Result

The Instant Articles plugin accepts the markup and transforms it accordingly.

# Actual Result

The plugin shows the following error:

_Invalid selector for fields `(image.url)`. The node being transformed was `<figure>` in the context of `InstantArticle` within the Rule `ImageRule` with these properties: `{ image.url=StringGetter}`_

---

**Version Info**

* Plugin version: 4.7.4
* WordPress version: 3.3.5
* PHP version:

**Comment by pestevez** [comment]
Hey @Salmanman - The rule I described in #779 should work for you:
```javascript
{
	"rules": [{
		"class": "AdRule",
		"selector": "figure.op-ad",
		"properties": {
			"ad.url": {
				"type": "string",
				"selector": "iframe",
				"attribute": "src"
			},
			"ad.height": {
				"type": "int",
				"selector": "iframe",
				"attribute": "height"
			},
			"ad.width": {
				"type": "int",
				"selector": "iframe",
				"attribute": "width"
			},
			"ad.embed": {
				"type": "children",
				"selector": "iframe"
			}
		}
	}]
}
```
Transformed output:
```html
<figure class="op-ad">
  <iframe src="http://jauria.digital/ad-cabify/" width="600" height="320"></iframe>
</figure>
```
I'm closing the issue now, but please feel free to reopen if you still face the problem or if you need additional information.
