### ISSUE TITLE
Log in with Facebook to finish connecting the Instant Articles Plugin to your account.

### ISSUE THREAD

**Issue by Wormedi** [Automattic/facebook-instant-articles-wp#681]
Problem with facebook login in Facebook Instant Articles Settings sory for my bad english thanks help me how to fix this problem
![untitled](https://cloud.githubusercontent.com/assets/28548710/26596378/cd466e0e-456e-11e7-843c-b41a914f7ae0.png)
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

* 

# Actual Result

* 

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by timjacobi** [comment]
This issue was reported agains an old version of the plugin. The process has significantly change since. Please update your plugin.
