### ISSUE TITLE
Entered incorrect app id and secret key 

### ISSUE THREAD

**Issue by zoomerge** [Automattic/facebook-instant-articles-wp#682]
# Steps required to reproduce the problem

1. Installed Facebook instant articles
2. On page two entered wrong app id: with email and secret key
3. The page reloaded and clicking on Get STARTED keeps reloading the plugin page. 

# Expected Result

*  Logging into Facebook instant articles properly

# Actual Result

* Logging into Facebook instant articles and setting it up

---

**Version Info**

* Plugin version: 3.3.5
* WordPress version: 4.7.5
* PHP version: 5.6

**Comment by pestevez** [comment]
Hey @zoomerge, thanks for flagging this issue. I don't believe this problem exists anymore since the latest version of the plugin (4.0.5) only requires the Page ID, so I'm closing this issue. Please feel free to reopen if you are still facing this problem or if you need additional information.
