### ISSUE TITLE
Global wordpress performances and oEmbeds 

### ISSUE THREAD

**Issue by bactisme** [Automattic/facebook-instant-articles-wp#685]
I was investigating a performance issues on my websites (two medium audiences), and it seems that the plugin waste of lot of ressources and uselessly break the wordpress oembed discover cache in a way I don't yet understand.

## The problem

We use a log of self embeds (using a block to promote our own article on another article) and our /feed is not in the cache (30 posts).

So for each user asking for /feed and for each post containing a embed, it generate one "local" request in order to discover the oembed iframe URL. A lot of "internal" http requests for just one client.

Wordpress seems to usually have a cache for oembed, but the code in facebook-instant-articles/embeds.php to not use that cache for my /feed.

## First investigation / The place where it happens?

The function `instant_articles_embed_oembed_html` make use of  `wp_oembed->get_provider` which use `discover` which make external request to call the embeded URL in order to find the embed iframe URL. A parameter exists to force non-discovery, but is not used.

The embeds.php file is actually included on all the request, `remove_all_filters( 'embed_oembed_html' );` is then run on each requests and not only instant articles endpoint, potentially breaking other things.

Same for `add_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10, 4 );`

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.5
* PHP version: PHP 5.6.30-0+deb8u1

**Comment by bactisme** [comment]
I pushed in my functions.php the stupid fix : 
```
remove_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10 );
if (defined('INSTANT_ARTICLES_SLUG') && is_feed( INSTANT_ARTICLES_SLUG )){
    add_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10, 4 );
}
```
And saw a quite big drop in used ressources. 
![phpfpm_connections-month](https://user-images.githubusercontent.com/369622/27277483-ab7de6d8-54de-11e7-8a56-1baa21b6b1db.png)

**Comment by diegoquinteiro** [comment]
Related to #457
