### ISSUE TITLE
Unclaimed URL

### ISSUE THREAD

**Issue by nonsintetic** [Automattic/facebook-instant-articles-wp#691]
# Steps required to reproduce the problem
0. SSL enabled domain
1. Added APP ID and Secret
2. Logged in and selected page
3. Made a style
4. Edited several articles and all seemed well, no errors in conversion

# Expected Result
* Articles appear in the page's Instant Articles list, no errors during conversion

# Actual Result
* When I edit an article for the first time, no errors, it says article has not yet been submitted to Facebook. If I save it I get this error: 
`Unclaimed URL: The URL https://<link-to-article>/ has not been claimed for Instant Articles. Please check to make sure you have a URL registered for your page. For more information refer to URLs in the Publishing Articles section of the Instant Articles documentation.`

Problem is:
- Some articles seemed to have made it to Facebook's IA section under Production Posts
- Everytime I try to save an article I get this error now

What I've tried:
- claiming the website manually in the Instant Articles settings (only has http as an option, not sure if it makes a difference) - The url gets added in FB but still getting the error.
- changing the URL of the Facebook app to https://website and http://website
- re-adding the APP ID and secret, re-selecting page..

---

**Version Info**

* Plugin version: 3.3.5
* WordPress version: 4.8
* PHP version: 7.0.20

**Comment by nonsintetic** [comment]
This was fixed somehow in the latest update. Thanks i guess 👍

**Comment by Imam8g** [comment]
> 
> # Steps required to reproduce the problem
> 
>     1. SSL enabled domain
> 
>     2. Added APP ID and Secret
> 
>     3. Logged in and selected page
> 
>     4. Made a style
> 
>     5. Edited several articles and all seemed well, no errors in conversion
> 
> 
> # Expected Result
> 
>     * Articles appear in the page's Instant Articles list, no errors during conversion
> 
> 
> # Actual Result
> 
>     * When I edit an article for the first time, no errors, it says article has not yet been submitted to Facebook. If I save it I get this error:
>       `Unclaimed URL: The URL https://<link-to-article>/ has not been claimed for Instant Articles. Please check to make sure you have a URL registered for your page. For more information refer to URLs in the Publishing Articles section of the Instant Articles documentation.`
> 
> 
> Problem is:
> 
>     * Some articles seemed to have made it to Facebook's IA section under Production Posts
> 
>     * Everytime I try to save an article I get this error now
> 
> 
> What I've tried:
> 
>     * claiming the website manually in the Instant Articles settings (only has http as an option, not sure if it makes a difference) - The url gets added in FB but still getting the error.
> 
>     * changing the URL of the Facebook app to https://website and http://website
> 
>     * re-adding the APP ID and secret, re-selecting page..
> 
> 
> **Version Info**
> 
>     * Plugin version: 3.3.5
> 
>     * WordPress version: 4.8
> 
>     * PHP version: 7.0.20
Hi i have the same problem but please help me to solve the issue ..

The URL http://risk.nahidjoy.com/archives/9531 has not been claimed for Instant Articles. Please check to make sure that you have a URL registered for your Page. For more information, refer to URLs in the Publishing articles section of the Instant Articles documentation.
