### ISSUE TITLE
Ampersand not outputting correctly in author byline

### ISSUE THREAD

**Issue by samborcia** [Automattic/facebook-instant-articles-wp#693]
My Facebook page name is called [Lake & McHenry County Scanner](https://www.facebook.com/LakeMcHenryScanner/). On my page's instant articles that are posted it's showing in the author byline as "`Lake &amp; McHenry County Scanner`". This is the HTML that's being generated:

`<address><a href="http://www.lakemchenryscanner.com">Lake &amp;amp; McHenry County Scanner</a>We are volunteers keeping the community informed of fire incidents around Lake &amp;amp; McHenry, Illinois Counties.</address>
`

---

**Version Info**

* Plugin version: 3.3.5
* WordPress version: 4.8
* PHP version: 5.6

**Comment by timjacobi** [comment]
Still a bug in 4.0.5 - Thanks for reporting

**Comment by timjacobi** [comment]
This is related to another bug which I have sent a fix for [here](https://github.com/facebook/facebook-instant-articles-sdk-php/pull/275).

**Comment by samborcia** [comment]
I'm still having this issue. It has not been fixed.

**Comment by timjacobi** [comment]
Well the PR I mentioned above is still open.

**Comment by vkama** [comment]
PR is now merged with master @samborcia, if you checkout master this should be resolved

**Comment by samborcia** [comment]
This issue is still not fixed.
