### ISSUE TITLE
Connecting with FB page

### ISSUE THREAD

**Issue by vyasdharmesh** [Automattic/facebook-instant-articles-wp#696]
# Steps required to reproduce the problem

1. Disconnect fb page from working plugin 
2. reconnect (by mistake login with other user which doesn't have app access)
3. now it's not getting connected

# Expected Result

* plugin should be connected with page

# Actual Result

* plugin not getting connected with fb page 

---

**Version Info**

* Plugin version: Version 3.3.5
* WordPress version: 4.8
* PHP version:

**Comment by pestevez** [comment]
Hey @vyasdharmesh, thanks for flagging this issue. I believe the latest version of the plugin (4.0.5) does not have this problem anymore, as we removed the step of connecting to a page in favor of just passing the Page ID.

I am closing this issue now but please feel free to reopen if you still have this problem or if you need additional information.
