### ISSUE TITLE
Trying to get property of non-object in fb-instant-articles/class-instant-articles-post.php

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/facebook-instant-articles-wp#707]
In version 4.0.1, I'm getting lots of the following PHP Notices in our debug log. Both of these notices always fire together.

Trying to get property of non-object in /wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 79
Trying to get property of non-object in /wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 892

I'm uncertain of exactly the code path that is leading to this error, though it is definitely not tied to the publication or pushing of articles to Facebook. We are getting it many times per minute from normal pageload activity.

* Plugin version: 4.0.1
* WordPress version: 4.8
* PHP version: 7.1.5

**Comment by diegoquinteiro** [comment]
Hi @kevinlisota,

Thanks for reporting. I'm spawning a PHP 7.1.5 environment to reproduce your error and will fix it as soon as I identify the source.

Thank you,
Diego
