### ISSUE TITLE
Post content missing

### ISSUE THREAD

**Issue by therethere** [Automattic/facebook-instant-articles-wp#71]
Post content is missing, tried on 5 different wordpress's. 

The instant articles feed is working on header, title, description, etc, but not on the article body. 
It seems get_the_content is not working.

**Comment by demoive** [comment]
@therethere, could you provide some more information about the issues you're experiencing? What led you to think the problem lies in `get_the_content`? Does the plugin show any warnings or errors when saving the post? Are the 5 WordPress instances you tried on the same (version, multisite, etc.)?

**Comment by therethere** [comment]
The problem was the php 5.3. I had to upgrade to 5.9. Then the plugin started to working.
