### ISSUE TITLE
Plugin is ignoring my custom transformer rules

### ISSUE THREAD

**Issue by Salmanman** [Automattic/facebook-instant-articles-wp#710]
# Steps required to reproduce the problem

1. I write the following rule `{"class":"IgnoreRule","selector":"div.fb-comments"}`

# Expected Result

* Plugin transforms the article without issues.

# Actual Result

* I keep getting the following warning: `No rules defined for <div class="fb-comments"> in the context of InstantArticle
`
---

**Version Info**

* Plugin version: 4.0.1
* WordPress version: 4.8

**Comment by diegoquinteiro** [comment]
Hi @Salmanman,

The actual configuration should look like:
```
{ "rules": [{"class":"IgnoreRule","selector":"div.fb-comments"}] }
```

Can you confirm whether you're using it like this?

Thank you,
Diego

**Comment by Salmanman** [comment]
Yes, yes. In fact. This is my full ruleset:

```
{"Rules":[{"class":"AdRule","selector":"iframe.publicidad","properties":{"ad.url":
{"type":"string","selector":"iframe.publicidad","attribute":"src"}}},{"class":"PassThroughRule","selector":"div.fb-comments"}]}
```
The `AdRule` doesn't work either, by the way, but the banner still shows so it didn't bother me much.

**Comment by timjacobi** [comment]
@Salmanman You have a typo in your configuration it needs to be `rules` instead of `Rules`. The plugin will then respect your rules.
