### ISSUE TITLE
Youtube video does not display - video could not be downloaded error

### ISSUE THREAD

**Issue by bghouse** [Automattic/facebook-instant-articles-wp#717]
I have tripled checked my post with the video embed.  No errors in the transformer and when I toggle the debug it looks correct:

<figure>
        <video>
          <source src="https://www.youtube.com/embed/e9RTMUj3OB4?feature=oembed"/>
        </video>
      </figure>

When I attempt to check it in the Facebook Manage Page app on my iPhone - I get no video.  just blank space.

If I go and edit in the post (still in development not production) I get a big red error message stating: 
General Errors: Could Not Download Video: Video could not be downloaded from https://www.youtube.com/embed/e9RTMUj3OB4?feature=oembed. No Video Detected: It looks like you're trying to upload something that isn't a video or that's corrupt. Please upload a video in a &lt;a href=&#039;http://www.facebook.com/help/?faq=218673814818907&amp;ec=1363032#What-formats-of-video-files-can-I-upload?&#039;&gt;supported format&lt;/a&gt;. Please check the video URL is correct and loads at the address given.

I have indeed checked that the video url loads in my browser:
https://www.youtube.com/embed/e9RTMUj3OB4?feature=oembed

I have a custom rule that seems to be doing it's job, but perhaps I'm using the wrong rule?

I used 

{
    "class": "VideoRule",
    "selector" : "div.videoWrapper",
    "properties" : {
        "video.url" : {
            "type" : "string",
            "selector" : "iframe",
            "attribute": "src"
        }
    }
}

Should I be using something else, like InteractiveRule maybe?  Am I missing another property maybe?

Here's a link to the page with the video I'm trying to make work:  http://welovesharks.club/shark-week-2017-everything-you-need-to-know/

**Comment by pestevez** [comment]
Yes, you should be using an [Embed](https://developers.facebook.com/docs/instant-articles/reference/embeds) element, which you can generate with the `InteractiveRule`.

The custom rule below should do what you want:
```javascript
{
  "rules":[
    {
      "class":"InteractiveRule",
      "selector":"div.videoWrapper",
      "properties":{
        "no-margin":{
          "type":"exists",
          "selector":"iframe.no-margin"
        },
        "column-width":{
          "type":"exists",
          "selector":"iframe.column-width"
        },
        "interactive.url":{
          "type":"string",
          "selector":"iframe",
          "attribute":"src"
        },
        "interactive.height":{
          "type":"int",
          "selector":"iframe",
          "attribute":"height"
        },
        "interactive.width":{
          "type":"int",
          "selector":"iframe",
          "attribute":"width"
        },
        "interactive.iframe":{
          "type":"children",
          "selector":"iframe"
        }
      }
    }
  ]
}
```

**Comment by bghouse** [comment]
Thank you - that worked perfectly!
