### ISSUE TITLE
how to resolve the problem (No rules defined for <div class"shareaholic-cavas"> in the contex of InstantArticle)

### ISSUE THREAD

**Issue by markZu** [Automattic/facebook-instant-articles-wp#719]
No rules defined for <div class"shareaholic-cavas"> in the contex of InstantArticle

healp me please 

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by pestevez** [comment]
Can you provide a sample of your markup? Also, are you defining custom rules in the plugin settings?

**Comment by markZu** [comment]
http://i.imgur.com/5QaVizn.png

**Comment by Darkseal** [comment]
I stumbled upon this issue and managed to work around it by adding a custom **IgnoreRule** in the following way:

http://www.ryadel.com/en/fix-no-rules-defined-for-in-context-of-instantarticle-error-facebook-istant-articles/

Here's the relevant code:

```
{ "rules": [
    {
        "class": "IgnoreRule",
        "selector" : "div.shareaholic-canvas"
    }
]}

```

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.

**Comment by newsvn1981** [comment]
No rules defined for <article> in the context of Small 
Tôi không thể khắc phục được lỗi này, nhờ giúp đỡ, cảm ơn.
