### ISSUE TITLE
instant article custom rule

### ISSUE THREAD

**Issue by emicrowatch** [Automattic/facebook-instant-articles-wp#721]
# Steps required to reproduce the problem

1. No rules defined for <div class="row"> in the context of InstantArticle
2. No rules defined for <div class="row horoscope"> in the context of InstantArticle
3. No rules defined for <div class="row horoscope"> in the context of InstantArticle
4. No rules defined for <div class="row horoscope"> in the context of InstantArticle
5. No rules defined for <div class="row horoscope"> in the context of InstantArticle
6. No rules defined for <div class="row horoscope"> in the context of InstantArticle
7. No rules defined for <div class="row horoscope"> in the context of InstantArticle

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
