### ISSUE TITLE
Updating post after published as IA & flagging post not to publish

### ISSUE THREAD

**Issue by bghouse** [Automattic/facebook-instant-articles-wp#722]
I've got my plugin setup now and posts are coming across when published into my development area (still testing).  Three things I can't figure out

1.) How can we flag a particular post to NOT automatically publish as an Instant Article once we setup the RSS feed to Production?

2.) If we go back and edit a post after it has been published as an Instant Article, how does that get updated?  Is it automatic?

3.) Development Mode checkbox:  It states this saves them as "drafts".  But does it save them as "drafts" in the Production or Development section?  It seems like you cannot promote an article from Development to Production - so trying to see if there is a way to save them as Production "drafts" if it isn't possible to flag a post not to publish

**Comment by timjacobi** [comment]
1.) Unfortunately this is currently not possible
2.) Yes the plugin will update the article
3.) It will save them as drafts in the development articles. Unfortunately you need to update the post in Wordpress after you have changed the setting. There is already a feature request to change this and we will look into it eventually
