### ISSUE TITLE
No rules defined for <div class="video-frame"> in the context of InstantArticle

### ISSUE THREAD

**Issue by anoopacid** [Automattic/facebook-instant-articles-wp#726]
This post was transformed into an Instant Article with some warnings
No rules defined for <div class="video-frame"> in the context of InstantArticle

---

**Version Info**

* Plugin version: 4.0.2
* WordPress version: 4.8
* PHP version:

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
