### ISSUE TITLE
Problem - No rules defined for <p> in the context of Bold

### ISSUE THREAD

**Issue by sxmuelmx** [Automattic/facebook-instant-articles-wp#728]
# Steps required to reproduce the problem

1. error transform post to instant articles
2. problem - No rules defined for <p> in the context of Bold
3. not work

 {"rules":[{
        "class": "ParagraphRule",
        "selector": "p"
    }]
}

# Expected Result

* <p>TULTITLÁN.- Integrantes del Grupo Táctico Operativo (GTO) <strong>Tultitlán</strong>, conformado por autoridades de los tres órdenes de gobierno, y coordinado por la Fiscalía General de Justicia del Estado de México (FGJEM), realizaron operativos de filtro y barrido en varias colonias del municipio, en donde fueron asegurados cuatro sujetos por diversos ilícitos.</p>
<p>Las movilizaciones se realizaron en las colonias Sierra de Guadalupe, Parque Sierra de Guadalupe, El Tesoro Ampliación San Marcos, San Marcos, Lázaro Cárdenas, <strong>Tultitlán</strong> Centro, Villa Esmeralda, El Obelisco, y Magnolias, en donde participaron elementos de los tres órdenes de gobierno. Por ello, fueron detenidos Rodolfo “N” y Roberto “N”, quienes se encontraban intercambiando envoltorios con hierba con las características de la marihuana por dinero en efectivo; en una revisión les fueron aseguradas 13 bolsas de plástico con presunta marihuana.</p>
<p>Además se detuvo a Mayolo “N”, quien presuntamente momentos antes habría lesionado a su esposa, con quien sostuvo una discusión. Finalmente, los servidores públicos aseguraron también a Curiel “N”, quien viajaba a bordo de un vehículo compacto con luces y estrobos, simulando ser un vehículo oficial. Los  detenidos fueron presentados ante el agente del Ministerio Público, quien inició las indagatorias correspondientes y determinará su situación legal.</p>
<p>Durante el operativo, también fueron revisados 230 vehículos, 390 personas y realizaron 1120 consultas de órdenes de aprehensión. Por lo que las autoridades que integran los GTO en el Estado de México reiteran su compromiso con la ciudadanía e invitan a la población a denunciar cualquier hecho delictivo al correo electrónico: cerotolerancia@edomex.gob.mx, al número telefónico 01 800 7028770,  o en la aplicación FGJEdomex, disponible para todos los teléfonos inteligentes de los sistemas iOS y Android.</p>

# Actual Result

* <p>TULTITLÁN&amp;period;- Integrantes del Grupo Táctico Operativo &amp;lpar;GTO&amp;rpar; <b>Tultitlán&amp;comma; conformado por autoridades de los tres órdenes de gobierno&amp;comma; y coordinado por la Fiscalía General de Justicia del Estado de México &amp;lpar;FGJEM&amp;rpar;&amp;comma; realizaron operativos de filtro y barrido en varias colonias del municipio&amp;comma; en donde fueron asegurados cuatro sujetos por diversos ilícitos&amp;period;&amp;NewLine;</b></p>

---

**Version Info**

* Plugin version: 4.0.2
* WordPress version: 4.8
* PHP version: 7.0

**Comment by nuapp** [comment]
same problem please help

**Comment by vbzu** [comment]
just enable mbstring in your hosting. If you're in servers like digitalocean. pls google on how to install mbstring and execute the command. that's it. once done, your next article works fine on facebook IA. :)

**Comment by timjacobi** [comment]
A `<p>` tag within a `<b>` or `<strong>` tag is not valid HTML and will therefore not work in transformation either.
