### ISSUE TITLE
No Rules Defined for <div> and <div class="quads-location quads-ad1">

### ISSUE THREAD

**Issue by codexify** [Automattic/facebook-instant-articles-wp#729]
I'm using Boombox theme on my WordPress, on all the posts, it is showing the following warnings:

- No rules defined for `<div class="quads-location quads-ad1">` in the context of InstantArticle
- No rules defined for `<div>` in the context of InstantArticle

Haven't find any solution, I tried making a custom rule but didn't work. Kindly help in this regard.

**Comment by DrLightman** [comment]
what kind of rules did you apply?

**Comment by codexify** [comment]
I didn't do anything, just activated the plugin.

**Comment by DrLightman** [comment]
Ah sorry, I understood that you tried to write a custom rule at least.

Well try adding this to your custom rules box in IA Advanced Settings, that should be empty at this point if you didn't add any yet.

    {
        "rules":
        [
        {
            "class": "PassThroughRule",
            "selector" : "div.quads-location.quads-ad1"
        }
      ]
    }

I suggest you study the relevant docs about the transformer rules:

https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
