### ISSUE TITLE
Meta Property for claiming your URL

### ISSUE THREAD

**Issue by ashbressler** [Automattic/facebook-instant-articles-wp#73]
FB now requires that you add a meta tag to authorize that you have access to the site that you're submitting your feed from. See https://developers.facebook.com/docs/instant-articles/claim-url.

Would it be possible to add a setting, in Tools/Website Verification Services perhaps, to enable adding this without a meta tags plugin.

**Comment by demoive** [comment]
This is a good suggestion, @ashbressler. Support for this _is_ on the roadmap — when the PR for this feature is active, I can merge with this issue or will just update here. Thanks!

**Comment by demoive** [comment]
This is a good suggestion, @ashbressler. Support for this, in some shape or form, _is_ on the roadmap — when a PR is available, will either merge with this issue or just provide an update here. Thanks!

**Comment by philipjohn** [comment]
@demoive Do we still need this, given that v2 introduces the API, or is this going to be required for feed-only usage?

**Comment by everton-rosario** [comment]
This won't be needed anymore, since the new flow will have it cleared via API and the new Wizard flow.
