### ISSUE TITLE
Transformation my gallery

### ISSUE THREAD

**Issue by amandacatraca** [Automattic/facebook-instant-articles-wp#731]
I need a rule for my gallery

I try this rule:
```json
	{
		"class": "SlideshowRule",
      "selector": "div.catraca-post-slideshow"
    },
	{
		"class": "IgnoreRule", "selector": "div.catraca-post-slideshow-inner" },
{
	"class": "IgnoreRule", "selector": "div.inner-gallery-banner" },
	 {
		 "class": "SlideshowImageRule",
      "selector": "div.slide",
      "properties": {
		 "image.url" : {
			 "type": "string",
              "selector": "img",
              "attribute": "src"
          },
          "caption.title" : {
			 "type": "string",
              "selector": "p.textleft"
          }
      }
  }
```

My code:
<div class="catraca-post-slideshow-inner">
	<input type="radio" id="button-1-2" name="slideshow-control-2" checked="checked" onclick="jQuery('#theater-btn-1-2').prop('checked', 'checked')">

	<div class="slide">
		<div class="slide-content image-1464569-2">
			<div class="contagem-slide-post textright"><p class="counter">1/4</p></div>
			<label class="image-holder" for="theater-switcher-1464563-2" style="height: 403px;">
				<img width="620" height="357" src="https://catraca.ms/wp-content/uploads/2017/07/cbe5f41d3cbceaba79d3852ae2531a6a8542d6f0_1200-630.jpg" class="attachment-620x450 size-620x450" alt="" srcset="https://catraca.ms/wp-content/uploads/2017/07/cbe5f41d3cbceaba79d3852ae2531a6a8542d6f0_1200-630.jpg 720w, https://catraca.ms/wp-content/uploads/2017/07/cbe5f41d3cbceaba79d3852ae2531a6a8542d6f0_1200-630-450x259.jpg 450w" sizes="(max-width: 620px) 100vw, 620px" data-lazy-loaded="true" style="display: block;">
			</label>

			<div class="arrows-holder"><label for="button-2-2" class="arrows right"><span></span></label></div>
			<label class="theater-switcher" for="theater-switcher-1464563-2"><span></span> Ampliar</label></div>
		<div class="slide-info clearfix">
			<div class="col-12 textleft"><p class="credit">Crédito da imagem: <b>Arquivo UH</b></p></div>
			<div class="col-12 legenda-slide">
				<p class="textleft">Carolina nasceu em Sacramento, Minas Gerais, mas viveu por muito tempo na favela do
					Canindé.</p></div>
		</div>
	</div>
	
</div>

---

**Version Info**

* Plugin version: 4.0.2 
* WordPress version: 4.8
* PHP version:

**Comment by timjacobi** [comment]
Hi @amandacatraca Unfortunately we can't offer to create rules for everyones use cases. I know this might not be the answer you'd like to hear but it would just be too much work.
