### ISSUE TITLE
[Documentation] How is the AMP transformation stuff supposed to work ?

### ISSUE THREAD

**Issue by Djiit** [Automattic/facebook-instant-articles-wp#734]
# Steps required to reproduce the problem

1. Try to use the AMP feature
2. Look at the doc... how wait ?!
3. Post an issue here :)

# Expected Result

* The README (or any documentation) should tell users how to test/use the AMP feature

# Actual Result

* Maybe I missed something, but it seems there isn't any documentation about the AMP feature.

---

**Version Info**

* Plugin version: 4.0.3
* WordPress version: 4.8
* PHP version: 7.0

Please tell me if I can further help you resolve this

Cheers

**Comment by timjacobi** [comment]
Thanks for submitting #740! Seems like you have figured it out :)
