### ISSUE TITLE
Image in Post enclosed in <strong> tag is not showing

### ISSUE THREAD

**Issue by upatricck** [Automattic/facebook-instant-articles-wp#741]
# Steps required to reproduce the problem

1. Create a post containing an image, make it **bold** through the editor ( I think most do this accidentally)

# Expected Result

*  The image won't display in instant article generated

# Actual Result

*  I think this should display

**Comment by timjacobi** [comment]
The builtin rules don't support this case but you can add a rule to support this.

```json
{
  "class" : "PassThroughRule",
  "selector": "//strong[descendant::img]"
}
```
