### ISSUE TITLE
Facebook scraper - when does it scrape?

### ISSUE THREAD

**Issue by DrLightman** [Automattic/facebook-instant-articles-wp#746]
Hello,

surely not an issue with the plugin, but I couldn't find anywhere this information.

With which frequency the facebook scraper scans my website? And consequently how long after I publish an article will be available in the instant articles library?

Thank you

**Comment by per4mance** [comment]
Very good question I'm interesting in too. Thanks :-)

**Comment by DrLightman** [comment]
By inspecting the source I found out that after a post has been saved orupdated an instant scrape request is submitted to:

`https://graph.facebook.com/?id=<url_encoded>&scrape=true`

Well at least it's something :)

**Comment by timjacobi** [comment]
Facebook doesn't document the exact scrape interval. However it is around the 10 minute mark.
