### ISSUE TITLE
Warning output on getimagesize

### ISSUE THREAD

**Issue by BranndonWork** [Automattic/facebook-instant-articles-wp#75]
Line 121 of `/dom-transform-filters/class-instant-articles-dom-transform-filter-image.php` is currently `$imagesize = getimagesize( $src );` but if the image returns a 404, a PHP warning is output in the feed code. I propose you change line 121 to the following `$imagesize = @getimagesize( $src );` to avoid error outputting in the article content.

**Comment by philipjohn** [comment]
As v2 removes the DOM transformation code, this is no longer an issue. Thanks for the report!

**Comment by kkranzo** [comment]
Hi @philipjohn - I am using a custom version of the plugin and am receiving that PHP error. Did the addition of the "@" remove the error for you?
