### ISSUE TITLE
Can someone provide the Custom Transformation rules for Facebook Instant Article

### ISSUE THREAD

**Issue by camaninder** [Automattic/facebook-instant-articles-wp#751]
# Steps required to reproduce the problem

1. 
2. 
3. 

# Expected Result

* 

# Actual Result

* 

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by everton-rosario** [comment]
Can you give more details?

The custom transformation rules will depend on your markup and the plugins/components your site is using.

Closing for now. Reopen when you send more info.

**Comment by camaninder** [comment]
My site is running on wordpress platform...with no special plugin.
