### ISSUE TITLE
Instant Article plugin for WP is not getting activated 

### ISSUE THREAD

**Issue by vishme247** [Automattic/facebook-instant-articles-wp#754]
# Steps required to reproduce the problem

1. Signed up to  Instant Articles
2. Downloded Instant Article plugin for WP
3. Tried activating the plugin

# Expected Result

* The plugin should have been activates

# Actual Result

* Does not activate . Its giving below error
**Parse error: syntax error, unexpected '[' in /home/content/92/12011492/html/theblogtime/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 107**

---

**Version Info** 

* Plugin version:  Version: 4.0.4
* WordPress version:  4.8.1
* PHP version:

**Comment by xdemarchi** [comment]
+1 - same error when try to activate this plugin:

Parse error: syntax error, unexpected '[' in /export/htdocs/blog.com.br/wp-content/plugins/facebook-instant-articles-wp/facebook-instant-articles.php on line 107

**Comment by timjacobi** [comment]
The plugin uses syntax which is not supported by PHP <5.4 so your need to update your PHP version to at least 5.4.

See [this](https://stackoverflow.com/a/10482105) StackOverflow article for more details.
