### ISSUE TITLE
Supporting multiple Facebook pages.

### ISSUE THREAD

**Issue by upatricck** [Automattic/facebook-instant-articles-wp#756]
Ability to support multiple pages is necessary because 
For example a website might have multiple pages targeted to users in different countries, 
Enabling instant articles for all the pages is a challenge, 
The plugin can help solve this.

**Comment by sohanlalpareek** [comment]
********missing my facebook page>pareeksonu/page/g.co/2sv/faiebook/googgle account>cod fatched wrong
my browser not work this dokument disorder

**Comment by timjacobi** [comment]
@upatricck You can use the RSS feed that the plugin generates to ingest the articles to any page.
This [doc](https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed/) describes how to configure the RSS feed. The RSS feed should be available under http://<your wordpress domain>/feed/instant-articles

**Comment by upatricck** [comment]
@timijacobi Thanks
