### ISSUE TITLE
Issue No Rules defined  for <div>

### ISSUE THREAD

**Issue by rmarote** [Automattic/facebook-instant-articles-wp#758]
Hello everyone, I'm geting this issues that needs to be fixed to get aproved my articles:

No rules defined for <div class="quads-location quads-ad2"> in the context of InstantArticle
No rules defined for <div class="quads-location quads-ad4"> in the context of InstantArticle
No rules defined for <div> in the context of InstantArticle
No rules defined for <div class="quads-location quads-ad3"> in the context of InstantArticle
No rules defined for <div> in the context of InstantArticle

**Version Info**

* Plugin version: 4.0.4
* WordPress version: 4.8.1

**Comment by timjacobi** [comment]
Can you please share the source code of your post?

**Comment by rmarote** [comment]
Who are you?

________________________________
De: Tim Jacobi <notifications@github.com>
Enviado: segunda-feira, 2 de outubro de 2017 09:24:08
Para: Automattic/facebook-instant-articles-wp
Cc: rmarote; Author
Assunto: Re: [Automattic/facebook-instant-articles-wp] Issue No Rules defined for <div> (#758)


Can you please share the source code of your post?

**Comment by rmarote** [comment]
Sorry :x I saw here github haha, I'll close the post I solved the issue


________________________________
De: Raphael Marote
Enviado: segunda-feira, 2 de outubro de 2017 09:32:31
Para: Automattic/facebook-instant-articles-wp; Automattic/facebook-instant-articles-wp
Cc: Author
Assunto: Re: [Automattic/facebook-instant-articles-wp] Issue No Rules defined for <div> (#758)


Who are you?

________________________________
De: Tim Jacobi <notifications@github.com>
Enviado: segunda-feira, 2 de outubro de 2017 09:24:08
Para: Automattic/facebook-instant-articles-wp
Cc: rmarote; Author
Assunto: Re: [Automattic/facebook-instant-articles-wp] Issue No Rules defined for <div> (#758)


Can you please share the source code of your post?
