### ISSUE TITLE
Transformer help on audio

### ISSUE THREAD

**Issue by taajuus** [Automattic/facebook-instant-articles-wp#760]
Embedded audio on WordPress page, using WP default player.

Output in html:
`<audio class="wp-audio-shortcode" id="audio-88358-1" preload="none" style="width: 100%;" controls="controls"><source type="audio/mpeg" src="http://nrj.fi/wp-content/uploads/2017/08/Nuoriso-ei-uskalla-kysya.mp3?_=1" /><a href="http://nrj.fi/wp-content/uploads/2017/08/Nuoriso-ei-uskalla-kysya.mp3">http://nrj.fi/wp-content/uploads/2017/08/Nuoriso-ei-uskalla-kysya.mp3</a></audio>`

No audio player visible on FB Instant Article, strips out all of above.
Plugin warnings on article page:
`No rules defined for <audio class="wp-audio-shortcode"> in the context of InstantArticle`

Tried custom transform rule:
`{ "class": "PassThroughRule", "selector" : ".wp-audio-shortcode" }`

No help, still everything stripped off and warnings following:
`No rules defined for <source> in the context of InstantArticle
No rules defined for <a> in the context of InstantArticle`
(related to html parts for _source type="audio/mpeg"_ and _a href="_)

Tried to understand FB transformation rules and create something like following:
`{ 
  "class": "AudioRule", 
  "selector": ".wp-audio-shortcode", 
  "properties": { 
    "audio.url": { 
      "type": "string", 
      "selector": "a", 
      "attribute": "href"
    }
  }
}`

...But I can't figure out correct rule.
Please help?

**Comment by taajuus** [comment]
Anyone?

**Comment by timjacobi** [comment]
Unfortunately `<audio>` is not supported in Instant Articles at the moment so we cannot implement it in the plugin. Please refer to the [docs](https://developers.facebook.com/docs/instant-articles/reference/) to see which elements are supported. Sorry for the bad news.

**Comment by sandeepavasthi01** [comment]
Hi,
I have facing the same issue. I want to add audio tag in my instant article. Is this possible for now?
