### ISSUE TITLE
No rules defined for <div class="td-paragraph-padding-4"> in the context of InstantArticle

### ISSUE THREAD

**Issue by wwms9967** [Automattic/facebook-instant-articles-wp#764]
I have submitted my articles to facebook for review, and it appears that I have a problem with the paragraphs. 
I don't know how to create a rule so that I can solve all the paragraphs issues all over the website, please help.
Thx.

**Comment by timjacobi** [comment]
Could you please add some examples so we can debug this?

**Comment by timjacobi** [comment]
Duplicate of #582

Please continue the discussion there.
