### ISSUE TITLE
disabling advertising

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#765]
Hello.
Recently, Facebook has changed the rules for monetizing content.
https://media.fb.com/2017/09/13/standards-and-guidelines-for-earning-money-from-your-content-on-facebook/
Since among the taboo subjects there were also natural disasters (and in the USA now hurricanes) the question of switching off advertising in instant articles becomes actual.
I think many would be useful to the function of disabling advertising on custom news.

**Comment by marktwatson** [comment]
You already can. Just don't add the fb audience network ID.

**Comment by lubimow** [comment]
@marktwatson Yes, but so we will disable advertising on all publications. And it makes sense to turn off the favorites. For example, on the news about the hurricane

**Comment by marktwatson** [comment]
You would have to just do it manually. There is no solution for this.

**Comment by timjacobi** [comment]
You can disable the ad placement on a _per article_ basis as described [here](https://developers.facebook.com/docs/instant-articles/monetization/ad-placement/) under _Manual Placement_.
