### ISSUE TITLE
Hide images

### ISSUE THREAD

**Issue by Slam2** [Automattic/facebook-instant-articles-wp#766]
Hi all !

It's not possible to hide a images in articles ? I've make a "no-mobile" class for my mobile version. But it's not possible with the rules ?
`<div class="entry-image"><img class="no-mobile alignright wp-image-2053 size-thumbnail" src="https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-150x150.png" alt="" srcset="https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-150x150.png 150w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-300x300.png 300w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-500x500.png 500w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-250x250.png 250w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-105x105.png 105w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512-350x350.png 350w, https://fqdn.net/wp-content/uploads/2017/06/FAQ-512.png 512w" sizes="(max-width: 150px) 100vw, 150px" width="150" height="150"></div>`

```
{
        "class": "ImageRule",
        "selector": "img.no-mobile",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "null"
            }
        }
    }

```

And another problem.. Instant Article use a resized image in "src". It's not possible to use maximal srcset size ?
`<figure id="attachment_2055" style="width: 300px" class="wp-caption alignright"><a href="https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810.jpg" class="single-popup"><img class="wp-image-2055 size-medium" src="https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810-300x199.jpg" alt="Devanture IXINA Englos" srcset="https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810-300x199.jpg 300w, https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810-768x511.jpg 768w, https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810-500x332.jpg 500w, https://fqdn.net/wp-content/uploads/2017/06/ixina_05935500_133416810.jpg 940w" sizes="(max-width: 300px) 100vw, 300px" width="300" height="199"></a><figcaption class="wp-caption-text">Agence IXINA Englos</figcaption></figure>`

Thanks a lot for your help

**Comment by timjacobi** [comment]
To strip out tags you want to use the `IgnoreRule`:

_This rule class will effectively strip out an element tag which matches the associated selector of the rule._

```json
{
        "class": "IgnoreRule",
        "selector": "img.no-mobile",
}
```
