### ISSUE TITLE
Featured Images not Showing up on Instant Articles

### ISSUE THREAD

**Issue by MainaWycliffe** [Automattic/facebook-instant-articles-wp#767]
The featured image from my blog is not showing up on the instant articles but it shows on the site. The only plugin i use moves is W3 Total Cache and WP Offload S3 Lite. Thanks.
![21477959_158556824726840_2014512830610407424_n](https://user-images.githubusercontent.com/12270550/30567357-a78d08be-9cd8-11e7-936a-2243152e2dd9.jpg)

**Comment by mathiasribeiro** [comment]
I'm also having the same problem.

**Comment by timjacobi** [comment]
The featured image is not part of the post source code which is what is being transformed. We could consider using the featured image for the Instant Article header. Please have a think about how you would like this to behave and open a feature request?
