### ISSUE TITLE
Author Name and Bio Showing Up on Byline

### ISSUE THREAD

**Issue by swshelper** [Automattic/facebook-instant-articles-wp#768]
# Steps required to reproduce the problem
![screenshot-business facebook com-2017-09-26-08-10-28-923](https://user-images.githubusercontent.com/32230829/30860255-8fa2caec-a294-11e7-9d05-11b0eb568b3f.png)

1. Instant Articles adds both the author name and author bio to the byline when published to FB
2. I am having to go in and edit every article to <address> Name </address>
3. Sometimes when I make these updates to the byline, it still does not update on FB after saving and publishing it back to live.

# Expected Result
I want the Byline to have only the author name and hide the author's bio.
* By Name

# Actual Result Not the same article as the html submitted above. This is an example of the byline output.
![output](https://user-images.githubusercontent.com/32230829/30860237-7b97f8ba-a294-11e7-9949-b9232159daec.png)
* 
How do I modify to hide the author bio and keep the author name?  I have only found solutions that hide the author byline completely.
---

**Version Info**

* Plugin version: 4.0.5
* WordPress version: 4.8.2
* PHP version: 7

**Comment by timjacobi** [comment]
Unfortunately I can't reproduce this. Are you using a particular plugin or design?

**Comment by swshelper** [comment]
I tried modifying the fb instant article feed template, and it appears to be working. Initially, when I tried it, I did not see any change.

**Comment by timjacobi** [comment]
Great. Can we help you with anything else in this case?

**Comment by everton-rosario** [comment]
If anything else, lets reopen.
