### ISSUE TITLE
Question about adding attributes to dom elements

### ISSUE THREAD

**Issue by jmouka** [Automattic/facebook-instant-articles-wp#77]
Hello, I'm trying to add some attributes, e.g. controls to the video tag <video controls>...</video>. Another example is <figure data-feedback="fb:likes,fb:comments">

What would be the recommended approach? To create a new dom transform filter, or to add apply_filter hooks into the existing ones?

**Comment by philipjohn** [comment]
Hi @jmouka - DOM transformation is no longer used in the plugin so that wouldn't be an option anymore I'm afraid. We do have the `instant_articles_content` filter - would that suffice?

**Comment by jmouka** [comment]
Good to know. I'll give that a try. Thank you!

**Comment by everton-rosario** [comment]
Hello, thanks for using Instant Articles @jmouka 
Im closing this for now. If any problem found, please file another issue.
