### ISSUE TITLE
Plugin ignores <OL> in content

### ISSUE THREAD

**Issue by pnoeric** [Automattic/facebook-instant-articles-wp#776]
# Steps required to reproduce the problem

1. Look at the original article: http://afv.com/12-reasons-two-is-better-than-one/
2. Search for the string "break it down"
3. Notice that following that string is a list of 8 items
4. Look at "view source" and repeat steps 2 and 3, you'll see where the `<ol>` list starts
5. Look at output of WP plugin: http://afv.com/feed/instant-articles
6. Again search for the string "break it down"
7. Notice the entire `<ol>` part of the original content isn't there!

# Expected Result

* All the content from the original post would be converted into IA format and output by the plugin

# Actual Result

* The IA plugin seems to ignore the entire `<ol>` structure and doesn't put it in the final output

---

**Version Info**

* Plugin version:  4.0.5
* WordPress version: 4.8.2

**Comment by timjacobi** [comment]
Confirm. Error is _No rules defined for `<h3>` in the context of ListItem_

**Comment by pnoeric** [comment]
Ah ok thanks Tim. I’ll be sure the HTML is cleaned up and see if that improved the results. Or if I have an ‘h3‘ tag, maybe that is the issue, if you’re seeing that error.

**Comment by timjacobi** [comment]
@pnoeric `<h3>` in `<ol>` is valid HTML but we don't currently support it. Removing the `<h3>` should fix your issue.

**Comment by pnoeric** [comment]
I've removed the OL entirely, but now I have a new problem..... the `<figure class="op-ad">` code isn't being sent through to the IA output. Same info as my post #1 above, just change 'break it down' to 'op-ad'. You will see the code in the web view but not in the IA output. This is a bug, no?

(BTW where is the log file for the IA plugin? I would love to see those error messages)

**Comment by timjacobi** [comment]
@pnoeric Can you please raise a separate issue for this. It makes it easier for us to track. Thanks :)

**Comment by pnoeric** [comment]
Sure, thanks.

**Comment by pestevez** [comment]
I'm closing this issue since we have #779 to track the second problem described.
