### ISSUE TITLE
Server crashing on activating this plugin

### ISSUE THREAD

**Issue by codeslane** [Automattic/facebook-instant-articles-wp#782]
# Steps required to reproduce the problem

1.  When Plugin is activated
2.  Deactivation of plugin solves the issues.
3.  Currently, Theme is Hestia. 

# Expected Result

*  This plugin needs to work fine with all the other plugins. 

# Actual Result

*  Server is crashing
The server ran out of resources, mostly CPU, RAM, I/O Usages runs out of memory.

Temporary Fix: Activating CloudFlare DDoS (I'm Under Attack) Protection solves this issue. 

---

**Version Info**

* Plugin version: Latest
* WordPress version: Up-To-Date
* PHP version: 5.1

**Comment by timjacobi** [comment]
Can you post some log files so we can see where it breaks?

**Comment by codeslane** [comment]
Sure, 

Here's the log file:

I read and found many lines like this 

108.162.245.129 - - [31/Aug/2017:05:49:14 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:49:14 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:49:22 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:49:22 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:49:52 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:49:53 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:50:14 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:50:14 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:50:42 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:50:42 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:51:16 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:51:16 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:52:43 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:52:43 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.245.129 - - [31/Aug/2017:05:53:06 -0700] "GET /contents/uploads/2017/06/1-moodo.jpg HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
108.162.246.94 - - [31/Aug/2017:05:53:06 -0700] "GET /contents/uploads/2017/05/NitroQ-power-bank.png HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
162.158.69.116 - - [31/Aug/2017:05:54:17 -0700] "GET /feed/instant-articles HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1"
162.158.75.33 - - [31/Aug/2017:05:58:47 -0700] "GET /feed/instant-articles HTTP/1.1" 404 9437 "-" "facebookexternalhit/1.1"

This plugin is really coded badly.
I have 2 websites on same server. With 1 this plugin works fine but for other it crash the server just after 2 3 mins. of activation.

[log.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/1375373/log.txt)

**Comment by timjacobi** [comment]
Sorry I don't see anywhere in the log file that would tell us how the plugin crashed the server. It will be hard for us to debug like this.

**Comment by codeslane** [comment]
I can redo the steps to reproduce the issue again, 
Just tell me how to make a log. 

I will forward that to you again.

**Comment by codeslane** [comment]
Well, 
After activating the cloudflare under attack protection. 
The server got a bit free from the I/O request. 

I think the issue is might with crawling/ facebots. 
Because plugin is creating a lot of php processes

**Comment by codeslane** [comment]
<img width="1440" alt="screen shot 2017-10-11 at 4 40 52 pm" src="https://user-images.githubusercontent.com/26877201/31445276-5544480c-aebb-11e7-9620-ae87e044abd4.png">
<img width="1440" alt="screen shot 2017-10-11 at 4 38 29 pm" src="https://user-images.githubusercontent.com/26877201/31445278-5612ab0c-aebb-11e7-9e1d-f3b8513c5df5.png">
<img width="1440" alt="screen shot 2017-10-11 at 4 37 51 pm" src="https://user-images.githubusercontent.com/26877201/31445279-56404e7c-aebb-11e7-931b-22434d91408a.png">


Attached the images.

**Comment by timjacobi** [comment]
It depends on your server. If you say the plugin crashes the server then we're going to need the server logs to see what leads to the crash.

**Comment by codeslane** [comment]
I got the issue. 

Whenever I activate this plugin, I got hit by IP's 216.245.212.126 / 50.63.85.70 & 166.62.10.48

I blocked all the IP's after seeing the log and pausing the CloudFlare service my server showed the IP's in error Logs. 
I blocked the above IP's ranges and my server again started working like before.
Even with this plugin, it working perfectly fine. 

Just look up your plugin it might have some vulnerabilities that causing the attack possible.

Because XML-RPC is already blocked on my site including pingbacks.


Thanks

**Comment by codeslane** [comment]
Update:

Blocking IPs doesn't solve the issue for long.
Still, server crashing with the plugin.

**Comment by steelmaiden** [comment]
I have the same problem... after activating the plugin, 30 minutes later, server load gets high and the website almost not reachable... I also use Cloudflare, not sure if the problem is somehow connected with it.

**Comment by codeslane** [comment]
Post your server logs. 

Maybe somehow they can solve our issues. 
Something is broken with plugin.

**Comment by timjacobi** [comment]
We need to get to a point where we understand what exactly consumes the CPU load. Any logs help.

**Comment by codeslane** [comment]
Tim, 

It crashes and in log what I found is same IP is trying to request and access multiple links at same time. 

This make the CPU loads goes mad. 

You Might need to check whole codes to get this.

**Comment by timjacobi** [comment]
Unfortunately, we can't debug a problem that we can't reproduce. Both of you are running on Cloudflare which means for now we can only assume that the plugin doesn't play well with Cloudflare. How so we can only say by debugging it on Cloudflare for which we rely on you since you have it running there.

**Comment by steelmaiden** [comment]
Ok i have enabled the plugin now and nothing has happened so far for the last 20 minutes.

Is there a cronjob that the plugin runs occasionally?

**Comment by codeslane** [comment]
I don’t think it’s a cloudflare issue because on my second site its working perfectly fine with cloudflare enabled. 

Only the issue is with https://www.knowurcodes.com

**Comment by steelmaiden** [comment]
I kept the plugin active for hours now and nothing happened. Seems like the high load happens randomly or with a specific action. I will have to disable it for now because i dont want my server to crash while im not monitoring it.

Do you run your website with issues on Nginx or Apache?

**Comment by codeslane** [comment]
Apache

**Comment by steelmaiden** [comment]
Ok it just happened again... load went over 20 and server got choked.
However, nothing appeared in my Nginx logs...
I deleted the plugin via SSH and the load went back to normal.
I've also noticed the mysqld was causing the high load.

**Comment by diegoquinteiro** [comment]
The plugin does read from mysql on the page load, so that might be causing the high load depending on the traffic.

- Do your sites have high audience?
- Do you have any cache layer enabled? 
  - If not, would you be able to try installing a cache plugin to see if the error still happens?

It is not clear whether the hits from Facebook Crawler that appear on your log are related to the crashing of the server.

Might be related to #786

**Comment by codeslane** [comment]
@diegoquinteiro My site doesn't have a high audience.
Yes, I have cache layer enabled also minified Javascript, CSS, HTML through Cloudflare.

I think the issue is with Hestia Theme, If you got any testing environment please do check it with Hestia https://wordpress.org/themes/hestia/

Please fix this issue if possible. 

Thanks,
Vaibhav Singh

**Comment by codeslane** [comment]
@timjacobi @diegoquinteiro @steelmaiden, 

I debugged the issue, after going through a lot of debugging process, I found the pingback was disabled on my server  _.htaccess_ file. 

This is the code causing the issue and crashing the server after activating the plugin.
<Files xmlrpc.php>
<IfModule mod_authz_core.c>
Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
Order deny,allow
deny from all
</IfModule>
</Files>

-----------------

This is the changes I made and instantly server processes go low and site again started working perfectly. 

<Files xmlrpc.php>
<IfModule mod_authz_core.c>
Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
Order deny,allow
allow from all
</IfModule>
</Files>

-------------

# Conclusion

Allow access to pingbacks and xmlrpc.php, they might cause conflicts with some theme and plugins and the instant article may not work with that theme/plugin. 

Hope this helps.

Disable any plugin blocked access to xmlrpc & pingbacks. If you have done the blocking manually from any theme or .htaccess , then remove those codes or change the code like I did.

Regards, 
Vaibhav Singh
