### ISSUE TITLE
Some articles are automatically going Live

### ISSUE THREAD

**Issue by addon25** [Automattic/facebook-instant-articles-wp#783]
# Steps required to reproduce the problem
Reproduced by accident. I can not determine when.

# Expected Result

* Posts should be posted as drafts .

# Actual Result

* Some articles are automatically going Live. I haven't determined any particular steps to recreate. Some times they are brand new articles, some times they are articles that have been live on WP for months and we republish them (change the date to current). Page config is correct https://imgur.com/EX8eiqB

---

**Version Info**

* Plugin version: 4.0.5
* WordPress version: 4.8.1
* PHP version: 7.1

**Comment by timjacobi** [comment]
The plugin publishes articles to production using the API. You can disable that by checking the _Enable development mode_ option in the settings. The articles will still be in the RSS feed so RSS ingestion will continue to work.

**Comment by timjacobi** [comment]
We have recently removed the code which calls the API since this is not supported anymore.
