### ISSUE TITLE
Need Transformer Rule for JW Player

### ISSUE THREAD

**Issue by anthonykantara** [Automattic/facebook-instant-articles-wp#785]
# Steps required to reproduce the problem

1. Embedded JW Player to wordpress article (both iframe and javascript)

# Expected Result

* Video player to be embedded into Instant Articles

# Actual Result

* Everything shows except the JW Player in IA.

---

**Version Info**

* Plugin version: 4.0.5
* WordPress version: latest
* PHP version: 7.0

**Comment by wle8300** [comment]
@anthonykantara I'm encountering this issue. How'd you fix it?
