### ISSUE TITLE
Multi-page articles only show first page

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#79]
If you have a multi-page article (i.e. one that has  within it) only include the first page.  

Ideally, it should include subsequent pages like (I think) the AMP plugin does.

**Comment by sgatz** [comment]
I created this function to merge my pages into one page

add_filter( 'instant_articles_before_render_post', 'my_instant_articles_before_render_post', 10 );
function my_instant_articles_before_render_post($post_object) {
	global $post;

 if ( false !== strpos( $post->post_content, '' ) ) 
    {
        // Reset the global $pages:
        $GLOBALS['pages']     = [ str_replace('', '', $post->post_content) ];

        // Reset the global $numpages:
        $GLOBALS['numpages']  = 0;

       // Reset the global $multipage:
        $GLOBALS['multipage'] = false;
    }

	return $post_object;
	
}

**Comment by philipjohn** [comment]
Hi @sgatz - `<!--nextpage-->` looks like something that would be made available by a plugin. That plugins will likely be hooking `the_content` filter to split posts into multiple pages. The best solution, then is to remove that hook using something like:

```
if ( is_feed( 'instant-articles' ) {
    remove_filter( 'the_content', '<plugin hook>' );
}
```

...replacing `<plugin hook>` with whatever function the plugin uses.
