### ISSUE TITLE
Articles doesn't publish to Instant Articles (Publishing Tools)

### ISSUE THREAD

**Issue by rothanachoun** [Automattic/facebook-instant-articles-wp#791]
# Steps required to reproduce the problem

1. Create a new post
2. After success we got
. This post will be available as an Instant Article.
. This post was transformed into an Instant Article with no warnings [Toggle debug information]

# Expected Result

* Published into Instant Articles (Publishing Tools)

# Actual Result

* Didn't see in Instant Articles (Publishing Tools)

---

**Version Info**

* Plugin version: 4.0.5
* WordPress version: 4.8.2
* PHP version: 5.5.9

**Comment by timjacobi** [comment]
Thank you for reporting this. I'm just looked into this and can reproduce it. Will post more info once I've got to the bottom of it.

**Comment by timjacobi** [comment]
Currently direct import is not supported. If you share the article on your page it will be scraped and made available to you in the _Publishing Tools_.

**Comment by rothanachoun** [comment]
I got it. Thanks for you help.

**Comment by timjacobi** [comment]
If there is anything else let's continue in #792
