### ISSUE TITLE
DOM filtering for headings with children

### ISSUE THREAD

**Issue by Aioros** [Automattic/facebook-instant-articles-wp#80]
Headings below `h2` (i.e. `h3`, `h4`, `h5`, and `h6`) are stripped of some of their child nodes. It seems to me that the problem lies in the `_build_fragment()` function of the filter, which loops over the child nodes with little care of the changing array length (the `address` filter, for example, does it right).

**Comment by philipjohn** [comment]
Is this still an issue for you in v2+ @Aioros ? We don't use DOM transformation any more so this may be fixed by the new method.

**Comment by Aioros** [comment]
Right, I don't think this is an issue anymore.

**Comment by everton-rosario** [comment]
@Aioros Thanks for using Instant Articles.

Closing this issue. Feel free to reopen or file another issue.
