### ISSUE TITLE
WP featured videos do not appear in Instant Articles 

### ISSUE THREAD

**Issue by dumango** [Automattic/facebook-instant-articles-wp#800]
Hello, 

I've been having problem with my wordpress **featured videos** and their instant article results.
For example this post has a featured video instead of featured image on the top:
http://obicimsinema.com/stranger-things-saadettin-teksoy/

However in the instant article version
https://www.facebook.com/obicimsinema/posts/191042724796262
there is no video appearing on the top as a featured video.

Therefore to fix this, i have to put the video two times in the related article.

One in the featured video on the top, the other is the one below for those who will be unable to see the featured video in instant articles.

This two times youtube video loading affects my article load as well on the desktop.

How can we fix this? So that my instant articles also have that featured videos.

Thanks a lot

**Here is my version info**

* Plugin version: 4.0.5
* WordPress version: 4.8.3
# #

**Comment by pestevez** [comment]
Hi @dumango,

How are you generating the embedded video in WordPress?

Also, can you go to the post edit page and in the Instant Article plugin section click on _[Toggle debug information]_ and share both _Source Markup_ and _Transformed Markup_?

Thanks!

**Comment by pestevez** [comment]
I am closing the issue now due to inactivity. Please feel free to reopen if you need additional information.

**Comment by demetrox** [comment]
oh my god.. i really need an answer to this issue
