### ISSUE TITLE
<Figurecaption> Not working on Instant Article

### ISSUE THREAD

**Issue by bsgies** [Automattic/facebook-instant-articles-wp#801]
Hi everyone,

I'm using captions on my WordPress website. Here's an example: http://prntscr.com/h5nn8t.

Now since it's a WP caption, the image is wrapped around: [caption id="attachment_15900" align="alignnone" width="737"]<img class="wp-image-15900 size-full" src="URL" /> <a href="abc.com" target="_blank">abc.com</a>[/caption]

When Facebook tried to transform it into an Instant article, it gave me the following error: http://prntscr.com/h5nq8v

`No rules defined for <div class="wp-caption alignnone"> in the context of InstantArticle`

for which I added this transform rule:

`{"rules": [ { "class": "IgnoreRule", "selector" : "p.wp-caption-text" }, { "class": "ImageRule", "selector" : "div.wp-caption", "properties" : { "image.url" : { "type" : "string", "selector" : "img", "attribute": "src" }, "image.caption" : { "type" : "element", "selector" : "p.wp-caption-text" } } } ]}
`
After using this transform rule the error is now fixed, but when I open instant article preview on mobile, this is how the caption is coming on it: http://prntscr.com/h5nrir.

So I either want the caption to come as how it is coming on WordPress (screenshot above) or completely remove it from the instant article. 

Can anyone help me with the issue?

Many Thanks.

**Comment by bsgies** [comment]
Bump?

**Comment by pestevez** [comment]
Hi @bsgies,

Can you please post the HTML markup of one of your articles having this issue? A URL works fine too. Thanks!

**Comment by bsgies** [comment]
`https://matterfeed.com/arche-cabin/`

**Comment by pestevez** [comment]
I believe the plugin is generating all the captions for that URL. Based on your `ia:markup_url` meta tag, the IA markup of this article is at https://matterfeed.com/arche-cabin/?ia_markup=1

I took a look at the IA markup, and it looks like all the images have the corresponding `figcaption` element. For example:

```html
<figure>
  <img src="https://d19v35xiwyakdk.cloudfront.net/uploads/2016/10/Pic9-15.jpg"/>
    <figcaption>
      <a href="http://tinyhousetalk.com/wp-content/uploads/tiny-arched-cabins-01-600x400.jpg">tinyhousetalk.com</a>
    </figcaption>
</figure>
```

Is it possible that the preview you are looking at is not updated? Please force a rescrape of your URL using the [Sharing Debugger](https://developers.facebook.com/tools/debug/) and see if the problem persists.

**Comment by bsgies** [comment]
Yes @pestevez I'm aware of the fact that the plugin is generating/transforming these captions into the figurecaption tag.

My question was if someone can help me disabling these caption being transformed into the instant article? Because I do not want to show image captions in my instant articles.

**Comment by bsgies** [comment]
@pestevez Seems like adding this transform rule has done the trick.

`{"rules": 
 [
   { 
     "class": "IgnoreRule", 
     "selector" : "p.wp-caption-text" 
   }, 
   { 
     "class": "ImageRule",
     "selector" : "div.wp-caption",
     "properties" : {
       "image.url" : {
         "type" : "string",
         "selector" : "img",
         "attribute": "src"
       }
     }
   }
 ]
}`

**Comment by pestevez** [comment]
Sorry, I misunderstood the issue. Yes, creating an `IgnoreRule` for the `p.wp-caption-text` selector and excluding the `image.caption` property of the `ImageRule` should do the trick.

I am closing the issue now, since you figure out the required rules, but please feel free to reopen if you need additional information.
