### ISSUE TITLE
No rules defined for <img> in the context of ListItem

### ISSUE THREAD

**Issue by HenkDz** [Automattic/facebook-instant-articles-wp#803]
# Steps required to reproduce the problem

1. Create Post
2. Insert Image in a List
3. get the "No rules defined for <img> in the context of ListItem" Error

# Expected Result

* after adding the Rule
        {
        "class": "ListItemRule",
        "selector" : "img"
        }
I thought It should work fine.

# Actual Result

* No rules defined for <img> in the context of ListItem 

---

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by pestevez** [comment]
Hi @HenkDz, can you please share a sample code snippet, and do you expect it to be transformed?

In any case, I believe that in Instant Articles images are not supported inside lists, per the Image element [documentation](https://developers.facebook.com/docs/instant-articles/reference/image):

> The `<figure>` element representing the image must be included standalone within the body of the article and not enclosed within a `<p>` element.

You may need to add a rule to remove the list tags and insert the images directly into the article body.

**Comment by HenkDz** [comment]
Yes I have Eliminated the issue by simply turning numeric Lists to simple 
<br/>1. some text <figure>img</figure>
<br/>2. some text <figure>img</figure>
The issue now is with multi pages articles. The plugin only transforms the first page before the first "page break". I, however, managed to save my page without any breaks (one long article) and then copied the 	
[Toggle debug information] --> Transformed Markup:
and paste it into the edit form in my FB page, which worked perfectly. Nonetheless, when I turned back my article to multi page article, the FB IA got updated using RSS feed and showed only the first page of my article.

**Comment by pestevez** [comment]
Let me do some research to see if there is an easier way to handle multi-page articles, but do you still need to have the RSS feed configured if you are using the WordPress plugin for Instant Articles?

**Comment by HenkDz** [comment]
Can I just drop the RSS feed and use only the plugin? If it's not a part of
the configuration, i have no need for it.

**Comment by pestevez** [comment]
Yes, you can drop the RSS feed ingestion method if all your articles go through the plugin in your publishing flow.

Regarding the multi-page articles, if they are important to you my recommendation is for you to close this issue and open a separate one. I think it will be easier to track and for other folks to chime in, but I'll leave that decision to you.

**Comment by pestevez** [comment]
Can you describe how are multi-page articles handled in the CMS? When you Save or Update the article, will the plugin have access to the full article content?

**Comment by HenkDz** [comment]
No, pestevez The plagin only shows the first page. That is, the page before the first page break. All other content from page two and up won't be shown in FB IA. Therefore, I have disabled the RSS feed and edit my articles manually.

**Comment by pestevez** [comment]
How is the content split into pages? Is it through a third-party plugin?

Can you share both _Source Markup_ and _Transformed Markup_ from the Instant Articles *Toggle debug information* section at the bottom of the post editing page?

**Comment by HenkDz** [comment]
No there is no Plugin to do that. In post edit form in WP you click insert--->Page Break. I would look like this:
    `page one 
--pagebreak--
page two`
And here are both Source Markup and Transformed Markup
 **Source Markup:** 
````
<div` dir="ltr" style="text-align: left;">
<div style="clear: both; text-align: center;"></div>
<h2 style="background: 0px 0px #ffffff; border: 0px; color: #2c3e50; font-family: 'PT Serif', sans-serif; margin: 0px 0px 15px; outline: 0px; padding: 0px; position: relative; transition: all 0.3s ease; vertical-align: baseline;"><span style="background-attachment: initial; background-clip: initial; background-image: initial; background-origin: initial; background-position: 0px 0px; background-repeat: initial; background-size: initial; border: 0px; margin: 0px; outline: 0px; padding: 0px; transition: all 0.3s ease; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; font-size: large; margin: 0px; outline: 0px; padding: 0px; transition: all 0.3s ease; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; color: #165a72; font-family: 'merriweather'; margin: 0px; outline: 0px; padding: 0px; transition: all 0.3s ease; vertical-align: baseline;"><span style="background: 0px 0px; border: 0px; color: #ff870c; float: left; font-size: 75px; line-height: 60px; margin: 0px; outline: 0px; padding: 4px 8px 0px 3px; transition: all 0.3s ease; vertical-align: baseline;">I</span>once had a Huawei Y6 Pro TIT-U02 and the only thing I ever wanted is to root this device. Naturally, I have looked every where for root methods whether using apps or flashing .img files. Eventually and after a quite long Time a Russian friend found the a way to dump the boot.img and port it to accept root. Follow the process to Root Huawei Y6 Pro.<br />
</span></span></span></h2>
<h2 style="background: 0px 0px #ffffff; border: 0px; color: #2c3e50; font-family: 'PT Serif', sans-serif; margin: 0px 0px 15px; outline: 0px; padding: 0px; position: relative; transition: all 0.3s ease; vertical-align: baseline;"><span style="font-family: verdana,geneva,sans-serif; font-size: 12pt;">The process is not easy and needs extreme focus let&#8217;s get started.</span></h2>
<h2><span style="color: #333399; font-size: 24pt; font-family: georgia,palatino,serif;">The Stages:</span></h2>
<ol>
<li><span style="font-size: 12pt;">Unlocking the bootloader. <a class='qlabs_tooltip_top qlabs_tooltip_style_50 cursor_help event_hover' style='' >(voids warranty)<span style='width: 180px; '  ><strong>Voiading Warranting.</strong>Be informed that unlocking your Huawei Y6 Pro TIT-U02 bootloader will show your warranty as void. No worries you can lock it back any time.</span></a>
</span></li>
<li><span style="font-size: 12pt;">Flashing Custom Recovery ( Carliv Touch Recovery by <b>jemmini </b>)</span></li>
<li><span style="font-size: 12pt;">Flash Boot.img</span></li>
<li><span style="font-size: 12pt;">flashing SuperSU-v2.79<br />
a. Installing BusyBox Pro (optional)<br />
b. </span>Installing Xposed (optional )</li>
</ol>
</div>
<p><!--nextpage--></p>
<h2><span style="font-family: georgia,palatino,serif; font-size: 24pt; color: #333399;">Stage 1: Unlocking the bootloader.</span></h2>
<p><span style="font-size: 12pt;">First you need to know that unlocking your bootloader <strong>voids warranty</strong>. However, you can lock it back any time.</span></p>
<h2><strong>NOTE:</strong> THIS PROCESS WILL REBOOT YOUR PHONE ON TO <span style="color: #ff0000;"><strong>FACTORY REST. </strong><span style="color: #000000;">All unsaved data will be lost. Make sure you backup your important data before starting the process.</span></span></h2>
<p><span style="font-size: 12pt;">Now to the process to unlock the bootloader of your Huawei Y6 Pro TIT-U02. In order to unlock the bootloader you need to follow a set of steps carefully.</span></p>
<h3><strong>Step 1: Enabling OEM unlocking.</strong></h3>
<p><span style="font-size: 12pt;">Before you unlock your bootloader <strong>MAKE SURE</strong> you have enabled your OEM unlocking. To do this go to</span> <a class='qlabs_tooltip_top qlabs_tooltip_style_50 cursor_pointer event_hover' style='' ><span style="font-size: 12pt;">options &#8211;&gt; about phone &#8211;&gt; tap five times on Build Number<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_17_17_32_06-169x300.png" /></span></a> in order to Enable developer options. Now,</span> <a class='qlabs_tooltip_top qlabs_tooltip_style_50 cursor_pointer event_hover' style='' ><span style="font-size: 12pt;">Enter Developer options and scroll to find OEM unlocking and Enable it</span><span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_17_17_37_59-169x300.png" /></span></a><span style="font-size: 12pt;"> a message will popup click Enable</span>. <a href="https://youtu.be/DroF-eXv14Q">Watch the Video Tutorial.</a></p>
<h3><strong>Step 2: Getting the unlock Code for your Huawei Y6 Pro TIT-U02<br />
</strong></h3>
<p style="padding-left: 30px;"><span style="font-size: 12pt;">In order to get your unlock code you need to follow:</span><br />
<span style="font-size: 12pt;"> <strong>The official Method (<span style="color: #00ff00;">Recommended</span>):</strong> <a href="https://emui.huawei.com/en/plugin/unlock/index"><span class="s1">Click Here</span></a> to request an official unlock code.</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt;"><strong>Pre-requisits</strong>:</span><br />
<span style="font-size: 12pt;"> 1.Huawei account, if you don’t have make one for free.</span><br />
<span style="font-size: 12pt;"> 2.Product Model Name, which you can get going in settings&gt;about phone, there you will see model number</span><br />
<span style="font-size: 12pt;"> 3.serial number &amp; IMEI are written on packing box, but you can also get serial by dialing this code *#*#2846579#*#* and then tap on manufacturing information. Also get IMEI by dialling *#06#</span><br />
<span style="font-size: 12pt;"> 4.To obtain the product ID number dial *#*#1357946#*#* if the code won&#8217;t run and the Dial pad just disappears don&#8217;t worry Just Return the phone to the Original language try one of <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >three languages<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_19_09_26_16-169x300.png" /></span></a> at the very bottom.</span></p>
<p style="padding-left: 60px;"><span style="font-size: 12pt;">or Download <a href="http://ouo.io/fqBoDn" target="_blank" rel="noopener">Huawei Unlocker</a> the Huawei <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >Unofficial Unlock code generator<span style='width: 300px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Huawei-Unlocker-300x271.png" /></span></a>. <strong>(It is flagged as a suspicious file by ESET anti virus but it is safe)</strong></span></p>
<h3><strong>Step 3: Unlocking the bootloader using Adb and Fastboot.</strong></h3>
<h3><span style="font-size: 16px; font-family: verdana,geneva,sans-serif;">Once you have got your unlock code, Save it or take screenshot and save it somewhere.</span></h3>
<div>
<p><span style="font-size: 12pt;">1. OEM unlock in developer options.</span><br />
<span style="font-size: 12pt;">2. Enable USB debugging in <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >Settings &gt; Developer Options &gt; USB Debugging<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Usb-Debugging-168x300.png" /></span></a> ( Make sure you have enabled oem unlocking)</span><br />
<span style="font-size: 12pt;">3. Connect your phone with PC &amp; type “adb devices” <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >your phone will ask for permission, check always allow from this pc &amp; grant permission.<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Untitled2-1-168x300.png" /></span></a></span><br />
<span style="font-size: 12pt;">4. Dwonload <b><a href="http://linkshrink.net/7JBnXd" target="_blank" rel="noopener">Minimal ADB and Fastboot</a> , </b> after downloading, extract the contents of <b><span id="file_name_short48260212">adb tools.rar</span></b> and Enter the folder where adb.exe is located, <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >Hold Shift+Mouse right click and select &#8220;Open command window here&#8221;<span style='width: 400px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Untitled-300x200.png" /></span></a>.</span><br />
<span style="font-size: 12pt;">5. Then type following command</span></p>
<pre><span style="font-size: 12pt;">adb reboot-bootloader</span></pre>
<p><span style="font-size: 12pt;">if this command doesn’t work, then disconnect USB cable switch off phone , hold volume down button and connect with pc, your phone should enter fastboot mode.</span></p>
<p><span style="font-size: 12pt;">Let windows install drivers, then type</span></p>
<pre><span style="font-size: 12pt;">fastboot devices</span></pre>
<pre><span style="font-size: 12pt;">fastboot oem unlock xxxxxxxxxxxxx</span></pre>
<p><span style="font-size: 12pt;">(xxxxxx is your unlock code) and your phone will be unlocked select <strong>yes</strong> by using volume up button.</span><br />
<span style="font-size: 12pt;">Before you proceed you should double check that your bootloader is unlocked. To do that Enter the code bellow.</span></p>
<pre><span class="notranslate" style="font-size: 12pt;">fastboot oem get-bootinfo</span></pre>
<p><span style="font-size: 12pt;">If you have followed the steps carefully this command should show something similar to this <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >image<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Oem-unlocked-300x88.png" /></span></a>.</span></p>
<p><span style="font-size: 12pt;">6. Run the code bellow to reboot your phone. The phone should boot on <strong>Factory Reset</strong>.</span></p>
<pre><span class="notranslate" style="font-size: 12pt;">fastboot reboot</span></pre>
</div>
<p><!--nextpage--></p>
<h2><span style="font-family: georgia,palatino,serif; font-size: 24pt; color: #333399;">Stage 2: flashing Custom Recovery ( Carliv Touch Recovery by <b></b><b>jemmini </b>)</span></h2>
<p><span style="font-size: 12pt;">Now that you have successfully Unlocked your bootloader, we proceed to stage 3 of the rooting process ,that is, Flashing The Custom recovery. To do so follow these steps. <b><span id="file_name_short48207901" style="color: black;"></span></b></span></p>
<p><span style="font-size: 12pt;"><strong>Step 1:</strong> download <a href="http://linkshrink.net/7OfAAv"><b><span id="file_name_short48207901">carlivrecovery.img</span></b><b><span id="file_name_short48207901">g</span></b><b><span id="file_name_short48207901"></span></b></a>. and <strong>place it in the adb folder. (Important)</strong> do not rename. (This recovery is made especially for TIT-U02 don&#8217;t try it elsewhere).</span></p>
<p><span style="font-size: 12pt;"><strong>Step 2:</strong>Here we do steps similar to those of the unlocking. First, Enter the folder where adb.exe is located. Click right mouse while holding left Shift. Now if your phone is not already in the bootloader mode you should run the code bellow to boot it into bootloader:</span></p>
<pre><span class="notranslate" style="font-size: 12pt;">adb reboot-bootloader</span></pre>
<p><span style="font-size: 12pt;">once your device reboots into bootloader run the codes bellow one by one to flash boot.img</span></p>
<pre><span class="notranslate" style="font-size: 12pt;">fastboot devices
fastboot flash recovery <span id="file_name_short48207901">carlivrecovery.i</span><span id="file_name_short48207901">m</span><span id="file_name_short48207901">g</span>
</span></pre>
<h4><strong>NOTE: Once the flash is complete <span style="color: #ff0000;">Do not reboot into system</span>. Hold VOL+ and run the following command:<br />
</strong></h4>
<pre><span class="notranslate" style="font-size: 12pt;">fastboot reboot</span></pre>
<h4><strong>Then select Recovery and press VOL- to </strong><strong>confirm.</strong></h4>
<p><!--nextpage--></p>
<h2><span style="font-family: georgia,palatino,serif; font-size: 24pt; color: #333399;">Stage 3: flashing Boot.img</span></h2>
<p><span style="font-size: 12pt;">Now that you have successfully flashed recovery, we proceed to stage 3 of the rooting process ,that is, Flashing Boot.img.</span></p>
<p><span style="font-size: 12pt;"><strong>Step 1:</strong> Download <a href="http://linkshrink.net/7pouDT" target="_blank" rel="noopener">boot.img</a>. and <strong>place it in your SD card.</strong></span></p>
<p><span style="font-size: 12pt;"><strong>Step 2: </strong>Enter the recovery mode and choose <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >Carliv Menu<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Carliv-Menue-300x212.png" /></span></a>. After that Choose <a class='qlabs_tooltip_top_center qlabs_tooltip_style_42 cursor_pointer event_hover' style='' >Flash Boot or recovery Image<span style='width: 180px; '  ><img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Carliv-Touch-300x230.png" /></span></a>. Select Flash boot Image and browse for Boot.img you have downloaded and placed in SD card in <strong>Step 1.</strong> Flash the boot image and <strong>clear cache ONLY</strong> then<strong> REBOOT</strong> into system. After that, Place the SuperSU-v2.79.zip you get from Stage 4 in you Sd card.</span><!--nextpage--></p>
<h2><span style="font-family: georgia,palatino,serif; color: #333399; font-size: 24pt;">Stage 4: Flashing SuperSU-v2.79<br />
</span></h2>
<p><span style="font-size: 12pt;">After flashing th boot.img and clearing cache and rebooting into system you need to Flash the Super user to get Root Rights. Follow the simple steps:</span></p>
<p><span style="font-size: 12pt;"><strong>Step 1: </strong>Dow,load <a href="http://linkshrink.net/7JXvSz" target="_blank" rel="noopener">SuperSU-v2.79</a>.</span></p>
<p><span style="font-size: 12pt;"><strong>Step 2:</strong> Reboot into recovery and select Install zip then browse for <b><span id="file_name_short48208045" style="color: black;"></span></b><span id="file_name_short48208045" style="color: black;">SuperSU-v2.79-SYSTEMMODE.zip</span> and confirm Install. Reboot your system and Voila You had you Huawei Y6 Pro Rooted. Enjoy The use of Powerful and Ultimate possibilities of root base apps.</span></p>
<p><span style="font-size: 12pt;"><strong>Step 3: </strong>Download <a href="https://www.up-4ever.com/neg15f5y9hn0"><span id="file_name_short48208043">BusyBox Pro+v55.apk</span></a><span id="file_name_short48208043">. and Install it. (optional)<br />
</span></span></p>
<p><span id="file_name_short48208043"><span style="font-size: 12pt;"><strong>Step 4: </strong>Follow this <a href="http://linkshrink.net/7bEYj2" target="_blank" rel="noopener">link</a> to download and Install Xposed. (optional)</span><br />
</span></p>
<p style="text-align: center;"><span style="font-size: 16px;">You can Find the latest Huwawei TIT-U02 Firmware from this <a href="http://consumer.huawei.com/et-en/support/downloads/detail/index.htm?id=91326&amp;key0=Mobile%20Phones&amp;key1=Smartphones&amp;key2=TIT-U02">link.</a></p>
<p><span style="font-size: 20px;"><strong>&gt;&gt;&gt;&gt;</strong></span></span><span style="font-size: 20px;"><strong><a href="http://consumer.huawei.com/et-en/support/downloads/detail/index.htm?id=91326&amp;key0=Mobile%20Phones&amp;key1=Smartphones&amp;key2=TIT-U02">HUAWEI Y6 Pro Firmware (TIT-U02, C328B107)</a>&lt;&lt;&lt;&lt;</strong></span><!--nextpage--></p>
<h2><span style="font-size: 24pt; font-family: georgia,palatino,serif; color: #333399;">Conclusion</span></h2>
<p><span style="font-size: 12pt;">Finally, you&#8217;ve rooted your Huawei Y6 Pro TIT-U02 and got access to a whole new level of Android Experience, Enjoy. Don&#8217;t forget to share and bookmark This page for further assistance. Feel free to share you experience or inquire about anything this tutorial has or should `have.</span></p>
```
**Transformed Markup:** 
````
<html>
  <head>
    <link rel="canonical" href="https://www.problem-solver.ml/root-huawei-y6-pro-tit-u02/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Huawei-Y6-Pro-1.jpg"/>
          <figcaption>Huwawei Y6 Pro TIT-U02</figcaption>
        </figure>
        <h1>How to Root Huawei Y6 Pro TIT-U02</h1>
        <time class="op-published" datetime="2017-10-19T08:30:03+00:00">October 19th, 8:30am</time>
        <time class="op-modified" datetime="2017-11-04T09:17:24+00:00">November 4th, 9:17am</time>
        <address><a>Problem Solver</a>As a typical web surfer, a gamer, an android developer, a designer, and a Multi-talented person, I face troubles every day. To solve those problems, I start googling and doing my own research. Eventually, I succeed in solving every single issue I face in my online experience. For this very reason, I’ve decided to start this blog and share my own experience in facing troubles and solving every single one of them in order to help those who have just faced them and spare them the trouble of looking and wasting time as I provide the direct up to date easy solutions to the very issue they face.</address>
      </header>
      <h2>Ionce had a Huawei Y6 Pro TIT-U02 and the only thing I ever wanted is to root this device. Naturally, I have looked every where for root methods whether using apps or flashing .img files. Eventually and after a quite long Time a Russian friend found the a way to dump the boot.img and port it to accept root. Follow the process to Root Huawei Y6 Pro.<br/></h2>
      <h2>The process is not easy and needs extreme focus let’s get started.</h2>
      <h2>The Stages:</h2>
      <ol>
        <li>Unlocking the bootloader. 
</li>
        <li>Flashing Custom Recovery ( Carliv Touch Recovery by <b>jemmini </b>)</li>
        <li>Flash Boot.img</li>
        <li>flashing SuperSU-v2.79<br/>
a. Installing BusyBox Pro (optional)<br/>
b. Installing Xposed (optional )</li>
      </ol>
      <h2>Stage 1: Unlocking the bootloader.</h2>
      <p>First you need to know that unlocking your bootloader <b>voids warranty</b>. However, you can lock it back any time.</p>
      <h2><b>NOTE:</b> THIS PROCESS WILL REBOOT YOUR PHONE ON TO <b>FACTORY REST. </b>All unsaved data will be lost. Make sure you backup your important data before starting the process.</h2>
      <p>Now to the process to unlock the bootloader of your Huawei Y6 Pro TIT-U02. In order to unlock the bootloader you need to follow a set of steps carefully.</p>
      <h2>
        <b>Step 1: Enabling OEM unlocking.</b>
      </h2>
      <p>Before you unlock your bootloader <b>MAKE SURE</b> you have enabled your OEM unlocking. To do this go to options –&gt; about phone –&gt; tap five times on Build Number in order to Enable developer options. Now, Enter Developer options and scroll to find OEM unlocking and Enable it a message will popup click Enable. <a href="https://youtu.be/DroF-eXv14Q">Watch the Video Tutorial.</a></p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_17_17_32_06-169x300.png"/>
      </figure>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_17_17_37_59-169x300.png"/>
      </figure>
      <h2>
        <b>Step 2: Getting the unlock Code for your Huawei Y6 Pro TIT-U02<br/></b>
      </h2>
      <p>In order to get your unlock code you need to follow:<br/> <b>The official Method (Recommended):</b> <a href="https://emui.huawei.com/en/plugin/unlock/index">Click Here</a> to request an official unlock code.</p>
      <p><b>Pre-requisits</b>:<br/> 1.Huawei account, if you don’t have make one for free.<br/> 2.Product Model Name, which you can get going in settings&gt;about phone, there you will see model number<br/> 3.serial number &amp; IMEI are written on packing box, but you can also get serial by dialing this code *#*#2846579#*#* and then tap on manufacturing information. Also get IMEI by dialling *#06#<br/> 4.To obtain the product ID number dial *#*#1357946#*#* if the code won’t run and the Dial pad just disappears don’t worry Just Return the phone to the Original language try one of three languages at the very bottom.</p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/2017_10_19_09_26_16-169x300.png"/>
      </figure>
      <p>or Download <a href="http://ouo.io/fqBoDn" rel="noopener">Huawei Unlocker</a> the Huawei Unofficial Unlock code generator. <b>(It is flagged as a suspicious file by ESET anti virus but it is safe)</b></p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Huawei-Unlocker-300x271.png"/>
      </figure>
      <h2>
        <b>Step 3: Unlocking the bootloader using Adb and Fastboot.</b>
      </h2>
      <h2>Once you have got your unlock code, Save it or take screenshot and save it somewhere.</h2>
      <p>1. OEM unlock in developer options.<br/>2. Enable USB debugging in Settings &gt; Developer Options &gt; USB Debugging ( Make sure you have enabled oem unlocking)<br/>3. Connect your phone with PC &amp; type “adb devices” your phone will ask for permission, check always allow from this pc &amp; grant permission.<br/>4. Dwonload <b><a href="http://linkshrink.net/7JBnXd" rel="noopener">Minimal ADB and Fastboot</a> , </b> after downloading, extract the contents of <b>adb tools.rar</b> and Enter the folder where adb.exe is located, Hold Shift+Mouse right click and select “Open command window here”.<br/>5. Then type following command</p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Usb-Debugging-168x300.png"/>
      </figure>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Untitled2-1-168x300.png"/>
      </figure>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Untitled-300x200.png"/>
      </figure>
      <blockquote>adb reboot-bootloader</blockquote>
      <p>if this command doesn’t work, then disconnect USB cable switch off phone , hold volume down button and connect with pc, your phone should enter fastboot mode.</p>
      <p>Let windows install drivers, then type</p>
      <blockquote>fastboot devices</blockquote>
      <blockquote>fastboot oem unlock xxxxxxxxxxxxx</blockquote>
      <p>(xxxxxx is your unlock code) and your phone will be unlocked select <b>yes</b> by using volume up button.<br/>Before you proceed you should double check that your bootloader is unlocked. To do that Enter the code bellow.</p>
      <blockquote>fastboot oem get-bootinfo</blockquote>
      <p>If you have followed the steps carefully this command should show something similar to this image.</p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Oem-unlocked-300x88.png"/>
      </figure>
      <p>6. Run the code bellow to reboot your phone. The phone should boot on <b>Factory Reset</b>.</p>
      <blockquote>fastboot reboot</blockquote>
      <h2>Stage 2: flashing Custom Recovery ( Carliv Touch Recovery by <b>jemmini </b>)</h2>
      <p>Now that you have successfully Unlocked your bootloader, we proceed to stage 3 of the rooting process ,that is, Flashing The Custom recovery. To do so follow these steps. </p>
      <p><b>Step 1:</b> download <a href="http://linkshrink.net/7OfAAv"><b>carlivrecovery.img</b><b>g</b></a>. and <b>place it in the adb folder. (Important)</b> do not rename. (This recovery is made especially for TIT-U02 don’t try it elsewhere).</p>
      <p><b>Step 2:</b>Here we do steps similar to those of the unlocking. First, Enter the folder where adb.exe is located. Click right mouse while holding left Shift. Now if your phone is not already in the bootloader mode you should run the code bellow to boot it into bootloader:</p>
      <blockquote>adb reboot-bootloader</blockquote>
      <p>once your device reboots into bootloader run the codes bellow one by one to flash boot.img</p>
      <blockquote>fastboot devices&#13;
fastboot flash recovery carlivrecovery.img&#13;
</blockquote>
      <h2>
        <b>NOTE: Once the flash is complete Do not reboot into system. Hold VOL+ and run the following command:<br/></b>
      </h2>
      <blockquote>fastboot reboot</blockquote>
      <h2>
        <b>Then select Recovery and press VOL- to </b>
        <b>confirm.</b>
      </h2>
      <h2>Stage 3: flashing Boot.img</h2>
      <p>Now that you have successfully flashed recovery, we proceed to stage 3 of the rooting process ,that is, Flashing Boot.img.</p>
      <p><b>Step 1:</b> Download <a href="http://linkshrink.net/7pouDT" rel="noopener">boot.img</a>. and <b>place it in your SD card.</b></p>
      <p><b>Step 2: </b>Enter the recovery mode and choose Carliv Menu. After that Choose Flash Boot or recovery Image. Select Flash boot Image and browse for Boot.img you have downloaded and placed in SD card in <b>Step 1.</b> Flash the boot image and <b>clear cache ONLY</b> then<b> REBOOT</b> into system. After that, Place the SuperSU-v2.79.zip you get from Stage 4 in you Sd card.</p>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Carliv-Menue-300x212.png"/>
      </figure>
      <figure>
        <img src="https://www.problem-solver.ml/wp-content/uploads/2017/10/Carliv-Touch-300x230.png"/>
      </figure>
      <h2>Stage 4: Flashing SuperSU-v2.79<br/></h2>
      <p>After flashing th boot.img and clearing cache and rebooting into system you need to Flash the Super user to get Root Rights. Follow the simple steps:</p>
      <p><b>Step 1: </b>Dow,load <a href="http://linkshrink.net/7JXvSz" rel="noopener">SuperSU-v2.79</a>.</p>
      <p><b>Step 2:</b> Reboot into recovery and select Install zip then browse for SuperSU-v2.79-SYSTEMMODE.zip and confirm Install. Reboot your system and Voila You had you Huawei Y6 Pro Rooted. Enjoy The use of Powerful and Ultimate possibilities of root base apps.</p>
      <p><b>Step 3: </b>Download <a href="https://www.up-4ever.com/neg15f5y9hn0">BusyBox Pro+v55.apk</a>. and Install it. (optional)<br/></p>
      <p><b>Step 4: </b>Follow this <a href="http://linkshrink.net/7bEYj2" rel="noopener">link</a> to download and Install Xposed. (optional)<br/></p>
      <p>You can Find the latest Huwawei TIT-U02 Firmware from this <a href="http://consumer.huawei.com/et-en/support/downloads/detail/index.htm?id=91326&amp;key0=Mobile%20Phones&amp;key1=Smartphones&amp;key2=TIT-U02">link.</a></p>
      <p>
        <b>&gt;&gt;&gt;&gt;</b>
        <b><a href="http://consumer.huawei.com/et-en/support/downloads/detail/index.htm?id=91326&amp;key0=Mobile%20Phones&amp;key1=Smartphones&amp;key2=TIT-U02">HUAWEI Y6 Pro Firmware (TIT-U02, C328B107)</a>&lt;&lt;&lt;&lt;</b>
      </p>
      <h2>Conclusion</h2>
      <p>Finally, you’ve rooted your Huawei Y6 Pro TIT-U02 and got access to a whole new level of Android Experience, Enjoy. Don’t forget to share and bookmark This page for further assistance. Feel free to share you experience or inquire about anything this tutorial has or should have.</p>
      <footer>
        <small>All Right Reserverd Problem Solver</small>
      </footer>
    </article>
  </body>
</html>
```

**Comment by pestevez** [comment]
Thanks, @HenkDz. I created #808 to track the multi-page articles question/issue; so I'm closing this one, as it was related to images and list items.
