### ISSUE TITLE
Content defined as encoded

### ISSUE THREAD

**Issue by wulfy** [Automattic/facebook-instant-articles-wp#81]
Hello,

we are using IA in our wordpress to generate the RSS fedd : www.goldenmoustache.com.
Unfortunately a lot's of articles are broken on Facebook because we are using this JS in our article content:

<script type="text/javascript">// <![CDATA[
window._ttf = window._ttf || []; _ttf.push({        pid          : 31664        ,lang        : "fr"        ,slot        : '.section .article > p'
      ,format      : "inread"
       ,components: {mute:{delay:0}}
      ,css         : "margin: 14px 0px;"
});
(function (d) {
       var js, s = d.getElementsByTagName('script')[0];
       js = d.createElement('script');
       js.async = true;
       js.src = '//cdn.teads.tv/js/all-v1.js';
       s.parentNode.insertBefore(js, s);
})(window.document);
// ]]></script>

Can you tell me why this code break the article in the rss feed ?
maybe the //]] ?

thank you

**Comment by wulfy** [comment]
the rss feed: http://www.goldenmoustache.com/feed/instant-articles

**Comment by philipjohn** [comment]
@wulfy Can you provide more info about how the feed is broken? Are you seeing errors? What are they, and where are they shown?

Note that there are very particular guidelines about what is acceptable in FBIA feeds: https://developers.facebook.com/docs/instant-articles

**Comment by everton-rosario** [comment]
Hello, thanks for using Instant Articles, @wulfy.

Any issue using the API integration?
We, from Facebook strongly encourages you to use the new API integration for Instant Articles, since you have more control and more flexibility to your articles.

Im closing this since it is old, but feel free to reopen if you still need any support.
