### ISSUE TITLE
Instant Article not firing Google Analytics

### ISSUE THREAD

**Issue by bsgies** [Automattic/facebook-instant-articles-wp#810]
I'm having an issue with the Facebook Instant article. I've installed Google Analytics for Instant articles via WP. The plugin is doing its job and adding <op-tracker> to the source code of every instant article. But yet Analytics is not counting the traffic. Although the code has been added to Instant article's code it seems like it's not firing.

WP implementation: https://image.prntscr.com/image/1Nf9DLvXQjKeww1RdE_Xyw.png
FB Instant article's source code: https://image.prntscr.com/image/33fZsAATR1uBywjOlfE4bg.png
Google Analytics dashboard: https://image.prntscr.com/image/65VMUrkRRjiDM9iD6g8z5A.png
URL of my website: https://matterfeed.com/embarrassing-celebrity-photos/

**Comment by pestevez** [comment]
Hey @bsgies - based on your description I agree that your problem is not related to the Instant Articles WordPress plugin, but to the script you are trying to run. My recommendation is for you to ask for help in [this Facebook group](https://www.facebook.com/groups/629655867187397/).

I am closing the issue now because its solution is outside the scope of this repo, but please find below a script I have used in the past (you'll have to use your GA ID):
```html
<script type="text/javascript">
  (function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
      m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', '{YOUR-GA-ID}', 'auto');
  ga('send', 'campaignSource');
  ga('set', 'campaignMedium', 'Facebook Instant Articles');
  ga('send', 'campaignMedium');
  ga('set', 'title', ia_document.title);
  ga('set', 'referrer', ia_document.referrer);
  ga('send', 'pageview');
</script>
```
I hope this helps!

**Comment by bsgies** [comment]
Hi @pestevez,

So should we not use the GA new code for gtag? I'm using the gtag code.

Regards,
Bilal

**Comment by pestevez** [comment]
I have not used it yet. Did you try the solution described at http://jesscarranza.blogspot.com/2017/09/facebook-instant-articles-google-analytics-gtag-js.html ?
If that does not work my suggestion is for you to ask in the Facebook group I mentioned.
