### ISSUE TITLE
Error on AMP generation

### ISSUE THREAD

**Issue by absentio** [Automattic/facebook-instant-articles-wp#812]
## Steps required to reproduce the problem

1.  Activate AMP Markup generation
2.  paste the json file content
3.  open an article using ?amp_markup=1

## Expected Result
A working amp page

## Actual Result 

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-extensions-in-php/src/Facebook/InstantArticles/AMP/AMPContext.php on line 89
## Version Info

* Plugin version: 4.0.5
* WordPress version:  4.8.3
* PHP version:  5.4.5

**Comment by pestevez** [comment]
Please post the JSON referenced in step 2., the Source Markup and Transformed Markup from the Instant Articles section at the bottom of the post editing page. Without this information, we are unable to help. Thanks

**Comment by absentio** [comment]
That's the JSON:
`{
	"background_color": "#FFFFFF",
	"title": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"subtitle": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"kicker": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"byline": {
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "ALL_CAPS",
		"color": "#000000",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"date_style": "MONTH_DAY_YEAR",
	"primary_heading": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "ALL_CAPS",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"secondary_heading": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"body_text": {
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"inline_link": {
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#4BB6F5",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "SIMPLE_UNDERLINE"
	},
	"block_quote": {
		"border": {
			"bottom": {
				"color": "#000000",
				"width": 0
			},
			"left": {
				"color": "#000000",
				"width": 2
			},
			"right": {
				"color": "#000000",
				"width": 0
			},
			"top": {
				"color": "#000000",
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "MEDIUM"
			},
			"right": {
				"scaling_factor": 1,
				"size": "SMALL"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"pull_quote": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"pull_quote_attribution": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "ALL_CAPS",
		"color": "#000000",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_title_small": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Helvetica Neue Bold",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_title": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_title_large": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_title_extra_large": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_credit": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "ALL_CAPS",
		"color": "#BFBFBF",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_description_small": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_description": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_description_large": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"caption_description_extra_large": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#808080",
		"display": "INLINE",
		"font": "Georgia",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"footer": {
		"background_color": "#FFFFFF",
		"border": {
			"bottom": {
				"width": 0
			},
			"left": {
				"width": 0
			},
			"right": {
				"width": 0
			},
			"top": {
				"width": 0
			}
		},
		"capitalization": "NONE",
		"color": "#000000",
		"display": "INLINE",
		"font": "Helvetica Neue",
		"line_height_scale": 1,
		"margin": {
			"left": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			},
			"right": {
				"scaling_factor": 1,
				"size": "DOCUMENT_MARGIN"
			}
		},
		"padding": {
			"bottom": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"left": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"right": {
				"scaling_factor": 1,
				"size": "NONE"
			},
			"top": {
				"scaling_factor": 1,
				"size": "NONE"
			}
		},
		"text_alignment": "LEFT",
		"text_size_scale": 1,
		"underline": "NONE"
	},
	"id": "1115978911799883",
	"name": "default",
	"is_default": true,
	"header": {
		"accent_color": "#FFFFFF",
		"background_color": "#2D3865",
		"logo": {
			"full_resolution_url": "https://scontent.xx.fbcdn.net/v/t39.5687-6/16781509_1359514814069507_2757645823264161792_n.png?oh=2fc85a47b72b2d7b0d44dde7cb179d60&oe=5AB01A5A",
			"full_resolution_width": 690,
			"full_resolution_height": 132,
			"thumbnail_url": "https://scontent.xx.fbcdn.net/v/t39.5687-6/16684947_1483217991722433_3403327902052253696_n.png?oh=6681def02ce6888602308d7e4cb0c72a&oe=5AA8EF9C",
			"id": "1359514804069508"
		},
		"logo_scale": 1
	}
}`

Source markup:
`<p>Ieri pomeriggio i militari della stazione dei carabinieri di Biancavilla, hanno arrestato in flagranza di reato due fratelli del luogo, un 19enne, in atto sottoposto agli arresti domiciliari,  e un 24enne. Durante un servizio antidroga i militari operanti notavano il 19enne fuori dalla propria abitazione, che alla vista dei Carabinieri rientrava precipitosamente in casa con il fratello maggiore. Insospettiti dal comportamento dei due, i militari procedevano a una perquisizione personale e domiciliare nel corso della quale venivano rinvenuti un involucro in cellophane contenente sostanza stupefacente tipo <em>marijuana</em> di grammi 10, 12 involucri di carta stagnola contenente sostanza stupefacente tipo <em>marijuana</em> del peso complessivo di grammi 10, 14 involucri di cellophane termosaldato contenenti sostanza stupefacente tipo di <em>cocaina</em> del peso complessivo di grammi 3, la somma in contanti di euro 160,00 in banconote di vario taglio, riconducibile all’attività di spaccio. La sostanza stupefacente ed il danaro sono stati sequestrati, mentre i due fratelli sono stati posti ai domiciliari in attesa del rito direttissimo, come disposto dall’autorità giudiziaria.</p>
<p><img class="aligncenter size-full wp-image-13606" src="http://www.url.com/wp-content/uploads/2017/11/Diapositiva1-1.jpg" alt="" width="468" height="663" srcset="http://www.url.com/wp-content/uploads/2017/11/Diapositiva1-1.jpg 468w, url/wp-content/uploads/2017/11/Diapositiva1-1-212x300.jpg 212w" sizes="(max-width: 468px) 100vw, 468px" /></p>`

Transformed markup:
`<html>
  <head>
    <link rel="canonical" href="http://www.url.com/url"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://www.url.com/wp-content/uploads/2017/11/Diapositiva2.jpg"/>
        </figure>
        <h1>SPACCIO DI DROGA. AI DOMICILIARI DUE FRATELLI DI BIANCAVILLA.</h1>
        <time class="op-published" datetime="2017-11-10T12:50:59+01:00">November 10th, 12:50pm</time>
        <time class="op-modified" datetime="2017-11-10T13:28:54+01:00">November 10th, 1:28pm</time>
        <address><a>Redazione</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=pl_id&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>Ieri pomeriggio i militari della stazione dei carabinieri di Biancavilla, hanno arrestato in flagranza di reato due fratelli del luogo, un 19enne, in atto sottoposto agli arresti domiciliari,  e un 24enne. Durante un servizio antidroga i militari operanti notavano il 19enne fuori dalla propria abitazione, che alla vista dei Carabinieri rientrava precipitosamente in casa con il fratello maggiore. Insospettiti dal comportamento dei due, i militari procedevano a una perquisizione personale e domiciliare nel corso della quale venivano rinvenuti un involucro in cellophane contenente sostanza stupefacente tipo <i>marijuana</i> di grammi 10, 12 involucri di carta stagnola contenente sostanza stupefacente tipo <i>marijuana</i> del peso complessivo di grammi 10, 14 involucri di cellophane termosaldato contenenti sostanza stupefacente tipo di <i>cocaina</i> del peso complessivo di grammi 3, la somma in contanti di euro 160,00 in banconote di vario taglio, riconducibile all’attività di spaccio. La sostanza stupefacente ed il danaro sono stati sequestrati, mentre i due fratelli sono stati posti ai domiciliari in attesa del rito direttissimo, come disposto dall’autorità giudiziaria.</p>
      <figure>
        <img src="http://www.url.com/wp-content/uploads/2017/11/Diapositiva1-1.jpg"/>
      </figure>
      <figure class="op-tracker">
        <iframe><script>
(google analytics code)
 
</script> </iframe>
      </figure>
    </article>
  </body>
</html>`

**Comment by pestevez** [comment]
Hey @absentio, I am unable to repro. I have two differences:
- I am running PHP version 7.0.21
- I don't have your Google Analytics code

Can you please disable temporarily your custom Analytics code and see if your problem persists?

**Comment by absentio** [comment]
Hello, I've disabled all the embedded code(facebook audition, google analytics),disabled all the custom rules and the problem is still the same. Is there something else that could I try?

**Comment by diegoquinteiro** [comment]
Hi @absentio,

This is a bug in the AMP extension that makes it incompatible with 5.4. I've went ahead and created this PR fixing the issue on the dependency project: https://github.com/facebook/facebook-instant-articles-sdk-extensions-in-php/pull/31

Once we review and merge the code on the extension, we'll be able to release a new version of the plugin that can generate AMP on 5.4. Meanwhile, would you consider upgrading to 5.6+?

Thanks!
Diego

**Comment by absentio** [comment]
Thank you for replying me. I've just updated to PHP 5.6. AMP is working well now, excluding accents on vowels like ò , à etc and "".

Source markup: `<p>Domenica 19 novembre, alle 18, nel corso di una celebrazione eucaristica nella chiesa Madre di Adrano, avrà luogo il rito della  &#8220;presa di possesso&#8221;  del nuovo parroco, padre Salvatore Stimoli, dopo la nomina ottenuta lo scorso 23 settembre. A presiedere la celebrazione eucaristica domenica sarà mons. Alfio Reina. (nella foto padre Stimoli con Papa Francesco, durante l&#8217;incontro di alcune settimane fa in Vaticano tra il Pontefice e sette preti del territorio che hanno festeggiato 25 anni di sacerdozio).</p>`

Transformed markup:
<p>Domenica 19 novembre, alle 18, nel corso di una celebrazione eucaristica nella chiesa Madre di Adrano, avrà luogo il rito della  “presa di possesso”  del nuovo parroco, padre Salvatore Stimoli, dopo la nomina ottenuta lo scorso 23 settembre. A presiedere la celebrazione eucaristica domenica sarà mons. Alfio Reina. (nella foto padre Stimoli con Papa Francesco, durante l’incontro di alcune settimane fa in Vaticano tra il Pontefice e sette preti del territorio che hanno festeggiato 25 anni di sacerdozio).</p>

**Comment by vkama** [comment]
Closing this as the PR @diegoquinteiro was merged.
