### ISSUE TITLE
Plugin not sending markup since last update

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#818]
The plugin states that this article has been submitted as an instant article when it’s published. But it’s not. On Facebook publishing tools the last one to be sent was over 2 weeks ago. I tried to deactivate the plugin and re activate. I deleted it and re installed it. And so on. But nothing works.
I haven’t added new plugins or changed anything in months so I can’t figure it out.
Is this going to be fixed ?

* Plugin version: 4.0.5
* WordPress version:  4.9
* PHP version: 7.1

**Comment by timjacobi** [comment]
Unfortunately the underlying APIs have changed so this is the normal behavior now.

From the Readme
> **Why doesn't my post appear in the list of Instant Articles in the publisher tools?** Your posts are imported to your library when they are shared on Facebook for the first time.

> Alternatively, you can trigger a manual scrape by pasting your URL on our Share Debugger

**Comment by Flynsarmy** [comment]
So IA isn't an automatic plugin anymore? You need to manually post a link to your article on facebook and the article will then appear in IA? What is the point of the plugin then?
