### ISSUE TITLE
get_the_title() should strip tags

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#82]
If you have tags in your article headline, facebook complains that no tags should be in article titles.  

Suggestion for a revised function like this:

	public function get_the_title() {
		$title = get_the_title( $this->get_the_ID() );
                $title = esc_html( strip_tags( $title ) ); //ADD - strip tags before sending to template
		/**
		 * Filter the post title for use in instant articles
		 *
		 * @since 0.1
		 *
		 * @param string                 $title                 The current post title.
		 * @param Instant_Article_Post   $instant_article_post  The instant article post
		 */
		$title = apply_filters( 'instant_articles_title', $title, $this );

		return $title;
	}

**Comment by sgatz** [comment]
workaround is using my own filter, but it should be in the plugin natively

**Comment by demoive** [comment]
@sgatz, this is a good suggestion! Since this issue was opened, however, tags within the title are escaped so the complaint you refer to should no longer. By properly escaping the content, we can avoid stripping tags and other content.

**Comment by bjornjohansen** [comment]
There shouldn’t be any markup in your title. If you have HTML there it will be considered part of the content – as it should. E.g. a title like “How to properly use <h1> HTML elements”, we don’t want to strip that out, but rather escape it – which is done properly now.

**Comment by nicolinuxfr** [comment]
I don't think it's working as intended. On my blog, I'm using HTML in titles and they are not escaped correctly : you can still see the tags in Facebook, as in the pictures below : 

![](https://cloud.githubusercontent.com/assets/2078386/14523764/a859927e-0235-11e6-97ae-a76a90b66434.jpg)

Here's the link to this article : https://voiretmanger.fr/mommy-dolan/

And here's the feed : https://voiretmanger.fr/feed/instant-articles/

**Comment by demoive** [comment]
@nicolinuxfr, thanks for the feedback. What are you thoughts on @bjornjohansen's previous comment regarding markup in your title?

**Comment by demoive** [comment]
Just noting a related PR on the Facebook Instant Articles SDK: https://github.com/facebook/facebook-instant-articles-sdk-php/pull/32

**Comment by nicolinuxfr** [comment]
@demoive I'm not sure I understand… I want to keep italics in my titles, and I wish they stay in the Instant Articles. Which is possible, when you create manually an article with `<em>` tags, it works fine for Facebook.

**Comment by nicolinuxfr** [comment]
@demoive I tried the PR on my setup (editing files manually) and unless I did something wrong, it's not working for me…

**Comment by nicolinuxfr** [comment]
Just tried 2.9 and I still have the issue. But since there was no changelog, I don't know if it was supposed to be fixed.
