### ISSUE TITLE
custom embed code

### ISSUE THREAD

**Issue by demetrox** [Automattic/facebook-instant-articles-wp#821]
## Steps required to reproduce the problem

1. go to ads section
2. choose custom embed code
3. setup <section class="op-ad-template"   and failed to run because there is an auto script 
<figure class="op-ad">
<iframe width="300" height="250">

4. There is also an auto close </iframe> and </figure..please remove this because my script failed to run

## Expected Result

no auto script for opening 
<figure class="op-ad">
<iframe width="300" height="250">

no auto script for closing
</iframe> and /figure

## Actual Result 
If you tell me there is only 2 available sizes for type of ads that support. Kindly create an error message if user failed to meet the size criteria instead of this auto script.

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.0.5
* WordPress version: 4.9
* PHP version: 7.024

**Comment by everton-rosario** [comment]
Not sure if I got your issue point here.

When configuring that your instant articles will use ADS, our plugin provides a way for you add automatically one AD script to each of your articles.
To do so, you can go to the left side menu, clicking on "Instant Articles" or selecting the Facebook Instant Articles plugin from the list of the already installed plugins and hit "settings".

Opening the sections tab, you go there and configure your type of ADS: 
Ad Type: `Custom Embed Code`
Embed code: 
```
<script>
    console.log("some valid javascript code here");
</script>
```
(note that you don't need to create by yourself the op-ad section)

Then this will include into all generated Instant Articles header the code below:
```
      <header>
         ....
        <figure class="op-ad">
          <iframe width="300" height="250">
            <script>
console.log("some valid javascript code here");
</script>
          </iframe>
        </figure>
      </header>
```

You can see this by clicking in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then looking at the "**Transformed Markup**" section.

Let us know if this is enough for you to proceed on adding your ads to your Instant Articles.

Also all the info you need to know about ADS (if you didn't already) is here: https://developers.facebook.com/docs/instant-articles/monetization/ad-placement

Closing it for now. Reopen if you need some extra info.

**Comment by demetrox** [comment]
i dont want to use `<figure class="op-ad">` i want to use `<section class="op-ad-template>` because i'm running multiple ads.. can you teach me how to delete this auto `<figure class="op-ad">` script?

**Comment by everton-rosario** [comment]
Oh, now I see, thanks for the clarification.
We do have support for this feature on the SDK.

To perform this, you just need to call the method `addAd()` on the HeaderElement.php class.

To perform this, from your WordPress plugin, you should do this:

```
function addAdSectionCallback( $instant_article ) {
    if ( $instant_article !== null ) {
        $header = $instant_article->getHeader();
        $header->addAd(
            Ad::create()
                ->withSource('http://somedomain.com/path/file')
                ->withHeight(640)
                ->withWidth(480)
                ->enableDefaultForReuse(); // This line marks what will be the default AD (with the op-ad-default)
        );

        // repeat this block here for each AD you wanna add to your Header section
        $header->addAd(
            Ad::create()
                ->withHTML('<h1>Some custom code</h1><script>console.log("valid javascript code");</script>')
                ->withHeight(640)
                ->withWidth(480);
        );

    }
    return $instant_article;
}
add_filter( 'instant_articles_transformed_element', 'addAdSectionCallback' );
```

This should do what you want to.

**Comment by demetrox** [comment]
orait thanks. this is what i need. thank you
