### ISSUE TITLE
feed not working production article

### ISSUE THREAD

**Issue by undarga** [Automattic/facebook-instant-articles-wp#823]
## Steps required to reproduce the problem
Create a new post
After success we got
. This post will be available as an Instant Article.
. This post was transformed into an Instant Article with no warnings [Toggle debug information]

## Actual Result 

1. create new post its not importing facebook production article since yesterday. i use https://eshlel.com/feed/instant-articles feed. 
2. older post updated. but its not importing production article. same
3. i configure Automatic Placement. ad_density=default. but each artichle contain only 1 ads. my article have 500-2000 words. i think each 250 word have one ads code. its is wrong?

If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: Version 4.0.5
* WordPress version:  version 4.9
* PHP version: version: 7.0.25

Without the above information we are not able to debug the issue and will close it.

**Comment by everton-rosario** [comment]
I've checked the RSS feed link you've shared, and in the current state, I could see 9 articles listed there:
- https://eshlel.com/archives/315
- https://eshlel.com/archives/21
- https://eshlel.com/archives/13
- https://eshlel.com/archives/404
- https://eshlel.com/archives/401
- https://eshlel.com/archives/347
- https://eshlel.com/archives/417
- https://eshlel.com/archives/9
- https://eshlel.com/archives/413

All these articles are enabled as Instant Article.

Any of the articles you've noticed not being updated, are they on this list?
If the article you updated is not listed on this RSS feed, you can use it as the OG scraper.
Then you just need to go to the Object share debugger tool: https://developers.facebook.com/tools/debug/
Paste the Article URL there, and hit force rescrape.

Remember to check for this link into the header of your web article:
`<meta property="ia:markup_url" content="YOUR_INSTANT_ARTICLE_URL_GOES_HERE">`

Closing for now, reopen if not covering the points you need.

**Comment by undarga** [comment]
meta property="ia:markup_url it link not my header. how i add ?
