### ISSUE TITLE
Transferring Instant Articles to Production Library

### ISSUE THREAD

**Issue by bsgies** [Automattic/facebook-instant-articles-wp#826]
Hi everyone,

I run a WordPress website which has more than 20,000 articles. Now when I asked my IA feed URL in FB IA configuration it merely fetches 20-25 posts. Upon asking multiple groups online everyone said one thing that you need to open and update all these articles in order to transform them into instant articles but the fact remains that it will take more than 15 years to open each and every article and update.

Can you guys tell me a way which can solve this issue? Probably something like a function which can push everything to instant.

Regards,
Bilal

**Comment by everton-rosario** [comment]
Hello!
Nice thing you are migrating and posting your articles as IA.
25k articles is a ton of it.
Technically using the IA WordPress plugin won't require you to republish and then wait for the RSS feed to post your content in chunks of 20 articles.

The best way for you is to use the latest version of the plugin and alternate to use the OG Scrapping strategy.
It ingests a link into all your HTML files/URLs, then once it gets shared into Facebook, our scraper finds the presence of this entry, then fetches the content.
```
<meta property="ia:markup_url" content="{URL}">
```
[Documentation](https://developers.facebook.com/docs/instant-articles/crawler-ingestion)

Just be sure all your URL from all your 25k posts have this new entry, with a correct generated Instant article markup referenced from the `{URL}`, then you will be good to go.

To test a few articles, is just sharing it into a post in Facebook, or scraping it from our [Object Share Debugger](https://developers.facebook.com/tools/debug/), always hitting the "Force Rescrape" button to be sure it will re-fetch the content.

Closing for now, but let us know if this helps you to ingest your content.
