### ISSUE TITLE
Post not submitted to Instant Articles page section

### ISSUE THREAD

**Issue by gmstam** [Automattic/facebook-instant-articles-wp#827]
## Steps required to reproduce the problem

1. Create a new post
2. Publish it

## Expected Result

Post correctly submitted in Instant Articles page section

## Actual Result 
No errors and no warning reported:
"This post will be available as an Instant Article.
This post was transformed into an Instant Article with no warnings"

But post is not submitted to Instant Articles page section although feed is well updated.
At the moment I use debug information to create an instant article manually.

## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.9.1
* PHP version: 7.0.23

**Comment by yeah-sir** [comment]
Hi @gmstam in order to get some insights into what might be going wrong, can you please attach the debug information you are seeing?

Thanks,
Yasser

**Comment by gmstam** [comment]
Do you mean debug information in the edit/new post page?

[debug.zip](https://github.com/Automattic/facebook-instant-articles-wp/files/1523028/debug.zip)

**Comment by yeah-sir** [comment]
Yup the debug information shown on the Instant Articles meta-box on the post edit screen for a post

**Comment by fatonsopa** [comment]
I confirm the error too. It started to happen today around 4pm GMT+1. Posts are not being added/updated to Instant when we add/update a post in wp. Just reinstalled plugin, and it didn't gave any effect!

**Comment by fatonsopa** [comment]
Any update on this? This is a critical issue that needs to be addressed ASAP!

**Comment by yeah-sir** [comment]
@gmstam @fatonsopa Can you please test if this issue still occurs in version 4.0.6 ?

**Comment by fatonsopa** [comment]
@yeah-sir Just updated the plugin. The same is happening.  I updated post's title and the changes are not being reflected in FB IA. I also added a new post, and it was not added as IA. The strange issue is that posts that have been scheduled when the plugin was working, are being added as IA in FB even now!

The plugin panel in the post is not telling me anything else except: "This post will be available as an Instant Article."

Is there any log/debug info that can help you?

**Comment by gmstam** [comment]
@yeah-sir I just removed older version and then I installed 4.0.6. I created a new post, but when I published it nothing was sent to FB IA production articles section. The plugin continues reporting its success message:
"This post will be available as Instant Article once it is shared on Facebook.
This post was transformed into an Instant Article with no warnings"

**Comment by fatonsopa** [comment]
Guys, I know you may have a busy schedule, but please, this is a critical issue that needs to be solved urgently.

Thanks :),

Faton

**Comment by mburak** [comment]
Hi guys, did you make sure that you shared in Facebook a post linking to the Instant Article's web page? Otherwise it won't be published as Instant Article.

**Comment by gmstam** [comment]
@mburak As we described, the process fails in a step backward. A post created in wordpress is not submitted to Instant Articles although metabox shows the success message. I'm using Instant Articles regularly till this bug came out.

**Comment by fatonsopa** [comment]
@mburak We have been using IA for more than a year now, so yes, we have published it on FB. However, I dig deep into the plugin's code and discovered that the post' content is being marked up well, but it's not being imported into IA at all!

**Comment by mburak** [comment]
@gmstam As you are describing, you only created and published the post in WP but not shared it in the FB page. As the message says, the Instant Article is created only once you shared the post in your FB page, not before.

**Comment by gmstam** [comment]
@mburak Normally, using IA plugin, when you publish a new post on WP the post will be submitted to Instant Articles production page. In this section will be set to Published. Now you can share the link. But if you share a link which is not submitted to IA, it will not parsed as Instant Article.

**Comment by mburak** [comment]
As it's pointed out in https://github.com/Automattic/facebook-instant-articles-wp/issues/818, this behavior has changed lately and this is how it works by design now.

**Comment by gmstam** [comment]
@mburak Sorry, I'm really embarassed. Thank you very much. Now It's working perfectly. @fatonsopa After you publish a post in WP, simply share the link on your Facebook Page. The post will be submitted to IA as published.

**Comment by fatonsopa** [comment]
Hey @gmstam @mburak Everything is working now. Thanks :)!

**Comment by FergusClare** [comment]
This problem is occurring for me as well.   

Steps to Reproduce:
1. In Wordpress engine site, create a new post
2. Debug information displays as follows:
![screen shot 2019-02-26 at 2 39 09 pm](https://user-images.githubusercontent.com/19366735/53444667-66ad6380-39d4-11e9-9dea-437afed63af9.png)
3. Share the article on Facebook
4. Open Facebook Mobile Application and view post
5. Post does not display as IA <--FAIL
6. Open Facebook Pages app and see that article is not present in production articles nor in development articles sections.
7. Check the Facebook Plugin within wordpress and confirm the following correct values are present
- Page ID 
- App ID 
- App Secret and Access Token (confirmed via FB Debugger tool for tokens)
- Article Style
- Copyright data
- Publish Article containing warnings

I've experimented with different configurations and each time am unable to successfully see the shared article on Facebook as an Instant Article.  Could really use some help debugging this.  Is it possible that because this is a microsite within a WP Engine group of sites the sharing isn't working correctly?
