### ISSUE TITLE
Fatal error: Cannot redeclare show_version_incompatible_warning

### ISSUE THREAD

**Issue by Ahmedsaber9** [Automattic/facebook-instant-articles-wp#829]
## Steps required to reproduce the problem

1.  download zip
2. install it form Wordpress

## Actual Result 
Fatal error: Cannot redeclare show_version_incompatible_warning() (previously declared in /hermes/bosnaweb28a/b1453/ipg.3almanyacom/3almanya/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:22) in /hermes/bosnaweb28a/b1453/ipg.3almanyacom/3almanya/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 23 

## Version Info

* Plugin version: the last
* WordPress version: 4.9.1 
* PHP version: 5.6.30

**Comment by yeah-sir** [comment]
@Ahmedsaber9 Looks like you have two instances of the Instant Articles plugin installed through folders `fb-instant-articles` and `facebook-instant-articles-wp-master`. Deleting one of these folders from the plugin directory should get rid of this issue

**Comment by mburak** [comment]
@Ahmedsaber9 Were you able to try what @yeah-sir suggested? Did that work?

**Comment by Ahmedsaber9** [comment]
yes it's work .. close it plz thanks  ^^

**Comment by Ahmedsaber9** [comment]
yes it's work .. closed
 thanks ^^
