### ISSUE TITLE
Double encoding with the image's alt

### ISSUE THREAD

**Issue by kittipongo** [Automattic/facebook-instant-articles-wp#83]
The image's alt in function instant_articles_shortcode_handler_caption() should be check the double encoding.
I quick fixed like this:
```
$alt = $imgs->item(0)->getAttribute( 'alt' ); 
if (mb_detect_encoding(utf8_decode($alt)) == 'UTF-8') {
	$alt = utf8_decode($alt);
}
```

**Comment by diegoquinteiro** [comment]
This refers to a old version. Please upgrade to the latest version.
