### ISSUE TITLE
Special Characters Problems

### ISSUE THREAD

**Issue by gasparlanca** [Automattic/facebook-instant-articles-wp#830]
## Steps required to reproduce the problem

1. I just installed facebook-instant-articles-wp and I'm having problems setting it up. First of all, it's only available in the Facebook Pages Manager app for us, editors of the page, but I think that's normal and supposed to until we have at least 10 articles upload for review, right?

So here's the actual problem: I've already gone to the design session and customized my appearance, but special characters (I'm sorry but I don't know what else to call them in English) like commas, dots, periods and new lines aren't working like they should. Example above.

Another problem: the instant article preview(?) is only showing the first paragraph of each news post (like the one pasted here), while we always have more than 1 paragraph in each post we do.

## Expected Result

Here's how it should look like:

Aos 8 anos, recebia uma fotografia assinada por Roger Federer como presente de aniversário da mãe. Agora, prepara-se para uma semana de treino exclusiva com o tenista suíço, com quem curiosamente partilha o dia de anos. Chama-se Félix Auger-Aliassime e tem os pés bem assentes na terra.

## Actual Result 

`Aos 8 anos&comma; recebia uma fotografia assinada por Roger Federer como presente de aniversário da mãe&period; Agora, prepara-se para uma semana de treino exclusiva com o tenista suíço&comma; com quem curiosamente partilha o dia de anos&period; Chama-se Félix Auger-Aliassime e tem os pés bem assentes na terra&period;&NewLine;
`
## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.9.1
* PHP version: where do I see this?

**Comment by gasparlanca** [comment]
Is there anyone here that can help me, please? 👍  :D

**Comment by vkama** [comment]
Could not repro this (check https://www.facebook.com/vktests/posts/1157106304425942) 
Please take a look if everything is configured properly, including plugins that may alter the text.
Try disabling all plugins but the IA and see if it still happens.

Closing, if you can get a repro please reopen.
