### ISSUE TITLE
How do I change the ad_density ?

### ISSUE THREAD

**Issue by mytc** [Automattic/facebook-instant-articles-wp#832]
There are too many ads appeared in IA, I would like to reduce it. I wonder anyway to change the ad_density value? I didn't found any hooks for this in the source code, and I don't want to edit the source codes. 

Anything that I missed?

**Comment by mburak** [comment]
Hi @mytc , I'm afraid that this feature is not implemented yet. We had the same request here https://github.com/Automattic/facebook-instant-articles-wp/issues/640 so I'll close this issue and you can go to the other one to follow the process. Thanks!
