### ISSUE TITLE
No rules defined for <div class="ead-preview"> in the context of InstantArticle

### ISSUE THREAD

**Issue by OlgaAnri** [Automattic/facebook-instant-articles-wp#836]
No rules defined for </div class="ead-preview"/> in the context of InstantArticle
and
No rules defined for </div class="ead-document"/> in the context of InstantArticle

<div class="ead-preview"><div class="ead-document" style="position:relative;padding-top:90%;"><iframe src="//docs.google.com/viewer?url=http%3A%2F%2Fstolypin.institute%2Fwp-content%2Fuploads%2F2017%2F12%2Fb.-titov-a.-shirov-strategiya-rosta-dlya-rossii.pdf&amp;embedded=true&amp;hl=en" title="Embedded Document" style="width:100%; height:100%; border: none; position: absolute;left:0;top:0;"></iframe></div></div>	

[embeddoc url="http://stolypin.institute/wp-content/uploads/2017/12/b.-titov-a.-shirov-strategiya-rosta-dlya-rossii.pdf" viewer="google"]

Plugin : Embed Any Document

**Comment by vkama** [comment]
Hi OlgaAnri.

We can't support every plugin out there with custom rules, that is why you are getting the warnings.

Please refer to https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules to create custom rules to support your use case.

Thanks,
Vinicius Kamakura
