### ISSUE TITLE
Image in Instant article post not displaying

### ISSUE THREAD

**Issue by DavidJourn** [Automattic/facebook-instant-articles-wp#837]
Hello,
I am using the PHP Melody v2.7.1 script to update my articles and the images, the images show up on the library of the instant article, but not on the instant article post page. What could have gone wrong here...please help.
David

LIBRARY PAGE
![instant](https://user-images.githubusercontent.com/34403329/33798922-c21d0c0e-dd21-11e7-9bf1-1337020b4f2f.png)

ARTICLE PAGE:
.
.
![main article](https://user-images.githubusercontent.com/34403329/33798931-f34a3dc4-dd21-11e7-9aa1-4235b3dabb85.png)

**Comment by vkama** [comment]
Sorry to hear that David.

Have you tried contacting PHP Melody support? This repository is strictly for issues with the IA Wordpress Plugin.

Thanks
