### ISSUE TITLE
No rules defined for <a> in the context of InstantArticle

### ISSUE THREAD

**Issue by BULLETmx** [Automattic/facebook-instant-articles-wp#838]
## Steps required to reproduce the problem

1. Install and activate plugin Instant articles for WP
2. Connecting site to FB page
3. Trying to submit article

## Expected Result

Article in FB IA library

## Actual Result 

Im trying to get this Call To Action Button in my IA but gets deleted, what should I do?

[button color="grey" size="normal" alignment="center" rel="follow" openin="samewindow" url="https://www.tiendacapilar.com/?utm_source=bullet%20blog&utm_medium=bullet%20blog%20art%C3%ADculo&utm_campaign=bullet%20blog%20art%C3%ADculo%20davines-holiday-gift-sets-2017&utm_content=Davines%20PREP%20%2F%20Your%20Hair%20Assistant%20Kit#!/Davines-PREP-Your-Hair-Assistant-Designed-by-Angelo-Seminara/p/97639511/category=26553645"]¡Comprar Ahora![/button]
## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.0.6
* WordPress version: 4.8.4
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by vkama** [comment]
Hello,

IA is a native format and we currently do not support buttons.
We do support some Call-to-Action units that you can configure under publishing tools, please refer to this guide: https://developers.facebook.com/docs/instant-articles/cta

Thanks,
VK

**Comment by izuemma** [comment]
can someone help me out, am having a problem with my articles, No rule defined in the context for instant articles

**Comment by everton-rosario** [comment]
Hello @izuemma 

Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Thanks for reaching out.

**Comment by izuemma** [comment]
Please can someone solve this problem for me?	No rules defined for <article> in the context of Small <article><footer><small>Copyright Acme</small> </footer></article>
No rules defined for <div class="mycase_reader"> in the context of InstantArticle
No rules defined for <div class="case_middle"> in the context of InstantArticle

![img_20180124_111235](https://user-images.githubusercontent.com/35340339/35326807-1d8c1202-00f8-11e8-9ea7-7f50f65b0c46
