### ISSUE TITLE
superscript, subscript, underline

### ISSUE THREAD

**Issue by leramatan** [Automattic/facebook-instant-articles-wp#839]
please add rule for superscript, subscript, underline.
Thanks

**Comment by vkama** [comment]
Thanks for your suggestion. We will investigate this.

**Comment by pestevez** [comment]
These elements (superscript, subscript, underline) are not supported in Instant Articles, so we cannot add them as features of the plugin.

If they are very important to you, I recommend you start the discussion here: https://www.facebook.com/groups/629655867187397/

I am closing the issue now, but we can reopen when/if they become available in the Instant Articles format.

**Comment by jnsprngs** [comment]
What could be added is optional logic to strip out underlines, subscripts, and superscripts ---->

`{"rules" : [
	{
		"class" : "IgnoreRule",
		"selector" : "u"
	},
	{
		"class" : "IgnoreRule",
		"selector" : "sup"
	},
	{
		"class" : "IgnoreRule",
		"selector" : "sub"
	}
]}`
