### ISSUE TITLE
Images from WP not showing up in IA, even after adding the code

### ISSUE THREAD

**Issue by dsmills** [Automattic/facebook-instant-articles-wp#844]
In my Wordpress blog, I've included a picture associated with every bullet point. However, when I published the article in IA, only a few images show up...Below I pasted some of the code from my IA where number 2. shows an image link, while the others are missing the code/link.

However, even when I replicated the exact code with the image link for each picture from my WP blog (Like so: `<figure><img src="http://www.daniellesoucymills.com/wp-content/uploads/2017/07/FullSizeRender-14.jpg"></figure>`) , then input it into my IA and hit "save", the image still doesn't show up. Any guidance on how I can get these pictures to appear? Do I have to add these codes elsewhere too?

At first, I had an error message at first "List item contains too many text elements" but I was able to get rid of all the errors. Now, just trying to add in all of my images if it's even possible? Do they have a limit? Thanks in advance!

Here is some of the code where images are missing from 1, 3,4, and 5:

```
<p>Here are a few signs you may never be able to hand over the divorce papers with Gymnastics, your very first true love:</p>
<p><strong>1. Even though you earned your degree, you continue to coach gymnastics, you own a gym, you create and sell gymnastics stuff, or you judge gymnastics meets, whether it relates to your college education or not. </strong>Yes, it is your real job and the thought of ever leaving it – the gymnastics world – makes you tear up. Or ball your eyes out.</p>

<p><strong>2. You sneak in some gymnastics in the office or wherever it is you work that’s not gymnastics related.</strong></p>
<figure><img src="http://www.daniellesoucymills.com/wp-content/uploads/2017/07/FullSizeRender-28.jpg"></figure><p><strong>3. You still hold handstand contests with your former gymnastics team buddies…</strong> in places as strange as the sidewalk outside of a restaurant where you just ate.</p>

<p><strong>4. There are little bumps on your hands that you may or may not be able to call calluses.</strong></p>
<p><strong>5. You still keep your grips, tiger paws, and even your old floor music in your car.</strong> Hey, you never know when you’ll get the urge to play around!</p>
```

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: WP Native Articles version 1.3.4
* WordPress version: 4.9.1
* PHP version:

**Comment by dsmills** [comment]
And duh, posting the code here will obviously bring up the blog post minus the code. Apparently, I can't upload a picture here either to show the code. At least I know it works?

**Comment by diegoquinteiro** [comment]
Hi @dsmills. 

This (WP Native Articles) is not the plugin from this repository. My best guess is that you're using this plugin: https://wp-native-articles.com

In this case, you might find this piece of their documentation useful: http://docs.wp-native-articles.com/article/42-images-missing-or-not-showing

Hope that helped!

Thanks for reaching out,
Diego
