### ISSUE TITLE
wpautop generates the error The HTML element does not contain any text: Avoid including empty HTML elements

### ISSUE THREAD

**Issue by str** [Automattic/facebook-instant-articles-wp#848]
By default, articles go through the `wpautop` filter, which wraps texts in `<p></p>` tags every time it finds a new line.  If I add a text + new line + image, and the image has a link to another page I get the image wrapped inside a new `<p>` tag. When converted to an instant article it gets converted to 

```HTML
<p><a href="some/target"><figure><img src="some/image.jpg"></figure></a></p>
```
And that generates the following error message in Facebook Instant Articles, because there is no text inside the `<p>` tag.

```
The HTML element does not contain any text: Avoid including empty HTML elements
```

**Comment by izuemma** [comment]
my facebook instant articles is rejected because of missing content and embed code, please can someone help me to fix it ?'

**Comment by everton-rosario** [comment]
The problem here is that you have an anchor wrapping your image and a paragraph wrapping the anchor.

Simply add this rules to your Custom Rules:
1. Click on the InstantArticles menu Item (usually it stays in the left menu bar)
2. It will open the InstantArticles plugin settings page.
3. Scroll down to find the section called: "Publishing Settings"
4. Enable the checkbox "Enable custom transformer rules"
5. Enter the rules within the common code as below:
```
{ "rules": [
    {
      "class": "ImageRule",
      "selector": "figure",
      "properties": {
          "image.url": {
             "type": "string",
             "selector": "img",
             "attribute": "src"
          } 
      } 
    },
    {
      "class": "PassThroughRule",
      "selector": "p > a"
    }
]}
```

Just tested into your case scenario: 
```
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

<p><a><figure><img src="some/image.jpg"></figure></a></p>

</body>
</html>
```

Generated this output:
```
<html>
  <head>
...
  </head>
  <body>
    <article>
      <h1>My First Heading</h1>
      <p>My first paragraph.</p>
      <figure>
        <img src="some/image.jpg"/>
      </figure>
    </article>
  </body>
</html>
```

**Comment by izuemma** [comment]
you mean i should test this code into my custom htlm  ?

**Comment by everton-rosario** [comment]
No, this goes into your custom configuration rules into the plugin setup.

Per the step by step I've mentioned, you will click on left menu called "Instant Articles" then setting those rules for your transformation proceed correctly

**Comment by izuemma** [comment]
what about the generates output, where will that be fix ?

**Comment by everton-rosario** [comment]
> https://github.com/Automattic/facebook-instant-articles-wp/issues/848#issuecomment-357221345
It was just an example using the same HTML structure from your case, with `<p><a><figure><img></figure></a></p>` tags.

You can see the generated Instant Article markup on the box overlay we have on each article as you edit it and hit button "Publish".

**Comment by izuemma** [comment]
ok do not be angry mr everton-rosario that am asking alot, i have already paste the code for transformer in my setting area, also the markup in the place, i will let you know if it works

**Comment by izuemma** [comment]
Hi
everton-rosario, i am still having the problem, is telling me
No rules defined for <div class="mycase4_reader"> in the context of InstantArticle

**Comment by izuemma** [comment]
This is the issues am facing.

<html>
  <head>
    <link rel="canonical" href="http://gossipmedianews.com/fulani-herdsmen-kill-50-benue-attack/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.6"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>




<div>
<p>Fulani people have been ushered into their early graves in the middlebelt area of Nigeria following a fresh attack by a Fulani militia on a local village.</p>
</div>
<div class="mycase4_reader">
<div></div>
<div><em>Some Benue villagers</em></div>
<div></div>
<div>Benue State Governor, Samuel Ortom, said on Tuesday that 50 persons were killed and many others injured after Fulani herdsmen attacked a Tiv community in the state.</div>
<div></div>
<div>Ortom, who addressed journalists at the Government House in Makurdi, blamed the Federal Government for not protecting the people.</div>
<div></div>
<div><em>“The blood of those people killed by the Fulani herdsmen are on the hands of the federal government and if nothing is done they will cry unto God,”</em> the governor said.</div>
<div></div>
<div>He said the federal government was alerted on the threat of the herdsmen who had vowed to resist the anti- grazing bill enacted by the state government.</div>
<div>The governor said nine livestock guards were killed and their Hilux patrol van razed in the attack.</div>
<div></div>
<div>During Tuesday’s attack, many people were slaughtered, children killed, and several had their hands chopped off.</div>
<div></div>
<div>A 30- year -old lady, Dooshima Anande, told The Nation that her brother who finished his youth service few days ago was killed in the attack.</div>
<div></div>
</div>

**Comment by izuemma** [comment]
Hi Everton,
my publishing settings on my plugin is showing, Class Boldrule Selector span Bold.
can you generate it for me ?

**Comment by everton-rosario** [comment]
What is the full message @izuemma ?
Lets centralize discussion into only one place.

I need you to inform your custom Rules you have.
To do that, I need you to copy and paste a content from the field from the settings of the "Facebook Instant Articles Wordpress Plugin".
The field you can find here: 
![Custom Rules](https://s3.amazonaws.com/instantarticles/examples/custom-rules.png)

Also I need you to copy and paste the both contents, source markup and the generated IA. To do that, you need to copy from this section from your Editor:
![Source IA Markup](https://s3.amazonaws.com/instantarticles/examples/source-transformed.png)

**Comment by str** [comment]
OK, this is what my rules say:

![selection_013](https://user-images.githubusercontent.com/123817/35072881-272e730a-fbac-11e7-9638-e18104926347.png)

And this is what the debug says in the post edition page:

![selection_015](https://user-images.githubusercontent.com/123817/35073713-d9f87820-fbaf-11e7-9716-ee2985bb59f1.png)

But this is the result in the FB instant articles manager:
![selection_016](https://user-images.githubusercontent.com/123817/35073739-fdad4192-fbaf-11e7-93c2-dc32192c8234.png)

I highlighted the image path as a pivot to track the tags.

The rule @everton-rosario did not work for me.

Thank you a lot for your time.

**Comment by everton-rosario** [comment]
Do you have any other plugins applying things to your published content?

That is weird because I don't see any `<p>` tags wrapping your Image on the first print "Transformed Markup" section.
But then the article you are showing me has it after it was ingested.

Just be sure you have it re-scraped before we dig a little more on this:
Open your article URL into our share debugger:
https://developers.facebook.com/tools/debug/

Then hit the button "scrape again" to force a refresh on the content ingested as IA.
