### ISSUE TITLE
I have ad quick adsense plugin in my site and after this i'm facing this issue plz help me  

### ISSUE THREAD

**Issue by akshayip** [Automattic/facebook-instant-articles-wp#850]
I have ad quick adsense plugin in my site and after this i'm facing this issue plz help me  

![kjkj](https://user-images.githubusercontent.com/32322239/34637489-f888e246-f2dd-11e7-8745-7c5750cf9797.PNG)
![vlkfsvkfds](https://user-images.githubusercontent.com/32322239/34637490-f8b32736-f2dd-11e7-898f-949f2b043d15.PNG)

**Comment by codeslane** [comment]
@akshayip facebook instant articles don't show google ads in the instant article. 
You can enable facebook ads from audience program in your facebook app. 

Regards,
Vaibhav

**Comment by everton-rosario** [comment]
Yes, @codeslane is right. The adsense is not supported.
You can apply for the AudienceNetwork here: https://www.facebook.com/audiencenetwork?ref=github

Then, it will be just usage of the snippet the Audience Network system will give to you, then you can add it to your Instant Article markup using this doc: https://developers.facebook.com/docs/instant-articles/monetization/audience-network
