### ISSUE TITLE
Rewrite rules are ignore

### ISSUE THREAD

**Issue by str** [Automattic/facebook-instant-articles-wp#852]
When a post is submitted, the `<h3>` tags stay as `<h3>` instead of being auto replaced to `<h2>`. I tried both with the default rules as well as redefining them in the "Custom transformer rules". 

![selection_002](https://user-images.githubusercontent.com/123817/34850553-ef7e3054-f6eb-11e7-9dd0-67e24bd1e38d.png)

## Version Info

* Plugin version: Version 4.0.6 
* WordPress version:  4.8.4
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by everton-rosario** [comment]
Can I take a look on the rules you've set?

How is your custom rules right now? Please append to the issue.
Will reopen once you update.
