### ISSUE TITLE
Post not submitted to Instant Articles page section After Published on Wordpress

### ISSUE THREAD

**Issue by vyasdharmesh** [Automattic/facebook-instant-articles-wp#855]
## Steps required to reproduce the problem

1.  Create a new post in Wordpress
2. Publish it

## Expected Result
Post should be available in Instant Article Section of Facebook page

My Feed URL: https://www.echhapu.com/feed/instant-articles
my Page ID: 461835360538417

## Actual Result 
Nothing happens

## Version Info
* Plugin version: 4.0.6 
* WordPress version: 4.9.1

Without the above information we are not able to debug the issue and will close it.

**Comment by vyasdharmesh** [comment]
My Feed URL: https://www.echhapu.com/feed/instant-articles
my Page ID: 461835360538417

**Comment by Jayad** [comment]
Hi, 
Could you scroll down till end of your post in wordpress and look for any warnings?

**Comment by vyasdharmesh** [comment]
Below is the message.

	This post will be available as Instant Article once it is shared on Facebook.

This post was transformed into an Instant Article with no warnings

Kindly help,

![ia-issue](https://user-images.githubusercontent.com/12527112/34970438-5fb555bc-fa9a-11e7-943c-63e47668a466.jpg)

**Comment by mburak** [comment]
Hey @vyasdharmesh, have you shared your article in a FB posts? 
Thanks.

**Comment by vyasdharmesh** [comment]
yes i did

but still not appearing in IA

**Comment by mburak** [comment]
Could you share your debug info? Source html and transformed html. 
Thank you.

**Comment by vyasdharmesh** [comment]
how to get that?

sorry but i didn't got you

**Comment by mburak** [comment]
Go to the bottom of your article and click on "**Toggle debug information**". There you will see these fields.

**Comment by vyasdharmesh** [comment]
Source HTML:
<p>વડાપ્રધાન નરેન્દ્ર મોદીની સરકારે સત્તા સાંભળ્યા બાદ દેશની વિદેશનીતિમાં
લગાતાર સુધારો જ નથી આવ્યો પરંતુ તે pro-active પણ થઇ છે. વિદેશોમાં ભારતની આ
pro-active વિદેશનીતિની ત્યારે ખાસ નોંધ લેવામાં આવી હતી જ્યારે ભારતે યમન માં
‘ઓપરેશન રાહત’ ચલાવીને માત્ર ભારતીયો જ નહીં પરંતુ વિદેશી નાગરિકોને પણ બચાવી
લીધા હતા. હાલમાં સિંગાપોર ખાતે યોજાયેલા ASEAN-India પ્રવાસી ભારતીય દિવસ
દરમ્યાન વિદેશમંત્રી સુષ્મા સ્વરાજે ઓપરેશન રાહત એક અજાણી હકીકત જાહેર કરી
હતી.</p>
<figure id="attachment_1424" style="max-width: 759px" class="wp-caption
aligncenter"><img class="size-full wp-image-1424" src="
http://echhapu.com/wp-content/uploads/2018/01/Modi-with-Saudi-King.jpg"
alt="" width="759" height="422" srcset="
https://echhapu.com/wp-content/uploads/2018/01/Modi-with-Saudi-King.jpg
759w,
https://echhapu.com/wp-content/uploads/2018/01/Modi-with-Saudi-King-300x167.jpg
300w" sizes="(max-width: 759px) 100vw, 759px" /><figcaption
class="wp-caption-text">Photo Courtesy: indianexpress.com
</figcaption></figure>
<p>2015માં યમન પર સાઉદી અરેબિયા અને તેના સાથી રાષ્ટ્રોએ હુમલો કર્યો હતો.
આવા સમયે યમનમાં કાર્યરત હજારો ભારતીયો અને અન્ય નાગરિકો ત્યાં ફસાઈ ગયા હતા.
ભારત સરકારે ભારતીયોને એમના હાલ પર છોડી દેવાને બદલે તેમને બચાવીને ભારત પરત
લાવવા માટે ઓપરેશન રાહત હાથ ધર્યું હતું. વિદેશ રાજ્યમંત્રી જનરલ વી કે સિંઘના
નેતૃત્વ હેઠળ ઓપરેશન રાહત 2015ની પહેલી એપ્રિલથી અગિયાર દિવસ સુધી સતત
ચલાવવામાં આવ્યું હતું.</p>
<p>શરુઆતમાં આ ઓપરેશનમાં ભારે તકલીફ પડી હતી કારણકે ત્યારે સાઉદી અરેબિયા
દ્વારા સતત બોમ્બમારો ચાલુ રાખવામાં આવ્યો હતો. વિદેશમંત્રી સુષ્મા સ્વરાજને
ખ્યાલ હતો કે વડાપ્રધાન નરેન્દ્ર મોદીને સાઉદી રાજા સલમાન સાથે અંગતરીતે ઘણા
સારા સંબંધ છે. આથી સ્વરાજે વડાપ્રધાન મોદીને કિંગ સલમાનને વાત કરીને ઘટતું
કરવા કહ્યું હતું.</p>
<p><strong>તમને ગમશે: <a href="
http://echhapu.com/2017/11/10/business-standards-lies-and-hit-job-on-rupani-caught/"
target="_blank" rel="noopener">SEBIના રૂપાણી વિષેના નિર્ણય પરની Business
Standardની બદમાશી પકડાઈ</a></strong></p>
<p>વડાપ્રધાન મોદીએ તરતજ કિંગ સલમાનને સીધો જ કોલ કર્યો હતો. કિંગ સલમાને વળતા
જવાબરૂપે ભારતની મદદ માટે કશું પણ કરવાની તૈયારી દર્શાવી હતી. તેમણે દરરોજ
સવારે 9 થી 11 દરમ્યાન એક અઠવાડિયા સુધી યમન પર બોમ્બમારો નહીં થાય તેવી ભારત
સરકારને વડાપ્રધાન મોદી દ્વારા ખાતરી આપી હતી.</p>
<p>ત્યારબાદ ભારત સરકારે યમન સરકારને વિનંતી કરી હતી કે તેઓ આ સમય દરમ્યાન એડન
સી પોર્ટ અને સના એરપોર્ટ ખુલ્લું રાખે. યમને પણ ભારતની દોસ્તીના સંબંધને
ધ્યાનમાં લઈને તેમ કરવાનું વચન આપ્યું હતું. આમ યમનમાં ફસાયેલા ભારતીય
નાગરીકોને દરરોજ બે કલાક, એક અઠવાડિયા સુધી એડન અને સના દ્વારા નજીક આવેલા
જિબુટી ખસેડવામાં આવ્યા અને છેવટે તમામ ભારતીય નાગરિકોને યમનથી સુખરૂપ સ્વદેશ
પરત લવાયા હતા.</p>
<p>ભારતની આ સફળ કાર્યવાહીને ધ્યાનમાં લઈને બાદમાં અમેરિકા અને કેટલાક યુરોપીન
દેશોની સરકારોએ પણ યમનમાં ફસાઈ પડેલા પોતાના નાગરિકોને યમનમાં આવેલી ભારતીય
રાજદૂતની ઓફિસનો સંપર્ક કરવાનું કહ્યું હતું. ભારતે એ દેશના નાગરિકોને પણ આ જ
સમય દરમ્યાન જિબુટી ખસેડ્યા હતા.</p>
<p>આમ કોઇપણ સરકાર જો પોતાના એક એક  નાગરિકના જીવ ની કિંમત સમજે તો જ ઓપરેશન
રાહત જેવી કાર્યવાહી ચપટી વગાડતા જ થઇ શકે છે.</p>
<p><em>eછાપું </em></p>


Transformmed Markup:
<html>
  <head>
    <link rel="canonical" href="
http://echhapu.com/2018/01/11/how-one-phone-call-from-modi-changed-the-game-in-yemen-news/
"/>
    <meta charset="utf-8"/>
    <meta property="op:generator"
content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application"
content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.6"/>
    <meta property="op:generator:transformer"
content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true
ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="
http://echhapu.com/wp-content/uploads/2018/01/Modi-with-Saudi-King.jpg"/>
          <figcaption>Photo Courtesy: indianexpress.com</figcaption>
        </figure>
        <h1>જ્યારે મોદીના એક ફોન કોલ દ્વારા ઓપરેશન રાહત શક્ય બન્યું</h1>
        <time class="op-published"
datetime="2018-01-11T20:45:05+05:30">January 11th, 8:45pm</time>
        <time class="op-modified"
datetime="2018-01-13T10:31:25+05:30">January 13th, 10:31am</time>
        <address><a href="http://echhapu.com">Team eChhapu</a>Team
'eChhapu' which writes and publishes features of common interests.</address>
        <figure class="op-ad">
          <iframe src="
https://www.facebook.com/adnw_request?placement=885820821596895_901090336736610&amp;adtype=banner300x250"
width="300" height="250"></iframe>
        </figure>
      </header>
      <p>વડાપ્રધાન નરેન્દ્ર મોદીની સરકારે સત્તા સાંભળ્યા બાદ દેશની
વિદેશનીતિમાં લગાતાર સુધારો જ નથી આવ્યો પરંતુ તે pro-active પણ થઇ છે.
વિદેશોમાં ભારતની આ pro-active વિદેશનીતિની ત્યારે ખાસ નોંધ લેવામાં આવી હતી
જ્યારે ભારતે યમન માં ‘ઓપરેશન રાહત’ ચલાવીને માત્ર ભારતીયો જ નહીં પરંતુ
વિદેશી નાગરિકોને પણ બચાવી લીધા હતા. હાલમાં સિંગાપોર ખાતે યોજાયેલા
ASEAN-India પ્રવાસી ભારતીય દિવસ દરમ્યાન વિદેશમંત્રી સુષ્મા સ્વરાજે ઓપરેશન
રાહત એક અજાણી હકીકત જાહેર કરી હતી.</p>
      <figure data-feedback="fb:likes">
        <img src="
http://echhapu.com/wp-content/uploads/2018/01/Modi-with-Saudi-King.jpg"/>
        <figcaption>Photo Courtesy: indianexpress.com</figcaption>
      </figure>
      <p>2015માં યમન પર સાઉદી અરેબિયા અને તેના સાથી રાષ્ટ્રોએ હુમલો કર્યો
હતો. આવા સમયે યમનમાં કાર્યરત હજારો ભારતીયો અને અન્ય નાગરિકો ત્યાં ફસાઈ ગયા
હતા. ભારત સરકારે ભારતીયોને એમના હાલ પર છોડી દેવાને બદલે તેમને બચાવીને ભારત
પરત લાવવા માટે ઓપરેશન રાહત હાથ ધર્યું હતું. વિદેશ રાજ્યમંત્રી જનરલ વી કે
સિંઘના નેતૃત્વ હેઠળ ઓપરેશન રાહત 2015ની પહેલી એપ્રિલથી અગિયાર દિવસ સુધી સતત
ચલાવવામાં આવ્યું હતું.</p>
      <p>શરુઆતમાં આ ઓપરેશનમાં ભારે તકલીફ પડી હતી કારણકે ત્યારે સાઉદી
અરેબિયા દ્વારા સતત બોમ્બમારો ચાલુ રાખવામાં આવ્યો હતો. વિદેશમંત્રી સુષ્મા
સ્વરાજને ખ્યાલ હતો કે વડાપ્રધાન નરેન્દ્ર મોદીને સાઉદી રાજા સલમાન સાથે
અંગતરીતે ઘણા સારા સંબંધ છે. આથી સ્વરાજે વડાપ્રધાન મોદીને કિંગ સલમાનને વાત
કરીને ઘટતું કરવા કહ્યું હતું.</p>
      <p>
        <b>તમને ગમશે: <a href="
http://echhapu.com/2017/11/10/business-standards-lies-and-hit-job-on-rupani-caught/"
rel="noopener">SEBIના રૂપાણી વિષેના નિર્ણય પરની Business Standardની બદમાશી
પકડાઈ</a></b>
      </p>
      <p>વડાપ્રધાન મોદીએ તરતજ કિંગ સલમાનને સીધો જ કોલ કર્યો હતો. કિંગ
સલમાને વળતા જવાબરૂપે ભારતની મદદ માટે કશું પણ કરવાની તૈયારી દર્શાવી હતી.
તેમણે દરરોજ સવારે 9 થી 11 દરમ્યાન એક અઠવાડિયા સુધી યમન પર બોમ્બમારો નહીં
થાય તેવી ભારત સરકારને વડાપ્રધાન મોદી દ્વારા ખાતરી આપી હતી.</p>
      <p>ત્યારબાદ ભારત સરકારે યમન સરકારને વિનંતી કરી હતી કે તેઓ આ સમય
દરમ્યાન એડન સી પોર્ટ અને સના એરપોર્ટ ખુલ્લું રાખે. યમને પણ ભારતની દોસ્તીના
સંબંધને ધ્યાનમાં લઈને તેમ કરવાનું વચન આપ્યું હતું. આમ યમનમાં ફસાયેલા ભારતીય
નાગરીકોને દરરોજ બે કલાક, એક અઠવાડિયા સુધી એડન અને સના દ્વારા નજીક આવેલા
જિબુટી ખસેડવામાં આવ્યા અને છેવટે તમામ ભારતીય નાગરિકોને યમનથી સુખરૂપ સ્વદેશ
પરત લવાયા હતા.</p>
      <p>ભારતની આ સફળ કાર્યવાહીને ધ્યાનમાં લઈને બાદમાં અમેરિકા અને કેટલાક
યુરોપીન દેશોની સરકારોએ પણ યમનમાં ફસાઈ પડેલા પોતાના નાગરિકોને યમનમાં આવેલી
ભારતીય રાજદૂતની ઓફિસનો સંપર્ક કરવાનું કહ્યું હતું. ભારતે એ દેશના નાગરિકોને
પણ આ જ સમય દરમ્યાન જિબુટી ખસેડ્યા હતા.</p>
      <p>આમ કોઇપણ સરકાર જો પોતાના એક એક  નાગરિકના જીવ ની કિંમત સમજે તો જ
ઓપરેશન રાહત જેવી કાર્યવાહી ચપટી વગાડતા જ થઇ શકે છે.</p>
      <p>
        <i>eછાપું </i>
      </p>
    </article>
  </body>
</html>

**Comment by vyasdharmesh** [comment]
I think the problem is resolved.

Actually, I claimed only url with www prefix in configuration page.

I realized, I also need to claim url without prefix. I just did that and it
seems articles are being converted now.

Thanks,

2018-01-16 21:49 GMT+05:30 Dhams DXB <dhams.dxb@gmail.com>:

**Comment by mburak** [comment]
Yeah, that should be it. Great!

**Comment by Rajnikant1012021** [comment]
article can not convert in instant article need help
