### ISSUE TITLE
Facebook profile could not be looked up for url

### ISSUE THREAD

**Issue by JFOC** [Automattic/facebook-instant-articles-wp#856]
## Steps required to reproduce the problem

1. Write a Post
2. Publish a Post
3. Check the Facebook Publishing Tools

## Actual Result 
This Article Contains Errors
To give your audience a better experience, fix the errors noted before you publish your article.

Facebook profile could not be looked up for url: Ensure all entity URLs correspond to Facebook profiles (got https://www.facebook.com/app_scoped_user_id/xxxxxxx)

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.0.6
* WordPress version: 4.9.1
* PHP version: 5.6.x

**Comment by mburak** [comment]
Hi @JFOC,

could you share what your source html and transformed html are? 
Also if you have any custom rules, please post them here.

Thanks.

**Comment by JFOC** [comment]
No idea why there is `<address><a href="https://www.facebook.com/app_scoped_user_id/10155887956119803/" rel="facebook">Frank9x9</a></address>`

[t1.txt](https://github.com/Automattic/facebook-instant-articles-wp/files/1633814/t1.txt)

**Comment by mburak** [comment]
Do you have any custom rules?

**Comment by mburak** [comment]
BTW, that URL is taken from the article poster's website set in the Wordpress config. If that URL is a Facebook URL, it needs to point to a FB profile url.

**Comment by mburak** [comment]
The solution should be what I mentioned before. Please feel free to reopen the ticket if that doesn't work for you.

**Comment by JFOC** [comment]
Hi,
Sorry for late reply. I still have this problem.
Custom Rules:
`{
    "rules":[
        { "class": "IgnoreRule", "selector": ".comment-author-link" },
        { "class": "IgnoreRule", "selector": "a.url" }
    ]
}`
