### ISSUE TITLE
Can't use "async" attribute for Custom Embed Code

### ISSUE THREAD

**Issue by wle8300** [Automattic/facebook-instant-articles-wp#857]
## Steps required to reproduce the problem
1. Use "async" attribute for analytics tracker (e.g., `<script async src="https://cdn.onthe.io/io.js/gokVbwe4UiqH"></script>`

## Expected Result
Settings would be successfully saved

## Actual Result 
Instead outputs this error: **Invalid HTML markup provided for custom analytics tracker code**

## Version Info
- Plugin version: 4.0.4
- WordPress version: 4.7.3
- PHP version: 5.5

**Comment by mburak** [comment]
Hi @wle8300, for now we only support XHTML for the custom Embed Code. 
Please use the async attribute this way: 
`<script async="async" src="..."></script>`

Thanks.

**Comment by wle8300** [comment]
Can I also use `async=“”`? Thanks for the help!

**Comment by wle8300** [comment]
Can I also use `async=“”`? Thanks for the help!

**Comment by mburak** [comment]
I think you can (we allow that) but the right way is async="async" as the documentation describes: https://www.w3schools.com/tags/tag_script.asp

**Comment by wle8300** [comment]
Ok will do Matias! Thanks for the speedy support :D
