### ISSUE TITLE
Plugin skips FB authorization screen/settings and sits on default screen, no way to go back?

### ISSUE THREAD

**Issue by animalpproject** [Automattic/facebook-instant-articles-wp#859]
## Steps required to reproduce the problem

1. I login to my New Wordpress site which is on a SHARED server and IP with other sites that also run Instant Articles plugin
2. I go to the plugin, and it shows me settings page, but does NOT show me how to enter App details and authorize my plugin and through the website itself.
3. I am UNABLE to find any way to activate the plugin through FB and with the APP ID, because it goes to the screen that normally shows after a successful app ID integration, but it's almost if it skipped this step.  Any way I can direct my URL to force it to go back and authorize?

This has happened on 2 sites and I keep going back and forth with no luck at all. I hope you can help, because this seems like a real issue which makes the plugin completely unusable to me.

## Expected Result
It should show the plugin activation with FB to authorize

## Actual Result 
It should show the plugin activation with FB to authorize, but it does NOT and instead shows the 
<img width="1500" alt="screen shot 2018-01-19 at 1 33 31 am" src="https://user-images.githubusercontent.com/20697817/35144269-ed20837a-fcb8-11e7-944a-c353d15a89a1.png">

* Plugin version: 4.0.6
* WordPress version: 4.9.2
* PHP version: PHP-FPM 7

I truly hope you can help me.

**Comment by animalpproject** [comment]
Also, I tried just putting in settings and letting it go, however no articles will submit when I save articles.  Nothing shows up in my FB under 'published articles' . If I enter in my RSS feed, it syncs, but without that, it doesn't do anything and no articles come through.  Even though my articles say "This post will be available as Instant Article once it is shared on Facebook" None of them are auto-submitting.  I'm assuming for some reason my my server IP is detecting that this has already been provisioned with the APP ID, or for some reason this plugin version is updated since I did this last and this feature has been removed for integrating with APP id etc?  - I'm really sorry if I'm just getting confused, but bottom line is, articles don't show up in production articles unless I add my RSS feed URL into the FB page configuration section and this never was how it was before. Stuff would just auto push when I published... Hope you can shed some light on my sad level of intelligence here. :/

**Comment by mburak** [comment]
Hi @animalpproject, you don't need to have an app for this process, you only need to configure your page id. 
As you are saying that RSS works for you I assume you already have your URL validated inside your publishing tools.
What I think you are missing is to share your article's link in a Facebook post so the Instant Article is created.
