### ISSUE TITLE
Sending author name to Google Analytics 

### ISSUE THREAD

**Issue by aproxis** [Automattic/facebook-instant-articles-wp#861]
## Expected Result

I would like to see Author statistics in Google Analytics.
Using "gtag" and "events" for this.
On website I'm doing like that:

```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxx-x"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-xxxxxxxx-x');

  <?php
    if (is_singular('post')) {
      $this_post = get_queried_object();
      $author_id = $this_post->post_author;
      echo "gtag('event', 'Author', {'event_category': 'Rating', 'event_label': '" . get_the_author_meta('display_name', $author_id) . "', 'non_interaction': true});\n";
    }
  ?>
</script>
```
 
How could I send such event? Ideas?

## Version Info

* Plugin version: 2.11
* WordPress version: 4.7.5
* PHP version: 5.4.45

**Comment by everton-rosario** [comment]
Im thinking of a way of you doing that. You should give this a try: 

You could create this service that replies the author name from a given URL.
We store the canonical URL into the object `ia_document.shareURL`

You can see the complete documentation about the `ia_document` here: https://developers.facebook.com/docs/instant-articles/analytics
Script as a jsonp on your server (the jsonp is just for crossdomain problems you might have).
```
  <?php
    if (is_singular('post')) {
      $this_post = DO FIND YOUR POST BY URL ON QUERY PARAMETER;
      $author_id = $this_post->post_author;
      echo 'var author = ' . get_the_author_meta('display_name', $author_id);
    }
  ?>
</script>
```

Then on your IA analytics code you could just insert that script:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxx-x"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-xxxxxxxx-x');
  var author = // Request url on your server getting it with the ia_document.shareURL
  gtag('event', 'Author', {'event_category': 'Rating', 'event_label': author, 'non_interaction': true});
</script>
```

Let us know the final complete solution.
