### ISSUE TITLE
Add option to choose weather to publish a post for instant article or not

### ISSUE THREAD

**Issue by codeslane** [Automattic/facebook-instant-articles-wp#862]
add a option in backend add new post to choose weather the article get converted for instant article or not.
User should able to choose the instant article publishing setting from wordpress only.

**Comment by vkama** [comment]
We have discussed this previously with our team and we opted to not create this feature.

You can return false in the **instant_articles_should_submit_post** filter to prevent the article from being ingested as an IA.
