### ISSUE TITLE
Facebook Instant Article Not Being Submitted To Production

### ISSUE THREAD

**Issue by stephen4800** [Automattic/facebook-instant-articles-wp#863]
## Steps required to reproduce the problem

1. Updated To Latest Version Of Wordpress & Instant Articles
2.  Publish Post To Instant Articles
3. 

## Expected Result

Post will appear in production & be available to post

## Actual Result 

Post is not appearing in production
Post is not converting to instant article

## Version Info

I am able to do it by getting the source and adding it directly to the production but it was working fine before?

Any ideas?

**Comment by TonySawma** [comment]
Hello .. I am facing the same issue! 
I have found a workaround for it until there's a fix.

After your article is published on your website and it says it was submitted to 'Instant Articles',
1) Head over to: https://developers.facebook.com/tools/debug/og/object/ 
2) Paste your link in the 'Input URL' box
3) Click 'Fetch New Scrape Information'
At this point, the post will be in 'Production' as unpublished. As soon as you share on Facebook, it will become Live.

Hope this helps!

**Comment by yeah-sir** [comment]
@stephen4800 Did @TonySawma's workaround fix your issue? We are debugging this issue on our end as well.

**Comment by stephen4800** [comment]
It did not work for me either. I have to keep manually adding.


________________________________

**Comment by vkama** [comment]
Hi @stephen4800 and @TonySawma, the plugin now won't automatically send the IA to Facebook anymore. But as sson as you share it, Facebook's crawler will hit your blog and ingest the Instant Article.

Thank you

**Comment by b0tm0nk** [comment]
there is no error in my instant articles it shows that there is some errors but when i try to correct it there is no error at all. before once i used to update it used to work fine but now it remains unpublished.
