### ISSUE TITLE
Site Tagline not Shown 

### ISSUE THREAD

**Issue by Sukhwinder500** [Automattic/facebook-instant-articles-wp#880]
## Steps required to reproduce the problem
Hello Everyone Please help me to get out of this. when i update my site #Tagline then its shown in my admin panel of website, But not shown as visitor or front page of my website. Please check the Screen shot Below.

1. Check screen shot 1 Tagline updated and shown from admin panel.
![tagline shown in admin panel](https://user-images.githubusercontent.com/32815650/36193364-97e44e54-118b-11e8-9735-63306cf358e4.jpg)

2. But its not shown as Normal Visitor (Publicly).
![not shown](https://user-images.githubusercontent.com/32815650/36193462-0d6bb996-118c-11e8-89c2-4234a4811004.jpg)

3. Please check Screen shot or Read What **My Hosting Team Reply** To me (I could see the theme files has been updated. If I change the theme the site is showing the "title" The "Blog" theme that you are using is showing the below error on the file when we on the error logs from wordpress. wp_title- assumed 'wp_title' in /var/sentora/hostdata/onlinetvs/public_html/postinfo.in/wp-content/themes/blogs/header.php on line 14 We would suggest you to check with the themes or re-upload the theme file from wordpress dashboard)

## Expected Result
Please Solve my issue Check screenshot below.

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 4.7.9
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by pestevez** [comment]
@Sukhwinder500 - is your issue related to the Instant Articles plugin?

**Comment by Sukhwinder500** [comment]
@pestevez  **No My issue is not related with instant article/**
Issue is My Website Tagline is not shown in Browser , But shown in admin panel "screenshot uploaded" please check tell me if any solution.
Website :- www.postinfo.in

**Comment by pestevez** [comment]
Please then open the issue in the corresponding GitHub repo. This one only tracks issues related to the Instant Articles WordPress plugin. Thanks
