### ISSUE TITLE
Insert Adx script

### ISSUE THREAD

**Issue by brunomosciatti** [Automattic/facebook-instant-articles-wp#882]
## Expected Result
See Google DFP (Adx) ads inside Instant Articles

## Actual Result 
Cant find the head tag to place my script inside it

## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.8.2
* PHP version: 7+

I'm trying to add my Adx tag inside Instant Article - it should be placed inside head tag but how can I add it there?

Documentation:
https://developers.facebook.com/docs/instant-articles/monetization/direct-sold

**Comment by pestevez** [comment]
In the plugin settings there is a section for ads:

![image](https://user-images.githubusercontent.com/18663703/36312822-b46bbd32-12fd-11e8-8197-bb0161049277.png)

The plugin will place the ads code in the right place in the generated Instant Article markup:

![image](https://user-images.githubusercontent.com/18663703/36312879-e2028244-12fd-11e8-9c30-4146d8b713d0.png)

Closing the issue now...
