### ISSUE TITLE
Amazon Associates Link Builder Plugin And Instant Articles for WP Compatibility Issue

### ISSUE THREAD

**Issue by onlinetushar** [Automattic/facebook-instant-articles-wp#884]
Please check screenshot ( https://ibb.co/hMD6cc ) and suggest how to solve this error?

Site URL: https://www.missionmpsc.com/

Instant Articles for WP Plugin version: 4.0.6
Amazon Associates Link Builder Plugin version: 1.5.4
WordPress version: 4.9.4
PHP version: 7

**Comment by onlinetushar** [comment]
This worked for me. Thank You @diegoquinteiro 

`{
    "rules":[
        { "class": "IgnoreRule", "selector": ".fb-comments" },
        { "class": "IgnoreRule", "selector": "comments-count" }
    ]
}
`

**Comment by vkama** [comment]
I am sorry, we don't support 3rd party plugins.
More information about how to create custom rules here: https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules
