### ISSUE TITLE
How to scrape articles to development library

### ISSUE THREAD

**Issue by bsgies** [Automattic/facebook-instant-articles-wp#887]
Hi,

Can anyone tell me how to scrape content to Development articles Library first before pushing it to Production Library?

I could not find any development FEED URL that I can enter in Instant article configuration section.

Please HELP!

Regards,
Bilal

**Comment by vkama** [comment]
This is the document for the ingestion:
https://developers.facebook.com/docs/instant-articles/crawler-ingestion

Also, in the plugin under Publishing Settings you can click the checkbox to enable the Development Mode, so it will go to your development feed.

**Comment by bsgies** [comment]
Hi Vkama,

Thanks for your response. I understand what you said by I'm just curious to know if there's a link to the development feed which I can go and enter into the Instant articles configuration section and refresh anytime.

I hope I made it more specific to you now.

Regards,
Bilal
