### ISSUE TITLE
How do I remove articles from Instant article feed?

### ISSUE THREAD

**Issue by bsgies** [Automattic/facebook-instant-articles-wp#889]
Hi,

I've had an issue with an article and I have deleted it from my production library. A few moments later the article is back up again in my production library. The reason for that is Facebook recrawled the RSS feed and found the article to be there.

But only if I can manage which article can be in my RSS feed will allow me to only send those articles to the Facebook production library.

Can someone please help how can this be achieved?

Regards,
Bilal

**Comment by mburak** [comment]
Hi @bsgies, this plugin builds the RSS based on your published posts, so if you don't want any of them to be on your feed, you'd need to unpublish/delete your post from Wordpress. If you need other kind of configuration you would have to create a custom feed and use that. 
I encourage you to stop using the RSS feed which doesn't give you any flexibility, so once you create an article in Wordpress and you share it on FB, the FB crawler would scrape your article and publish it as an instant article. Then if you want to remove that article from being an Instant Article, you can go to the publishing tools and do so.
