### ISSUE TITLE
AMP canonical and publisher issue

### ISSUE THREAD

**Issue by FrancescJR** [Automattic/facebook-instant-articles-wp#892]
I am really sorry I can't really reproduce the error, so please be free to close the issue if you feel appropriate, it's just I feel that some AMP pages are not created properly  with this 2 issues:
1. canonical is not set properly (for some reason google crawled some post with  weird canonical href - for example the author of the post instead ). This would be one of the page google complains of: https://xceed.me/blog/it/dana-ruh-al-kinki-club-di-bologna/?amp_markup=1 even though if I use the same google tester it says everything is alright, but on teh registered issue it says that the canonical link is this one:  https://xceed.me/blog/it/author/eugenio/ 

2. Structured data is not properly set (this is a warning). That would be that publisher of the "newsArticle" is missing on the metadata. And that is indeed the case if you look at buildSchemaOrgMetadata($context) in AMPArticle, publisher is only set inside and if, but it si always reuqired by google (which btw doesn't accept @type person, but only @type organization)

I am writing this in case it may help somebody eventually, but again, close the issue or delete it etc etc

**Comment by mburak** [comment]
I'm sorry @FrancescJR but I couldn't reproduce this either, please feel free to create a new issue if you have more context on how to reproduce it. Thanks!
