### ISSUE TITLE
This post was transformed into an Instant Article with some warnings

### ISSUE THREAD

**Issue by nstrazimiri** [Automattic/facebook-instant-articles-wp#894]
## Steps required to reproduce the problem

1. Hello I have a wordpress website where i have installed Facebook Intant Articles. For every article it keeps me showing that i have transformation warning. My server is Ubuntu 14. I moved my website from my actual server to another one, and it works perfect.Always using same theme, same plugins. So maybe i thought i miss any php extension. I googled about it but no results.I have the latest version of plugin, and wordpress. 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

#source markup
<p><a href="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png"><img class="size-full wp-image-66861 aligncenter" src="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png" alt="" width="755" height="429" srcset="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png 755w, https://shendeti.com.al/wp-content/uploads/2018/03/liver13-300x170.png 300w, https://shendeti.com.al/wp-content/uploads/2018/03/liver13-739x420.png 739w, https://shendeti.com.al/wp-content/uploads/2018/03/liver13-640x364.png 640w, https://shendeti.com.al/wp-content/uploads/2018/03/liver13-681x387.png 681w" sizes="(max-width: 755px) 100vw, 755px" /></a></p>
<p><strong>Përshtati në shqip: Blertina Koka</strong></p>
<p>Lajme të mira, fansa të kafes: Keni një arsye më shumë përse duhet ta shijoni kafen e mëngjesit. Pas një analize që iu është bërë 9 studimeve të mëparshme, shkencëtarët kanë zbuluar se personat që konsumojnë 2 filxhanë kafe në ditë janë 44% më pak të rrezikuar që të zhvillojnë cirrozë të mëlçisë. Rreziku vazhdon të ulet me 65% tek njerëzit që konsumojnë 3 dhe 4 filxhanë kafe.</p>
<p>Cirroza është një sëmundje e mëlçisë, e zhvilluar pas një dëmtimi të gjatë të këtij organi, që pengon në funksionimin e tij.</p>
<p>“Rezultatet e këtij studimi mund të jenë të rëndësishme për njerëzit që janë të ndjeshëm ndaj kësaj sëmundjeje”, thotë autori kryesor i studimit, dr. O. J., nga Universiteti Kennedy of Southampton në Britani, edhe pse duhet të bëhen më shumë kërkime shkencore, shpjegon ai për Forbes.</p>
<p>“Tani kemi nevojë për teste klinike për të hetuar mbi përfitimet dhe dëmet e kafes, kështu mjekët mund të japin rekomandime specifike për pacientët”.</p>
<p>Gjithsesi ekspertët rekomandojnë që mos ta teproni me kafen, pasi mund të zhbëjnë efektet shëndetësore të saj, që shkojnë përtej mëlçisë. Konsumimi i tepërt i kafes është lidhur me problemet me zemrën, imunitetin e dobët, disa lloje kanceri etj.</p>
<p>Gjithsesi, nëse doni ta nisni ditën me 1 filxhan kafe, të pini edhe 1, 2 apo 3 gjatë ditës, mund ta bëni. Studime të tjera kanë zbuluar se kafja është burimi kryesor i antioksiduesve në dietën tonë.</p>
<p><strong>Burimi: Health / <a href="http://shendeti.com.al/" target="_blank" rel="noopener">Shendeti.com.al</a></strong></p>

#Tranformed Markup
<html>
  <head>
    <link rel="canonical" href="https://shendeti.com.al/cfare-ndodh-me-melcine-nese-pini-2-filxhane-kafe-cdo-dite/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.6"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png"/>
        </figure>
        <h1>Çfarë ndodh me mëlçinë nëse pini 2 filxhanë kafe çdo ditë</h1>
        <time class="op-published" datetime="2018-03-06T12:00:01+00:00">March 6th, 12:00pm</time>
        <time class="op-modified" datetime="2018-03-06T14:31:47+00:00">March 6th, 2:31pm</time>
        <address><a href="https://shendeti.com.al">Blerta Koka</a></address>
      </header>
      <footer>
        <small>Gazeta Shëndeti 2018</small>
      </footer>
    </article>
  </body>
</html>

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.0.6
* WordPress version: 4.9.4
* PHP version: 7.0

Without the above information we are not able to debug the issue and will close it.

**Comment by mburak** [comment]
Hi @nstrazimiri, I'm not seeing any warning using your source html. 
Do you have any custom rule? Also, could you share the warning that you are getting? Thanks!

**Comment by nstrazimiri** [comment]
Hello @mburak ,

Below is my code from my wordpress admin. 
The errors that i get are:  
No rules defined for <img> in the context of Anchor
No rules defined for <p> in the context of Anchor 
I don't have any custom rule. I tried some but none of them works, i keep geting the same errors. 
As i said before, the same content, in another server works just fine. 
```
<a href="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png"><img class="size-full wp-image-66861 aligncenter" src="https://shendeti.com.al/wp-content/uploads/2018/03/liver13.png" alt="" width="755" height="429" /></a>

<strong>Përshtati në shqip: Blertina Koka</strong>

Lajme të mira, fansa të kafes: Keni një arsye më shumë përse duhet ta shijoni kafen e mëngjesit. Pas një analize që iu është bërë 9 studimeve të mëparshme, shkencëtarët kanë zbuluar se personat që konsumojnë 2 filxhanë kafe në ditë janë 44% më pak të rrezikuar që të zhvillojnë cirrozë të mëlçisë. Rreziku vazhdon të ulet me 65% tek njerëzit që konsumojnë 3 dhe 4 filxhanë kafe.

Cirroza është një sëmundje e mëlçisë, e zhvilluar pas një dëmtimi të gjatë të këtij organi, që pengon në funksionimin e tij.

“Rezultatet e këtij studimi mund të jenë të rëndësishme për njerëzit që janë të ndjeshëm ndaj kësaj sëmundjeje”, thotë autori kryesor i studimit, dr. O. J., nga Universiteti Kennedy of Southampton në Britani, edhe pse duhet të bëhen më shumë kërkime shkencore, shpjegon ai për Forbes.

“Tani kemi nevojë për teste klinike për të hetuar mbi përfitimet dhe dëmet e kafes, kështu mjekët mund të japin rekomandime specifike për pacientët”.

Gjithsesi ekspertët rekomandojnë që mos ta teproni me kafen, pasi mund të zhbëjnë efektet shëndetësore të saj, që shkojnë përtej mëlçisë. Konsumimi i tepërt i kafes është lidhur me problemet me zemrën, imunitetin e dobët, disa lloje kanceri etj.

Gjithsesi, nëse doni ta nisni ditën me 1 filxhan kafe, të pini edhe 1, 2 apo 3 gjatë ditës, mund ta bëni. Studime të tjera kanë zbuluar se kafja është burimi kryesor i antioksiduesve në dietën tonë.

<strong>Burimi: Health / <a href="http://shendeti.com.al/" target="_blank" rel="noopener">Shendeti.com.al</a></strong>

```

**Comment by mburak** [comment]
@nstrazimiri it's weird, that should work very straightforward, there are already default rules taking care of that. What plugins are you using?

**Comment by nstrazimiri** [comment]
@mburak , i use the official plugin from wordpress.org page : https://wordpress.org/plugins/fb-instant-articles/
 that's why I posted here, because i didn't find anything similar to the web.

**Comment by diegoquinteiro** [comment]
Hi @nstrazimiri, Instant Articles (not the plugin) currently does not support links with images inside or links with paragraphs inside. The intended behavior for the plugin on this scenario is to not convert and fallback to the mobile web version.

Thank you!
