### ISSUE TITLE
Fatal Error Unexpected "." expecting "," ... line 27

### ISSUE THREAD

**Issue by ewrightmedia** [Automattic/facebook-instant-articles-wp#91]
Hello, upon activating the plugin, I get this error. I have already installed composer in the plugin directory (thank you by the way for updating the readme)

Triggered a Fatal Error

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /wp-content/plugins/facebook-instant-articles-wp-master/settings/class-instant-articles-settings.php on line 27

Thank you

**Comment by diegoquinteiro** [comment]
Hi @ewrightmedia, Diego from Facebook here.

This is one of the issues we fixed related older versions PHP (older than 5.6.x). The fix on #87, and we expect to be able to merge it very soon!

**Comment by ewrightmedia** [comment]
Thank you for all of your great work on this! 

Much appreciated, and looking forward

**Comment by diegoquinteiro** [comment]
Thank you @ewrightmedia!

This was fixed and landed. Please download the last release or simply install the plugin from the WordPress Plugin repository.
