### ISSUE TITLE
Crashing MultiSite when Articles published

### ISSUE THREAD

**Issue by codeslane** [Automattic/facebook-instant-articles-wp#919]
Crashing Multisite when any new article is published.

**Comment by diegoquinteiro** [comment]
Hi @codeslane, thanks for reporting. Can you provide the version info as required on the issue template?

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 
* PHP version: 

Without the above information we are not able to debug the issue.

**Comment by everton-rosario** [comment]
Closing, please reopen with the needed info, so we can check it properly.
