### ISSUE TITLE
Enchancement - WYSIWYG Instant Articles transformer

### ISSUE THREAD

**Issue by YOzaz** [Automattic/facebook-instant-articles-wp#92]
Hey guys, congratulations and thanks for an amazing job you've done here!
I have a proposal for this package. In general, it's now built specifically for WordPress, which is fine. However, I think it can be easily split into two packages, which such scopes:

* Universal package to translate ORM (or any data format) to Instant Articles format.
* WordPress plugin implementation, using tools above.

The thing is, that most of the CMS systems actually do have database models (more or less), therefore have WYSIWYG editors installed - usually it's either CkEditor, either TinyMCE. If you'd make general translation code more abstract, it would be quite easy to adopt it to other systems as well, not WordPress only. E.g. people will be able to write native plugin to CkEditor.

**Comment by diegoquinteiro** [comment]
Hey @YOzaz, one more time: thank you a lot for helping!

Please take a look at the SDK: https://github.com/facebook/facebook-instant-articles-sdk-php - there you can see the workings of our transformation engine.

I think this discussion is more suitable to there, and these are all interesting ideas.

Would you mind opening a similar issue there? I'll be closing this one as it is not WP-plugin-related.
