### ISSUE TITLE
The plugin does not publish articles on facebook

### ISSUE THREAD

**Issue by mail47002** [Automattic/facebook-instant-articles-wp#920]
Good day. I have a problem with the plugin for wordpress instant articles
The plugin does not publish articles on facebook, although the article shows that everything is ok.
http://joxi.net/E2pzaNpf9g8K7r

## Version Info
* Plugin version:  4.0.6
* WordPress version: 4.9.5
* PHP version: 7.0

Without the above information we are not able to debug the issue and will close it.

**Comment by diegoquinteiro** [comment]
That's correct. This plugin does not publish articles on Facebook, it only transforms it to Instant Articles so it's rendered as Instant Articles once it is published by you or someone on Facebook.
