### ISSUE TITLE
Your Facebook Page is in violation of Instant Articles policies. Review the policies to see what changes can be made to regain access.

### ISSUE THREAD

**Issue by randika2018** [Automattic/facebook-instant-articles-wp#921]
Your Facebook Page is in violation of Instant Articles policies. Review the policies to see what changes can be made to regain access.
why this problem.
![instanat](https://user-images.githubusercontent.com/38404972/38781262-ccaed0d4-40ff-11e8-8513-2c246b03532c.JPG)

**Comment by randika2018** [comment]
how does solute this problem. please help me

**Comment by demetrox** [comment]
this is not plugin issue..lol

**Comment by everton-rosario** [comment]
Can you share the Page ID?

**Comment by yeah-sir** [comment]
@randika2018 you can find more details on Instant Articles policies on the link below. Kindly review to see if your page meets the standards. If not your page will not eligible for Instant Articles. You can find steps to regain access there as well:

https://developers.facebook.com/docs/instant-articles/policy/

**Comment by ankshvayt** [comment]
I've answered this here: https://github.com/Automattic/facebook-instant-articles-wp/issues/925#issuecomment-415930528
