### ISSUE TITLE
FIA-WP not getting all post data

### ISSUE THREAD

**Issue by BlankSuporte5** [Automattic/facebook-instant-articles-wp#922]
I have a Recipes Blog, where I use some Custom Fields to set Ingredients and Directions, as you can see here:
![image](https://user-images.githubusercontent.com/38261894/38813760-38df6398-4166-11e8-8878-7bb8eccfe961.png)

But the feed gets only the content data (Which I use for directions).
![image](https://user-images.githubusercontent.com/38261894/38813844-75f877ec-4166-11e8-9b4b-a4008552840e.png)

As a result of this, Facebook gets only the content data for FIA

Can I get the custom fields to be also sent by the feed?

## Version Info
* Plugin version:  4.0.6
* WordPress version: 4.9.5
* PHP version: 7.0.24

**Comment by jerclarke** [comment]
This is already possible but you'll need to use PHP plugin code to insert content into the IA output and you'll also need to be very careful to ensure the content you insert is valid IA format HTML. 

Read this link for my previous reply to a similar question with code example: https://github.com/Automattic/facebook-instant-articles-wp/issues/890#issuecomment-371926279

**Comment by everton-rosario** [comment]
As @jerclarke mentioned, we have a way to perform the content addition at the moment of the HTML content generation per https://github.com/Automattic/facebook-instant-articles-wp/issues/890#issuecomment-371926279

You can also do it on the moment after Instant article was created, using the hook: 
add_action( ''instant_articles_after_transform_post", "function_to_add_specific_things" );

function function_to_add_specific_things($instantArticlePost) {
    // Get post content and add as Element structure in InstantArticle element class.
}
