### ISSUE TITLE
i have problem with insttant article

### ISSUE THREAD

**Issue by bakry3d** [Automattic/facebook-instant-articles-wp#923]
hello every one

please the instant article its not working

the problem is

Too Many Line Breaks: This text block uses too many line breaks (<br/> elements). Please split the text block into multiple paragraphs or reduce the number of line breaks to a maximum of 5.

can any one help me

**Comment by dilllily3** [comment]
and facebook send this



Thank you for submitting an appeal. We've reviewed your Page for monetization eligibility. At this time, we aren't able to reinstate its access to Ad Breaks, Branded Content, and/or Instant Articles. To use these features, your Page must comply with Facebook's policies and terms and our monetization eligibility criteria. We recommend that you address your Page's compliance going forward, as it may become eligible within 90 days to re-access the monetization features previously utilized.

This decision regarding your Page's eligibility to use any monetization features on Facebook may not be appealed again for 90 days.

Learn more about our monetization eligibility criteria: https://www.facebook.com/facebookmedia/get-started/monetizationstandards
Thanks,

Mildred

**Comment by everton-rosario** [comment]
Can you share the Page ID?
To the topic of line breaks, you can add a filter to remove extra line breaks and keep just one on Instant Articles.

**Comment by bakry3d** [comment]
This id
385005064969364

What's you think about

{
    "rules":
    [
    {
        "class": "IgnoreRule",
        "selector" : ".wp-caption.aligncenter"
    }
  ]
}




Is that good ,?

**Comment by bakry3d** [comment]
any help ?

**Comment by bafi** [comment]
I have the same problem

**Comment by everton-rosario** [comment]
To your comment, regarding the rule, it is possible.
I was wondering you applying some filters like this (first google result about removing line breaks):

https://kellenmace.com/remove-line-breaks-wordpress/

Regarding the monetization standards, this is not the right channel to do it. You should go thru your "publishing tools"/"instant articles" within your Facebook Page.
