### ISSUE TITLE
Disable ads on specific content

### ISSUE THREAD

**Issue by lubimow** [Automattic/facebook-instant-articles-wp#924]
How do I disable ads on inappropriate content for facebook?
Perhaps there is a way to not publish news in Instant Articles with a tag (tag in Wordpress)?

**Comment by everton-rosario** [comment]
Hello @lubimow this is how you can do it:
https://github.com/Automattic/facebook-instant-articles-wp/issues/396#issuecomment-242133950

Let us know if this was something you were looking for.
