### ISSUE TITLE
"Resubmit for review" button disabled - Facebook Instant articles 

### ISSUE THREAD

**Issue by Ironir** [Automattic/facebook-instant-articles-wp#928]
Hello everyone, 

I applied for instant articles lately, and did all the steps as required, after I submitted for review facebook asked to edit some articles or post new ones, and I already did that but still the "resubmit for review" button is disabled, what should I do? I contacted the Facebook support but without success... 

![screenshot_5](https://user-images.githubusercontent.com/34078470/39124561-26f92dd0-46fc-11e8-87e0-3f553bff6e5b.jpg)

**Comment by yeah-sir** [comment]
Hi @Ironir can you send over your page id ?

**Comment by Ironir** [comment]
Page ID: 306287716188954

**Comment by lyluch** [comment]
I have the same problem. Please help solving the problem.

**Comment by JohnWickerz** [comment]
I have the same problem, until to submmit a new reviews, IA is dead?

**Comment by pangmedia** [comment]
Same issue with me too......
its been 10days and facebook still has not responded.....

**Comment by mburak** [comment]
Hi @Ironir, I'm sorry but this is not related to the WP plugin. I suggest you to go through the support page: https://developers.facebook.com/support/
Also, check for any warnings or messages surrounding your site configuration.
Check this thread to see if it falls into same case: #925

Thanks.

**Comment by RRPANDEYY** [comment]
Resubmit for review" button disabled - Facebook Instant articles
**Read and troubleshoot these Steps** 
1. If Facebook reject your articles with some errors For Ex:-  not rendering properly or not enough article or fix this issue before submitting . Do first THING delete your all article from production article 
2.  Paste attest 15 Good article which should be okay with Facebook community guidelines means not violence , gambling , murder rape , sex nudity .
3.  do not use RSS FEED  automation keep it manual  .

4. leave it and keep watch after few hrs your button will be clickable or any error flagged their .

5. If your all articles match the instant article parameters then it will be sure your site approved .

6. if still not Fix the issue can share next errror to me to assist better to community .

Regards,

Rahul Pandey

**Comment by johnny-wrgwq** [comment]
error is happening for me too. my url is approved but I can't click on submit for review button

**Comment by madislianchhing** [comment]
> Resubmit for review" button disabled - Facebook Instant articles
> **Read and troubleshoot these Steps**
> 
> 1. If Facebook reject your articles with some errors For Ex:-  not rendering properly or not enough article or fix this issue before submitting . Do first THING delete your all article from production article
> 2. Paste attest 15 Good article which should be okay with Facebook community guidelines means not violence , gambling , murder rape , sex nudity .
> 3. do not use RSS FEED  automation keep it manual  .
> 4. leave it and keep watch after few hrs your button will be clickable or any error flagged their .
> 5. If your all articles match the instant article parameters then it will be sure your site approved .
> 6. if still not Fix the issue can share next errror to me to assist better to community .
> 
> Regards,
> 
> Rahul Pandey

Hello, Mr. Rahul, can i have you phone number or gmail to contact about facebook submit issue
