### ISSUE TITLE
plz help me when i vrefy my fb site i got this message

### ISSUE THREAD

**Issue by mizansyl** [Automattic/facebook-instant-articles-wp#929]
The provided URL is not being accepted because the site has minimal readership, which violates the Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL## Steps required to reproduce the problem

**Comment by yeah-sir** [comment]
hi @mizansyl. This is not bug but content policy. You can find more information on possible steps to resolve here: https://developers.facebook.com/support/bugs/1809474069346452/
