### ISSUE TITLE
Is anyone actively maintaining this plugin any longer?

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#93]
There has been some pretty critical issues posted here that need to be addressed in order for a lot of people to get their articles approved. However, they have not been addressed/responded to in over two weeks.

Is there no team at Automattic actively maintaining this anymore?

**Comment by YOzaz** [comment]
@kkranzo yes it is:
https://developers.facebook.com/bugs/1368699553155531/
https://github.com/Automattic/facebook-instant-articles-wp/pull/87
https://github.com/Automattic/facebook-instant-articles-wp/pull/90

**Comment by kkranzo** [comment]
Okay, good to know.

Seems like this should be addressed asap since I am sure a lot of people who want to use Instant Articles have this issue:

https://github.com/Automattic/facebook-instant-articles-wp/issues/60
