### ISSUE TITLE
Instant Articles not submitted to Production Article 

### ISSUE THREAD

**Issue by lyluch** [Automattic/facebook-instant-articles-wp#935]
My Facebook page lost access to Instant Article. I sent an appeal about 6 months ago. Now IA allows me to resubmit for review by posting 3 articles. After posting, Instant Article not submitted to Production Articles, that’s why I can’t click on Resubmit button. 

I have tried many methods people sharing on the web but it’s not working anyway. 

Anyone can solve this problem? Please tell me.

**Comment by mburak** [comment]
Hi @lyluch, this is not completely related to the WP plugin. But please check for any warnings or messages surrounding your site configuration.

Check this thread to see if it falls into same case: #925
