### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by theinoomg** [Automattic/facebook-instant-articles-wp#945]
## Steps required to reproduce the problem

1. 
2. 
3. 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by everton-rosario** [comment]
Looks like you missed to inform the content.

Please open an issue with full and complete information.
