### ISSUE TITLE
Production articles show articles are Live, still Instant Article is not working

### ISSUE THREAD

**Issue by man152207** [Automattic/facebook-instant-articles-wp#946]
Hi! Instant article for my website has suddenly stopped working since around some days. When i went to the production article section all articles are Live but still when articles are shared on any of the pages it opens in the browser. Can someone please help!
## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.9.6

**Comment by everton-rosario** [comment]
Check for any warnings or messages surrounding your site configuration.

Check this thread to see if it falls into same case: #925
