### ISSUE TITLE
"Not Approved URLs" Showing on The Configuration Tab

### ISSUE THREAD

**Issue by pumamammal** [Automattic/facebook-instant-articles-wp#947]
## Steps required to reproduce the problem

 I've lost my Instant Article and I hope to get it back. My Url gets about 13,000 visits in a day and the page gets about 300,000 engagement in a day.

This morning, I saw Pending URLs and Not Approved Urls.

Please what does "Not Approved Urls" mean.

**Comment by everton-rosario** [comment]
Please, use the Publishing tools under your page for this type of request.
