### ISSUE TITLE
Installation issues with Instant articles.

### ISSUE THREAD

**Issue by viplavm** [Automattic/facebook-instant-articles-wp#948]
## Steps required to reproduce the problem

1.  Instant articles plugin not getting installed . 
2. Please read the details below.
3.

## Expected Result
Installation and activation of plugin. 

## Actual Result 
![image](https://user-images.githubusercontent.com/40262943/41402251-6f50fce6-6fdf-11e8-89c6-83118183b779.png)

If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

* Plugin version:  Version: 4.0.6
* WordPress version: 4.9.6
* PHP version: 5.6.30

Without the above information, we are not able to debug the issue and will close it.

**Comment by everton-rosario** [comment]
Looks like you have file permissions issue while copying and running the script to build and install the dependencies from the WordPress plugin.

Can you confirm if your system is allowing or has write permmission on the folder listed on the error message you've printed?
`fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-extensions-in-php/tests/Facebook/InstantArticles/AMP/articles/media-cache/heart-rate-age-300x182gif`

This folder sits under your plugin structure. Looks like this is a very long file name though, that should not be embed within the package.


Let's reopen if bug identified.
