### ISSUE TITLE
My wordpress entries do not have errors, but they are not shown in articles in production and I have everything configured well.

### ISSUE THREAD

**Issue by marlonarias** [Automattic/facebook-instant-articles-wp#955]
greetings I have a problem since day I am trying to request the instant articles, but I could not add my domain and I get a message that says pending and uploaded 10 articles but the instant articles do not want to load me.

* Plugin version: 4.0.6 
* WordPress version: 4.9.6 
* PHP version:

**Comment by yeah-sir** [comment]
Hi @marlonarias , each page needs to undergo Instant Articles Review before its enabled to post. You can find more on how to get approved for this here: https://developers.facebook.com/docs/instant-articles/get-started/article-review/
