### ISSUE TITLE
NOT APPROVED URLS: WHAT DOES IT MEAN?

### ISSUE THREAD

**Issue by pumamammal** [Automattic/facebook-instant-articles-wp#959]
I've been trying to apply for a new Instant Article, 
I used my first url, it went under the NOT APPROVED URL

I used the second one, went to the business manger to claim ownership and it also went under the NOT APPROVED URL

Please who knows the criteria to get ones's url approved?

**Comment by jerclarke** [comment]
It's normal, you need thousands and thousands of visitors to your site from Facebook or the site won't qualify. They refuse to tell us the actual numbers, and claim not being popular on Facebook is a violation of the "Standards".

Probably give up and spend your time on other platforms that welcome small publishers. 

See #925

**Comment by pumamammal** [comment]
@jerclarke , I have thousand and thousands of views. My facebook page has oer 1million likes and at least 200k engagement a day. The weblinks is about 30k in a day.

I don't get the low readership error, what I get "Not Approved Url" 

I think the "Not Approved Url" has to do with another criteria.

**Comment by yeah-sir** [comment]
@pumamammal You can find details about the Instant Articles Review process and content policies here: https://developers.facebook.com/docs/instant-articles/get-started/article-review/

**Comment by pumamammal** [comment]
@yeah-sir What could be the issue. My Instant article was banned for an unknown reason. I have 200,000 monthly traffic monthly. 150,000 from facebook. 
My URL is under "Not Approved Url"

I've read the policy several times and I'm not violating any of them. 
url: correctbae.ng
facebook  Page: Correct Bae

**Comment by eng1romya** [comment]
and my site also have this not approved
www.cncworld.tk
