### ISSUE TITLE
Footer Credit html code escaped

### ISSUE THREAD

**Issue by abdusfauzi** [Automattic/facebook-instant-articles-wp#96]
Why need to `esc_html()` if Facebook guidelines permit the use of `<p>` tags within `<aside>`? How about hyperlink `<a>`?

https://github.com/Automattic/facebook-instant-articles-wp/blob/master/template.php#L114

**Comment by stuartshields** [comment]
@abdusfauzi What you can do is duplicate the template file and then use wp_kses to allow certain html elements in.

**Comment by abdusfauzi** [comment]
Ahh. Sounds great. Anyway, how should I do it?

**Comment by stuartshields** [comment]
@abdusfauzi Looks like they've taken out the support for the custom template.php file. In v0.1 we had that ability but now we do not. I don't think there is a way around it, unless the plugin authors correctly add a hook/action for us to grab. I'm still going through the v2 changes and will let you know if I find another way.

**Comment by abdusfauzi** [comment]
@stuartshields ops. it's ok. I guess they will introduce that again, later updates. 😃

**Comment by diegoquinteiro** [comment]
Hi @abdusfauzi @stuartduff,

We're now using the Facebook Instant Articles PHP SDK to generate the markup: https://github.com/facebook/facebook-instant-articles-sdk-php

I'm adding a new filter that runs after the generation of the `InstantArticle` element from the SDK, where you can add your custom footer using `Elements` from the SDK.

**Comment by diegoquinteiro** [comment]
The hook is on master now, you can add a custom footer like this:

```php
use Facebook\InstantArticles\Elements\Footer;
use Facebook\InstantArticles\Elements\Paragraph;

add_filter('instant_articles_transformed_element', function ($article) {
    $article->withFooter(
        Footer::create()
            ->addCredit(
                Paragraph::create("First paragraph"),
            )
            ->addCredit(
                Paragraph::create("Second paragraph"),
            )
    );
    return $article;
});
```

Does that work?

**Comment by stuartshields** [comment]
@diegoquinteiro  Does it allow for html elements? like hyperlinks? In theory it should also work for variables right?

**Comment by diegoquinteiro** [comment]
@stuartduff inside `Paragraph`, or within `addCredit(...)`, you can have `Anchor`, `Bold` and `Italic` elements. You'll need to build your Anchor, Bold and Italic instances programatically, like:

```php
use Facebook\InstantArticles\Elements\Footer;
use Facebook\InstantArticles\Elements\Paragraph;
use Facebook\InstantArticles\Elements\Bold;
use Facebook\InstantArticles\Elements\Italic;
use Facebook\InstantArticles\Elements\Anchor;

add_filter('instant_articles_transformed_element', function ($article) {
    $article->withFooter(
        Footer::create()
            ->addCredit(
                Paragraph::create()
                    ->appendText(
                        Bold::create()->appendText("Some bold text");
                    )
                    ->appendText(
                        ", some unformatted text "
                    )
                    ->appendText(
                        Anchor::create()->withURL("http://your.url/here")->appendText("and some link")
                    )
                    ->appendText(
                        "."
                    )
            )
    );
    return $article;
});
```
That would output your footer as:

```html
<footer>
    <aside>
        <p><b>Some bold text</b>, some unformatted text <a href="http://your.url/here">and some link</a>.</p>
    </aside>
</footer>
```

**Comment by stuartshields** [comment]
@diegoquinteiro Thanks, I'll try it a bit later. Will we see some form of documentation on using the Facebook SDK for Instant Articles?

**Comment by diegoquinteiro** [comment]
@stuartduff definitely! Any feedback and suggestions are also very welcome.

Meanwhile, please take a look at our SDK docs, tests and examples, and feel free to ask us if you miss anything.

Let me know if you could get it to work.

Thank you,
Diego

**Comment by stuartshields** [comment]
@diegoquinteiro 

I had to change `withURL` to `withHref` and since it's in another class for our files the following worked:

`add_filter('instant_articles_transformed_element', function ($article) {
					$article->withFooter(
						\Facebook\InstantArticles\Elements\Footer::create()
							->addCredit(
								\Facebook\InstantArticles\Elements\Paragraph::create()
									->appendText(
										\Facebook\InstantArticles\Elements\Bold::create()->appendText("Some bold text")
				)
					->appendText(
						", some unformatted text "
					)
						->appendText(
							\Facebook\InstantArticles\Elements\Anchor::create()->withHref("http://your.url/here")
								->appendText("and some link")
						)
						->appendText(
							"."
						)
					)
			);
			return $article;
		});`

**Comment by diegoquinteiro** [comment]
@stuartduff Oh, that is true. We might not change to `withURL(...)` right now to not break backwards compatibility. 

You should be able to use the Advanced tab JSON editor to paste a custom ruleset with higher priority then the built-in rules.

Where do you wanna enable comments/likes? In images? I can bake a custom ruleset for you to try to accomplish this.

**Comment by stuartshields** [comment]
@diegoquinteiro Yes in images please.

**Comment by diegoquinteiro** [comment]
Something like this can be used:

```javascript
{
    "rules":
    [{
        "class": "ImageRule",
        "selector": "//img|//p[img]|//p[a[img]]|//a[img]",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            },
            "image.caption": {
                "type": "element",
                "selector": "img[@alt]"
            },
            "image.like" : {
                "type" : "exists",
                "selector" : "img"
            },
            "image.comments" : {
                "type" : "exists",
                "selector" : "img"
            }
        }
    }]
}
```

**Comment by diegoquinteiro** [comment]
@stuartshields sorry, I meant that any rule you specify on the custom rules JSON editor will have higher priority then the built-in rules, so you can override behaviours.

**Comment by stuartshields** [comment]
@diegoquinteiro Ah cool! Thanks for being clear.

**Comment by diegoquinteiro** [comment]
I'll close this one as the Footer thing was resolved.

**Comment by abdusfauzi** [comment]
Whoa. This escalated quickly 😅 v0.2 => v2.3 in one night.

@diegoquinteiro thanks for the updates and explanation. Got to dig and read up further 😄

**Comment by sgatz** [comment]
@diegoquinteiro Using your filter hook, I can't seem to figure out how to read the Footer element.  For example, I only want to add in my own footer <small> element, but preserve anything else that's already there.  But it seems I can only replace the whole thing.  Am I missing something?

**Comment by apollosk** [comment]
@diegoquinteiro Where should I add the code you provided for custom IA footer? Which file in the plugin folder should I modify? Please let me know. Thank you in advance.

**Comment by everton-rosario** [comment]
@sgatz @apollosk Now you can do this with this PR: #612
