### ISSUE TITLE
Indeed Config - Help

### ISSUE THREAD

**Issue by Desitalk** [Automattic/facebook-instant-articles-wp#961]
I was Installed Latest FIAW - To my website 

I Need Help with Config New Settings 

I given Application ID 
Secret - 
But How to Get Page Access Token ? please Help me out !! 

i was Tried without Page Access Token . When am trying to Debug Getting error 
**Missing Properties The following required properties are missing: fb:app_id**

Please Help me Out

**Comment by jerclarke** [comment]
Detailed instructions somewhere prominent is what this needs. 

Here are the most detailed instructions we've gotten, pasted from #878 

> To generate one you can use the Graph API Explorer, or implement the calls by yourself.
> 
> Im exemplifying here the flow on the Graph API Explorer:
> 
> 1. Access the tool: https://developers.facebook.com/tools/explorer/
> 2. Select the application on the first top right bottom (same application you are using as ID on the plugin)
> 3. Select "Get token" button, selecting a sub option: Page Access
> 4. This should open a popup window, then you will follow as your user
> 5. It will now fill in the access token on the form field: "Access Token"
> 6. Copy this access token and go to Token Debugger: https://developers.facebook.com/tools/debug/accesstoken/
> 7. Click on extend token
> 8. Copy and paste this token back into the Graph API Explorer
> 9. Call GET: /me/accounts
> 10. Find your page access token
> 11. Confere this last copied token into the Token Debugger to check it expire date.
> 12. Use this long-lived token into your Token field on the settings.

**Comment by Desitalk** [comment]
Thank You !! ... 

After That Am trying Debug  Getting These errors 

The following required properties are missing: og:url, og:type, og:title, og:image, og:description, fb:app_id

**Comment by rb-git** [comment]
@jerclarke - Thanks a lot for the instructions. I discovered the update not syncing issue yesterday and was horrified to read through [878](https://github.com/Automattic/facebook-instant-articles-wp/issues/878). Surprised nobody else flagged this - Thanks a lot for your persistence and getting this fixed. 
@devteam - These detailed instructions need to be updated on the plugin page as well.

**Comment by everton-rosario** [comment]
Hey @rb-git per our latest release, we are generating a key and signing the re-scrape request.
This was added into the v4.1 and up.

Then the token config and the detailed step-by-step shouldn't be needed anymore.

Let us know if you still need the token config. (this was a mid-term solution per @jerclarke raised an important issue).

Now the final solution is this signing to the scrape request.
