### ISSUE TITLE
Is there any support for video link covers yet?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#963]
I've been interested in this functionality for some time now and am seeing more pages start to make use of it: https://developers.facebook.com/docs/instant-articles/reference/cover/

It doesnt appear as though the plugin has any direct support for it, which is fine if there was a hook we could use to manually add the <figure> element in but I can't see any.

Could someone point me in the direction of how to possibly implement this in the short term?

**Comment by samichamoun** [comment]
anyone?

**Comment by samichamoun** [comment]
I am just looking for some sort of hook to be able to use manually

**Comment by pippo-c-l** [comment]
<video>
<source src="link here" type="video/mp4" />
</video>
 There is the possibility to add it manually but it will disappear in about 1 hour 👎

**Comment by everton-rosario** [comment]
@samichamoun you've already found this gist: https://gist.github.com/everton-rosario/26fe2a14591e603c5db37d4d6dc6ba06

To perform that kind of custom code setup you can create a plugin or change a custom theme implementation.
