### ISSUE TITLE
Notice: Undefined index: display_warning_column in /home/wikileaks4india/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 466

### ISSUE THREAD

**Issue by kishore9302** [Automattic/facebook-instant-articles-wp#965]
I am using Instant Articles for WP plugin so please solve this error.
Thanks

**Comment by samnangei9** [comment]
[Uploading fb-instant-articles.4.1.1.zip…]()

**Comment by kishore9302** [comment]
what is this..
please fix error plz

Automattic/facebook-instant-articles-wp] Notice: Undefined index:
display_warning_column in /home/wikileaks4india/public_html/wp-con
tent/plugins/fb-instant-articles/facebook-instant-articles.php on line 466

**Comment by kittipongo** [comment]
Enable "FB IA Status column" option for quick fix.

**Comment by kishore9302** [comment]
currently i am enabled it

Thanks

**Comment by markbarnes** [comment]
You can fix this notice by editing the line to:

`$display_warning_column = isset($publishing_settings[ 'display_warning_column' ]) ? $publishing_settings[ 'display_warning_column' ] : "0";`
