### ISSUE TITLE
Something went wrong. Please contact direct support.

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#97]
We have updated the Instant Article Wordpress Plugin(https://github.com/Automattic/facebook-instant-articles-wp) to latest version 2.0. But at the end we found that we are unable to insert the URL at the RSS section and I have been told that something went wrong. Please contact direct support. 

We believe that it might be connect using API but in the Pages Manager the Instant Article wasn't running perfectly as it displaying auto draft and older post rather than current 1. 

<img width="606" alt="12995528_899916156783798_160842312_n" src="https://cloud.githubusercontent.com/assets/4049250/14417888/b1e88304-ffec-11e5-87e2-74fec922e29b.png">
<img width="1173" alt="12995610_500076453513473_1447729079_n" src="https://cloud.githubusercontent.com/assets/4049250/14417890/b24e94b4-ffec-11e5-8b42-2cf145d38f51.png">

**Comment by stuartshields** [comment]
@CarsonLee27 I'm not from support, but I've had similar issues.

Your feed hasn't fully generated correctly - http://tantannews.com/feed/instant-articles (You can access it via http://tantannews.com/instant-articles as well if you needed to know), scroll right down the bottom, you'll see that the feed hasn't completed generating itself (should finish with </rss>), this could be an issue with your hosting not having enough available memory to generate the feed itself.

**Comment by CarsonLee27** [comment]
Thank you so much bro!! Nice angle you have there, this might be one of the issue as I found that the memory almost hit the ceiling. 

Just wondering when u having similar issues, did you found that your pages manager show auto-draft and a lot of uncomplete article?

**Comment by stuartshields** [comment]
@CarsonLee27 No I didn't. Here is a trick for you if memory is an issue:

Put the limit of the posts generated in the rss feed to 15, wait about 10 minutes and visit the feed URL to see if it generated correctly. If it has, jump onto Facebook Instant Articles and see if the Feed will now be accepted, if it is, wait the 3 - 5 minutes for the posts to come in. Once they come in, go back to your site, click Update on another 15 posts, wait 5 minutes, see if the feed generated correctly, if it has go to Facebook Instant Articles and see if they are added. Repeat above until you have the 50 Facebook requires. 

Once done, go through each post on Facebook Instant Articles, that has the yellow triangle next to it, see what the errors are (if any), manually fix them from there. Once you've done that and have the 50 posts, remove the feed and apply to get the Page accepted for Instant Articles. Once your accepted, re-add the feed. 

Might be a long way of doing things, however it worked for us and we got approved within 24hrs.
